feat: introduce MyCo features E2E tests
SAP/spartacus pull request #10005
Opened 2020-11-25 12:02 UTC by kacperknapik

Closes #9804

2020-11-25 13:31 UTC, Zeyber requested changes

2020-11-25 13:31 UTC, Zeyber commented on projects/storefrontapp-e2e-cypress/cypress/helpers/b2b/my-company/models/my-company.config.ts
> +  featureToggles?: string[];
Should be named something more appropriate, like `featureTests`.

2020-11-25 13:31 UTC, Zeyber commented on projects/storefrontapp-e2e-cypress/cypress/helpers/b2b/my-company/my-company-features.ts
> +function userPasswordTest(): void {
Can we move this test into its on separate file like `user-password.ts`?

2020-12-04 12:10 UTC, Matejk00 approved these changes

2020-12-04 13:07 UTC, Zeyber approved these changes

2020-12-04 13:07 UTC, merged