avoid duplicate calls to CPQ
SAP/spartacus pull request #10135
Opened 2020-11-30 17:29 UTC by Uli-Tiger

2020-12-03 15:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/spartacus?pullRequest=10135) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/spartacus?pullRequest=10135) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/spartacus?pullRequest=10135) it.</sub>

2020-12-07 10:20 UTC, ChristophHi requested changes
I only saw a small typo

2020-12-07 10:20 UTC, ChristophHi commented on feature-libs/product/configurators/rulebased/root/interceptor/cpq-access-storage.service.ts
> +   * will receive the new data. Will only have an efffect, if thre are any subscribers
Typo

2020-12-07 10:41 UTC, AlexanderKuschner approved these changes

2020-12-07 16:32 UTC, merged