GH-8929 refactor: remove console logs
SAP/spartacus pull request #10382
Opened 2020-12-11 17:09 UTC by Parthlakhani

closes #8929

2020-12-30 21:05 UTC, bgambocjaviniar requested changes
remove line 21 and line 40 in this unit test, which are the variable and the testbed injection

- make sure to always double check and run the unit test even if it was just logs

2020-12-30 21:40 UTC, Parthlakhani commented
Understood. Did the changes.

2021-01-11 15:47 UTC, bgambocjaviniar approved these changes

2021-01-26 15:30 UTC, Platonn approved these changes

2021-01-26 23:38 UTC, merged