chore: Progress with the script
SAP/spartacus pull request #10687
Opened 2021-01-13 10:42 UTC by marlass

2021-01-20 19:41 UTC, hackergil requested changes
- When I ran the script, I noticed that there are checks for some APIs in node_modules, which should not be the case I think?
- Some comments on the PR

2021-01-20 19:41 UTC, hackergil commented on tsconfig.compodoc.json
> +        "projects/schematics/src/public_ap"
typo I think?

2021-01-20 19:41 UTC, hackergil commented on tools/config/tsconfig-paths.ts
> +  const tsConfigContent = parse(fs.readFileSync(tsconfigPath, 'utf-8'));
call readTsConfigFile() instead?

2021-01-22 15:50 UTC, znikola requested changes

2021-01-22 15:50 UTC, znikola commented on tools/config/manage-dependencies.ts
> +                      `You should use absolute paths only for testing modules.`,
Maybe we phrase it like this:
`You should use absolute paths only in test files`?

2021-01-22 15:50 UTC, znikola commented on tools/config/manage-dependencies.ts
> +          'yarn add <dependency-name> (--dev)'
As `--dev` is an optional argument, let's use the common syntax for optional args: `[--dev]`

2021-01-25 09:49 UTC, znikola approved these changes, later dismissed

2021-01-25 17:11 UTC, hackergil commented
@marlass Here's an example of what I was saying. We should not be scanning node_modules

```
Checking imports of Node.js APIs

--- projects/schematics/node_modules/@angular-devkit/core/node/host.d.ts -------
 ✖  Node.js API `fs` is referenced.

 i  Node.js APIs can only be used in SSR code or in schematics specs.
    You might have wanted to import it from some library instead.
--------------------------------------------------------------------------------


--- projects/schematics/node_modules/@angular-devkit/core/node/testing/index.d.ts
 ✖  Node.js API `fs` is referenced.

 i  Node.js APIs can only be used in SSR code or in schematics specs.
    You might have wanted to import it from some library instead.
---------------------------------------------------------------------------------


--- projects/schematics/node_modules/@nguniversal/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
 ✖  Node.js API `fs` is referenced.

 i  Node.js APIs can only be used in SSR code or in schematics specs.
    You might have wanted to import it from some library instead.
```

2021-01-25 17:16 UTC, hackergil requested changes
Added a comment about scanning node_modules

2021-01-25 17:17 UTC, marlass commented
> @marlass Here's an example of what I was saying. We should not be scanning node_modules
> 
> ```
> Checking imports of Node.js APIs
> 
> --- projects/schematics/node_modules/@angular-devkit/core/node/host.d.ts -------
>  ✖  Node.js API `fs` is referenced.
> 
>  i  Node.js APIs can only be used in SSR code or in schematics specs.
>     You might have wanted to import it from some library instead.
> --------------------------------------------------------------------------------
> 
> 
> --- projects/schematics/node_modules/@angular-devkit/core/node/testing/index.d.ts
>  ✖  Node.js API `fs` is referenced.
> 
>  i  Node.js APIs can only be used in SSR code or in schematics specs.
>     You might have wanted to import it from some library instead.
> ---------------------------------------------------------------------------------
> 
> 
> --- projects/schematics/node_modules/@nguniversal/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
>  ✖  Node.js API `fs` is referenced.
> 
>  i  Node.js APIs can only be used in SSR code or in schematics specs.
>     You might have wanted to import it from some library instead.
> ```

We no longer have node_modules in libraries directories. Isn't is some leftover node_modules dir in your local repository?

2021-01-25 17:39 UTC, hackergil approved these changes

2021-01-25 20:16 UTC, merged