Change product list default page size to 12
SAP/spartacus pull request #10937
Opened 2021-01-29 10:03 UTC by dydome

close #3075

2021-05-27 19:42 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-components/product/product-list/container/product-list-component.service.ts
> +  protected defaultPageSize = 12;
fixes the issue at hand, but I rather have this configurable as the comment says. I believe this was left out for a long time.

What we can do here is make it configurable by putting it in the `view-config.ts`, which the customer can configure to the size they want

Therefore, need to update

- `view-config.ts`
- `default-scroll-config.ts` --> change the name to default-view-config.ts` as we probably want a default size of 12.

2021-05-27 19:43 UTC, bgambocjaviniar requested changes
^

2021-06-14 18:48 UTC, bgambocjaviniar requested changes
1 - fix review changes
2 - fix the e2es as some was hardcoded to 10 instead of 12 products as length (old e2es). Afterwards, create a ticket to make it dynamic and not dependent on these values.
3 - create the deprecations notes in this PR for the name change and the constructor deprecation in `product-list-component.service.ts`

2021-06-14 18:48 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-components/product/product-list/container/product-list-component.service.ts
> +    protected viewConfig: ViewConfig
Let's just call it `config` instead of `viewConfig` as it contains all the configurations in our application, and by convention from what I'm seeing

2021-06-14 18:48 UTC, bgambocjaviniar commented on projects/storefrontlib/src/shared/config/view-config.ts
> +    defaultPageSize: number;
make it optional

2021-06-14 18:49 UTC, bgambocjaviniar requested changes

2021-06-14 18:49 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-components/product/product-list/container/product-scroll/product-scroll.component.spec.ts
> +            defaultPageSize: 12,
remove the changes from this PR once this is removed https://github.com/SAP/spartacus/pull/10937#discussion_r651191495

2021-06-14 18:49 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-components/product/product-list/container/product-scroll/product-scroll.component.spec.ts
> +            defaultPageSize: 12,
remove the changes from this PR once this is removed  
 https://github.com/SAP/spartacus/pull/10937#discussion_r651191495

2021-06-16 20:18 UTC, bgambocjaviniar requested changes
fix your remaining e2es

- the one we fixed together solved most of them, but the infinite-scroll e2e is still broken

Instead of relying of the pipeline to wait and build to see if it works, do the following in your local

- Make sure the backend url matches the one set in cypress.json. Change the url accordingly if you'll test in a different server.

make sure you have your dependencies are installed in the storefrontapp-e2e-cypress folder
-  (TEST RUNNER) `yarn e2e:open` choose the infinite scroll e2e to be run in the cypress test runner 
- (HEADLESS) `yarn e2e:run --spec cypress/integration/regression/infinite-scroll.e2e-spec.ts`

2021-06-16 20:18 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/product-list-component.service.migration.ts
> +  deprecatedParams: [],
include the old constructor in here as explained in DM

2021-06-17 12:42 UTC, bgambocjaviniar submitted a review, later dismissed

2021-06-17 12:52 UTC, marlass requested changes

2021-06-17 12:52 UTC, marlass commented on docs/migration/4_0.md
> +`ConfiguratorCartEntryInfoComponent` now also requires `CommonConfiguratorUtilsService`.
I think it wasn't supposed to be duplicated

2021-06-17 12:52 UTC, marlass commented on projects/storefrontlib/src/cms-components/product/config/default-view-config.ts
> +export const defaultViewConfig: ViewConfig = {
Add migration to this renamed symbol and mention it in the migration doc

2021-06-17 12:52 UTC, marlass commented on projects/storefrontlib/src/cms-components/product/product-list/container/product-list-component.service.ts
> -  protected defaultPageSize = 10;
Mention in the docs that this property was removed (also say how customer can configure it now) and add method-property migration.

2021-06-17 13:23 UTC, marlass commented on projects/schematics/src/migrations/4_0/methods-and-properties-deprecations/data/product-list-component.service.migration.ts
> +    comment: `Property '${DEFAULT_PAGE_SIZE}' was removed, to modify default page size use '${PROVIDE_CONFIG_FUNCTION}' and set your default page size.`,
```suggestion
    comment: `Property '${DEFAULT_PAGE_SIZE}' was removed, to modify default page size use 'view.defaultPageSize' configuration property.`,
```

2021-06-17 13:25 UTC, marlass requested changes
Also I don't see the migration and info about `defaultScrollConfig` change to  `defaultViewConfig`

2021-06-18 07:38 UTC, marlass approved these changes, later dismissed

2021-06-18 09:22 UTC, marlass approved these changes

2021-06-18 09:24 UTC, merged