Feature/gh 9991
SAP/spartacus pull request #11008
Opened 2021-02-04 18:06 UTC by Parthlakhani

closes #9991

2021-02-09 15:53 UTC, Pucek9 commented on feature-libs/organization/administration/components/shared/card/card.component.html
> +    <ng-content select="[messages]"></ng-content>
```suggestion
    <ng-content select="[info]"></ng-content>
```
let use some other tag

2021-02-09 15:55 UTC, Pucek9 commented on feature-libs/organization/administration/components/shared/detail/explain-disable-messages/explain-disable-messages.component.ts
> +  @Input() disabledCreateMessage?: string;
why string? as you use it as boolean it's unexpected

2021-02-16 04:20 UTC, Pucek9 submitted a review, later dismissed

2021-02-16 12:23 UTC, Pucek9 commented
QA Steps: 
Verify custom messages displayed in cases:
- [ ] 1 message for disabled purchase limit, 0 messages for purchase limit with disabled unit
- [ ] 1 message for disabled budget, 2 messages for disabled budget with disabled unit
- [ ] 1 message for disabled cc, 2 messages for disabled cc with disabled unit
- [ ] 1 message for disabled user, 2 messages for disabled user with disabled unit
 unit
- [ ] 1 message for disabled user, 2 messages for disabled user with disabled unit
- [ ] 1 message for disabled unit, 2 messages for disabled unit with disabled parent unit, 1 message for root unit

Add custom content to the message, eg, cost center details component:
```ts
  <cx-explain-disable-messages info i18nRoot="orgCostCenter" [forceDisplay]="true">
    <li>Custom message</li>
  </cx-explain-disable-messages>
```  
Verify that Custom message is added to list and displayed

2021-02-17 11:00 UTC, Matejk00 commented
Hey, I did QA for this ticket. All scenarios works fine. However I've found one styling issue. 
![css](https://user-images.githubusercontent.com/6958810/108194795-5178f480-7117-11eb-8810-835fb2bfb2c0.png)

In my opinion text in message box should be aligned with info icon. Right now text is positioned slighthly to the bottom.

@Parthlakhani what do you think?

2021-02-17 11:08 UTC, Matejk00 requested changes
https://github.com/SAP/spartacus/pull/11008#issuecomment-780477645

2021-02-17 14:19 UTC, Parthlakhani commented
> Hey, I did QA for this ticket. All scenarios works fine. However I've found one styling issue.
> ![css](https://user-images.githubusercontent.com/6958810/108194795-5178f480-7117-11eb-8810-835fb2bfb2c0.png)
> 
> In my opinion text in message box should be aligned with info icon. Right now text is positioned slighthly to the bottom.
> 
> @Parthlakhani what do you think?

I agree, I am checking how I can fix this.

2021-02-18 15:20 UTC, Matejk00 submitted a review, later dismissed

2021-02-23 18:28 UTC, Pucek9 commented on feature-libs/organization/administration/components/shared/detail/explain-disable-messages/explain-disable-messages.component.spec.ts
> +        const element = fixture.debugElement
its no longer element, its array of string now
```suggestion
        const values = fixture.debugElement
```

2021-02-23 18:29 UTC, Pucek9 commented on feature-libs/organization/administration/components/shared/detail/explain-disable-messages/explain-disable-messages.component.spec.ts
> +        expect(element).not.toEqual(action.expectedValue);
instead of verify .not.toEqual we can use the same array and probivde an empty array as expected value 🙂

2021-02-25 13:48 UTC, Pucek9 approved these changes

2021-02-25 14:05 UTC, Matejk00 approved these changes

2021-02-25 14:10 UTC, merged