Update email domain name of test users
SAP/spartacus pull request #11106
Opened 2021-02-11 23:16 UTC by giancorderoortiz

Avoid confusion of test users generated during e2e vs test users in Spartacus sample data.

2021-02-12 16:57 UTC, hackergil requested changes

2021-02-12 16:57 UTC, hackergil commented on projects/storefrontapp-e2e-cypress/cypress/helpers/user.ts
> +  return `user_${alias}_${timestamp}@ydev.sapcx.com`;
how about `test_user_${alias}_${timestamp}@sapcx.com`; ?

2021-02-12 18:29 UTC, giancorderoortiz commented on projects/storefrontapp-e2e-cypress/cypress/helpers/user.ts
> +  return `user_${alias}_${timestamp}@ydev.sapcx.com`;
done

2021-02-25 14:50 UTC, hackergil approved these changes

2021-02-25 23:39 UTC, merged