chore: Migrate to eslint
SAP/spartacus pull request #11214
Opened 2021-02-22 07:22 UTC by marlass

2021-02-23 16:08 UTC, Pucek9 commented on package.json
> +    "@angular-eslint/template-parser": "1.2.0",
```suggestion
    "@angular-eslint/builder": "^1.2.0",
    "@angular-eslint/eslint-plugin": "^1.2.0",
    "@angular-eslint/eslint-plugin-template": "^1.2.0",
    "@angular-eslint/schematics": "^1.2.0",
    "@angular-eslint/template-parser": "^1.2.0",
```

2021-02-23 16:08 UTC, Pucek9 commented on package.json
> +    "eslint-plugin-prefer-arrow": "1.2.2",
```suggestion
    "eslint-plugin-deprecation": "^1.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsdoc": "^30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
```

2021-02-23 16:09 UTC, Pucek9 commented on package.json
> +    "@typescript-eslint/parser": "4.3.0",
```suggestion
    "@typescript-eslint/eslint-plugin": "^4.3.0",
    "@typescript-eslint/parser": "^4.3.0",
```

2021-02-23 16:27 UTC, Pucek9 requested changes
IMO we could simplify particular `.eslintrc.json` files to avoid duplicate configuration for overriding exactly the same stuff

2021-02-23 19:23 UTC, marlass commented on package.json
> +    "eslint-plugin-prefer-arrow": "1.2.2",
```suggestion
    "eslint-plugin-prefer-arrow": "^1.2.2",
```

2021-02-24 13:36 UTC, Pucek9 approved these changes

2021-03-01 08:49 UTC, dunqan approved these changes

2021-03-01 08:57 UTC, merged