Feature/gh 11325
SAP/spartacus pull request #11440
Opened 2021-03-09 18:41 UTC by ren-tham

2021-03-16 10:44 UTC, dydome requested changes
In my opinion, there are a couple of tests that should be added to SavedCartListComponent:
1) trigger loadSavedCarts on init
2) watch onSuccess on init
3) test for goToSavedCartDetails method
4) test for restoreSavedCart method
5) test for onSuccess method

All above are very similar to the test in SavedCartFormDialogComponent.

2021-03-16 10:44 UTC, dydome commented on projects/core/src/cart/store/reducers/multi-cart.reducer.spec.ts
> +fdescribe('Multi Cart reducer', () => {
remove 'f'

2021-03-16 17:49 UTC, bgambocjaviniar requested changes
I would like you to include sorting of the dates in here as well 

Basically, under `feature-libs/cart/saved-cart/components/list/saved-cart-list.component.ts` line 20, you do something like

```
savedCarts$: Observable<Cart[]> = this.savedCartService
    .getList()
    .pipe(
      map((lists) =>
        lists.sort((a, b) =>
       /// sort the saveTime property
/// latest to oldest
        )
      )
    );
```

2021-03-17 09:20 UTC, dydome approved these changes

2021-03-22 13:28 UTC, merged