refactor: improve cart item list component unit tests coverage
SAP/spartacus pull request #11676
Opened 2021-03-26 10:13 UTC by psmul

Closes: #11609

2021-03-26 12:07 UTC, mszczepaniak submitted a review, later dismissed

2021-03-26 14:21 UTC, mszczepaniak submitted a review, later dismissed

2021-03-29 08:41 UTC, marlass requested changes

2021-03-29 08:41 UTC, marlass commented on projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.spec.ts
> +    console.log(component.form);
```suggestion
```

2021-03-29 09:10 UTC, marlass approved these changes

2021-03-29 10:45 UTC, merged