make configurator UISettings in constructor optional
SAP/spartacus pull request #11677
Opened 2021-03-26 10:44 UTC by Uli-Tiger

PS: also removed the mockedFocus Directive from the test, as it is obviously not required, but cause a strict mode issue in the test.

2021-03-26 13:11 UTC, ChristophHi requested changes

2021-03-26 13:11 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/input-field/configurator-attribute-input-field.component.ts
> +  constructor(protected config?: ConfiguratorUISettings) {
Could you add the 2 alternative constructor definitions like Kris recommended?

2021-03-26 13:11 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/input-field/configurator-attribute-input-field.component.ts
> +  public readonly FALLBACK_DEBOUNCE_TIME = 500;
Could you make it private?

2021-03-26 13:11 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/numeric-input-field/configurator-attribute-numeric-input-field.component.ts
> +    protected config?: ConfiguratorUISettings
Also please add 2 constructor definitions

2021-03-26 14:31 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/attribute/types/input-field/configurator-attribute-input-field.component.ts
> +  constructor(protected config?: ConfiguratorUISettings) {
done

2021-03-26 14:32 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/attribute/types/input-field/configurator-attribute-input-field.component.ts
> +  public readonly FALLBACK_DEBOUNCE_TIME = 500;
done

2021-03-26 14:32 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/attribute/types/numeric-input-field/configurator-attribute-numeric-input-field.component.ts
> +    protected config?: ConfiguratorUISettings
done

2021-03-29 08:42 UTC, schuppell approved these changes

2021-03-29 08:42 UTC, merged