[WIP] Import export feature
SAP/spartacus pull request #11794
Opened 2021-04-02 09:48 UTC by Matejk00

Closes: #11498 
Closes: #11329

2021-04-13 10:31 UTC, Pucek9 commented on feature-libs/cart/import-export/core/model/import-export.model.ts
> +  // size unit is MB
https://github.com/SAP/spartacus/pull/11861/files#r612324643

2021-04-13 10:32 UTC, Pucek9 commented on feature-libs/cart/import-export/core/model/import-export.model.ts
> +  checkEmptyFile?: Boolean;
https://github.com/SAP/spartacus/pull/11861/files#r612320475

2021-04-14 20:05 UTC, Platonn commented on feature-libs/cart/import-export/core/services/import-export.service.ts
> +import { FileValidity, InvalidFileInfo } from '../model';
To avoid potential compilation issues, let's import not from barrel but from a direct file path.

2021-04-14 20:14 UTC, Platonn commented on feature-libs/cart/import-export/core/model/import-export.model.ts
> +export type FileValidity = {
For consistency, let's stick to `interface`s for describing models.

2021-04-14 20:20 UTC, Platonn commented on feature-libs/cart/import-export/core/services/import-to-cart.service.ts
> +import { SavedCartService } from '@spartacus/cart/saved-cart/core';
After the SavedCartFacade was introduced in PR https://github.com/SAP/spartacus/pull/11949, we should not reference directly SavedCartService.

2021-04-14 20:40 UTC, Platonn commented on feature-libs/cart/import-export/core/services/import-to-cart.service.ts
> +    this.userIdService.invokeWithUserId((userId) => {
invokeWithUserId is deprecated. Please use takeUserId method instead.

2021-04-14 20:44 UTC, Platonn commented on feature-libs/cart/import-export/core/services/import-to-cart.service.ts
> +  private subscription = new Subscription();
The `subscription` reference should be exposed (as protected) for customers in case they want to amend the method that uses that subscription, i.e. `addProductsToCart()`

2021-04-14 20:49 UTC, Platonn commented on feature-libs/cart/import-export/core/config/import-export-config.ts
> +  importExport: {
I'm sorry I was not enough precise before. The `importExport` key is a bit too general.  What about `cartImportExport`?

2021-08-23 16:46 UTC, morganm58 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +          font-weight: bold;
font weight should be a variable.
font-weight: var(--cx-font-weight-bold);

2021-08-23 16:46 UTC, morganm58 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +              font-weight: bold;
should be font-weight: var(--cx-font-weight-bold);

2021-08-23 16:47 UTC, morganm58 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +            font-weight: bold;
font-weight: var(--cx-font-weight-bold);

2021-08-23 16:47 UTC, morganm58 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +            font-weight: normal;
font-weight: var(--cx-font-weight-normal);

2021-08-23 17:23 UTC, morganm58 requested changes, later dismissed
I left some comments about the font-weight variables.

2021-10-19 12:25 UTC, Platonn commented on feature-libs/cart/import-export/components/export-entries/export-products-to-csv.spec.ts
> +describe('ExportProductsToCsvService', () => {
nitpick:  filename `export-products-to-csv.spec.ts ` -> `export-products-to-csv.service.spec.ts`

2021-10-20 06:17 UTC, Matejk00 commented on feature-libs/cart/import-export/components/export-entries/export-products-to-csv.spec.ts
> +describe('ExportProductsToCsvService', () => {
Updated.

2021-10-20 06:18 UTC, Matejk00 commented on feature-libs/cart/import-export/core/model/import-export.model.ts
> +export type FileValidity = {
done

2021-10-20 06:19 UTC, Matejk00 commented on feature-libs/cart/import-export/core/services/import-to-cart.service.ts
> +import { SavedCartService } from '@spartacus/cart/saved-cart/core';
done

2021-10-20 06:20 UTC, Matejk00 commented on feature-libs/cart/import-export/core/config/import-export-config.ts
> +  importExport: {
done

2021-10-20 06:21 UTC, Matejk00 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +          font-weight: bold;
changed

2021-10-20 06:21 UTC, Matejk00 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +              font-weight: bold;
done

2021-10-20 06:21 UTC, Matejk00 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +            font-weight: bold;
done

2021-10-20 06:21 UTC, Matejk00 commented on feature-libs/cart/import-export/styles/_import-entries-dialog.scss
> +            font-weight: normal;
done

2021-10-20 06:22 UTC, Matejk00 commented
> I left some comments about the font-weight variables.

SCSS files have been updated

2021-10-20 11:17 UTC, Platonn commented on projects/storefrontapp/src/app/spartacus/spartacus-features.module.ts
> +    ImportExportFeatureModule,
nitpick:
Would you mind renaming the section `** External features **` to `** Feature libraries **`, please? It will be more precise.
Than you can move your new module under there.
The purpose of this section was to diffrentiate code that has been already extracted to feature libraries from code that still lives in the storefrontlib monolith

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/components/import-export/import-export.module.ts
> +            ],
Can you help me understand, what happens in the future when we want to support displaying import-export.component in the order details page? Will we have a circullar dependency?

If this mapping doesn't support order details or some other page and it will require some refactor to support it, I'd like to hide this mapping in the component (so it's not configurable) to avoid maitaining this config as a public API.

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/model/import-to-cart.model.ts
> +export enum NameSource {
To be more precise, what about renaming `CartNameSource`?

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/cart-import-export.context.ts
> +  protected abstract add(products: ProductData[]): Observable<string>;
It's not so obvious at the first sight what this abstract method should do and what should return? Can you elaborate in the JSDoc, please?

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/import-export.context.ts
> +}
This contract is reused in many places. Could you please describe in JSDocs the methods/fields of this interface and why we need this interface?

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/cart-import-export.context.ts
> +export abstract class CartImportExportContext {
This service contains a lot of logic worth testing. I have problem to find unit tests of this service.

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/cart-import-export.context.ts
> +  protected mapMessages(
Can you describe in JSDoc what this method does, please?

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/order-confirmation-export-context.service.spec.ts
> +// TODO: Add unit tests
👀

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/order-details-export-context.service.spec.ts
> +// TODO: Add unit tests
👀

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/quick-order-import-export-context.service.ts
> +        .load(productData.productCode)
Do we _really_ need to call the adapter directly here?

Normally we should call only the `ProductService` facade, but not the layers below (connector nor adapter).

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/quick-order-import-export-context.service.ts
> +  results$ = new Subject<ProductImportInfo>();
Do we _really_ need to expoese `results$ = new Subject<ProductImportInfo>();` as a property of this service?
Instead, it would be nice to scope it only to the body of the `addEntries()` method.
If you don't have time for the refactor, please at least make `results$` protected.

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/package.json
> +    "@spartacus/order": "4.2.0",
Are those changes really needed in this PR?

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/saved-cart/components/add-to-saved-cart/add-to-saved-cart.component.spec.ts
> +      ],
Are those changes really needed in this PR?

(it also applies to a few other spec files below in this PR)

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/tsconfig.lib.json
> +      "@spartacus/user/profile/root": ["dist/user/profile/root"]
Are all above changes needed in this PR?

(same applies to other tsconfig files in this PR)

2021-10-20 11:17 UTC, Platonn commented on feature-libs/checkout/package.json
> +    "clean:schematics": "../../node_modules/.bin/rimraf \"schematics/**/*.js\" \"schematics/**/*.js.map\" \"schematics/**/*.d.ts\"",
Is this change really needed in this PR?

(same applies to other package.json files in this PR)

2021-10-20 11:17 UTC, Platonn commented on projects/schematics/src/dependencies.json
> +    "@spartacus/order": "4.2.0",
Are those changes really needed in this PR?

2021-10-20 11:17 UTC, Platonn commented on projects/storefrontlib/shared/components/form/file-upload/file-upload.component.html
> +<div>
Do we really need this div? I guess it only centers the content (according to the CSS)
It would be good to avoid DOM elements, unless they are justified.
Instead, I believe can we center just the whole content of the cx-file-upload.
```css
cx-file-upload {
  text-align: center;
  ...
}
```

2021-10-20 11:17 UTC, Platonn commented on projects/storefrontlib/shared/components/form/file-upload/file-upload.component.ts
> +   * Allowed extensions for the file. It's setting attribute used for OS window for choosing files.
```suggestion
   * Allowed file types. It's setting attribute used for OS window for choosing files.
```

2021-10-20 11:17 UTC, Platonn commented on projects/storefrontlib/shared/services/file/csv/export-csv.service.spec.ts
> +describe('ExportCsvFileService', () => {
Let's align file name `export-csv.service.spec.ts` -> `export-csv-file.service.spec.ts`

2021-10-20 11:17 UTC, Platonn commented on projects/storefrontlib/shared/services/file/csv/import-csv-file.service.ts
> +  protected validNotParsable(
Let's rename to verb: valid... -> validate...

2021-10-20 11:17 UTC, Platonn commented on feature-libs/cart/import-export/core/services/order-details-export-context.service.ts
> +import { OrderDetailsService } from '@spartacus/order/components';
⚠️ Blocker issue ⚠️ It will cause a cyclic dependency in the short future.

Here the `cart` lib depends on the `order` lib. 
But @WeizhengSap and @plabadie in the meantime are extracting the cart lib ([epic/cart-lib](https://github.com/SAP/spartacus/tree/epic/cart-lib)), where the `order` lib will depend on the `cart` lib.
Note: in 6.0 we might want to remove the dependency introduced by their PR.

But for now, we should definitely avoid `cart` lib depending on the `order` lib. We need to discuss it.
I'd like to know your feelings: what do you think about moving the import-export feature to the order lib? pros? cons?

2021-10-20 11:53 UTC, Matejk00 commented on projects/storefrontlib/shared/services/file/csv/import-csv-file.service.ts
> +  protected validNotParsable(
method name changed

2021-10-20 11:55 UTC, Matejk00 commented on projects/storefrontlib/shared/services/file/csv/export-csv.service.spec.ts
> +describe('ExportCsvFileService', () => {
done

2021-10-20 12:07 UTC, Matejk00 commented on feature-libs/cart/import-export/core/model/import-to-cart.model.ts
> +export enum NameSource {
enum name renamed

2021-10-20 12:10 UTC, Matejk00 commented on projects/schematics/src/dependencies.json
> +    "@spartacus/order": "4.2.0",
I think that they are unnecessary

2021-10-20 12:16 UTC, Matejk00 commented on feature-libs/cart/package.json
> +    "@spartacus/order": "4.2.0",
I removed those

2021-10-20 12:17 UTC, Matejk00 commented on feature-libs/checkout/package.json
> +    "clean:schematics": "../../node_modules/.bin/rimraf \"schematics/**/*.js\" \"schematics/**/*.js.map\" \"schematics/**/*.d.ts\"",
Updated

2021-10-20 13:57 UTC, Matejk00 commented on feature-libs/cart/tsconfig.lib.json
> +      "@spartacus/user/profile/root": ["dist/user/profile/root"]
Updated

2021-10-20 15:20 UTC, Pucek9 commented on feature-libs/cart/import-export/core/services/order-details-export-context.service.ts
> +import { OrderDetailsService } from '@spartacus/order/components';
If in the future there will be something like context available, import lib (no matter where it is) should use it without knowing about details. Context interfaces should be somewhere higher (storefrontlib?), and implementations in specified features/modules (quick order, order details, cart, saved carts). Now interfaces and all implementations are in cart/import-export/core/services

2021-10-20 15:47 UTC, Pucek9 commented on feature-libs/cart/import-export/components/import-export/import-export.module.ts
> +            ],
Do you mean `checkoutReviewOrder`? It uses an active cart context.
`order details/confirmation` context will be moved to another branch (and wait for his chance in the future)

2021-10-20 15:55 UTC, Pucek9 commented on feature-libs/cart/saved-cart/components/add-to-saved-cart/add-to-saved-cart.component.spec.ts
> +      ],
It caused a lot of errors in our shared (cart) lib.

2021-10-20 16:37 UTC, Pucek9 commented on feature-libs/cart/import-export/core/services/quick-order-import-export-context.service.ts
> +        .load(productData.productCode)
The best I can is use `ProductConnector.get`. `ProductService.get` have a lot of additional logic, using events, etc., and seems as not working with this.

2021-10-20 23:08 UTC, Pucek9 commented on feature-libs/cart/import-export/core/services/order-details-export-context.service.ts
> +import { OrderDetailsService } from '@spartacus/order/components';
Created draft PR and moved logic there https://github.com/SAP/spartacus/pull/14083

2021-10-20 23:08 UTC, Pucek9 commented on feature-libs/cart/import-export/components/import-export/import-export.module.ts
> +            ],
https://github.com/SAP/spartacus/pull/11794#discussion_r733207826

2021-10-20 23:32 UTC, Pucek9 commented on projects/storefrontlib/shared/components/form/file-upload/file-upload.component.html
> +<div>
solved: [`ae72661` (#11794)](https://github.com/SAP/spartacus/pull/11794/commits/ae726617f8658598927c887bc0b3a896b5e42dc3)

2021-10-27 12:26 UTC, Platonn commented on feature-libs/cart/import-export/components/export-entries/index.ts
> +export * from './export-order-entries.module';
[minor] for consistency, would be good to rename:
export-products-to-csv.service -> export-order-entires-to-csv.service

2021-10-27 12:26 UTC, Platonn commented on feature-libs/cart/import-export/components/import-to-cart/import-entries-dialog/import-entries-form/import-entries-form.component.ts
> +  providers: [CxDatePipe],
Do we really need to provide CxDatePipe here? I cannot here usages of it.
btw. We also provide it in the ImportToNewSavedCartFormComponent, but we use it actually there.

2021-10-27 12:26 UTC, Platonn commented on feature-libs/cart/import-export/core/model/import-entries.config.ts
> +}
The whole config is big. Let's add JSdocs for the config properties for better dev experience
[but can postpone to another PR, if you like]

2021-10-27 12:26 UTC, Platonn commented on feature-libs/cart/import-export/core/model/index.ts
> +export * from './import-entries.config';
filenames are inconsistent (.config vs .model). If we have mixed stuff inside, let's split configs and models to sparate files and folders /config and /model
[can be postponed to another PR, doesn't affect public API, nor functionality]

2021-10-27 12:26 UTC, Platonn commented on feature-libs/checkout/root/pages/order-confirmation-get-order-entries-context.ts
> +export class OrderConfirmationGetOrderEntries
For consistency:
- Let's add Context suffix to the class name
- TBH I'm not fond of adding `Get` in the context class name. For the interface it might stay. IMHO it sufficess OrderConfirmationOrderEntriesContext. 

Note: it also applies to `OrderDetailsGetOrderEntriesContext` -> `Get`
Note: it also applies to `NewSavedCardAddOrderEntriesContext` -> `Add`

2021-10-27 12:26 UTC, Platonn commented on projects/storefrontlib/cms-components/cart/order-entries-context/cart-import.context.ts
> + */
👍

2021-10-27 12:26 UTC, Platonn commented on projects/storefrontlib/context/routing-context.service.ts
> +    return Object.assign({}, ...routes.map((route) => route['data']));
This logic is incorrect. It merges all data objects, but not the contexts objects
I'll fix it.

2021-10-27 12:36 UTC, Pucek9 commented on feature-libs/cart/import-export/components/import-to-cart/import-entries-dialog/import-entries-form/import-entries-form.component.ts
> +  providers: [CxDatePipe],
good catch! it should be only in ImportToNewSavedCartFormComponent

2021-10-27 12:40 UTC, Pucek9 commented on feature-libs/checkout/root/pages/order-confirmation-get-order-entries-context.ts
> +export class OrderConfirmationGetOrderEntries
My mistake with missing suffix, thanks!

2021-10-27 13:14 UTC, Platonn commented on projects/storefrontlib/context/routing-context.service.ts
> +    return Object.assign({}, ...routes.map((route) => route['data']));
Fixed in https://github.com/SAP/spartacus/pull/11794/commits/5a67754fd40b787b99907a3c325b8b551f33307b

2021-10-27 14:42 UTC, Matejk00 commented on feature-libs/cart/import-export/core/model/import-entries.config.ts
> +}
Added JSdoc

2021-10-27 23:22 UTC, Pucek9 approved these changes

2021-10-28 11:12 UTC, Platonn approved these changes

2021-10-28 18:04 UTC, merged