refactor: Utility for grabbing all configs
SAP/spartacus pull request #11879
Opened 2021-04-08 11:37 UTC by marlass

2021-04-12 08:55 UTC, znikola requested changes

2021-04-12 08:55 UTC, znikola commented on projects/schematics/src/shared/utils/config-utils.ts
> +    const properties = literal.getChildrenOfKind(
Let's try to minimize the amount of indentations :)
We could do `const properties = literal.getChildrenOfKind() ?? []` and avoid the `if (properties) {`.

2021-04-12 08:55 UTC, znikola commented on projects/schematics/src/shared/utils/config-utils.ts
> +  const configs: Node[] = [];
We can declare this variable just before the line 313

2021-04-12 08:55 UTC, znikola commented on projects/schematics/src/shared/utils/config-utils.ts
> +            elements.forEach((element) => {
We can also streamline this to `initializer?.getElements().forEach((element) => {` and avoid having the nested `if` statement.

2021-04-12 08:55 UTC, znikola commented on projects/schematics/src/shared/utils/new-module-utils.ts
> +export function getModule(sourceFile: SourceFile): CallExpression | undefined {
Can we refactor the `addToModuleInternal()` from this file to use this new helper function?

2021-04-15 07:23 UTC, znikola requested changes

2021-04-15 07:23 UTC, znikola commented on projects/schematics/src/shared/utils/import-utils.ts
> +    if (declaration?.getModuleSpecifier().getText().includes('@spartacus/')) {
Maybe it's safer to use `startsWith`.

2021-04-15 07:23 UTC, znikola commented on projects/schematics/src/shared/utils/import-utils.ts
> +      result = true;
You could just `return true` here, get rid of the `let result = false;` and `return false` at the end of the method.
It's a personal preference, and your call if you want to do it.

2021-04-15 07:23 UTC, znikola commented on projects/schematics/src/shared/utils/config-utils_spec.ts
> +}),
Does it make sense to repeat this configuration, but using the `as` syntax? In this way, we are confident that we covering both cases.

2021-04-15 07:23 UTC, znikola commented on projects/schematics/src/shared/utils/config-utils.ts
>    return configs;
After thinking a bit, let's remove this method. No need to keep it if it's not used anywhere.

2021-04-15 07:23 UTC, znikola commented on projects/schematics/src/shared/utils/config-utils_spec.ts
> +...someSpread,
Nice.

2021-04-15 12:49 UTC, marlass commented on projects/schematics/src/shared/utils/config-utils_spec.ts
> +}),
Would make sense if we would keep the config util ;)

2021-04-15 13:03 UTC, znikola approved these changes

2021-04-15 13:24 UTC, merged