fix: Updating styles on screen reader heading changes.
SAP/spartacus pull request #11933
Opened 2021-04-12 14:24 UTC by morganm58

Closes GH-11869

2021-04-12 15:31 UTC, saad-mo requested changes
I still see the following issues:

- Homepage: Product Titles carousel (Our best selling products & What's New) have lost their original styling. The font is much bigger. 
![Screen Shot 2021-04-12 at 10 29 55 AM](https://user-images.githubusercontent.com/15215400/114420743-31dfd480-9b7a-11eb-9734-40fe5ff3d616.png)

- Checkout Pages: "Shipping Address", "Shipping Method", "Payment" font size is bigger 
![Screen Shot 2021-04-12 at 10 27 57 AM](https://user-images.githubusercontent.com/15215400/114420299-d1509780-9b79-11eb-8435-c89ed2901062.png)

- Wish List Page: The product title font is too big
![Screen Shot 2021-04-12 at 10 23 43 AM](https://user-images.githubusercontent.com/15215400/114420150-b0884200-9b79-11eb-80e5-11c610590253.png)

2021-04-12 19:52 UTC, developpeurweb commented on projects/storefrontstyles/scss/components/misc/card/_card.scss
> +  }
Let's avoid using CSS vars for font size and use `@include type ()` instead.

2021-04-12 19:52 UTC, developpeurweb commented on projects/storefrontstyles/scss/cxbase/mixins/_checkout-media-style.scss
>    }
Let's avoid using CSS vars for font size and use `@include type ()` instead.

2021-04-12 20:12 UTC, saad-mo approved these changes
Looks good to marge (pending Miguel's comments)

2021-04-12 20:21 UTC, developpeurweb requested changes
Let's avoid using CSS vars for font size and use `@include type ()` instead. Other than that it looks fine. Pls notice you have a conflict that might prevent you from merging.

2021-04-13 16:57 UTC, developpeurweb approved these changes
LGTM

2021-04-13 16:57 UTC, merged