Added unit tests for inventory display.
SAP/spartacus pull request #12037
Opened 2021-04-19 16:09 UTC by ren-tham

2021-04-26 15:51 UTC, mszczepaniak commented on projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.spec.ts
> +
```suggestion
```

2021-04-26 15:51 UTC, mszczepaniak commented on projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.spec.ts
> +
```suggestion
```

2021-04-26 15:52 UTC, mszczepaniak commented on projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.spec.ts
> +      const currentMockProduct: Product = {
let's put currentMockProduct in the describe above and reuse it for every it case

2021-06-30 21:11 UTC, bgambocjaviniar requested changes
https://github.com/SAP/spartacus/pull/11978#pullrequestreview-696581686

i'd prefer this file gets included in that PR above, and to adapt to the fixes asked in the PR if necessary

2021-06-30 21:11 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-components/cart/add-to-cart/add-to-cart.component.spec.ts
> +fdescribe('AddToCartComponent', () => {
remove fdescribe

2021-07-05 20:26 UTC, merged