Remove any insensitive terms in codebase.
SAP/spartacus pull request #12172
Opened 2021-04-28 18:18 UTC by ren-tham

2021-04-29 17:54 UTC, LTiger14 requested changes
I also noticed that the `mock-url.pipe.ts` and the `url-testing.module.ts` contain insensitive terms.

Since these files are used for testing it shouldn't be too hard to change those terms.

2021-04-29 17:54 UTC, LTiger14 commented on projects/storefrontstyles/scss/_page-template.scss
>  // whitelisted page template selectors are processed
`whitelisted` in the comment

2021-04-29 17:54 UTC, LTiger14 commented on projects/storefrontstyles/scss/_page-template.scss
> +// unless (some) they are blacklisted using `$page-template-blocklist`
`blacklisted` in the comment

2021-04-29 17:54 UTC, LTiger14 commented on feature-libs/storefinder/styles/layout/_index.scss
>  // whitelisted page template selectors are processed
`whitelisted` is still in the comment

2021-04-29 17:54 UTC, LTiger14 commented on feature-libs/organization/administration/styles/_page-template.scss
>  // whitelisted page template selectors are processed
`whitelisted` is still in the comment.

2021-04-29 17:54 UTC, LTiger14 commented on feature-libs/organization/administration/styles/_page-template.scss
>  // unless (some) they are blacklisted
`blacklisted` is still in the comment.

2021-04-30 12:36 UTC, LTiger14 requested changes

2021-04-30 12:36 UTC, LTiger14 commented on projects/storefrontstyles/scss/_page-template.scss
> +// unless (some) they are blocklisted using `$page-template-blocklist`
[nitpick] could you change this to `// unless (some) that are blocklisted using `$page-template-blocklist``

2021-04-30 12:36 UTC, LTiger14 commented on feature-libs/storefinder/styles/layout/_index.scss
> +// unless (some) they are blocklisted
[nitpick] could you change this to `// unless (some) that are blocklisted using `$page-template-blocklist``

2021-04-30 12:36 UTC, LTiger14 commented on feature-libs/organization/administration/styles/_page-template.scss
> +// unless (some) they are blocklisted
[nitpick] could you change this to `// unless (some) that are blocklisted using `$page-template-blocklist``

2021-05-04 15:36 UTC, LTiger14 requested changes
I forgot to mention could you add your changes to the deprecation documentation.

2021-05-11 13:39 UTC, LTiger14 approved these changes, later dismissed

2021-06-09 12:09 UTC, marlass approved these changes

2021-06-09 12:21 UTC, Platonn approved these changes

2021-06-09 12:24 UTC, merged