chore: Deprecation for CartItemComponent in 4.0
SAP/spartacus pull request #12209
Opened 2021-04-29 12:27 UTC by dydome

close: #9511

2021-05-04 07:27 UTC, marlass requested changes
Could you also provide migration for that (with removed-public-api-deprecation mechanism)?

2021-05-04 09:15 UTC, marlass requested changes

2021-05-04 09:15 UTC, marlass commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
> +    comment: `'${ITEM}' interface was removed from ${CART_ITEM_COMPONENT}.`,
Could you add info about replacement interface? OrderEntry?

2021-05-04 10:52 UTC, marlass approved these changes

2021-05-11 07:15 UTC, Platonn commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
> +    comment: `'${ITEM}' interface was removed from ${CART_ITEM_COMPONENT}. User ${ORDER_ENTRY} instad.`,
```suggestion
    comment: `'${ITEM}' interface was removed from ${CART_ITEM_COMPONENT}. Use ${ORDER_ENTRY} instad.`,
```

2021-06-04 08:32 UTC, marlass commented
Merged to `epic/4-0-deprecations`

2021-06-04 08:32 UTC, closed without merging