chore: Deprecation for StoreFinderService and StoreDataService
SAP/spartacus pull request #12230
Opened 2021-04-30 09:53 UTC by Zeyber

Closes: #11093

2021-05-12 18:04 UTC, ren-tham reviewed
All changes/migration files look good. The build seems to be failing though, please have a look.

2021-06-16 15:03 UTC, marlass commented on docs/migration/4_0.md
> +- Service has been removed and functions moved to `StoreFinderService`.
Can we have removed public api migration for that?

2021-06-16 15:03 UTC, marlass commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/store-finder-list.component.migration.ts
> +    },
Missing param for Document.

Syntax like this is needed:

```
{
      className: DOCUMENT,
      literalInference: ANY_TYPE,
      injectionToken: {
        token: DOCUMENT_STRING,
        importPath: ANGULAR_COMMON,
      },
    },
    ```

2021-06-16 15:03 UTC, marlass commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/google-map-renderer.service.migration.ts
> +  ],
To make it produce correct order you also have to remove script loader and then add it again.

2021-06-17 11:18 UTC, marlass requested changes

2021-06-17 11:18 UTC, marlass commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/store-finder-list.component.migration.ts
> +  ],
To have correct order after migration we also need to remove the `document` and add it once again

2021-06-17 11:24 UTC, marlass approved these changes

2021-06-17 11:55 UTC, merged