GH-12078: add lg property to navigation in vc interactive module
SAP/spartacus pull request #12250
Opened 2021-05-03 09:25 UTC by Changsuwan

2021-05-03 11:56 UTC, ChristophHi requested changes
The issue still persists. I am testing on Mac/Chrome

2021-05-04 14:04 UTC, Changsuwan commented
With the current fix, the group menu in the hamburger menu disappears with a little delay. However, according to the product owner, the result of the fix is acceptable.

2021-05-05 12:55 UTC, ChristophHi approved these changes

2021-05-05 13:07 UTC, ChristophHi requested changes
Please add this change to  /feature-libs/product-configurator/rulebased/root/cpq/cpq-configurator-interactive.module.ts also

2021-05-05 13:13 UTC, ChristophHi approved these changes

2021-05-05 14:41 UTC, merged