chore: Deprecation for SelectiveCartService  in 4.0
SAP/spartacus pull request #12264
Opened 2021-05-04 10:37 UTC by dydome

close #10547

2021-05-06 13:52 UTC, marlass requested changes
Could you add info to the migration doc as well?

2021-05-07 06:41 UTC, dydome commented
> Could you add info to the migration doc as well?

Added

2021-05-07 09:10 UTC, marlass approved these changes

2021-06-04 08:00 UTC, marlass commented
Merged to `epic/4-0-deprecations`

2021-06-04 08:00 UTC, closed without merging