chore: replace getUrl method from OccEndpointsService with buildUrl
SAP/spartacus pull request #12282
Opened 2021-05-04 20:01 UTC by saad-mo

PR  1 of 3 for #10729

2021-05-12 18:13 UTC, LTiger14 requested changes

2021-05-12 18:13 UTC, LTiger14 commented on projects/storefrontlib/src/shared/components/modal/modal.directive.ts
> +  protected buildUrl(): string | undefined {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/checkout/guards/checkout-steps-set.guard.ts
> +          return of(this.buildUrl('checkout'));
Revert changes on this file, this shouldn't have been changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/smart-edit/smart-edit.module.ts
> +@NgModule({
Why has this changed? Make sure your branch is up to date.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/smart-edit/services/smart-edit.service.ts
> +    return this.moduleToken && this._launchedInSmartEdit;
Why has this changed? Make sure your branch is up to date.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/smart-edit/smart-edit.token.ts
> +);
Why has this changed? Make sure your branch is up to date.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/site-context/services/site-context-url-serializer.spec.ts
> +    buildUrlEncodingParameters: () => ['language', 'currency'],
Revert changes on this file, this shouldn't have been changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/site-context/services/site-context-url-serializer.ts
> +    return this.siteContextParams.buildUrlEncodingParameters();
Revert changes on this file, this shouldn't have been changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/site-context/services/site-context-params.service.ts
> +  buildUrlEncodingParameters(): string[] {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/site-context/services/site-context-routes-handler.spec.ts
> +      buildUrlEncodingParameters: () => ['language'],
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/site-context/services/site-context-routes-handler.ts
> +    const routingParams = this.siteContextParams.buildUrlEncodingParameters();
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/site-context/config/config-loader/site-context-config-initializer.ts
> +  private buildUrlParams(params: string[] | undefined): string[] {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/routing/facade/routing.service.ts
> +  buildUrl(commands: UrlCommands, extras?: NavigationExtras): string {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/routing/facade/routing.service.spec.ts
> +  describe('buildUrl', () => {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/routing/external-routes/external-routes.service.ts
> +  protected buildUrlMatcher(): UrlMatcher {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/services/occ-fields.service.ts
> +  private buildUrlWithFields(url: string, fields: (string | object)[]): string {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/config-loader/occ-loaded-config-converter.ts
> +  private buildUrlParams(params: string[]): string[] {
Please revert, this shouldn't have changed.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/organization/administration/occ/converters/occ-org-unit-approval-processes-normalizer.spec.ts
>      (url, { orgUnitId }) => (url === 'orgUnit' ? url + orgUnitId : url)
should be `{ urlParams: { orgUnitId }}`

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/organization/administration/occ/converters/occ-org-unit-node-list-normalizer.spec.ts
>      (url, { orgUnitId }) => (url === 'orgUnit' ? url + orgUnitId : url)
should be `{ urlParams: { orgUnitId }}`

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/organization/administration/occ/converters/occ-org-unit-node-normalizer.spec.ts
>      (url, { orgUnitId }) => (url === 'orgUnit' ? url + orgUnitId : url)
should be `{ urlParams: { orgUnitId }}`

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/organization/administration/occ/converters/occ-org-unit-normalizer.spec.ts
>      (url, { orgUnitId }) => (url === 'orgUnit' ? url + orgUnitId : url)
should be `{ urlParams: { orgUnitId }}`

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/product-configurator/common/assets/ng-package.json
> +    "entryFile": "./public_api.ts",
Why is this change here? Please make sure your branch is up to date.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/product-configurator/rulebased/components/previous-next-buttons/configurator-previous-next-buttons.component.spec.ts
>    getCurrentGroupId() {
Why are there changes on this file? Please make sure your branch is up to date.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/product-configurator/rulebased/components/previous-next-buttons/configurator-previous-next-buttons.component.ts
> +                    delay(0) //we need to consider the re-rendering of the page
Please make sure your branch is up to date.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.spec.ts
> +import { Type } from '@angular/core';
Why are there changes on this file? Please make sure your branch is up to date.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/product-configurator/rulebased/cpq/occ/cpq-configurator-occ.service.spec.ts
> +    buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
This is not the correct function definition. It should be `buildUrl(endpoint: string, attributes?: DynamicAttributes, propertiesToOmit?: BaseOccUrlProperties)`.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/product-configurator/rulebased/occ/variant/variant-configurator-occ.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
This is not the correct function definition. It should be `buildUrl(endpoint: string, attributes?: DynamicAttributes, propertiesToOmit?: BaseOccUrlProperties)`.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/product-configurator/textfield/occ/occ-configurator-textfield.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
This is not the correct function definition. It should be `buildUrl(endpoint: string, attributes?: DynamicAttributes, propertiesToOmit?: BaseOccUrlProperties)`.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/storefinder/occ/adapters/occ-store-finder.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
This is not the correct function definition. It should be `buildUrl(endpoint: string, attributes?: DynamicAttributes, propertiesToOmit?: BaseOccUrlProperties)`.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/user/account/components/login-register/login-register.module.ts
> +  imports: [CommonModule, RouterModule, UrlModule, PageSlotModule, I18nModule],
Should not be here after you update your branch.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/user/account/occ/adapters/occ-user-account.adapter.spec.ts
> +  buildUrl(endpointKey: string, _urlParams?: object, _queryParams?: object) {
This is not the correct function definition. It should be `buildUrl(endpoint: string, attributes?: DynamicAttributes, propertiesToOmit?: BaseOccUrlProperties)`.

2021-05-12 18:13 UTC, LTiger14 commented on feature-libs/user/profile/occ/adapters/occ-user-profile.adapter.spec.ts
> +  buildUrl(endpointKey: string, _urlParams?: object, _queryParams?: object) {
This is not the correct function definition. It should be `buildUrl(endpoint: string, attributes?: DynamicAttributes, propertiesToOmit?: BaseOccUrlProperties)`.

2021-05-12 18:13 UTC, LTiger14 commented on integration-libs/cds/.release-it.json
> +            "peerDependencies.@spartacus/schematics",
Should not be here after you update the branch.

2021-05-12 18:13 UTC, LTiger14 commented on integration-libs/cds/src/services/cds-endpoints.service.ts
> +  buildUrl(
Keep this as `getUrl` and make the necessary changes.

2021-05-12 18:13 UTC, LTiger14 commented on integration-libs/cds/src/services/cds-endpoints.service.spec.ts
> +  describe('buildUrl', () => {
All should be `getUrl`

2021-05-12 18:13 UTC, LTiger14 commented on integration-libs/cds/src/merchandising/adapters/strategy/cds-merchandising-strategy.adapter.ts
> +      this.cdsEndpointsService.buildUrl(
The `cdsEndpointsService` only has a `getUrl`.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/anonymous-consents/http-interceptors/anonymous-consents-interceptor.ts
> +                this.occEndpoints.buildUrl('anonymousConsentTemplates')
Should be `getUrl`

2021-05-12 18:13 UTC, LTiger14 commented on integration-libs/cds/src/merchandising/adapters/strategy/cds-merchandising-strategy.adapter.spec.ts
> +  buildUrl = createSpy('MockCdsEndpointsService.buildUrl').and.callFake(
Should all be `getUrl`

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/cart/event/cart-event.builder.spec.ts
>    CartAddEntryEvent,
This file should not be changed once you update your branch.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/cart/event/cart-event.builder.ts
>    CartAddEntryEvent,
This file should not be changed once you update your branch.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/cart/event/cart.events.ts
>    quantity: number;
This file should not be changed once you update your branch.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/cms/page/routing/routing-page-meta.resolver.ts
> +  private buildUrlPart(route: ActivatedRouteSnapshot): string {
Should not be changed

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/cms/services/dynamic-attribute.service.spec.ts
> +const mockProperties = {
This file should not be changed once you update your branch.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/cms/services/dynamic-attribute.service.ts
> +    const properties =
This file should not be changed once you update your branch.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/global-message/http-interceptors/handlers/forbidden/forbidden.handler.ts
> +          queryParams: { userId: 'current' },
This should be a `urlParams`

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/adapters/cart/occ-cart-entry.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
Wrong method definition.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/adapters/cart/occ-cart.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
Wrong method definition.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/adapters/cart/occ-save-cart.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
Wrong method definition.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/adapters/checkout/occ-checkout-delivery.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
Wrong method definition.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/adapters/checkout/occ-checkout.adapter.spec.ts
> +  buildUrl(endpoint: string, _urlParams?: object, _queryParams?: object) {
Wrong method definition. Please go through all the files.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/adapters/cms/occ-cms-component.adapter.ts
> +    // const context = this.getContextParams(pageContext);
Please remove this comment.

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/adapters/product/occ-product.adapter.ts
> +      queryParams: undefined,
You don't need `queryParams: undefined,`

2021-05-12 18:13 UTC, LTiger14 commented on projects/core/src/occ/services/occ-endpoints.service.spec.ts
> +  describe('buildUrl', () => {
You can delete this block, there was already one for the `buildUrl` function.

2021-05-14 17:37 UTC, saad-mo commented on projects/core/src/anonymous-consents/http-interceptors/anonymous-consents-interceptor.ts
> +                this.occEndpoints.buildUrl('anonymousConsentTemplates')
since `getUrl` has been removed from `OccEndpointsService`, I beive it should still be `buildUrl` in this case?

2021-05-19 13:44 UTC, LTiger14 requested changes

2021-05-19 13:44 UTC, LTiger14 commented on feature-libs/organization/administration/occ/converters/occ-org-unit-node-list-normalizer.spec.ts
>          },
This provider doesn't look like it's required please make sure it is. If it is required it should just be `OccEndpointService` no need for the { provide }

2021-05-19 13:44 UTC, LTiger14 commented on projects/core/src/occ/adapters/cms/legacy-occ-cms-component.adapter.spec.ts
> +
Remove white space please

2021-05-19 13:44 UTC, LTiger14 commented on projects/core/src/occ/adapters/cms/legacy-occ-cms-component.adapter.spec.ts
> +  function assertPostRequestbuildUrl(fields: string, pageSize: string) {
Should be names `assertPostRequestBuildUrl`

2021-05-19 18:54 UTC, saad-mo commented
Fresh PR with only the changed files #12512

2021-05-19 18:54 UTC, closed without merging