Removed deprecations + added augmentation for occendpoints
SAP/spartacus pull request #12335
Opened 2021-05-06 20:54 UTC by bgambocjaviniar

closes GH-11507

2021-05-12 17:04 UTC, WeizhengSap commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
> +    comment: `'${ASM_MODULE}' was moved to @spartacus/asm.`,
moved to @spartacus/asm/components

2021-05-12 17:18 UTC, WeizhengSap commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
> +  },
`AsmConfig` is also deprecated. So, it is missing in here.

2021-05-12 17:19 UTC, WeizhengSap requested changes
see my comments.

2021-05-12 17:45 UTC, WeizhengSap approved these changes, later dismissed

2021-06-01 14:00 UTC, WeizhengSap submitted a review, later dismissed

2021-06-03 17:41 UTC, marlass approved these changes

2021-06-03 17:42 UTC, merged