chore: deprecation of SmartEditModule in 4.0
SAP/spartacus pull request #12345
Opened 2021-05-07 12:54 UTC by WeizhengSap

close #12168

2021-05-14 13:28 UTC, bgambocjaviniar requested changes

2021-05-14 13:28 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/dynamic-attribute.service.migration.ts
> +      className: SMART_EDIT_SERVICE,
👍 

was confused at first, but then I found it was only smart_edit_service that was always available before from https://github.com/SAP/spartacus/pull/10700/files

2021-05-14 13:28 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/4_0/methods-and-properties-deprecations/methods-and-properties-deprecations.ts
> +  ...PAGE_EVENT_BUILDER_MIGRATION,
👍

2021-05-14 13:28 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
> +    node: 'SmartEditModule',
make these into constants as done above in other files `projects/schematics/src/shared/constants.ts`

2021-06-03 13:47 UTC, bgambocjaviniar requested changes

2021-06-03 13:47 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
>      comment: `'SmartEditModule was removed. Use @spartacus/smartedit instead.`,
replace `'SmartEditModule` with `${SMART_EDIT_MODULE}`

2021-06-03 13:47 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
>      comment: `'SmartEditService was moved to @spartacus/smartedit/core.`,
replace `'SmartEditService` with `${SMART_EDIT_SERVICE}`

2021-06-03 14:05 UTC, bgambocjaviniar approved these changes

2021-06-04 09:13 UTC, marlass commented
Merged to `epic/4-0-deprecations`

2021-06-04 09:13 UTC, closed without merging