feat: Add saved cart page meta resolver to add breadcrumbs for saved cart details
SAP/spartacus pull request #12548
Opened 2021-05-26 12:33 UTC by dydome

close #12545

2021-05-26 12:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +   * Translation key for the breadcrumb of Organization home page
Saved cart 👍 

but I guess similar to organization, we can follow it's practices and make it like cart.breadcrumb

2021-05-27 03:41 UTC, bgambocjaviniar requested changes
main things on the PR:

1 - fix your build as it breaks now when building the cart library (saved cart)
2 - fix instances of keywords of 'Organization' from this PR
3 - rename breadcrumb to Saved Carts similarly to how Accelerator is functioning
4 - question for is you: do we need the robot method? I would say maybe, but the path is protected, so it would not make sense to have it searcheable by web scrapers. Maybe not?

2021-05-27 03:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +   * It's empty when the current page is the SAved Cart page.
Saved* instead of SAved

2021-05-27 03:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> + * Resolves the page data for Organization Pages.
Saved Cart Pages

2021-05-27 03:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +   * Translation key for the breadcrumb of Organization home page
Saved cart 👍

but I guess similar to organization, we can follow it's practices and make it like savedCarts.breadcrumb

2021-05-27 03:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/assets/translations/en/saved-cart.i18n.ts
> +export const breadcrumb = 'Saved Carts List';
let's move this to the `saveCartList` obj 
line 15

2021-05-27 03:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +    protected semanticPath: SemanticPathService,
This dependency isn't being used. I believe what you want to do is check the semantic routes for `savedCarts`

You can do that by using this service.get in order to get the path that's hardcoded as `SAVED_CART_HOME_PATH`

2021-05-27 03:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/assets/translations/en/saved-cart.i18n.ts
> +export const breadcrumb = 'Saved Carts List';
Also, rename it to Saved Carts instead similar to how Accelerator did it back in the days

2021-05-27 03:41 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +    protected semanticPath: SemanticPathService,
Therefore, remove that hard-coded variable

2021-05-27 03:42 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +                link: this.SAVED_CART_HOME_PATH,
similar to. https://github.com/SAP/spartacus/pull/12548#discussion_r640253122

2021-05-27 18:00 UTC, bgambocjaviniar requested changes
1 - address the issues, but don't resolve them if you didn't fix them or comment why you are resolving them
2 - do not forget that I want to support the `resolveRobots` method as the cms page from Accelerator contained the property `robotTag` and has a follow set with it

![Screen Shot 2021-05-27 at 12 48 19 PM](https://user-images.githubusercontent.com/29099466/119874686-e26c2280-bef3-11eb-87a9-8bfa5460330e.png)

2021-05-27 18:00 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> + * @property {string} SAVED_CART_HOME_PATH the default path for Saved Cart home poge.
You missed this (to remove since we no longer have this variable)

2021-05-27 18:00 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +        const [home] = breadcrumbs;
I liked how it was before instead of this.

Remove it and put it back to what it was
```
const [home, ...restBreadcrumbs] = breadcrumbs ?? [];
return [home, ...savedCartPageBreadcrumb, ...restBreadcrumbs];
```

The only difference to make the build pass was to do .... ?? [];

2021-05-27 18:00 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +        const [home] = breadcrumbs;
update unit tests accordingly

2021-05-27 20:39 UTC, dydome commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +        const [home] = breadcrumbs;
I spoke about it with Marcin and he said to remove part 'restBreadcrumbs' as here in saved cart it is not in use.

2021-05-27 20:59 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +        const [home] = breadcrumbs;
I agree that it's not in use, but it solidifies it in case there's future pages no?

2021-05-28 03:31 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/assets/translations/translations.ts
> +    'breadcrumb',
No longer have breadcrumb only. Need to remove

2021-05-28 03:38 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/core/services/saved-cart-page-meta.resolver.ts
> +        const [home] = breadcrumbs;
Well if Marcin agrees of that implementation above, then okay

2021-05-28 03:39 UTC, bgambocjaviniar commented on feature-libs/cart/saved-cart/assets/translations/translations.ts
> +    'breadcrumb',
After fixing this, I believe we can merge it in the morning my time

2021-05-28 03:44 UTC, bgambocjaviniar requested changes
After fixing the dangling breadcrumb above, it should be mergeable soon

1 problem from smoke test that I found is if you visit the saved cart (listing) page, then go to another page that has breadcrumb from my-accounts, then saved carts breadcrumb will always be part of the breadcrumbs, which is not good. Not sure where the bug is.

For example, to reproduce:
1 - go to the saved cart listing page through my-account
2 - click any other my-account like password, email address, my-company and the breadcrumb will always consist of Home / Saved carts even when you navigate elsewhere.
![Screen Shot 2021-05-27 at 11 42 50 PM](https://user-images.githubusercontent.com/29099466/119926386-5256c900-bf45-11eb-8f2c-a352531d191e.png)

2021-05-28 12:50 UTC, bgambocjaviniar approved these changes

2021-05-31 07:23 UTC, merged