chore: Deprecation for Remove duplicated launch dialog services
SAP/spartacus pull request #12570
Opened 2021-05-28 11:51 UTC by Pucek9

Closes #12167

2021-05-28 18:56 UTC, plabadie commented on feature-libs/checkout/occ/adapters/occ-checkout-delivery.adapter.ts
> +  protected setDeliveryAddressEndpoint(
I may be missing something, but since this `setDeliveryAddressEndpoint` returns an endpoint, should it not be called `get{something}Endpoint`?

2021-05-28 19:07 UTC, plabadie approved these changes

2021-05-29 08:24 UTC, marlass requested changes
Would be good to validate all endpoints with their usage and rename them from generic endpoints like "deliveryAddresses" -> "createDeliveryAddress" and "removeDeliveryAddress" etc.

This should be simple for customer to understand for which actions we use particular endpoint and not to go through our code to find out.

2021-05-29 08:24 UTC, marlass commented on feature-libs/checkout/occ/model/occ-checkout-endpoints.model.ts
> +    deliveryAddresses?: string | OccEndpoint;
Can we rename this endpoint to `createDeliveryAddress`?

2021-05-29 08:24 UTC, marlass commented on feature-libs/checkout/occ/adapters/occ-checkout-cost-center.adapter.ts
> +  protected getCartCostCenterEndpoint(
Can we also rename it to `getSetCartCostCenterEndpoint` for consistency as we changed name of the endpoint?

2021-05-29 08:24 UTC, marlass commented on feature-libs/checkout/occ/adapters/occ-checkout-delivery.adapter.ts
> +  protected setDeliveryAddressEndpoint(
I think all these methods should start with `get`. This one is especially confusing as the name suggests that this methods sets delivery address endpoint. and not only gives you "setDeliveryAddress" endpoint

2021-06-07 07:24 UTC, marlass approved these changes

2021-06-08 20:20 UTC, merged