GH-12190: Remove checkout dependencies in PromotionService
SAP/spartacus pull request #12651
Opened 2021-06-02 19:19 UTC by plabadie

closes GH-12190

2021-06-04 14:21 UTC, WeizhengSap commented on projects/storefrontlib/src/shared/services/promotion/abstract-promotion.service.ts
> +import { Cart, Order, OrderEntry, PromotionResult } from '@spartacus/core';
How about this:
```
@Injectable()
export abstract class PromotionService {
  protected loacatin: PromotionLocation;
  
  abstract getOrderPromotions();

  // then the functions used by children
  getProductPromotionForEntry;
  getProductPromotion;
  isConsumedByEntry;
```
Then in checkout:
```
@Injectable({
  providedIn: 'root',
})
export class CheckoutPromotionService extends PromotionService {
  location = PromotionLocation.Checkout;

  // then implement the getOrderPromotions(), also move the getOrderPromotionsFromOrderHelper to this class.
```
When use it in checkout:
```
providers: [
            {
              provide: PromotionService,
              useExisting: CheckoutPromotionService,
            },
          ],
```
same thing for the `Order` and `ActiveCart`

2021-06-04 14:38 UTC, WeizhengSap commented on projects/storefrontlib/src/shared/services/promotion/abstract-promotion.service.ts
> +import { Cart, Order, OrderEntry, PromotionResult } from '@spartacus/core';
`getOrderPromotion` maybe can be renamed to `getPromotion`?

2021-06-04 14:38 UTC, WeizhengSap requested changes
please check my suggestion.

2021-06-08 20:13 UTC, plabadie commented
Replaced by #12686

2021-06-08 20:13 UTC, closed without merging