test: E2E Search + Checkout
SAP/spartacus pull request #12769
Opened 2021-06-14 19:52 UTC by bit172

closes #12012

2022-02-10 10:50 UTC, dydome requested changes

2022-02-10 10:50 UTC, dydome commented on projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-checkout.ts
> +export const firstAddToCartSelector = `${productSearchFlow.productItemSelector} cx-add-to-cart:first`;
not sure if it is required, I think we can put it directly in the cy.get

2022-02-10 10:50 UTC, dydome commented on projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-checkout.ts
> +export function registerUser() {
Are you sure there is no ready method for this in another place?

2022-02-10 10:50 UTC, dydome commented on projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-checkout.ts
> +  cy.wait(`@${loginPage}`);
```suggestion
  cy.wait(`@${loginPage}`).its('response.statusCode').should('eq', 200);
```

2022-02-10 10:50 UTC, dydome commented on projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-checkout.ts
> +  checkout.loginUser(sampleUser);
shouldn't we log in the user first?

2022-02-10 10:50 UTC, dydome commented on projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-checkout.ts
> +  checkout.fillAddressFormWithCheapProduct(sampleUser as AddressData, cart);
this method changed, please update

2022-02-10 10:50 UTC, dydome commented on projects/storefrontapp-e2e-cypress/cypress/helpers/product-search-checkout.ts
> +  checkout.fillPaymentFormWithCheapProduct(sampleUser as PaymentDetails);
```suggestion
  checkout.fillPaymentFormWithCheapProduct(sampleUser);
```

2022-02-10 10:50 UTC, dydome commented on projects/storefrontapp-e2e-cypress/cypress/integration/regression/product-search-checkout/product-search-checkout.e2e-spec.ts
> +      const productName = 'DSC-N1';
shouldn't we use any product from helpers?

2022-02-16 19:03 UTC, bit172 commented
These tests will be rewritten since most functions are outdated

2022-02-23 08:22 UTC, dydome approved these changes

2022-02-23 08:22 UTC, merged