chore: Deprecation for ExpressCheckoutService in 4.0
SAP/spartacus pull request #12868
Opened 2021-06-18 09:41 UTC by dydome

close #12855

2021-06-18 09:53 UTC, marlass requested changes

2021-06-18 09:53 UTC, marlass commented on projects/schematics/src/shared/constants.ts
> +export const SPARTACUS_CHECKOUT_ROOT = `${SPARTACUS_CHECKOUT}/administration/root`;
administration? 👀

2021-06-18 09:53 UTC, marlass commented on feature-libs/checkout/components/services/express-checkout.service.ts
> -  protected resetCheckoutProcesses() {
Also add method-property migration for this method and mention it in the docs

2021-06-18 10:28 UTC, marlass requested changes

2021-06-18 10:28 UTC, marlass commented on projects/schematics/src/migrations/4_0/methods-and-properties-deprecations/data/express-checkout.service.migration.ts
> +    comment: `// ${TODO_SPARTACUS} Method '${RESET_CHECKOUT_PROCESSES}' was removed, use '${CLEAR_CHECKOUT_SERVICE}' method instead`,
Add it also to the migration doc

2021-06-18 10:40 UTC, marlass requested changes

2021-06-18 10:40 UTC, marlass commented on docs/migration/4_0.md
> +- Method `resetCheckoutpProcesses` was removed, use `clearCheckoutService` method instead.
```suggestion
- Method `resetCheckoutProcesses` was removed, use method `resetCheckoutProcesses` from `ClearCheckoutService` instead.
```

2021-06-18 10:40 UTC, marlass commented on projects/schematics/src/migrations/4_0/methods-and-properties-deprecations/data/express-checkout.service.migration.ts
> +    comment: `// ${TODO_SPARTACUS} Method '${RESET_CHECKOUT_PROCESSES}' was removed, use '${CLEAR_CHECKOUT_SERVICE}' method instead`,
```suggestion
    comment: `// ${TODO_SPARTACUS} Method '${RESET_CHECKOUT_PROCESSES}' was removed, use method '${RESET_CHECKOUT_PROCESSES}' from '${CLEAR_CHECKOUT_SERVICE}' instead`,
```

2021-06-18 10:44 UTC, marlass approved these changes, later dismissed

2021-06-21 08:35 UTC, marlass approved these changes, later dismissed

2021-06-25 08:32 UTC, dydome commented
Currently suspended. Architects' analysis needed, waiting for @marlasak  decision.

2021-06-29 09:09 UTC, znikola requested changes

2021-06-29 09:09 UTC, znikola commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/express-checkout.service.migration.ts
> +  importPath: SPARTACUS_CHECKOUT_CORE,
According to the written 4_0.md file, the `express-checkout.service.ts` is now in the `@spartacus/checkout/components`, while the `SPARTACUS_CHECKOUT_CORE` constants points to `@spartacus/checkout/core`

2021-06-29 09:09 UTC, znikola commented on projects/schematics/src/migrations/4_0/rename-symbol/rename-symbol.ts
> +import { SPARTACUS_CHECKOUT_ROOT } from 'feature-libs/checkout/schematics/constants';
Please fix the import

2021-06-30 14:50 UTC, marlass approved these changes

2021-06-30 18:03 UTC, merged