chore: Deprecations in ModalService
SAP/spartacus pull request #12891
Opened 2021-06-21 13:15 UTC by bgambocjaviniar

closes GH-12865

2021-06-23 17:39 UTC, marlass requested changes

2021-06-23 17:39 UTC, marlass commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/modal.service.migration.ts
> +};
Could you add second migration for situation where customer didn't provided ApplicationRef and FeatureConfigService?


Also in this migration you don't need `addParam`, as this migration will work for customers that provided both of those services, so only the remove was needed.

2021-06-23 18:32 UTC, marlass requested changes

2021-06-23 18:32 UTC, marlass commented on projects/schematics/src/migrations/4_0/constructor-deprecations/data/modal.service.migration.ts
> +    { className: FEATURE_CONFIG_SERVICE, importPath: SPARTACUS_STOREFRONTLIB },
In this case, we only want to add application ref.

2021-06-23 18:32 UTC, marlass commented on docs/migration/4_0.md
> +- Removed `FeatureConfigService` from constructor.
It would be good to mention that applicationRef is required parameter now

2021-06-23 18:39 UTC, marlass approved these changes, later dismissed

2021-06-28 13:15 UTC, LTiger14 approved these changes

2021-06-28 18:09 UTC, merged