fix: Labels updates for screen reader support GH-11192
SAP/spartacus pull request #12952
Opened 2021-06-28 14:54 UTC by saad-mo

This PR includes Label changes from #11192.

Closes #11192

2021-06-30 17:33 UTC, hackergil requested changes

2021-06-30 17:33 UTC, hackergil commented on projects/storefrontlib/src/shared/components/list-navigation/sorting/sorting.component.ts
> +  get selectedLabel() {
Please add a unit test for this method

2021-06-30 22:21 UTC, saad-mo commented on projects/storefrontlib/src/shared/components/list-navigation/sorting/sorting.component.ts
> +  get selectedLabel() {
@Pucek9

2021-07-05 17:36 UTC, hackergil approved these changes, later dismissed

2021-07-14 19:54 UTC, hackergil submitted a review, later dismissed

2021-07-16 14:50 UTC, hackergil approved these changes

2021-07-16 15:57 UTC, merged