feat: add theme parameter to schematics install
SAP/spartacus pull request #13057
Opened 2021-07-08 20:38 UTC by LTiger14

closes #13056

2021-07-09 08:59 UTC, znikola requested changes

2021-07-09 08:59 UTC, znikola commented on projects/schematics/src/add-spartacus/index.ts
> +    if (options && options.theme) {
Can we use optional chaining?

2021-07-09 08:59 UTC, znikola commented on projects/schematics/src/add-spartacus/schema.json
> +    "theme": {
Do we want to make it interactive, so that a user can choose from a list?
If we decide to take this approach, make sure there's a sensible default set, for cases when this is ran with `--interactive=false`

2021-07-12 14:18 UTC, LTiger14 commented on projects/schematics/src/add-spartacus/schema.json
> +    "theme": {
Discussed offline, for now we will keep it as is so as not to force an additional step.

2021-07-12 15:38 UTC, znikola approved these changes, later dismissed

2021-07-14 14:12 UTC, znikola approved these changes

2021-07-14 14:12 UTC, merged