chore: improve 4.0 migrations - part 2
SAP/spartacus pull request #13168
Opened 2021-07-16 17:40 UTC by Platonn

related to #13082

2021-07-19 09:08 UTC, znikola commented on projects/schematics/src/migrations/4_0/rename-symbol/rename-symbol.ts
> +    // projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item/cart-item.component.ts
Nitpick: this comment should be before the object ;)

2021-07-19 09:08 UTC, znikola commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
> +    comment: `'${PERSONALIZATION_MODULE}' was removed. Use @spartacus/tracking/personalization instead. To benefit from lazy loading it by default, consider removing the module import and running the
As `Personalization` is just a feature from the tracking lib, maybe we can specify the command like so:
`ng add @spartacus/tracking --features=Personalization`. What do you think?

2021-07-19 09:08 UTC, znikola commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
>      node: PRODUCT_VARIANTS_MODULE,
On line 228 we also have the AsmModule migration. Maybe we should mention the "To benefit from lazy loading it by default, consider removing the module import and running the command..."?

2021-07-20 09:47 UTC, znikola requested changes

2021-07-20 09:47 UTC, znikola commented on projects/schematics/src/migrations/4_0/removed-public-api-deprecations/removed-public-api-deprecation.ts
> +    comment: `'${PRODUCT_VARIANTS_MODULE}' was removed from @spartacus/storefront. Use @spartacus/product/variants feature-library instead. To benefit from lazy loading it by default, consider removi
Similar to the personalization, we can specify the exact feature: `--features=Product-Variants`

2021-07-20 09:59 UTC, znikola approved these changes

2021-07-20 10:19 UTC, dunqan approved these changes

2021-07-20 10:47 UTC, merged