chore: improve the docs of the 4.0 migration process
SAP/spartacus pull request #13165
Opened 2021-07-16 16:34 UTC by Platonn

TODO: backport it to the maintenance branch

2021-07-19 08:12 UTC, znikola requested changes

2021-07-19 08:12 UTC, znikola commented on docs/migration/4_0.md
> +When the update has finished running, inspect your code for comments that begin with `// TODO:Spartacus`. For detailed information about each injected comment, see [Detailed List of Changes](#detaile
I wouldn't use the `injected` term here. Maybe just "added"?

2021-07-19 08:12 UTC, znikola commented on docs/migration/4_0.md
> +ng update @ng-bootstrap/ng-bootstrap@10 @ng-select/ng-select@7 @angular/cli@12
When upgrading angular, we should run `ng update @angular/core@12 @angular/cli@12` (both core and cli, and not just cli).

2021-07-20 09:43 UTC, znikola approved these changes

2021-07-20 09:50 UTC, dunqan approved these changes

2021-07-20 10:16 UTC, merged