Fix for isStable loading for quick order
SAP/spartacus pull request #13294
Opened 2021-07-29 12:54 UTC by dydome

close #13282

2021-07-30 02:58 UTC, bgambocjaviniar commented on feature-libs/cart/quick-order/components/quick-order/quick-order.component.ts
> +  isCartStable$: Observable<any> = combineLatest([
Let's talk after/before standup

I'm not quite sure why we need a spinner for your page as it's not dependent on any data especially with cart.

2021-07-30 03:33 UTC, bgambocjaviniar commented on feature-libs/cart/quick-order/components/quick-order/quick-order.component.ts
> +  isCartStable$: Observable<any> = combineLatest([
```suggestion
  isCartStable$: Observable<boolean> = combineLatest([
```

However, let's talk about this, or maybe you can bring this up to someone as I know GC will complain once he sees this flicker.

Example of the flicker @ 19s and 34s


https://user-images.githubusercontent.com/29099466/127596047-30c191ef-d7f2-4bfc-b620-7059ed9bd590.mov

2021-07-30 03:43 UTC, bgambocjaviniar commented on feature-libs/cart/quick-order/components/quick-order/quick-order.component.ts
> +  isCartStable$: Observable<any> = combineLatest([
You can try hooknig into the `CartAddEntryEvent` for load and remove the spinner when `CartEntryAddEntrySuccess/FailEvent` is fired

2021-08-06 05:09 UTC, bgambocjaviniar requested changes
LGTM, just some naming differences + needing unit test

However, as long as the team agrees about disabling most of the links / actions on the page, then I'm all for it. Reason why I'm asking is I see we're disabling links to the product and such, but we can always navigate out of this page by clicking a category, homepage, my-account, etc.

2021-08-06 05:09 UTC, bgambocjaviniar commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +  get loading(): boolean {
we have one above called `isDisabled`, so let's name this `isLoading` to stay consistent. Update instances throughout the PR as well.

2021-08-06 05:09 UTC, bgambocjaviniar commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +    this._loading = value;
add unit test for this to see if the input is disabled similarly to `isDisabled` unit test.

2021-08-06 05:09 UTC, bgambocjaviniar commented on feature-libs/cart/quick-order/components/quick-order/quick-order.component.ts
> +  isCartStable$: Observable<boolean> = combineLatest([
add unit test for this to determine the output of each emission

2021-08-06 09:20 UTC, mszczepaniak approved these changes

2021-08-06 09:50 UTC, merged