fix: Add CDS E2E tests to pipeline (GH-12732)
SAP/spartacus pull request #13668
Opened 2021-09-09 15:04 UTC by ShankariGiri-I

The goal of this PR is to update and include CDS e2e tests to the travis pipeline so that its easy to test the integration library whenever a new version of spartacus needs to be released. 

The changes in this PR attempts to close: [GH-12732](https://github.com/SAP/spartacus/issues/12732)

2021-09-14 15:04 UTC, bgambocjaviniar reviewed
waiting on https://github.com/SAP/spartacus/pull/13685 to be merged before testing the e2e

2021-09-16 14:38 UTC, ShankariGiri-I commented
Agree! However, the merchandising tests are being handled by team occtopus and they have time to fix this only in their upcoming sprint https://cxjira.sap.com/browse/OCC-6118. We thought we could get profile-tag tests to be working in the meantime.

2021-10-08 14:39 UTC, bgambocjaviniar requested changes

2021-10-08 14:39 UTC, bgambocjaviniar commented on package.json
> +    "start:cds": "env-cmd --no-override -e dev,b2c,cds,$SPA_ENV ng serve",
let's remove this

as you can always set cds to true before starting the application as follows

1 - go to `.env-cmd` and make B2C for `CX_CDS` true OR go to `environment.ts` and set remove the build.process and set it to true for CDS

2021-10-08 14:39 UTC, bgambocjaviniar commented on .env-cmdrc
> +    "CX_CDS": "true"
add CX_CDS to false under b2c as well

2021-10-13 13:30 UTC, bgambocjaviniar approved these changes

2021-10-13 13:34 UTC, merged