fix: Add vocalized feedback on Order Confirmation for SR users
SAP/spartacus pull request #13727
Opened 2021-09-15 13:53 UTC by BenjaminEmiliani

Closes #13587

2021-09-22 17:03 UTC, saad-mo commented
Code changes look good. Let's wait for @developpeurweb to his SR review.

2021-09-23 21:04 UTC, developpeurweb requested changes, later dismissed
This works well with VoiceOver. 
Unfortunately, it doesn't work with JAWS and NVDA.
I don't have modification suggestions at this point. I'll keep researching, gather some references and get back to you.

2021-10-15 17:25 UTC, developpeurweb commented on feature-libs/checkout/components/order-confirmation/components/order-confirmation-thank-you-message/order-confirmation-thank-you-message.component.html
> +  <div aria-live="assertive" aria-atomic="true">
Unfortunately, this still doesn't work for JAWS and NVDA.
I was wondering if it would be possible to add a "success" global message with the order number and the email being sent text. Even if it's a breaking change and push for 5.0.

2021-12-29 17:09 UTC, BenjaminEmiliani commented
No solution has worked for all screen readers. Closing PR. Implement solution once #14371 is done

2021-12-29 17:09 UTC, closed without merging