feat: warning about product out of stock
SAP/spartacus pull request #13744
Opened 2021-09-16 10:35 UTC by psmul

Closes: #11907

2021-09-16 11:03 UTC, dydome requested changes

2021-09-16 11:03 UTC, dydome commented on projects/storefrontlib/src/cms-components/cart/validation/cart-item-warning/cart-validation-cart-item-warning.component.html
> +<ng-container *ngIf="cartModification$ | async as cartModification">
What you think to use here 'cx-message' component which is new type of messages with ng-content so you can put inside all you want, and in near future probably it will be somehow implement in global message?

2021-09-16 11:03 UTC, dydome commented on projects/storefrontlib/src/cms-components/cart/cart-shared/cart-shared.module.ts
> +import { CartValidationCartItemWarningModule } from '../validation/cart-item-warning/cart-validation-cart-item-warning.module';
I will suggest changing the naming here as a double cart is not necessary.

2021-09-16 11:03 UTC, dydome commented on projects/storefrontlib/src/cms-components/cart/validation/cart-validation-warnings-state.service.ts
> +  shouldEndClear$ = new Subject<boolean>();
not sure what means 'shouldEndClear' maybe a different name?

2021-09-16 12:27 UTC, psmul commented on projects/storefrontlib/src/cms-components/cart/validation/cart-item-warning/cart-validation-cart-item-warning.component.html
> +<ng-container *ngIf="cartModification$ | async as cartModification">
So I made a quick test with cx-message, but sadly it doesn't fit my needs. API differs too much to be useful in this case.

2021-09-17 09:19 UTC, dydome requested changes

2021-09-17 09:19 UTC, dydome commented on projects/storefrontlib/cms-components/cart/validation/cart-item-warning/cart-item-validation-warning.component.ts
> +  selector: 'cx-cart-validation-cart-item-warning',
I think select name should also change

2021-09-17 09:19 UTC, dydome commented on projects/storefrontlib/cms-components/cart/cart-shared/cart-item/cart-item.component.html
> +  <cx-cart-validation-cart-item-warning
probably wrong selector name is here

2021-09-17 09:19 UTC, dydome commented on projects/storefrontstyles/scss/components/cart/_cart-item-validation-warning.scss
> +%cx-cart-validation-cart-item-warning {
probably to change

2021-09-17 09:19 UTC, dydome commented on projects/storefrontstyles/scss/components/cart/_index.scss
> +  cx-cart-validation-cart-item-warning !default;
and here

2021-09-17 10:10 UTC, dydome approved these changes

2021-09-17 10:16 UTC, merged