fix: Prevent query initial double load
SAP/spartacus pull request #13921
Opened 2021-09-29 12:43 UTC by marlass

- [x] double loader factory execution fix
- [x] unit tests to cover query service
- [ ] incorrect order of emissions after query reset fix

Closes #13894

2021-09-29 14:35 UTC, znikola requested changes

2021-09-29 14:35 UTC, znikola commented on projects/core/src/util/command-query/query.service.ts
>      );
can we improve the jsdoc comment above?
from `if query will be unsubscribed when data is loaded, we will end up with loading flag set to true`
to `if the query will be unsubscribed from while the data is being loaded, we will end up with the loading flag set to true`

2021-09-29 14:35 UTC, znikola commented on projects/core/src/util/command-query/query.service.ts
> +      retryInterruptedLoad$,
let's also add a comment here e.g. `we need to evaluate retryInterruptedLoad$ before other triggers in order in order to not emit multiple times`

2021-09-29 14:35 UTC, znikola commented on projects/core/src/util/command-query/query.service.ts
> +      ...(options?.resetOn ?? []),
Unless I'm missing something, we shouldn't reload the data when the reset trigger fires

2021-09-29 14:35 UTC, znikola commented on projects/core/src/util/command-query/query.service.ts
> +              loading: true,
If we're just resetting the state, the `loading` flag should be false by default

2021-09-29 14:35 UTC, znikola commented on projects/core/src/util/command-query/query.service.spec.ts
>      it('should load if first accessed', () => {
Maybe these two tests should be under `describe('get')`

2021-09-29 14:35 UTC, znikola commented on projects/core/src/util/command-query/query.service.spec.ts
> +          reloadOn: [TestingEvent],
Let's rename the `TestingEvent` to `ReloadEvent`. It improves the readability of this test

2021-09-29 14:35 UTC, znikola commented on projects/core/src/util/command-query/query.service.spec.ts
> +                loading: true,
Just to understand, this one is testing the case when the reloadOn trigger fired?
And that's why the loading is true, but the data is the old one.

2021-09-30 08:18 UTC, marlass commented on projects/core/src/util/command-query/query.service.spec.ts
>      it('should load if first accessed', () => {
It kinda make sense to have them outside particular method, because they test the general create of the query not get or getState methods.

2021-10-02 12:54 UTC, znikola requested changes

2021-10-02 12:54 UTC, znikola commented on projects/core/src/util/command-query/query.service.ts
> +        return retryStream$;
We should discuss this. It can lead to some infinite loops

2021-10-04 08:00 UTC, znikola approved these changes

2021-10-11 16:23 UTC, merged