feat: Cart validation
SAP/spartacus pull request #13964
Opened 2021-10-05 12:47 UTC by psmul

Closes: #11902

2021-10-06 10:42 UTC, marlass requested changes

2021-10-06 10:42 UTC, marlass commented on projects/core/src/cart/connectors/validation/cart-validation.adapter.ts
> +  abstract load(
```suggestion
  abstract validate(
```

2021-10-06 10:42 UTC, marlass commented on projects/core/src/cart/connectors/validation/cart-validation.connector.ts
> +  }
```suggestion
  validate(cartId: string, userId: string): Observable<CartModificationList> {
    return this.adapter.validate(cartId, userId);
  }
```

2021-10-06 10:42 UTC, marlass commented on projects/core/src/cart/facade/cart-validation.service.ts
> +import { UserIdService } from '../../auth';
Can we have more precise import paths?

2021-10-06 10:42 UTC, marlass commented on projects/core/src/cart/facade/cart-validation.service.ts
> +      ]).pipe(
To be safe that we execute it only once I recommend using take(1)
```suggestion
      combineLatest([
        this.activeCartService.getActiveCartId(),
        this.userIdService.takeUserId(),
      ]).pipe(
      	take(1),
```

2021-10-06 10:42 UTC, marlass commented on projects/core/src/cart/facade/cart-validation.service.ts
> +import { UserIdService } from '../../auth';
I think it applies to more files

2021-10-06 10:42 UTC, marlass commented on projects/core/src/cart/facade/cart-validation.service.ts
> +  getCartValidationStatus(): Observable<CartModificationList> {
```suggestion
  validateCart(): Observable<CartModificationList> {
```

2021-10-06 10:42 UTC, marlass commented on projects/core/src/occ/adapters/cart/occ-cart-validation.adapter.ts
> +  load(cartId: string, userId: string): Observable<CartModificationList> {
```suggestion
  validate(cartId: string, userId: string): Observable<CartModificationList> {
```

2021-10-06 10:42 UTC, marlass commented on projects/core/src/occ/adapters/cart/occ-cart-validation.adapter.ts
> +      catchError((error) => throwError(error)),
```suggestion
      catchError((error) => throwError(normalizeHttpError(error))),
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-details/cart-details.component.html
> +      <ng-container *cxFeatureLevel="'4.1'">
```suggestion
      <ng-container *cxFeatureLevel="'4.2'">
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-shared/cart-item/cart-item.component.html
> +  <ng-container *cxFeatureLevel="'4.1'">
```suggestion
  <ng-container *cxFeatureLevel="'4.2'">
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.ts
> +   * @deprecated since 4.1
```suggestion
   * @deprecated since 4.2
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.html
> +    <ng-container *cxFeatureLevel="'!4.1'">
```suggestion
    <ng-container *cxFeatureLevel="'!4.2'">
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.html
> +    <ng-container *cxFeatureLevel="'4.1'">
```suggestion
    <ng-container *cxFeatureLevel="'4.2'">
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.ts
> +      this.router.events.subscribe((event: Event) => {
```suggestion
      this.router?.events.subscribe((event: Event) => {
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.ts
> +  buttonEnabled = true;
It's supposed to be set to true during cart validation guard?
If so, maybe it should be called `cartValidationInProgress` to give it more meaning

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.module.ts
> +import { ProgressButtonModule } from '../../../shared';
more precise import path

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-warnings-state.service.ts
> +    this.subscription.add(this.checkForValidationResultClear$.subscribe());
Can we move it to some function so it can be extended/overwrote by customers?

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-warnings-state.service.ts
> +    this.subscription?.unsubscribe();
```suggestion
    this.subscription.unsubscribe();
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-warnings-state.service.ts
> +export class CartValidationWarningsStateService implements OnDestroy {
How about a simpler name for this service?

```suggestion
export class CartValidationStateService implements OnDestroy {
```

2021-10-06 10:42 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/guards/cart-validation.guard.ts
> +  }
Can we have this logic in the service?

From here I would just call method updating result and navigationId from that service.

2021-10-07 08:41 UTC, psmul commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.ts
> +  buttonEnabled = true;
Yea idea behind it is to inform somehow user about action running in background because without that user would be left with a blocked button without any information about processing (validating) before routing further.

2021-10-11 07:26 UTC, marlass requested changes

2021-10-11 07:26 UTC, marlass commented on projects/core/src/cart/facade/cart-validation.service.ts
> +  protected getCartModificationListCommand: Command = this.command.create(
```suggestion
  protected validateCartCommand: Command = this.command.create(
```

2021-10-11 07:26 UTC, marlass commented on projects/core/src/cart/facade/cart-validation.service.ts
> +    return this.getCartModificationListCommand.execute(undefined);
```suggestion
    return this.validateCartCommand.execute();
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.ts
> +  cartValidationInProgress = true;
I think values of this variable should be the opposite. At the begging it should not be false, then switched to true, and when navigation finishes to false once again.

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/cart-totals/cart-totals.component.ts
> +    this.subscription?.unsubscribe();
```suggestion
    this.subscription.unsubscribe();
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-state.service.ts
> +  NAVIGATION_SKIPS = 2;
```suggestion
  protected NAVIGATION_SKIPS = 2;
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-state.service.ts
> +  navigationIdCount = 0;
```suggestion
  protected navigationIdCount = 0;
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-state.service.ts
> +  private subscription = new Subscription();
```suggestion
  protected subscription = new Subscription();
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-state.service.ts
> +  cartValidationResult$ = new ReplaySubject<CartModification[]>(1);
It should be visible to the outside as `Observable`, to avoid calls of `next` from outside.
```suggestion
  cartValidationResult$: Observable<CartModification[]> = new ReplaySubject<CartModification[]>(1) as Observable<CartModification[]>;
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-state.service.ts
> +  checkForValidationResultClear$ = this.routingService.getRouterState().pipe(
```suggestion
  protected checkForValidationResultClear$ = this.routingService.getRouterState().pipe(
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-state.service.ts
> +  setInitialState() {
```suggestion
  protected setInitialState() {
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-validation-state.service.ts
> +  setNavigationIdStep() {
```suggestion
  protected setNavigationIdStep() {
```

2021-10-11 07:26 UTC, marlass commented on projects/core/src/cart/facade/cart-validation.service.spec.ts
> +    service.validateCart().subscribe().unsubscribe();
```suggestion
    service.validateCart();
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-item-warning/cart-item-validation-warning.module.ts
> +import { IconModule } from '../../../misc';
precise path for import please

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-warnings/cart-validation-warnings.module.ts
> +import { IconModule } from '../../../misc';
better path

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/guards/cart-validation.guard.ts
> +    protected routingService: RoutingService
```suggestion
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-item-warning/cart-item-validation-warning.component.ts
> +      map((modificationList: CartModification[]) =>
```suggestion
      map((modificationList) =>
```

Isn't it automatically typed from the service?

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-item-warning/cart-item-validation-warning.component.ts
> +import { ICON_TYPE } from '../../../misc';
better import path

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-warnings/cart-validation-warnings.component.ts
> +  visibleWarnings: { [key: string]: boolean } = {};
```suggestion
  visibleWarnings: Record<string, boolean> = {};
```

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-warnings/cart-validation-warnings.component.ts
> +import { ICON_TYPE } from '../../../misc';
better import path

2021-10-11 07:26 UTC, marlass commented on projects/storefrontlib/cms-components/cart/validation/cart-warnings/cart-validation-warnings.component.ts
> +      map((modificationList: CartModification[]) => {
```suggestion
      map((modificationList) => {
```

2021-10-13 18:59 UTC, marlass submitted a review, later dismissed

2021-10-21 12:03 UTC, marlass approved these changes

2021-10-21 12:18 UTC, marlass approved these changes

2021-10-22 10:29 UTC, merged