Epic/quick order v2
SAP/spartacus pull request #13973
Opened 2021-10-06 07:28 UTC by dydome

Another part of Quick rder updates

2021-10-15 10:19 UTC, marlass requested changes

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/assets/translations/en/quick-order.i18n.ts
> +  entriesWereAdded: '({{ quantity }}) {{ product }} has been added to the cart',
Isn't it a breaking change? We should keep the old key at least until 5.0

2021-10-15 10:19 UTC, marlass commented on projects/storefrontapp/src/environments/environment.ts
> -  b2b: buildProcess.env.CX_B2B ?? false,
Why this change?

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +    protected winRef: WindowRef
That's a breaking change. Add new services at the end of the constructor as optional. Add deprecated version

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/core/services/quick-order.service.ts
>    ) {}
That's a breaking change. The order should be preserved of the parameters and searchAdapter should be optional. Deprecation should be done with separated deprecated constructor.

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/core/services/quick-order.service.ts
> +  protected generateOrderEntry(product: Product, quantity: number): OrderEntry {
I think quantity should also be optional for now to avoid breaking change.

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/core/services/quick-order.service.ts
> +    if (entryStockLevel && entry.quantity && entry.quantity > entryStockLevel) {
```suggestion
    if (entryStockLevel && entry.quantity > entryStockLevel) {
```

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/core/services/quick-order.service.ts
> +        if (newQuantity && entryStockLevel && newQuantity > entryStockLevel) {
```suggestion
        if (entryStockLevel && newQuantity > entryStockLevel) {
```

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/root/config/quick-order-form-config.ts
> +}
How about making this config a bit more nested, but more future-proof? If we would like for example to add maybe option in next release to configure max number of products in quick order list, we could another property to `quickOrder` instead of adding another top level config option.

```suggestion
export abstract class QuickOrderFormConfig {
  quickOrder?: {
    searchForm?: {
      displayProductImages: boolean;
      maxProducts: number;
      minCharactersBeforeRequest: number;
    }
  };
}
```

2021-10-15 10:19 UTC, marlass commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.html
> +        'quick-order-form-search-icon': !isResultsBoxOpen()
Can we keep the `search` class here and in styles until 5.0 (and mark it to removal in 5.0)? Right now it is a breaking change.

2021-10-15 10:19 UTC, marlass commented on projects/storefrontapp-e2e-cypress/cypress/integration/b2b/regression/quick-order/b2b-quick-order.e2e-spec.ts
> +      it('should show result box  for 5 products', () => {
```suggestion
      it('should show result box with 5 products', () => {
```

2021-10-15 13:04 UTC, dydome commented on projects/storefrontapp/src/environments/environment.ts
> -  b2b: buildProcess.env.CX_B2B ?? false,
not sure why I change this order, reverting

2021-10-15 13:06 UTC, dydome commented on feature-libs/cart/quick-order/core/services/quick-order.service.ts
> +        if (newQuantity && entryStockLevel && newQuantity > entryStockLevel) {
Unfortunately, tslint showing that newQuantity is possible undefined so this construction is not good

2021-10-15 13:24 UTC, dydome commented on feature-libs/cart/quick-order/root/config/quick-order-form-config.ts
> +}
agree

2021-10-18 13:00 UTC, marlass requested changes

2021-10-18 13:00 UTC, marlass commented on feature-libs/product/README.md
>  # Spartacus Product
I don't think this change should be in this PR (I guess it was part of image-zoom?

2021-10-18 13:00 UTC, marlass commented on feature-libs/cart/quick-order/core/services/quick-order.service.ts
> +  addProduct(product: Product, quantity: number = 1): void {
Params needs to be updated in QuickOrderFacade

2021-10-18 13:00 UTC, marlass commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +        (element?.className || '').includes('quick-order-form-reset-icon')
```suggestion
        (element.className || '').includes('quick-order-results-products') ||
        (element.className || '').includes('quick-order-form-reset-icon')
```

2021-10-18 13:00 UTC, marlass commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +  add(product: Product, event?: Event): void {
Does it make sense to have event optional?

2021-10-18 13:00 UTC, marlass commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +  protected isEmpty(product?: string): boolean {
```suggestion
  protected isEmpty(string?: string): boolean {
```

2021-10-18 14:46 UTC, marlass approved these changes

2021-10-18 15:38 UTC, merged