Bugfix/occ 6119
SAP/spartacus pull request #13996
Opened 2021-10-07 11:48 UTC by kinga-k

Fix for duplicate request to strategy service from merchandising carousel component.

Also fixes https://github.com/SAP/spartacus/issues/14105.

2021-10-13 19:10 UTC, bgambocjaviniar requested changes

2021-10-13 19:10 UTC, bgambocjaviniar commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +    private config: CdsConfig,
This is a breaking change, therefore you would need to deprecate this constructor and create other constructors through constructor overload.

An example would be this https://github.com/SAP/spartacus/blob/develop/projects/storefrontlib/cms-components/cart/add-to-cart/add-to-cart.component.ts#L71

---
One note, instead of having these two dependencies, we can depend maybe on only `ProfileTagLifecycleService`.consentChanged, which returns an object that shows if the consent is granted or not.

2021-10-13 19:10 UTC, bgambocjaviniar commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +    return this.consentService
As mentioned above, you can use the one dependency which would be ProfileTagLifecycleService.

**However, I do have a question.**

I believe this logic should be done in the profile tag part, where the `getConsentReference` would return empty string is consent is not given or undefined right?

2021-10-13 19:10 UTC, bgambocjaviniar commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +              startWith(''),
Can you remind me of the case for merchandising, where the consent is not given. Should it request something to the strategy endpoint if it is not given? 

I believe that would be the case as if we take a look at https://jsapps.cltq4tr3nt-contextdr1-d66-public.model-t.cc.commerce.ondemand.com/apparel-uk-spa/en/GBP/?profileTagDebug=true 
when we remove the consent, it does not send a request when it does not have a consent reference.

I believe anything related to CDS (profiletag / merchandising) can only get triggered only if the consent is given for CDS right? Therefore, keeping what it had before and removing startWith('') would solve the issue at hand.

2021-10-13 19:10 UTC, bgambocjaviniar commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +              startWith(''),
In conclusion,

1 - if logic holds for with and without consentReference to send a request to strategy, then I believe the logic, where the `getConsentReference` from profile tag service should be changed to emit an empty string or null if no consent is given.

2 - From my point of view and context, merchandising shouldn't request any data from strategies until a consent is given

3 - have to not create breaking changes as customers who uses the old versions will have their application broken once they upgrade. Make sure to create an issue in the spartacus repo to keep track of the deprecation if it needs to be done.

4 - there's a current bug with this implementation as they're no longer distinct when toggling. Make sure consent is enabled. Toggle it off and back on, and see the there's a duplicate request.

5 - merge latest integration-libs to this branch to get the e2es that Shankari merged in so that it can run against this PR as well.

2021-10-13 19:12 UTC, bgambocjaviniar commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +    private config: CdsConfig,
refer to https://github.com/SAP/spartacus/pull/13996/files#r728368238 before starting to fix/debug

2021-10-13 19:12 UTC, bgambocjaviniar commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +    return this.consentService
refer to https://github.com/SAP/spartacus/pull/13996/files#r728368238 before starting to fix/debug

2021-10-14 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/spartacus?pullRequest=13996) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/spartacus?pullRequest=13996) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: kinga-k<br/>:x: BenjaminEmiliani<br/>:x: bit172<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/spartacus?pullRequest=13996) it.</sub>

2021-10-14 13:55 UTC, kinga-k commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +              startWith(''),
1 - I didn't want to change code from profile tag to not break that functionality
2 - Merchandising Carousel should be displayed on the storefront even if consent are not given
3 - Ok
4 - You are right. I didn't noticed this problem.
5 - I have merged it

2021-10-14 14:52 UTC, bgambocjaviniar commented on integration-libs/cds/src/merchandising/facade/cds-merchandising-user-context.service.ts
> +              startWith(''),
1 - the reason why it's best to keep it in profile tag this logic is because getConsentReference should be emitting a default and we wouldn't be repeating ourselves to say if a consent is given or not. It would help alleviate the issue on adding dependencies for breaking changes here as well, whereas the functionality fix on profile tag will be considered a bugfix instead of a breaking change.

2021-11-05 15:30 UTC, closed without merging