fix: add SR to Pagination items (#13537)
SAP/spartacus pull request #14029
Opened 2021-10-13 16:00 UTC by BenjaminEmiliani

Closes #13537

2021-10-14 07:55 UTC, Zeyber requested changes

2021-10-14 07:55 UTC, Zeyber commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +    return `${type} ${PaginationItemType.PAGE}`;
Not necessary but if you wanted to shorten this code

```suggestion
    return type === PaginationItemType.PAGE
      ? `${type} ${label}`
      : `${type} ${PaginationItemType.PAGE}`;
```

2021-10-14 07:55 UTC, Zeyber commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +   * @param item
This label `item` doesn't match the input param.

2021-10-14 07:55 UTC, Zeyber commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +  getAriaLabel(label: string, type: PaginationItemType) {
Good practice to always have the return type.

```suggestion
  getAriaLabel(label: string, type: PaginationItemType): string {
```

2021-10-14 07:55 UTC, Zeyber commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +   * @returns
Returns what?

2021-10-14 13:09 UTC, BenjaminEmiliani commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +    return `${type} ${PaginationItemType.PAGE}`;
Changed

2021-10-14 13:09 UTC, BenjaminEmiliani commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +  getAriaLabel(label: string, type: PaginationItemType) {
Fixed

2021-10-14 13:09 UTC, BenjaminEmiliani commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +   * @param item
Fixed

2021-10-14 13:09 UTC, BenjaminEmiliani commented on projects/storefrontlib/shared/components/list-navigation/pagination/pagination.component.ts
> +   * @returns
Fixed

2021-10-14 19:19 UTC, developpeurweb approved these changes
Works well with JAWS and NVDA.

2021-10-15 07:29 UTC, Zeyber approved these changes

2021-10-15 14:17 UTC, merged