fix: Carousel button labels
SAP/spartacus pull request #14020
Opened 2021-10-12 16:20 UTC by bit172

closes #13429

2021-10-12 19:38 UTC, saad-mo commented on projects/storefrontlib/shared/components/carousel/carousel.component.ts
> +  getIndicatorAriaLabel(size: number, currentIndex: number, length: number) {
need a unit test for this function

2021-10-12 19:39 UTC, saad-mo commented on projects/storefrontlib/shared/components/carousel/carousel.component.ts
> +    return `slide ${currentSlide}`;
`slide` here is static text. it can be moved to the template and also converted into a translation key.

2021-10-14 14:13 UTC, BenjaminEmiliani requested changes

2021-10-14 14:13 UTC, BenjaminEmiliani commented on projects/storefrontlib/shared/components/carousel/carousel.component.html
> +      [attr.aria-label]="'common.carousel.previous' | cxTranslate"
I believe you meant [attr.aria-label]="'carousel.previous' | cxTranslate"

2021-10-15 15:20 UTC, saad-mo commented on projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts
> +      it('should have the right indicator labels', () => {
duplicate of `it` on line 324

2021-10-15 15:20 UTC, saad-mo commented on projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts
> +      it('should have the right indicator labels', () => {
duplicate of `it` on line 279

2021-10-15 15:21 UTC, saad-mo commented on projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts
> +    it('should return the 1rst slide', () => {
should return the `1st` slide

2021-10-15 15:25 UTC, saad-mo commented on projects/assets/src/translations/en/common.ts
> +  carousel: {
maybe make the key names more specific 

- previousSlide: 'Previous slide',
- nextSlide: 'Next Slide' 
- slideNumber: 'Slide {{currentSlideNumber}}',

2021-10-15 15:27 UTC, saad-mo requested changes
some more minor updates needed

2021-10-15 15:29 UTC, saad-mo commented on projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts
> +      it('should have the right indicator labels', () => {
instead of using left/right, pls use previous/next indicators to aligns with translation keys

2021-10-15 15:29 UTC, saad-mo commented on projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts
> +      it('should have the right indicator labels', () => {
instead of using left/right, pls use previous/next indicators to aligns with translation keys

2021-10-15 15:38 UTC, bit172 commented on projects/storefrontlib/shared/components/carousel/carousel.component.spec.ts
> +      it('should have the right indicator labels', () => {
The word 'right' here is not implying directions but rather being correct. 
I could change the word if the meaning is too ambiguous.

2021-10-18 16:08 UTC, saad-mo commented on projects/assets/src/translations/en/common.ts
> +  carousel: {
@bit172 this is marked as resolved, but I don't need the changes. will the change be made or leave it as is?

2021-10-18 16:31 UTC, saad-mo approved these changes

2021-10-18 17:27 UTC, BenjaminEmiliani approved these changes

2021-10-18 20:10 UTC, merged