fix: add voice over support for no stores found message
SAP/spartacus pull request #14034
Opened 2021-10-14 08:33 UTC by Matejk00

Closes: #13735

2021-10-14 15:23 UTC, saad-mo submitted a review, later dismissed

2021-10-14 19:00 UTC, developpeurweb requested changes
Unfortunately, this doesn't work for JAWS and NVDA. As discussed on the a11y channel, only if preloading is not possible, then let's use `role="alert"`.

2021-10-15 10:15 UTC, Matejk00 commented
I added `role="alert"` to support JAWS and NVDA.

2021-10-15 14:34 UTC, saad-mo commented
@developpeurweb I am not sure how to test this? With VO open, I can tab to the "Use My Location" button and hit enter to trigger a search. Since geolocation is not enabled, the page eventually renders "No stores found in database..." text but VO does not detect this change, and nor is the text interactive so there is still no narration. Not sure if I need to trigger the full page narration again but that does not seem very intutive. Please advise

2021-10-15 16:30 UTC, developpeurweb requested changes
Sorry, I meant to convey using `role="alert"` **instead of** `aria-live="assertive"` and `aria-atomic="true"`. Pls remove those two.
**Works well with JAWS and NVDA btw**

2021-10-15 16:32 UTC, developpeurweb commented on feature-libs/storefinder/components/store-finder-search-result/store-finder-search-result.component.html
> +        aria-live="assertive"
Please remove aria-live="assertive" aria-atomic="true" and leave only role="alert".

2021-10-15 16:32 UTC, developpeurweb commented on feature-libs/storefinder/components/store-finder-stores-count/store-finder-stores-count.component.html
> +        aria-live="assertive"
Please remove aria-live="assertive" aria-atomic="true" and leave only role="alert".

2021-10-15 16:36 UTC, developpeurweb commented
> @developpeurweb I am not sure how to test this? With VO open, I can tab to the "Use My Location" button and hit enter to trigger a search. Since geolocation is not enabled, the page eventually renders "No stores found in database..." text but VO does not detect this change, and nor is the text interactive so there is still no narration. Not sure if I need to trigger the full page narration again but that does not seem very intutive. Please advise

@saad-mo type any city name in North America (or a typo) then tab to the magnifying glass and hit enter.

2021-10-18 18:04 UTC, developpeurweb approved these changes
Works well with JAWS and NVDA

2021-10-18 20:01 UTC, saad-mo approved these changes

2021-10-19 12:01 UTC, merged