Feature/gh 13806 exit button
SAP/spartacus pull request #14043
Opened 2021-10-15 07:33 UTC by Changsuwan

2021-10-15 10:35 UTC, Larisa-Staroverova reviewed
Please, see my comments

2021-10-15 10:35 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/common/assets/translations/en/configurator-common.ts
> +      exitshort: 'Exit',
Please, use a camel case, for instance `exitShort` or better `exitMobil`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.html
> +  <span class="cx-config-exit-button-text">
It is necessary  to wrap text within the button with a `span`
Please, remove it

2021-10-15 10:35 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.ts
> +  goBack() {
Please, write a comment

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-top: 14px;
`margin-block-start` should be used instead `margin-top`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-top: 4px;
`margin-block-start` should be used instead `margin-top`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-top: 14px;
`margin-block-start` should be used instead `margin-top`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-bottom: 14px;
`margin-block-end` should be used instead `margin-bottom`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-bottom: 4px;
`margin-block-end` should be used instead `margin-bottom`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-bottom: 14px;
`margin-block-end` should be used instead `margin-bottom`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-bottom: 4px;
`margin-block-end` should be used instead `margin-bottom`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-top: 4px;
`margin-block-start` should be used instead `margin-top`

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +  .VariantConfigExitButton {
Try to avoid code duplication. You could work with the comma operator

2021-10-15 10:35 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +  .VariantConfigExitButton {
The better solution without code duplication could be:
```
 .VariantConfigExitButton,
  .VariantConfigOverviewExitButton {
    margin-block-start: 14px;
    margin-block-end: 14px;
    margin-inline-start: auto;
    margin-inline-end: 14px;

    @include media-breakpoint-down(sm) {
      margin-block-start: 4px;
      margin-inline-end: 0px;
      margin-block-end: 4px;
      margin-inline-start: auto;
    }
  }
```

2021-10-15 10:35 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-exit-button.scss
> +  .cx-exit-configurator {
Code duplication!

2021-10-15 10:35 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-exit-button.scss
> +%cx-configurator-exit-button {
See this working solution:
```
%cx-configurator-exit-button {
  align-items: center;
  font-weight: 600;
  font-size: 15px;
  margin-inline-start: 5px;
  margin-inline-end: 5px;

  button {
    border-radius: var(--cx-buttons-border-radius);
    border: 2px solid white;
    background-color: transparent;
    height: 44px;
    color: white;
  }
}
```

2021-10-15 10:35 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.html
> +<button class="cx-config-exit-button" tabindex="0" (click)="goBack()">
Shorter solution:
```
<button tabindex="0" (click)="goBack()">
    <ng-container *ngIf="isDesktop() | async">
      {{ 'configurator.button.exit' | cxTranslate }}
    </ng-container>
    <ng-container *ngIf="isMobile() | async">
      {{ 'configurator.button.exitshort' | cxTranslate }}
    </ng-container>
</button>
```

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-top: 14px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-bottom: 14px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-top: 4px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-bottom: 4px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-bottom: 4px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +      margin-top: 4px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-bottom: 14px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +    margin-top: 14px;
done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +  .VariantConfigExitButton {
Done

2021-10-15 13:15 UTC, Changsuwan commented on projects/storefrontstyles/scss/components/layout/header/_header.scss
> +  .VariantConfigExitButton {
Done

2021-10-15 13:15 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/styles/_configurator-exit-button.scss
> +  .cx-exit-configurator {
Fixed

2021-10-15 13:15 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/styles/_configurator-exit-button.scss
> +%cx-configurator-exit-button {
Done

2021-10-15 13:16 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.ts
> +  goBack() {
Done

2021-10-15 13:16 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.html
> +  <span class="cx-config-exit-button-text">
Done

2021-10-15 13:16 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.html
> +<button class="cx-config-exit-button" tabindex="0" (click)="goBack()">
Done

2021-10-15 13:16 UTC, Changsuwan commented on feature-libs/product-configurator/common/assets/translations/en/configurator-common.ts
> +      exitshort: 'Exit',
Done

2021-10-18 06:54 UTC, Larisa-Staroverova requested changes
`goBack` method has not been tested yet. 2 tests are failing. Please, fix them!

2021-10-18 06:54 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.html
> +<button class="cx-config-exit-button" tabindex="0" (click)="goBack()">
Please, remember to **Resolve conversation**, when you are done with the comment. Thanks!

2021-10-18 06:54 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.ts
> +  goBack() {
Please, remember to Resolve conversation, when you are done with the comment. Thanks!

2021-10-18 06:54 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-exit-button.scss
> +%cx-configurator-exit-button {
Please, remember to **Resolve conversation**, when you are done with the comment. Thanks!

2021-10-19 07:43 UTC, Larisa-Staroverova requested changes
Please, take into account my comments

2021-10-19 07:43 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.ts
> +  goBack() {
Please, rename this method, for instance `exit` or `exitConfiguration`
The current method name does not correspond to what this method does, namely exit a configuration

2021-10-19 07:43 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.ts
> +   * the method navigates to the previous page when user clicks on the configurator exit button.
The comment should start with a verb in 3-d person singular, for instance `navigates`, `exits`
Furthermore, your comment does not correspond to what this method does, namely exit a configuration.
Please, adjust the comment accordingly.

2021-10-19 07:43 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.spec.ts
> +  describe('navigation tests', () => {
Please, rename the test description, for instance `exit a configuration`

2021-10-19 07:43 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.spec.ts
> +    it('should navigate to product detail page if going back to previous page does not work', () => {
According to the current implementation, after clicking on the `exit configuration` button, the end-user always exits a configuration / goes to the product detail page.
Please, adjust the test description accordingly.

2021-10-19 07:57 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.ts
> +  goBack() {
Done

2021-10-19 07:58 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.ts
> +   * the method navigates to the previous page when user clicks on the configurator exit button.
Done

2021-10-19 07:59 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.spec.ts
> +    it('should navigate to product detail page if going back to previous page does not work', () => {
Done

2021-10-19 08:06 UTC, Changsuwan commented on feature-libs/product-configurator/rulebased/components/exit-button/configurator-exit-button.component.spec.ts
> +  describe('navigation tests', () => {
Done

2021-10-19 09:57 UTC, Larisa-Staroverova submitted a review, later dismissed

2021-10-20 05:24 UTC, Larisa-Staroverova approved these changes

2021-10-20 05:28 UTC, merged