Epic/image zoom
SAP/spartacus pull request #14046
Opened 2021-10-15 09:24 UTC by mszczepaniak

Closes #13315

2021-10-18 10:02 UTC, marlass requested changes

2021-10-18 10:02 UTC, marlass commented on feature-libs/product/image-zoom/assets/translations/translations.ts
> +export const imageZoomTranslations: TranslationResources = {
```suggestion
export const productImageZoomTranslations: TranslationResources = {
```

2021-10-18 10:02 UTC, marlass commented on feature-libs/product/image-zoom/assets/translations/translations.ts
> +export const imageZoomTranslationChunksConfig: TranslationChunksConfig = {
```suggestion
export const productImageZoomTranslationChunksConfig: TranslationChunksConfig = {
```

2021-10-18 10:02 UTC, marlass commented on feature-libs/product/image-zoom/components/image-zoom-components.module.ts
> +export class ImageZoomComponentsModule {}
```suggestion
export class ProductImageZoomComponentsModule {}
```

2021-10-18 10:02 UTC, marlass commented on projects/storefrontlib/layout/launch-dialog/config/launch-config.ts
> +  IMAGE_ZOOM = 'IMAGE_ZOOM',
Can we do that with type augmentation?

2021-10-18 10:02 UTC, marlass commented on feature-libs/product/image-zoom/components/product-image-zoom/default-image-zoom-layout.config.ts
> +export const defaultImageZoomLayoutConfig: LayoutConfig = {
```suggestion
export const defaultProductImageZoomLayoutConfig: LayoutConfig = {
```

That's the general rule we want to do. Everything that is exported in public API should be prefixed with the library name, before the feature name.

2021-10-18 12:02 UTC, marlass requested changes

2021-10-18 12:02 UTC, marlass commented on projects/storefrontstyles/package.json
> +  "version": "4.1.0",
This should've not been commited during schematics testing

2021-10-18 12:02 UTC, marlass commented on projects/schematics/package.json
> +  "version": "4.1.0",
This one also should not have been commited

2021-10-18 12:02 UTC, marlass commented on feature-libs/product/image-zoom/core/models/image-zoom-thumbnails.model.ts
> +export interface ThumbnailsGroup {
Let's move this model to root entry point and remove the core entry point

2021-10-18 12:02 UTC, marlass commented on feature-libs/product/_index.scss
> +@import '~@spartacus/styles';
Let's only import here what's needed

2021-10-18 12:02 UTC, marlass commented on feature-libs/product/image-zoom/components/product-image-zoom/image-zoom-product-images/image-zoom-product-images.component.ts
> +export class ImageZoomProductImagesComponent {
Did you thought about extending here `ProductImagesComponent` to avoid duplication of some methods?

2021-10-18 12:02 UTC, marlass commented on feature-libs/product/image-zoom/components/product-image-zoom/image-zoom-trigger/image-zoom-trigger.component.ts
> +      this.subscriptions.add(
Would be good to clear this subscriptions on component destroy

2021-10-18 21:08 UTC, mszczepaniak commented on feature-libs/product/image-zoom/assets/translations/translations.ts
> +export const imageZoomTranslations: TranslationResources = {
done

2021-10-18 21:08 UTC, mszczepaniak commented on feature-libs/product/image-zoom/assets/translations/translations.ts
> +export const imageZoomTranslationChunksConfig: TranslationChunksConfig = {
done

2021-10-18 21:11 UTC, mszczepaniak commented on feature-libs/product/image-zoom/components/image-zoom-components.module.ts
> +export class ImageZoomComponentsModule {}
done

2021-10-18 21:57 UTC, mszczepaniak commented on feature-libs/product/image-zoom/components/product-image-zoom/image-zoom-trigger/image-zoom-trigger.component.ts
> +      this.subscriptions.add(
done

2021-10-18 21:59 UTC, mszczepaniak commented on projects/storefrontstyles/package.json
> +  "version": "4.1.0",
reverted

2021-10-18 21:59 UTC, mszczepaniak commented on projects/schematics/package.json
> +  "version": "4.1.0",
reverted

2021-10-19 05:58 UTC, mszczepaniak commented on projects/storefrontlib/layout/launch-dialog/config/launch-config.ts
> +  IMAGE_ZOOM = 'IMAGE_ZOOM',
@marlass I am not sure what would you like me to do here

2021-10-19 07:32 UTC, mszczepaniak commented on feature-libs/product/image-zoom/components/product-image-zoom/default-image-zoom-layout.config.ts
> +export const defaultImageZoomLayoutConfig: LayoutConfig = {
done

2021-10-19 08:03 UTC, mszczepaniak commented on feature-libs/product/image-zoom/core/models/image-zoom-thumbnails.model.ts
> +export interface ThumbnailsGroup {
done

2021-10-19 08:03 UTC, mszczepaniak commented on feature-libs/product/image-zoom/components/product-image-zoom/image-zoom-product-images/image-zoom-product-images.component.ts
> +export class ImageZoomProductImagesComponent {
good idea, done

2021-10-19 10:13 UTC, mszczepaniak commented on projects/storefrontlib/layout/launch-dialog/config/launch-config.ts
> +  IMAGE_ZOOM = 'IMAGE_ZOOM',
done

2021-10-20 11:09 UTC, marlass requested changes

2021-10-20 11:09 UTC, marlass commented on projects/storefrontlib/cms-components/product/product-images/product-images.component.ts
> +  protected mainMediaContainer = new BehaviorSubject<any>(null);
Can we have better type here than `any`?

2021-10-20 11:09 UTC, marlass commented on feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-thumbnails/product-image-zoom-thumbnails.component.ts
> +  isActive(thumbnail: ImageGroup): Observable<any> {
Maybe `Observable<boolean>` as return type?

2021-10-20 11:26 UTC, marlass submitted a review, later dismissed

2021-10-20 11:26 UTC, mszczepaniak commented on feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-thumbnails/product-image-zoom-thumbnails.component.ts
> +  isActive(thumbnail: ImageGroup): Observable<any> {
done

2021-10-20 12:37 UTC, marlass submitted a review, later dismissed

2021-10-20 14:47 UTC, marlass approved these changes

2021-10-20 14:49 UTC, merged