fix: add SR and autofocus to card component actions (#13585)
SAP/spartacus pull request #14073
Opened 2021-10-19 19:09 UTC by BenjaminEmiliani

Stale PR #13774
Closes #13585

2021-10-25 08:37 UTC, Zeyber requested changes
Please create/add to `docs/migration/5_0.md` about the breaking changes in the template using heading `### Card Component`. See previous migration docs about what this looks like.

Also, this PR must not be merged until all minor versions before `5.0` have been released so that we do not merge breaking changes into `develop`.

2021-10-26 14:10 UTC, morganm58 submitted a review, later dismissed

2022-01-03 10:33 UTC, Zeyber approved these changes

2022-01-04 15:41 UTC, RadhepS approved these changes

2022-01-04 15:42 UTC, merged