Adjust normalizer & serializer to enable retract mode
SAP/spartacus pull request #14098
Opened 2021-10-25 10:55 UTC by Larisa-Staroverova

2021-10-26 13:47 UTC, ChristophHi requested changes

2021-10-26 13:47 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      MockOccModuleConfig.backend.retractTriggered = true;
Strict mode issue

2021-10-26 13:47 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      MockOccModuleConfig.backend.retractTriggered = false;
Strict mode issue

2021-10-26 13:47 UTC, ChristophHi commented on projects/core/src/occ/config/occ-config.ts
> +  retractTriggered?: boolean;
(1) We should not introduce that in the generic config file
(2) The name is confusing. This is about adding an additional value, which should be reflected in the parameter name

2021-10-26 13:47 UTC, ChristophHi commented on projects/core/src/occ/adapters/product/default-occ-product-config.ts
> +    retractTriggered: false,
We should not introduce that in the generic config file

2021-10-27 04:45 UTC, Larisa-Staroverova commented on projects/core/src/occ/adapters/product/default-occ-product-config.ts
> +    retractTriggered: false,
Where should the retract mode be introduced?

2021-10-27 04:46 UTC, Larisa-Staroverova commented on projects/core/src/occ/config/occ-config.ts
> +  retractTriggered?: boolean;
What is the better naming according to your point of view?

2021-10-27 04:55 UTC, ChristophHi commented on projects/core/src/occ/config/occ-config.ts
> +  retractTriggered?: boolean;
What about 'addRetractOption' ?

2021-10-27 06:26 UTC, ChristophHi commented on projects/core/src/occ/adapters/product/default-occ-product-config.ts
> +    retractTriggered: false,
As we just discussed, ProductConfiguratorUISettingsConfig is probably a good place

2021-10-27 10:49 UTC, Larisa-Staroverova commented on projects/core/src/occ/config/occ-config.ts
> +  retractTriggered?: boolean;
Done!

2021-10-27 10:49 UTC, Larisa-Staroverova commented on projects/core/src/occ/adapters/product/default-occ-product-config.ts
> +    retractTriggered: false,
Done!

2021-10-27 10:49 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      MockOccModuleConfig.backend.retractTriggered = true;
Done!

2021-10-27 10:49 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      MockOccModuleConfig.backend.retractTriggered = false;
Done!

2021-11-03 05:49 UTC, ChristophHi requested changes
This does not work with CPS, the retract value code must not be sent to the backend. CPS responds with

ERROR [hybrisHTTP25] [RequestErrorHandlerImpl] While calling the cps service the following server error occured:{
  "status" : 422,
  "typeId" : null,
  "type" : "unprocessable entity",
  "message" : "Update checks failed",
  "messageDetails" : {
    "area" : "CFG_VALIDATION",
    "id" : "002",
    "created" : "2021-11-03T05:45:20.991Z",
    "severity" : "ERROR",
    "transient" : true,
    "plainMessage" : "Update checks failed",
    "attributes" : [ ],
    "formattedMessage" : "Update checks failed"
  },
  "moreInfo" : null,
  "details" : [ {
    "typeId" : "40003.002",
    "type" : "data_invalid",
    "field" : "CHHI_CON",
    "value" : "###RETRACT_VALUE_CODE###",
    "message" : "Value ###RETRACT_VALUE_CODE### exceeds the maximum length of 1 for characteristic CHHI_CON",
    "messageDetails" : {
      "area" : "CFG_VALIDATION",
      "id" : "150",
      "created" : "2021-11-03T05:45:20.989Z",
      "severity" : "ERROR",
      "transient" : true,
      "plainMessage" : "Value {0} exceeds the maximum length of {1} for characteristic {2}",
      "attributes" : [ {
        "attribute" : "###RETRACT_VALUE_CODE###",
        "type" : "string"
      }, {
        "attribute" : "1",
        "type" : "float"
      }, {
        "attribute" : "CHHI_CON",
        "type" : "string"
      } ],
      "formattedMessage" : "Value ###RETRACT_VALUE_CODE### exceeds the maximum length of 1 for characteristic CHHI_CON"
    },
    "moreInfo" : null
  } ]
}

2021-11-03 13:19 UTC, ChristophHi requested changes
Still does not work. It's possible to de-select, but afterwards, no value can be set

2021-11-08 13:24 UTC, ChristophHi approved these changes

2021-11-08 13:30 UTC, merged