fix: add aria attribute to breadcrumb component (#3608)
SAP/spartacus pull request #14095
Opened 2021-10-22 17:38 UTC by saad-mo

closes #3608

2021-10-22 17:40 UTC, saad-mo commented on projects/storefrontlib/cms-components/navigation/breadcrumb/breadcrumb.component.html
> +<nav [attr.aria-label]="'common.breadcrumbs' | cxTranslate">
@developpeurweb do we need to have `nav` in breadcrumb?

2021-10-22 17:41 UTC, saad-mo commented on projects/storefrontlib/cms-components/navigation/breadcrumb/breadcrumb.component.html
> +  <ol [attr.aria-label]="'common.breadcrumbs' | cxTranslate">
@developpeurweb just wanted to confirm that the duplication of aria-label on on `ol` and `nav` is for cross-screen reader compatibility?

2021-10-28 23:45 UTC, developpeurweb commented on projects/storefrontlib/cms-components/navigation/breadcrumb/breadcrumb.component.html
> +<nav [attr.aria-label]="'common.breadcrumbs' | cxTranslate">
@saad-mo yes please, to make the breadcrumbs appear to users navigating the page using landmarks. Also, if we try to get there by using VO's rotor, the focus never reaches the component, it jumps back to wherever the focus was previously. It seems to get fixed if we add a `tabindex="-1"` to the `<nav>`. Can you check if this happens on your end as well?

2021-10-28 23:45 UTC, developpeurweb commented on projects/storefrontlib/cms-components/navigation/breadcrumb/breadcrumb.component.html
> +  <ol [attr.aria-label]="'common.breadcrumbs' | cxTranslate">
@saad-mo yes, please. Unfortunately, VO fails to vocalize it, even though it shows up correctly in the rotor. If you get there only by tabbing (not by rotor) it will be announced as a _"list with 3 items"_, but it doesn't provide the context of being part of the "breadcrumbs".

2021-10-28 23:52 UTC, developpeurweb reviewed
It LGTM, but before merging, can you please verify the `tabindex="-1"` improvement on your end?

2021-11-29 11:54 UTC, dydome requested changes
please provide migration doc

2021-12-06 19:32 UTC, saad-mo commented
@

> please provide migration doc

added

2021-12-06 19:41 UTC, saad-mo commented
> It LGTM, but before merging, can you please verify the `tabindex="-1"` improvement on your end?

@developpeurweb I tested with `tabindex="-1"` it and it did fix the tabbing issue when navigating. PR is ready for review again

2021-12-07 01:11 UTC, developpeurweb commented
> > It LGTM, but before merging, can you please verify the `tabindex="-1"` improvement on your end?
> 
> @developpeurweb I tested with `tabindex="-1"` it and it did fix the tabbing issue when navigating. PR is ready for review again

Works well for VO/NVDA/JAWS

2021-12-07 01:12 UTC, developpeurweb approved these changes, later dismissed

2021-12-08 11:52 UTC, psmul requested changes

2021-12-08 11:52 UTC, psmul commented on docs/migration/css-changes-in-version-5.md
> +## Change in Breadcrumb component style structure
```suggestion
## Changes in styles

### Breadcrumb component 
```

2021-12-08 11:52 UTC, psmul commented on docs/migration/css-changes-in-version-5.md
> +## Change in Breadcrumb component style structure
I think it's better we create separate section to gather all style changes. There might be more coming.

2021-12-09 07:27 UTC, psmul approved these changes

2021-12-10 17:23 UTC, developpeurweb approved these changes

2021-12-10 17:55 UTC, dydome approved these changes

2021-12-10 18:04 UTC, merged