fix: Fix pdp heading levels (#13484)
SAP/spartacus pull request #14342
Opened 2021-11-16 12:21 UTC by dydome

close #13484

2021-11-25 11:57 UTC, psmul approved these changes

2021-11-25 11:58 UTC, psmul requested changes
Actually this introduces breaking change. Some fallback needs to be provided

2021-11-25 12:01 UTC, psmul approved these changes

2021-11-25 12:09 UTC, mszczepaniak approved these changes

2021-11-25 13:35 UTC, merged

2021-11-29 11:51 UTC, dydome commented
no migration doc