fix: No indication if a menu is collapsed or expanded for Main Menus
SAP/spartacus pull request #14422
Opened 2021-11-24 03:18 UTC by Pucek9

Closes #13561

2021-11-29 11:56 UTC, dydome requested changes
please provide migration doc

2022-01-21 23:03 UTC, developpeurweb submitted a review, later dismissed
Works well for VO, JAWS, NVDA.

2022-01-24 10:23 UTC, dydome requested changes

2022-01-24 10:23 UTC, dydome commented on docs/migration/5_0.md
> +- `common.navigation.shopAll` from has been removed.
from ... has -> probably something is missing here

2022-01-24 10:23 UTC, dydome commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +      <ng-container *ngIf="flyout && node.children?.length > 0; else span">
`; else span` -> for me, I would recommend using different word rather than a tag name

2022-01-24 10:23 UTC, dydome commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.ts
> +  closeIfClickedTheSameLink(navNode: NavigationNode) {
): void {

2022-01-24 10:23 UTC, dydome commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.ts
> +  protected ariaCollapseNodes() {
): void {

2022-01-24 15:23 UTC, developpeurweb approved these changes, later dismissed
All is good on Screen Reader's end.

2022-01-24 17:31 UTC, developpeurweb submitted a review, later dismissed

2022-01-25 08:37 UTC, dydome approved these changes

2022-01-25 08:44 UTC, merged