chore: QuickOrderService deprecation clean up and migration configuration
SAP/spartacus pull request #14509
Opened 2021-12-03 11:46 UTC by psmul

Closes: #14059

2021-12-03 11:52 UTC, dydome submitted a review, later dismissed

2021-12-06 11:53 UTC, dydome requested changes

2021-12-06 11:53 UTC, dydome commented on feature-libs/cart/quick-order/core/services/quick-order.service.spec.ts
> -  describe('should trigger search products', () => {
This part shouldn't be removed

2021-12-06 13:21 UTC, dydome approved these changes, later dismissed

2021-12-07 08:19 UTC, dydome approved these changes

2021-12-07 08:27 UTC, znikola approved these changes

2021-12-07 08:30 UTC, merged