chore: QuickOrderFormComponent deprecation clean up and migration configuration
SAP/spartacus pull request #14510
Opened 2021-12-03 12:10 UTC by psmul

Closes: #14058

2021-12-03 12:24 UTC, dydome requested changes

2021-12-03 12:24 UTC, dydome commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
>      protected cd?: ChangeDetectorRef, // TODO(#14058): Make it required
I think we should make it required.

2021-12-03 12:26 UTC, psmul commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
>      protected cd?: ChangeDetectorRef, // TODO(#14058): Make it required
Good catch, thank you!

2021-12-03 12:35 UTC, dydome approved these changes

2021-12-06 14:03 UTC, znikola approved these changes

2021-12-06 14:04 UTC, merged