chore: Move models out of core for checkout
SAP/spartacus pull request #14626
Opened 2021-12-15 07:10 UTC by bgambocjaviniar

2021-12-22 14:11 UTC, znikola requested changes

2021-12-22 14:11 UTC, znikola commented on feature-libs/cart/main/root/models/cart.model.ts
> +import { PaymentDetails } from '@spartacus/checkout/base/root';
I'm wondering if this is a good idea - _checkout_ already depends on _cart_, but now we're making _cart_ depend on _checkout_.
Maybe this is a good sign that `PaymentDetails` actually belongs to _user_ lib?

2021-12-22 14:11 UTC, znikola commented on feature-libs/cart/main/root/models/cart.model.ts
>    Address,
A similar question is for the _order_ lib.

2021-12-22 14:11 UTC, znikola commented on feature-libs/cart/main/root/models/cart.model.ts
>    Currency,
Not sure how this happened, but once we run `yarn generate:deps` and `yarn config:update` we get the checkout ts configs inside of the checkout tsconfig itself 🤔

2021-12-23 16:11 UTC, bgambocjaviniar commented on feature-libs/cart/main/root/models/cart.model.ts
> +import { PaymentDetails } from '@spartacus/checkout/base/root';
moving to cart

2021-12-24 04:57 UTC, merged