fix: Add aria attributes to facets
SAP/spartacus pull request #14911
Opened 2022-01-31 09:54 UTC by Zeyber

PLP Part of #11637

2022-01-31 23:56 UTC, developpeurweb commented
**Test outcome for PLP:**
- **JAWS** - Brakes pattern. Reads whole content of the panel, then button expanded state at the end, ENTER key gets overridden and will not work to enter into the panel,  it only works for expanding button. 
- **NVDA** -  Forces accessible pattern, so it's mostly fine.
- **VO** - Follows implemented custom pattern, which never lands on the button, but on the first item.

**Some thoughts/options**

- Removing the double-enter and double-escape pattern.
- Aux key events (up/down arrow to jump groups, TAB to go one-by-one)

**Also:**
- Let's try IDs without spaces and associating the buttons.
- Do we need IDs? if we remove aria-controls and use aria-label, will it sound the same?

![Screen Shot 2022-01-31 at 5 51 48 PM](https://user-images.githubusercontent.com/15113219/151890099-84ae11bf-e2bd-4d8f-8ecb-0439a7e7dd41.png)
![Screen Shot 2022-01-31 at 5 55 34 PM](https://user-images.githubusercontent.com/15113219/151890106-9101424b-8b7a-4549-9867-2fd1dc1ad0fb.png)
![Screen Shot 2022-01-31 at 5 58 55 PM](https://user-images.githubusercontent.com/15113219/151890107-38f95239-1d14-4fb2-93a3-80e2e81904ba.png)

2022-02-01 21:54 UTC, developpeurweb commented
- We still have some issues with `aria-labelledby` linking to IDs.
- Is it possible to remove the double-enter and double-escape pattern? 
It would be a better cross-screen-reader experience if the user just follows the source order, item-by-item when they are available once a given panel is open. The facet "group skipping" has different behaviour across SRs.

![Screen Shot 2022-02-01 at 3 43 51 PM](https://user-images.githubusercontent.com/15113219/152057571-50eacf69-0b92-48f9-976f-c96773c55d67.png)
![Screen Shot 2022-02-01 at 3 44 20 PM](https://user-images.githubusercontent.com/15113219/152057577-8c713dac-5e7d-4a42-b995-9494babd1f48.png)

2022-02-10 00:44 UTC, developpeurweb submitted a review, later dismissed
This works well on JAWS/NVDA/VO

2022-02-21 11:13 UTC, Matejk00 requested changes

2022-02-21 11:13 UTC, Matejk00 commented on docs/migration/5_0.md
> +### FacetListComponent
It is doubled section for `### FacetListComponent` in 5_0 document. We can add this info to existing one under "Template Changes".

2022-02-21 11:31 UTC, Matejk00 approved these changes

2022-02-21 22:48 UTC, developpeurweb approved these changes
This works well with JAWS/NVDA/VO

2022-02-22 09:57 UTC, merged