fix: add checkout step to title (#13539)
SAP/spartacus pull request #14919
Opened 2022-01-31 20:54 UTC by BenjaminEmiliani

Closes #13539

2022-02-02 21:06 UTC, bgambocjaviniar commented on projects/storefrontlib/cms-components/navigation/page-header/page-title.component.ts
> +    this.title$ = combineLatest([
as mentioned, do not couple 'any checkout' logic to this 'generic' page title

2022-02-02 21:07 UTC, bgambocjaviniar commented on feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts
> +  resolveTitle(): Observable<string | undefined> {
from the first hint provided in DM, you can use resolveHeading() to change the breadcrumb title and resolveTitle will change the actual title displayed in the header and web browser

2022-02-02 21:07 UTC, bgambocjaviniar requested changes
^

2022-02-02 21:09 UTC, bgambocjaviniar commented on projects/storefrontlib/cms-components/navigation/page-header/page-title.component.ts
> +    this.title$ = combineLatest([
put it back to what it was and use resolveHeading() in the checkout-page resolver
```suggestion
     this.title$ = this.pageMetaService.getMeta().pipe(
      filter(isNotNullable),
      map((meta) => (meta.heading || meta.title) ?? '')
```

2022-02-03 19:41 UTC, bgambocjaviniar requested changes

2022-02-03 19:41 UTC, bgambocjaviniar commented on feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts
> -    return this.cart$.pipe(
we can safely remove cart$ from this file as it's no longer being used nor it was even being used for a lonnngggg time apparently haha

2022-02-03 19:41 UTC, bgambocjaviniar commented on feature-libs/checkout/base/core/services/checkout-page-meta.resolver.spec.ts
> +    let result!: string;
instead of saying it will always be a string, let's put the type as  `string | undefined`, similarly to line 59

2022-02-03 21:21 UTC, bgambocjaviniar commented on feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts
>    implements PageTitleResolver, PageDescriptionResolver, PageRobotsResolver
I missed this, but for convention on interfaces that helps to 'include' the abstract methods to be implemented, you should implement PageHeadingResolver

2022-02-03 21:22 UTC, bgambocjaviniar commented on feature-libs/checkout/base/core/services/checkout-page-meta.resolver.spec.ts
> +    basePageMetaResolver.resolveTitle = createSpy().and.returnValue(
let's include resolveTitle method under the mock class in line 23

2022-02-04 17:58 UTC, bgambocjaviniar approved these changes

2022-02-04 17:59 UTC, merged

2022-02-07 10:43 UTC, znikola commented on feature-libs/checkout/base/core/services/checkout-page-meta.resolver.ts
> +    return this.translationService.translate('pageMetaResolver.checkout.title');
Question: aren't we "loosing" the information about the total items in the current cart (which we had before)?

---------/---------
/reply:
@znikola in terms of the logic yes, but not in terms of the application. What I mean by that is the method previously translated  'pageMetaResolver.checkout.title' and would pass totalItems of the cart as a parameter. But this key in our base application does not handle any parameters:
<img width="528" alt="Screen Shot 2022-02-07 at 9 07 50 AM" src="https://user-images.githubusercontent.com/49131189/152803536-b47ce1fd-40db-4278-8a17-9e616fa33cec.png">

And if a customer is using a custom translation key that expects the parameter, then it will be reported to them in the 5.0 md that the method no longer translates this key with a parameter