fix: Use ngoninit in delivery address and payment steps
SAP/spartacus pull request #15000
Opened 2022-02-11 10:57 UTC by znikola

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/root/events/checkout-cost-center-event.listener.spec.ts
> -    it(`should dispatch CheckoutClearDeliveryAddressEvent`, () => {
Now that we removed this test, we'll have to add a new one, for the new approach.

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/root/events/checkout-cost-center-event.listener.spec.ts
> -      const event = createFrom(CostCenterSetEvent, {
And it seems we didn't do this for the previous smoothing PR, where we chained the facade calls instead of relying on events?

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/components/checkout-cost-center/checkout-cost-center.component.ts
> -  isAccountPayment$: Observable<boolean> = this.checkoutPaymentTypeFacade
Why do we have to remove the stream, and store the result of it in the local variable?

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/components/checkout-cost-center/checkout-cost-center.component.ts
> +        .subscribe((paymentType: boolean) => {
I would just go with: `subscribe((isAccountPayment) => {`

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/components/checkout-cost-center/checkout-cost-center.component.ts
> +  @HostBinding('class.hidden') disabled = false;
Instead of creating a new property, can we derive the value by do something like this:

```ts
 @HostBinding('class.hidden') get disabled(): boolean {
  return !this.isAccountPayment;
}
```
I guess we would have to move it after `isAccountPayment` property is defined.

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/components/checkout-payment-type/checkout-payment-type.component.ts
> +          complete: () => this.checkoutStepService.next(this.activatedRoute),
Maybe we should also call `onSuccess` to stop the spinner? What do you think?
It's probably not required, as we're navigating away.

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/styles/components/steps/payment-type/_payment-type.scss
> -  padding-top: 2.375rem;
🤔

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/assets/translations/en/checkout-b2b.i18n.ts
> +    methodOfPayment: {
We were missing this?

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/components/checkout-payment-type/checkout-payment-type.component.html
> +<h2 class="cx-checkout-title d-none d-lg-block d-xl-block">
We didn't have the step's title?

2022-02-21 13:04 UTC, znikola commented on feature-libs/checkout/b2b/components/checkout-payment-type/checkout-payment-type.component.ts
>    next(): void {
I'd like to try to simplify the method:

```ts
  next(): void {
    // set po number to cart
    const poNumInput = this._poNumberInput.nativeElement.value;
// does this condition now even make sense? If no type is selected, we navigate to the next step?
    if (!this.typeSelected || poNumInput === this.cartPoNumber) {
      this.checkoutStepService.next(this.activatedRoute);
      return;
    }

    this.busy$.next(true);

    this.checkoutPaymentTypeFacade
      .setPaymentType(this.typeSelected, poNumInput)
      .subscribe({
// potentially add this.onSuccess();
        complete: () => this.checkoutStepService.next(this.activatedRoute),
        error: () => this.onError(),
      });
  }
```

Does it make sense? We can discuss

2022-02-21 18:37 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/components/checkout-payment-type/checkout-payment-type.component.html
> +<h2 class="cx-checkout-title d-none d-lg-block d-xl-block">
nay added it to help with the leak by making improvement in the template

2022-02-21 18:37 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/assets/translations/en/checkout-b2b.i18n.ts
> +    methodOfPayment: {
nope for header

2022-02-21 18:39 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/styles/components/steps/payment-type/_payment-type.scss
> -  padding-top: 2.375rem;
as shown, it's because the sub title having it's own padding

2022-02-21 18:39 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/components/checkout-payment-type/checkout-payment-type.component.ts
>    next(): void {
simplified, but as explained no need for success on completion

2022-02-21 18:40 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/components/checkout-payment-type/checkout-payment-type.component.ts
> +          complete: () => this.checkoutStepService.next(this.activatedRoute),
nope, as explained

2022-02-21 18:41 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/components/checkout-cost-center/checkout-cost-center.component.ts
> -  isAccountPayment$: Observable<boolean> = this.checkoutPaymentTypeFacade
to use it for the host binding in the component so that as we used to just subscribe in the template with the use of the pipe

2022-02-22 02:48 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/components/checkout-cost-center/checkout-cost-center.component.ts
> +        .subscribe((paymentType: boolean) => {
yup yup was my ts linter causing my issue :d

2022-02-22 03:13 UTC, bgambocjaviniar commented on feature-libs/checkout/b2b/root/events/checkout-cost-center-event.listener.spec.ts
> -    it(`should dispatch CheckoutClearDeliveryAddressEvent`, () => {
tried will explain

2022-02-22 20:02 UTC, bgambocjaviniar commented
small bug (almost fixed)

2022-02-22 20:02 UTC, bgambocjaviniar requested changes
small bug (almost fixed)

2022-02-24 14:38 UTC, znikola commented on feature-libs/checkout/base/root/events/checkout-delivery-mode-event.listener.ts
> +  protected onDeliveryModeReset(): void {
Let's add an explanation why are re-loading the cart after resetting the delivery modes

2022-02-24 21:31 UTC, bgambocjaviniar approved these changes

2022-02-24 21:39 UTC, merged