feat: Move the placeOrder() logic from the checkout library to the order library
SAP/spartacus pull request #15206
Opened 2022-02-22 04:46 UTC by bgambocjaviniar

closes GH-14649

2022-02-25 12:19 UTC, znikola requested changes

2022-02-25 12:19 UTC, znikola commented on feature-libs/order/components/unnamed-order-confirmation/unnamed-order-confirmation-thank-you-message/unnamed-order-confirmation-thank-you-message.component.html
> +      {{ order.replenishmentOrderCode ?? order.code }}
This is a very nice idea.
We should consider how to do it once we are able to separate the repl from the rest of order code.

2022-02-25 12:19 UTC, znikola commented on feature-libs/checkout/base/occ/config/default-occ-checkout-config.ts
> +        // placeOrder: 'users/${userId}/orders?fields=FULL',
Let's mark it with a todo comment, e.g.: `TODO:#move-order`

2022-02-25 12:19 UTC, znikola commented on feature-libs/checkout/base/root/checkout-root.module.ts
>          // TODO:#checkout - remove ORDER_FEATURE once we move the order placing functionality to the order lib
Let's not forget to remove `TODO:#`

2022-02-25 12:19 UTC, znikola commented on feature-libs/checkout/base/root/config/default-checkout-routing-config.ts
> +      // orderConfirmation: { paths: ['order-confirmation'] },
Let's mark it with a todo comment, e.g.: `TODO:#move-order`

2022-02-25 12:19 UTC, znikola commented on feature-libs/checkout/scheduled-replenishment/occ/model/occ-checkout-scheduled-replenishment-endpoints.model.ts
> +  abc?: string | OccEndpoint;
Let's mark it with a todo comment, e.g.: TODO:#move-order

2022-02-25 12:19 UTC, znikola commented on feature-libs/checkout/scheduled-replenishment/root/checkout-scheduled-replenishment-root.module.ts
> +    // provideDefaultConfig(defaultCheckoutScheduledReplenishmentRoutingConfig),
So the routing config is going to live in the order lib?

2022-02-25 17:18 UTC, bgambocjaviniar commented on feature-libs/checkout/scheduled-replenishment/root/checkout-scheduled-replenishment-root.module.ts
> +    // provideDefaultConfig(defaultCheckoutScheduledReplenishmentRoutingConfig),
it's in order lib, I just didn't want both libs have conflict if that will be an issue

2022-02-28 14:37 UTC, znikola requested changes

2022-02-28 14:37 UTC, znikola commented on feature-libs/order/components/guards/order-confirmation.guard.spec.ts
> +  getOrderDetails = createSpy().and.returnValue(of(undefined));
What do you think about `getPlacedOrderDetails`?

2022-02-28 14:37 UTC, znikola commented on feature-libs/order/occ/config/default-occ-order-config.ts
> +        /** placing or scheduling an order endpoints start **/
The comment is a bit misleading by stating this endpoint is for both placing a regular order _and_ scheduling an order

2022-02-28 14:37 UTC, znikola commented on feature-libs/checkout/scheduled-replenishment/components/checkout-place-order/checkout-place-order.component.ts
> +    protected scheduledReplenishmentFacade: ScheduledReplenishmentOrderFacade
```suggestion
    protected scheduledReplenishmentOrderFacade: ScheduledReplenishmentOrderFacade
```

2022-02-28 14:37 UTC, znikola commented on feature-libs/order/core/facade/order.service.ts
> +  protected order$ = new BehaviorSubject<Order | undefined>(undefined);
```suggestion
  protected placedOrder$ = new BehaviorSubject<Order | undefined>(undefined);
```
?

2022-02-28 14:37 UTC, znikola commented on feature-libs/order/root/facade/order.facade.ts
> +      async: true,
We don't use store in the facade's impl, and I think we can remove this

2022-02-28 14:37 UTC, znikola commented on feature-libs/order/root/facade/scheduled-replenishment.facade.ts
>        async: true,
We don't use store in the facade's impl, and I think we can remove this

2022-02-28 17:01 UTC, znikola approved these changes

2022-02-28 17:51 UTC, plabadie approved these changes

2022-02-28 17:53 UTC, merged