feat: vocalize when item is added to wish list (#15216)
SAP/spartacus pull request #15218
Opened 2022-02-22 19:50 UTC by BenjaminEmiliani

Closes #15216

2022-02-23 08:15 UTC, dydome requested changes, later dismissed
That is pretty strange but it is not working for me. @BenjaminEmiliani please ping me we can test it together.

2022-02-28 21:40 UTC, developpeurweb submitted a review, later dismissed
Works well for JAWS/NVDA/VO

2022-03-02 08:11 UTC, pawelfras approved these changes, later dismissed

2022-03-03 20:45 UTC, Pucek9 commented on projects/storefrontlib/shared/components/assistive-technology-message/assistive-technology-message.directive.ts
> +          if (current) {
```suggestion
          // Override current assitive message.
          if (globalMessageEntities?[GlobalMessageType.MSG_TYPE_ASSISTIVE) {
```

2022-03-03 20:55 UTC, Pucek9 approved these changes

2022-03-03 20:57 UTC, Pucek9 reviewed
you might consider removing timeout from global message config

2022-03-03 21:14 UTC, Pucek9 commented
> you might consider removing timeout from global message config (MSG_TYPE_ASSISTIVE)

ok, confirmed that then it will read it every time there are messages of a different type

2022-03-04 16:20 UTC, merged