feat: Make digital payment lazy loading
SAP/spartacus pull request #15229
Opened 2022-02-23 14:12 UTC by WeizhengSap

close #13821

2022-02-25 13:30 UTC, znikola requested changes

2022-02-25 13:30 UTC, znikola commented on projects/storefrontapp/src/app/spartacus/features/b2b-digital-payments/replenishment-digital-payments.module.ts
> +export class ReplenishmentDigitalPaymentsModule {}
Didn't we agree to have a "wrapper" module only for one checkout? Either the base, b2b or repl?

I think it's enough if just keep the `projects/storefrontapp/src/app/spartacus/features/digital-payments-feature.module.ts`

2022-02-25 13:30 UTC, znikola commented on projects/storefrontapp/src/app/spartacus/features/b2b-digital-payments/checkout-replenishment-dp-feature.module copy.ts
> +import { NgModule } from '@angular/core';
Didn't we agree to have a "wrapper" module only for one checkout? Either the base, b2b or repl?

Also, the file name contains a `copy`?

I think it's enough if just keep the `projects/storefrontapp/src/app/spartacus/features/digital-payments-feature.module.ts`

2022-02-25 13:30 UTC, znikola commented on projects/storefrontapp/src/app/spartacus/features/b2b-digital-payments/b2b-digital-payments.module.ts
> +export class B2BDigitalPaymentsModule {}
Didn't we agree to have a "wrapper" module only for _one_ checkout? Either the base, b2b _or_ repl?

I think it's enough if just keep the `projects/storefrontapp/src/app/spartacus/features/digital-payments-feature.module.ts`

2022-02-25 13:30 UTC, znikola commented on projects/storefrontapp/src/app/spartacus/features/b2b-digital-payments/checkout-b2b-dp-feature.module.ts
> +export class CheckoutB2bDpFeatureModule {}
Didn't we agree to have a "wrapper" module only for _one_ checkout? Either the base, b2b _or_ repl?

I think it's enough if just keep the `projects/storefrontapp/src/app/spartacus/features/digital-payments-feature.module.ts`

2022-02-25 13:30 UTC, znikola commented on integration-libs/digital-payments/schematics/add-digital-payments/index.ts
> -      },
We need to keep this part.
It instructs schematics to install the checkout lib (if not installed)

2022-02-25 13:30 UTC, znikola commented on integration-libs/digital-payments/schematics/constants.ts
> +export const CHECKOUT_BASE_FEATURE_NAME_CONSTANT = 'CHECKOUT_FEATURE';
Let's use only one constant.
I suggest to move the one from `feature-libs/checkout/schematics/constants.ts` to `projects/schematics/src/shared/constants.ts` and use it in both feature libs.

2022-02-25 13:30 UTC, znikola commented on projects/storefrontapp/src/app/spartacus/spartacus-features.module.ts
> +  }
Didn't we agree to have a "wrapper" module only for _one_ checkout? Either the base, b2b _or_ repl?

Do we need to have three module in our sample app?

2022-02-25 14:07 UTC, WeizhengSap commented on projects/storefrontapp/src/app/spartacus/features/b2b-digital-payments/replenishment-digital-payments.module.ts
> +export class ReplenishmentDigitalPaymentsModule {}
it is for our `storefrontapp`, otherwise how to make our `storefrontapp` work with B2B + digital payment?

2022-03-01 10:38 UTC, znikola commented on projects/storefrontapp/src/app/spartacus/features/b2b-digital-payments/replenishment-digital-payments.module.ts
> +export class ReplenishmentDigitalPaymentsModule {}
I'm not sure if we even run DP in our environment?
That's why I was wondering why to bloat our app, if we aren't owning DP and running it frequently?

2022-03-01 13:53 UTC, WeizhengSap commented on projects/storefrontapp/src/app/spartacus/features/b2b-digital-payments/checkout-replenishment-dp-feature.module copy.ts
> +import { NgModule } from '@angular/core';
I removed the b2b wrapper modules.

2022-03-01 14:30 UTC, znikola approved these changes

2022-03-01 14:31 UTC, merged