feat: Add Quick Order missing vocalization (#15233)
SAP/spartacus pull request #15262
Opened 2022-02-28 11:41 UTC by dydome

close #15233

2022-03-01 17:09 UTC, developpeurweb requested changes
Notifications seem to work fine in all SR, **except** the one about items being deleted, mainly because it focuses on the "undo" button. So, either
1. focus the whole alert to include both, message and button, in the narration
... or
2. remove the focus management jump from the button (and just extend the time for the user to be able to get there with the keyboard).

2022-03-03 20:09 UTC, developpeurweb approved these changes, later dismissed
This works well for JAWS*/NVDA/VO
*Works well on JAWS+Firefox. Bugs with JAWS+Chrome (it will be addressed on a separate bug ticket if persistent).

2022-03-04 09:26 UTC, Matejk00 requested changes

2022-03-04 09:26 UTC, Matejk00 commented on feature-libs/cart/quick-order/components/quick-order/quick-order.component.html
> +      <div aria-live="polite" class="cx-visually-hidden">
I think this `aria-live="polite"` attribute is not necessary here, as we have all messages wrapped into another aria-live attribute.

2022-03-04 09:26 UTC, Matejk00 commented on feature-libs/cart/quick-order/components/quick-order/quick-order.component.html
> +      <div aria-live="polite" class="cx-visually-hidden">
I think this `aria-live="polite"` attribute is not necessary here, as we have all messages wrapped into another aria-live attribute.

2022-03-04 09:26 UTC, Matejk00 commented on feature-libs/cart/quick-order/components/quick-order/quick-order.component.html
> +      <div aria-live="polite" class="cx-visually-hidden">
I think this `aria-live="polite"` attribute is not necessary here, as we have all messages wrapped into another aria-live attribute.

2022-03-04 09:26 UTC, Matejk00 commented on feature-libs/cart/quick-order/root/config/quick-order-config.ts
> +      hardDeleteTimeout: number;
Can we add any jsdoc what this `hardDeleteTimeout` property stand for?

2022-03-04 09:26 UTC, Matejk00 commented on projects/storefrontlib/cms-components/misc/message/message.component.ts
> +        // GlobalMessageType.MSG_TYPE_CONFIRMATION:
Should we have commented this out?

2022-03-04 10:24 UTC, Matejk00 approved these changes

2022-03-04 10:28 UTC, merged