GH-11194 Enable notify me button when user is logged in
SAP/spartacus pull request #15272
Opened 2022-03-01 12:47 UTC by Dalvir-Personal

2022-03-03 23:24 UTC, developpeurweb requested changes
Tested with product `872912`
This works on VO and Mac only, but not on Windows, with or without JAWS/NVDA.
What happens on Windows is that the NOTIFY ME button won't get enabled once the user signs in.
It displays the signed-in message, but the button is still disabled. Both Chrome and Firefox.
![2022-03-03_18-11-09](https://user-images.githubusercontent.com/15113219/156669811-75a58e28-686d-4a60-a860-a4498ad3aa3e.jpg)

2022-03-07 20:47 UTC, developpeurweb approved these changes, later dismissed
Seems to work now with JAWS/NVDA/VO.
Pls make sure a dev reviews the code before merging

2022-03-08 08:05 UTC, Matejk00 commented
There is a prietter issue in `projects/storefrontapp-e2e-cypress/cypress/helpers/notification.ts`.
Please use `yarn prettier:fix`.

2022-03-09 08:17 UTC, Matejk00 approved these changes

2022-03-09 08:18 UTC, merged