feat: Vocalisation for PLP after rearrangement by sorting/facets/view (#15217)
SAP/spartacus pull request #15292
Opened 2022-03-03 09:45 UTC by pawelfras

closes #15217

2022-03-03 21:11 UTC, developpeurweb requested changes
This works for NVDA and VO. 
But not for JAWS, neither on Chrome nor Firefox. Needs to work on JAWS on at least one of the two browsers.

2022-03-08 16:04 UTC, developpeurweb submitted a review, later dismissed
The update message is heard after the JAWS bloat. NVDA/VO work as expected.

2022-03-09 07:29 UTC, Matejk00 submitted a review, later dismissed

2022-03-09 08:03 UTC, Matejk00 approved these changes

2022-03-09 09:20 UTC, merged