chore: fix a bug in cart-item-list.component.ts
SAP/spartacus pull request #15314
Opened 2022-03-04 20:24 UTC by WeizhengSap

close #15286

2022-03-10 20:47 UTC, bgambocjaviniar commented on feature-libs/cart/base/components/cart-shared/cart-item-list/cart-item-list.component.ts
> +          control.patchValue({ quantity: item.quantity }, { emitEvent: false });
In what case do we ever land in here? I tried smoke testing this, but I can't find an instance on where this fires, except the unit tests due to direct manipulation of items.

However, I understand if we have an existing control, then let's just give the value to what the item currently have as quantity. But to me it's the same if we remove the if else and just create a new control, but again, this never happens on the app, but only in the unit tests

------------
Basically, I favor keeping what it was before, but changing 

this.form.setControl(controlName, group);

to 

this.form.addControl(controlName, group);
**as it was before**

2022-03-10 20:48 UTC, bgambocjaviniar commented on feature-libs/cart/base/components/cart-shared/cart-item-list/cart-item-list.component.spec.ts
> +      mockItem0.quantity = mockItem0Qty;
👍  I understand we want to set back the quantity to the same it was before to not cause any leak for other future assertions for people, but first I need clarify[ this question before approving](https://github.com/SAP/spartacus/pull/15314/files#r824142667) (we might even remove this if you agree)

2022-03-10 20:48 UTC, bgambocjaviniar commented on feature-libs/cart/base/components/cart-shared/cart-item-list/cart-item-list.component.spec.ts
> +    it('should update controls when quantity change', () => {
I believe this should be, but we might remove depending on the answer in https://github.com/SAP/spartacus/pull/15314/files#r824142667
```suggestion
    it('should update existing controls when quantity change', () => {
```

2022-03-10 20:52 UTC, bgambocjaviniar requested changes
running all e2es* just to verify if saved cart got fixed for being able to focus and other e2es working as intended

Will revert previous commit once pipeline is done, but also change my be done depending on the question related to https://github.com/SAP/spartacus/pull/15314/files#r824142667

2022-03-14 15:33 UTC, WeizhengSap commented on feature-libs/cart/base/components/cart-shared/cart-item-list/cart-item-list.component.ts
> +          control.patchValue({ quantity: item.quantity }, { emitEvent: false });
we use `setControl` because of this ticket https://github.com/SAP/spartacus/issues/14955.

2022-03-17 04:11 UTC, bgambocjaviniar commented on feature-libs/cart/base/components/cart-shared/cart-item-list/cart-item-list.component.ts
> +          control.patchValue({ quantity: item.quantity }, { emitEvent: false });
quick call during the day as I need to verify something

2022-03-17 04:32 UTC, bgambocjaviniar approved these changes

2022-03-17 13:23 UTC, merged