chore: Remove deprecated code and add EventService as required dependency to ComponentWrapperDirective and InnerComponentsHostDirective (#14960)
SAP/spartacus pull request #15369
Opened 2022-03-14 13:28 UTC by dydome

close #14960

2022-03-21 13:04 UTC, Zeyber requested changes

2022-03-21 13:04 UTC, Zeyber commented on projects/schematics/src/migrations/5_0/constructor-deprecations/data/component-wrapper.directive.migration.ts
> +      className: EVENT_SERVICE,
I think this would add the `EventService` a second time to the constructor.

2022-03-21 13:19 UTC, Zeyber submitted a review, later dismissed

2022-03-21 13:55 UTC, Zeyber submitted a review, later dismissed

2022-03-22 08:54 UTC, szczepaniak-michal submitted a review, later dismissed

2022-03-30 10:24 UTC, szczepaniak-michal approved these changes

2022-03-30 11:06 UTC, merged