fix: Support redirects to protected pages from external authenticators
SAP/spartacus pull request #15491
Opened 2022-03-30 06:22 UTC by Zeyber

Closes: #13622

2022-04-27 00:32 UTC, Pucek9 commented on projects/core/src/auth/user-auth/services/oauth-lib-wrapper.service.ts
> +  loginInProgress$: Observable<boolean> = new BehaviorSubject<boolean>(false);
You needn't define an explicit type of property if it's easily inferred by TS. Also calling a method with false causes the type (boolean) to be easily pressed.
![image](https://user-images.githubusercontent.com/8040837/165411069-4833767d-c8e4-4bb3-a55f-80f2cce33332.png)

In this case, you tricked TS that it's an `Observable` by unnecessary type narrowing, making you unable to explicitly refer to the `next` method (which occurs in `BehaviorSubject`, but not in `Observable`) if you have to use an assertion somewhere, there is most likely an oversight somewhere.

2022-04-27 09:26 UTC, Pucek9 approved these changes

2022-04-27 09:52 UTC, Pucek9 commented on projects/core/src/auth/user-auth/services/oauth-lib-wrapper.service.ts
> +  loginInProgress$ = new BehaviorSubject(false);
```suggestion
  protected loginInProgress$ = new BehaviorSubject(false);

  isLoginInProgress(): Observable<boolean> { return this.loginInProgress&.asObservable(); }
```

2022-04-27 11:15 UTC, Pucek9 requested changes
If we dont want to return explicite BehaviorSubject, let's return .asObservable() instead

2022-05-05 11:22 UTC, Pucek9 approved these changes
I was not able to confirm improvement by QA because it's hard to reproduce the issue on develop.

2022-05-05 12:04 UTC, Platonn commented on projects/core/src/auth/user-auth/facade/auth.service.ts
> +      this.oAuthLibWrapperService.isLoginInProgress(),
Did you consider any other alternative solutions?

Now `isUserLoggedIn()` indirectly depends now on calling `tryLogin()` specifically.

Nitpicks on details:
- Are there any other cases (besides invoking `tryLogin()`) when the “login process is in progress” and we should allow for observing it via `loginInProgress$`? Currently it’s bound only to the custom implementation of `tryLogin()`. And what about other processes when “login is in progress”? I don’t know TBH, maybe calling another method of `OAuthService`? e.g. `tryLoginWithBlahBlah` etc. or calling the OCC endpoint for login?
- should `isUserLoggedIn()` return false when the “login is in progress”? Or should it hold emitting any values until the login is in progress (e.g. use rxjs `filter("...login is in progress...")`)? And if we hold emiting values, what side effects might it cause?

2022-05-05 12:08 UTC, Platonn requested changes
I'd be happy to understand the roots of the problem so to see if there are any possible alternative solutions.

As we agreed offline, I'm setting status "Request changes" so it's not merged accidentally.

2023-04-18 13:42 UTC, closed without merging