Feature/gh 15499
SAP/spartacus pull request #15579
Opened 2022-04-08 14:46 UTC by Uli-Tiger

Adds a new UI setting 'enableNavigationToConflict' with default false. It controls whether attributes render a link to navigate to the conflict group or just a message. Prerequisite for enabling the setting is commerce 2205.

2022-04-11 11:13 UTC, Uli-Tiger commented
@schuppell: can you give me some guidance how to handle those breaking changes?
> ## Public API changes
> ### ⚠️ @spartacus/product-configurator/rulebased
> 
> ```diff
>  
>  // @public (undocumented)
>  export class ConfiguratorAttributeHeaderComponent extends ConfiguratorAttributeBaseComponent implements OnInit {
> -    constructor(configUtils: ConfiguratorStorefrontUtilsService, configuratorCommonsService: ConfiguratorCommonsService, configuratorGroupsService: ConfiguratorGroupsService);
> +    constructor(configUtils: ConfiguratorStorefrontUtilsService, configuratorCommonsService: ConfiguratorCommonsService, configuratorGroupsService: ConfiguratorGroupsService, configuratorStorefrontUtilsService: ConfiguratorStorefrontUtilsService, configuratorUiSettings: ConfiguratorUISettingsConfig);
>      // (undocumented)
>      attribute: Configurator.Attribute;
>      // (undocumented)
> @@
> ```
> 
> #### ⚠️ Some entry points are currently impossible to analyze.
> Read more
> #### 💰 How to debug problems?
> Read more

2022-04-19 14:31 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.ts
> -    protected configuratorStorefrontUtilsService: ConfiguratorStorefrontUtilsService
just in case someone is wondering. _configuratorStorefrontUtilsService_ was added a few days ago by @Changsuwan (https://github.com/SAP/spartacus/commit/6a8beb3df815017823c71b9ef9ec9be04e6c10d9). However it is just a duplicate of configUtils (line 38) and was never used. hence i removed it after consulting with her.

2022-04-20 09:29 UTC, Larisa-Staroverova submitted a review, later dismissed

2022-04-25 10:16 UTC, ChristophHi requested changes
Looks good. Please add JS doc and turn the new dependency into mandatory as discussed..

2022-04-25 10:16 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.ts
> +  isNavigationToConflictEnabled(): boolean {
Please add JS doc for this public one

2022-04-26 12:37 UTC, Uli-Tiger commented
i'll provide the schematics for constructor deprecation in a another PR.

2022-04-26 13:26 UTC, ChristophHi approved these changes

2022-04-26 14:11 UTC, merged