Reordered the scss files load
SAP/spartacus pull request #15599
Opened 2022-04-13 19:19 UTC by Dalvir-Personal

2022-04-19 13:25 UTC, morganm58 approved these changes

2022-04-19 15:48 UTC, bgambocjaviniar requested changes
as discussed, please do not merge this re-order as it is not a viable solution

cart and order lib should be re-worked to not re-import the base styles

2022-04-19 15:56 UTC, morganm58 requested changes
Brian proposed a solution that solves the problem without having potential future issues. cart and order libs are duplicating the styles

2022-04-20 15:58 UTC, bgambocjaviniar requested changes
@morganm58 

the changes you applied looks good, but I would like the following to follow the convention we have in place

1 - make a new PR as all branches that is not a release or an epic are called feature. So name the branch `feature/GH-15534`
2 - @morganm58  after pushing a new branch for the one in develop (do not create those other branches that will point to maintenance branches as it just causes overhead to change down the road IF there will have additional changes). Leave the imports where they are and do not re-order them
3 - name the pull request as `style: Fixes re-import of entire spartacus/styles` <-- something along those lines so that when we merge, it will be there automatically without manually changing it

apply changes requested in other changes below (IF applicable)

2022-04-20 15:58 UTC, bgambocjaviniar commented on feature-libs/cart/_index.scss
> +@import 'cxbase/blocks/modal';
let's include the package path and place it under the spartacus/styles/scss/core to bundle them

`@import '~@spartacus/styles/scss/cxbase/blocks/modal';`

2022-04-20 15:58 UTC, bgambocjaviniar commented on feature-libs/cart/_index.scss
> +@import 'misc/hamburger';
Took a glance, but I don't think the cart styles is using anything from the hamburger stylesheet right?

2022-04-20 15:58 UTC, bgambocjaviniar commented on feature-libs/cart/_index.scss
> +@import 'misc/dialog';
Don't think it's being used anywhere in the cart styles

2022-04-20 15:58 UTC, bgambocjaviniar commented on feature-libs/cart/_index.scss
> +@import 'misc/table';
Same as previous. Let's include the package name

`@import '~@spartacus/styles/scss/misc/table';`

2022-04-20 15:58 UTC, bgambocjaviniar commented on feature-libs/cart/_index.scss
> +@import 'misc/table';
What do you think about just putting this import in `feature-libs/cart/base/styles/components/_cart-item-list.scss` 

as that's the only place that is using extending .cx-agnostic-table

OR 

do you think it should be at the top level?

2022-04-20 15:58 UTC, bgambocjaviniar commented on feature-libs/order/styles/_index.scss
> +@import '~@spartacus/styles/scss/core';
I haven't checked yet, but is core the only necessary things for the order stylesheet.

It is using something from modal, tables, etc? Same reasoning as in the cart stylesheet

2022-04-20 15:58 UTC, bgambocjaviniar commented on integration-libs/epd-visualization/_index.scss
> -@import '~@spartacus/styles/scss/app';
Why did app get removed. Was there no instances of some re-used classes from our styles?

2022-04-20 15:58 UTC, bgambocjaviniar commented on projects/storefrontstyles/scss/theme/sparta/_variables.scss
> +$font-family-sans-serif: $font-family !default;
is this necessary? If not, let's keep it as what it was before as I don't see a need to set it as a default from the issue at hand

2022-04-20 15:58 UTC, bgambocjaviniar commented on projects/storefrontstyles/scss/theme/sparta/_variables.scss
> +$font-size-base: 1rem !default; //16px
same for above, do we really want it as default?

2022-04-20 15:58 UTC, bgambocjaviniar commented on projects/storefrontstyles/scss/theme/sparta/_variables.scss
>  $h2-font-size: $font-size-base * 1.75; //28px
@morganm58 

all that being said, please create a new branch with the proper conventions!

2022-04-20 16:01 UTC, bgambocjaviniar commented on integration-libs/epd-visualization/_index.scss
> -@import '~@spartacus/styles/scss/app';
Same applies for cart and order. Have to make sure we didn't miss anything

2022-04-21 03:56 UTC, bgambocjaviniar commented
closing in favor for https://github.com/SAP/spartacus/pull/15619

2022-04-21 03:56 UTC, closed without merging