feat: migration to add translation service to constructor
SAP/spartacus pull request #15597
Opened 2022-04-13 11:50 UTC by Uli-Tiger

2022-04-25 09:11 UTC, ChristophHi requested changes

2022-04-25 09:11 UTC, ChristophHi commented on projects/schematics/src/migrations/5_0/constructor-deprecations/data/configurator-attribute-numeric-input-field.component.migration.ts
> +export const CONFIGURATOR_ATTRIBUTE_INPUT_FIELD_COMPONENT_MIGRATION: ConstructorDeprecation =
Please have this constant named according to the underlying component and the migration file name:
```suggestion
export const CONFIGURATOR_ATTRIBUTE_NUMERIC_INPUT_FIELD_COMPONENT_MIGRATION: ConstructorDeprecation =
```

2022-04-25 14:42 UTC, ChristophHi submitted a review, later dismissed

2022-04-27 08:31 UTC, psmul approved these changes

2022-04-27 14:11 UTC, merged