feat: add show/hide functionality to password inputs (#14066)
SAP/spartacus pull request #15593
Opened 2022-04-12 19:47 UTC by BenjaminEmiliani

Closes #14066

2022-04-28 10:43 UTC, Matejk00 commented
Also maybe is worth to mention about this component in our docs: https://sap.github.io/spartacus-docs/components/ :)

2022-04-28 10:58 UTC, Matejk00 requested changes

2022-04-28 10:58 UTC, Matejk00 commented on projects/storefrontlib/shared/components/form/toggle-password-visibility/toggle-password-visibility.component.ts
> +  protected showState = {
Might be more TypeScript friendly to define a model for `TogglePasswordState`. For example:

```
export interface TogglePasswordState {
  icon: ICON_TYPE;
  inputType: string;
  ariaLabel: string;
}
```

Then all states can consists of same type of properties:
```
  protected SHOWN_PASSWORD: TogglePasswordState = {
    icon: ICON_TYPE.EYE_SLASH,
    inputType: 'text',
    ariaLabel: 'passwordVisibility.hidePassword',
  };

  protected HIDDEN_PASSWORD = {
    icon: ICON_TYPE.EYE,
    inputType: 'password',
    ariaLabel: 'passwordVisibility.showPassword',
  };
```

2022-04-28 10:58 UTC, Matejk00 commented on projects/storefrontlib/shared/components/form/toggle-password-visibility/toggle-password-visibility.component.ts
> +    if (this.state === this.hideState) {
This can be simplified:
```
    this.state === this. hideState
      ? (this.state = this.showState)
      : (this.state = this. hideState);
```

2022-04-28 10:58 UTC, Matejk00 commented on projects/storefrontlib/shared/components/form/toggle-password-visibility/toggle-password-visibility.directive.ts
> +    const parent = this.elementRef.nativeElement.parentNode;
Here I think we can re-use first const.
```
    const parent = input.parentNode;
```

2022-04-28 10:58 UTC, Matejk00 commented on projects/storefrontlib/shared/components/form/toggle-password-visibility/toggle-password-visibility.component.ts
> +  state = this.hideState;
This should be type of `TogglePasswordState`. See comment above.

2022-04-28 10:58 UTC, Matejk00 commented on projects/storefrontlib/shared/components/form/toggle-password-visibility/toggle-password-visibility.component.ts
> +  constructor() {}
It can be removed if empty.

2022-04-28 10:58 UTC, Matejk00 commented on projects/storefrontlib/shared/config/form-config.ts
> +    passwordVisibility: boolean;
maybe would be better to name it `togglePasswordVisibility`?

2022-04-28 11:23 UTC, Pucek9 commented on projects/storefrontlib/shared/components/form/toggle-password-visibility/toggle-password-visibility.component.ts
> +    if (this.state === this.hideState) {
I think you mean 
```
    this.state =
      this.state === this.hideState ? this.showState : this.hideState;
```

2022-04-28 11:25 UTC, Matejk00 commented on projects/storefrontlib/shared/components/form/toggle-password-visibility/toggle-password-visibility.component.ts
> +    if (this.state === this.hideState) {
yes, I meant using this if notation

2022-05-06 08:07 UTC, Matejk00 submitted a review, later dismissed

2022-05-06 11:21 UTC, Matejk00 approved these changes

2022-05-06 18:49 UTC, merged