add tabability and check screen reader
SAP/spartacus pull request #15603
Opened 2022-04-14 08:32 UTC by Changsuwan

2022-04-22 14:31 UTC, steinsebastian requested changes

2022-04-22 14:31 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.html
> +      tabindex="0"
I would add an aria-label attribute for this link to the conflict solver to give the blind user a better understanding what this link is about.
It might be added like this:
      [attr.aria-label]="
        'configurator.a11y.navigateToConflict'
          | cxTranslate: { attribute: attribute.label }
      "
Then an appropriate text has to be added to file configurator-common.ts, like:
      navigateToConflict: 'Follow link to get more details on conflict for attribute {{ attribute }}',

2022-04-26 10:55 UTC, steinsebastian approved these changes, later dismissed

2022-04-27 06:22 UTC, steinsebastian approved these changes

2022-04-27 08:03 UTC, ChristophHi approved these changes

2022-04-27 12:21 UTC, merged