Conflict Solver Enhancement: Retract conflicting read-only value
SAP/spartacus pull request #15651
Opened 2022-04-26 09:00 UTC by Larisa-Staroverova

2022-04-26 14:13 UTC, ChristophHi requested changes

2022-04-26 14:13 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      configUISettingsConfig.productConfigurator.addRetractOption = true;
Class has 9 strict mode issues. Please fix.

One way to fix is 

   `   (configUISettingsConfig.productConfigurator ??= {}).addRetractOption =  false;`

2022-04-26 14:13 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.ts
> +          sourceAttribute.type ?? OccConfigurator.UiType.NOT_IMPLEMENTED,
Branch not covered with test

2022-04-26 14:13 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.ts
> +  convertAttributeType(
Could we extend the signature only by OccConfigurator.Attribute? Then we could later on add more variables that influence the uiType without doing breaking changes

2022-04-27 04:21 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      configUISettingsConfig.productConfigurator.addRetractOption = true;
Done!

2022-04-27 06:10 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.ts
> +          sourceAttribute.type ?? OccConfigurator.UiType.NOT_IMPLEMENTED,
Done!

2022-04-27 07:40 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.ts
> +  convertAttributeType(
Done!

2022-04-27 08:43 UTC, ChristophHi requested changes

2022-04-27 08:43 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.ts
> +            valueDisplay: '',
This line can be removed, right?

2022-04-27 09:17 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.ts
> +            valueDisplay: '',
Done!

2022-04-27 09:18 UTC, ChristophHi approved these changes

2022-04-27 11:27 UTC, merged