Feature/cxspa 332
SAP/spartacus pull request #15698
Opened 2022-05-02 11:05 UTC by FollowTheFlo

PDF Component implementation, this PR includes:
Business logic and styling
Not to take in account in this PR: logo and Accessibility as still need to be defined.

2022-05-02 15:09 UTC, RadhepS requested changes

2022-05-02 15:09 UTC, RadhepS commented on .env-cmdrc
> +    "CX_BASE_URL": "https://52.188.69.146:59002"
should be changed back when merging

2022-05-02 15:09 UTC, RadhepS commented on projects/core/src/model/cms.model.ts
> +  height: number;
height should be optional since it can be undefined from smartedit

2022-05-02 15:09 UTC, RadhepS commented on projects/storefrontlib/cms-components/content/pdf/pdf.component.html
> +      (click)="!data?.pdfFile?.url || download(data.pdfFile)"
not able to start your branch but,

do we need `!data`? Also, do we need the download function or can we always just use the URL?

2022-05-02 15:09 UTC, RadhepS commented on projects/storefrontlib/cms-components/content/pdf/pdf.component.html
> +      aria-label="Download PDF file"
aria label should be translated unless this will be done in a difference PR

2022-05-03 11:09 UTC, FollowTheFlo commented on .env-cmdrc
> +    "CX_BASE_URL": "https://52.188.69.146:59002"
yes , i did it on purpose, the plan is to set it on epic/pdf, will be change back before merge to develop.

2022-05-03 13:09 UTC, RadhepS requested changes

2022-05-03 13:09 UTC, RadhepS commented on projects/storefrontlib/cms-components/content/pdf/pdf.component.html
> +      {{ data?.name || data?.pdfFile?.altText || 'document.pdf' }}
We can add translation to the fallback document.pdf text

2022-05-03 13:11 UTC, RadhepS commented on projects/storefrontstyles/scss/components/content/pdf/_pdf.scss
> +%cx-pdf {
Can you have Mikel review the CSS please?

2022-05-03 13:21 UTC, RadhepS commented on projects/storefrontlib/cms-components/content/pdf/pdf.component.html
> +      {{ data?.name || data?.pdfFile?.altText || 'document.pdf' }}
Can you verify with UX/UI whether we should append .pdf to the name of the file? Easier for people to know its a pdf file but, I noticed other websites don't include the .pdf extension in the name

2022-05-03 14:14 UTC, morganm58 commented on projects/storefrontstyles/scss/components/content/pdf/_pdf.scss
> +      margin-left: 10px;
This should be `margin-inline-start: 0.625rem;` This will make it work with directionality. And we should be using rem instead of px for padding, margin and font-sizes

2022-05-03 14:18 UTC, morganm58 commented on projects/storefrontstyles/scss/components/content/pdf/_pdf.scss
> +    font-size: 0.875 rem;
Font-sizes should be variables. `font-size: var(--cx-font-size, 0.875rem);`

2022-05-03 14:23 UTC, morganm58 commented on projects/storefrontstyles/scss/components/content/pdf/_pdf.scss
> +    padding: 15px;
Can you change the px to rem. this would be 0.938rem

2022-05-10 15:48 UTC, RadhepS requested changes

2022-05-10 15:48 UTC, RadhepS commented on projects/assets/src/translations/en/pdf.ts
> +    document: 'Document',
i think this can be `defaultName: 'Document'`

2022-05-11 14:00 UTC, morganm58 approved these changes

2022-05-11 17:52 UTC, RadhepS approved these changes

2022-05-11 18:17 UTC, merged