chore: Review Deleted Api
SAP/spartacus pull request #16001
Opened 2022-07-18 05:33 UTC by bgambocjaviniar

closes https://jira.tools.sap/browse/CXSPA-718

2022-07-25 08:16 UTC, znikola requested changes

2022-07-25 08:16 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +        "migrationComment": "It is not used in the base checkout entrypoint (b2c) as checkout has been decoupled into base (b2c), b2b, and replenishment. The method is found when b2b checkout is used
```suggestion
        "migrationComment": "It is not used in the base checkout entrypoint (b2c) as checkout has been decoupled into base (b2c), b2b, and scheduled replenishment. The method is found when b2b checkout is used instead, which uses the new class 'CheckoutB2BAuthGuard.",
```

2022-07-26 14:44 UTC, znikola requested changes

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "newEntryPoint": "@spartacus/checkout/base/core",
Nice!

2022-07-26 14:44 UTC, znikola commented on projects/schematics/src/migrations/5_0/rename-symbol/rename-symbol.ts
> +  },
Does this handle the case when we renamed the property? 
E.g., previously we had

```ts
constructor(..., protected checkoutDetailsService: CheckoutDetailsService, ...) {}
```

but now we changed the type _and_ the property name: 

```ts
constructor(..., protected checkoutQueryService: CheckoutQueryService, ...) {}
```

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +        "migrationComment": "'CheckoutDeliveryService' has been splitted and renamed to 'CheckoutDeliveryAddressFacde' and 'checkoutDeliveryModesFacade'. Use 'checkoutDeliveryAdressFacade' and 'check
```suggestion
        "migrationComment": "'CheckoutDeliveryService' has been splitted and renamed to 'CheckoutDeliveryAddressFacde' and 'CheckoutDeliveryModesFacade'. Use 'checkoutDeliveryAdressFacade' and 'checkoutDeliveryModesFacade' instead.",
```

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "newNamespace": "",
Just curious, do we have specify this?

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
```suggestion
    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.github.io/spartacus-docs/commands-and-queries. You can leverage RxJS' error handling when calling the 'createAndSetAddress()' from CheckoutDeliveryAddressFacade.",
```

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
Nice.

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
```suggestion
    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.github.io/spartacus-docs/commands-and-queries. You can leverage the 'createAndSetAddress()' from CheckoutDeliveryAddressFacade.",
```

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
Same as for the previous.
I'm not sure what you mean by "You can leverage the creation of delivery address 'state' using"? I think we can just tell customers to use the new API method, without specifying if it's a state or not?
And to be even more precise - it's a command, therefore not a state.

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
Won't be flagging these anymore. It would be good to align on the previous comments.
If we decide to change these messages, I think you can just do a search to find them all.

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
I'm thinking is the first part too much?
This: `It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.github.io/spartacus-docs/commands-and-queries. ` might repeat way too often, and it might just create noise in the code.
I think it should be obvious the clients should read the c&q docs, which already mentions the fact the checkout doesn't use ngrx anymore.

2022-07-26 14:44 UTC, znikola commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
```suggestion
    "migrationComment": "It is not used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.github.io/spartacus-docs/commands-and-queries.",
```

2022-07-27 06:09 UTC, bgambocjaviniar commented on tools/breaking-changes/data/breaking-changes.json
> +    "newNamespace": "",
nay, just template things haha if ever a newNameSpace was actually made

2022-07-27 06:12 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/5_0/rename-symbol/rename-symbol.ts
> +  },
Looking at the source code for it, it does not unfortunately, but they'd have the imports changed to use the correct one :d 

---
all in all, these were one of my pain points, where I asked Patrick that we should make a mgiration comment available for all migrations

2022-07-27 06:14 UTC, bgambocjaviniar commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
yeye it was already fixed in one of the latest commits

2022-07-27 06:26 UTC, bgambocjaviniar commented on tools/breaking-changes/data/breaking-changes.json
> +    "migrationComment": "It is no used anymore. Checkout library no longer uses NgRX to dispatch actions. Please take a look at Commands & Queries documentation on how we handle state https://sap.git
yeye I understand it's a command, but they can derive the state by leveraging RxJS using that command, but yeah how I wrote it is confusing :P

2022-07-27 09:47 UTC, znikola commented on projects/schematics/src/migrations/5_0/rename-symbol/rename-symbol.ts
> +  },
Yes, the imports would change. 
A minor problem is that they would have two properties with different names that do the same thing.

2022-07-27 09:47 UTC, znikola approved these changes

2022-07-27 20:15 UTC, merged