fix: AMP violations on Approval dashboard Page
SAP/spartacus pull request #16045
Opened 2022-08-03 18:00 UTC by kimhw0630

fixed AMP violations on Approval dashboard Page
https://jira.tools.sap/browse/CXSPA-476

2022-08-04 14:22 UTC, justinlee01 approved these changes, later dismissed

2022-09-01 10:20 UTC, Zeyber requested changes
All seems okay. Just needs mentioning the template changes in `6_0.md`.

2022-09-01 14:17 UTC, Zeyber approved these changes, later dismissed

2022-09-06 12:56 UTC, Zeyber approved these changes

2022-09-06 12:57 UTC, merged