ng bootstrap removal draft for consignment feature dialog (CXSPA-1248)
SAP/spartacus pull request #16131
Opened 2022-09-06 12:59 UTC by psmul

Closes: CXSPA-1248

2022-09-08 16:09 UTC, morganm58 commented on projects/storefrontstyles/scss/cxbase/blocks/modal.scss
> +// Ng-bootstrap modal Styling
You can remove these commented out styles

2022-09-08 16:43 UTC, morganm58 commented on feature-libs/order/components/order-details/order-detail-items/consignment-tracking/tracking-events/tracking-events.component.html
> +        <div class="shipment-heading">
Should have the `cx-` prefix on the classes

2022-09-08 16:44 UTC, morganm58 commented on feature-libs/order/components/order-details/order-detail-items/consignment-tracking/tracking-events/tracking-events.component.html
> +              <div class="shipment-title">
Same here with the `cx-` prefix on the classes

2022-09-08 16:45 UTC, morganm58 commented on feature-libs/order/components/order-details/order-detail-items/consignment-tracking/tracking-events/tracking-events.component.html
> +              <div class="shipment-content">
same here with the `cx` prefix here as well

2022-09-08 16:46 UTC, morganm58 commented on feature-libs/order/components/order-details/order-detail-items/consignment-tracking/tracking-events/tracking-events.component.html
> +      <div class="events modal-body">
`cx-` prefix on `events` as well and the other event classes below

2022-09-13 07:52 UTC, pawelfras requested changes

2022-09-13 07:52 UTC, pawelfras commented on docs/migration/5_0.md
> +- Changed `<div class="event-content">` to `<div class="-tracking-event-content">`
Missing `cx` in class name

2022-09-13 07:52 UTC, pawelfras commented on feature-libs/order/components/order-details/order-detail-items/consignment-tracking/consignment-tracking.component.ts
> +      this.subscription.add(dialog.pipe(take(1)).subscribe());
`query:` Do we need to use `subscription` in this case? I believe `take(1)` is handling unsubscribe under the hood. Consider to remove `Subscription` and `OnDestroy` interface.

2022-09-13 07:52 UTC, pawelfras commented on feature-libs/order/components/order-details/order-detail-items/consignment-tracking/tracking-events/tracking-events.component.ts
> +    protected launchdialogService: LaunchDialogService
Missing camelCase

2022-09-13 10:24 UTC, pawelfras approved these changes

2022-09-13 10:25 UTC, merged