feat: upgrade to Angular 14
SAP/spartacus pull request #16175
Opened 2022-09-19 14:33 UTC by WeizhengSap

2022-09-23 14:52 UTC, plabadie commented on scripts/install/config.default.sh
> +ANGULAR_CLI_VERSION='^14.1.3'
I think we missed this one for the 14.2 upgrade.

2022-09-23 18:59 UTC, plabadie commented on feature-libs/checkout/base/occ/public_api.ts
> +export * from './model/index';
delete the corresponding index.ts

2022-09-23 19:20 UTC, plabadie commented on feature-libs/organization/order-approval/public_api.ts
> +export * from './order-approval.module';
Likely need to delete the associated index.ts file

2022-09-23 20:38 UTC, plabadie requested changes
See the 2 small comments about index.ts files.

2022-09-26 15:38 UTC, plabadie approved these changes

2022-09-26 16:21 UTC, merged

2023-07-18 16:52 UTC, RadhepS commented on scripts/install/functions.sh
> +  ng add @spartacus/tracking --skip-confirmation --no-interactive --features "TMS-GTM" --features "TMS-AEPL"
why was @{spartacus_version} removed?