fix: adapt configuration related additions in cart to refactored tables
SAP/spartacus pull request #16307
Opened 2022-10-14 12:36 UTC by Platonn

- bundle-info component: style always in a compact way
- issues-notification component: reduce the margin-top

closes #15566

2022-10-14 13:11 UTC, ChristophHi requested changes
Why does the mobile display deviate from desktop (desktop not showing the labels in the bundle summary)?
Mobile:
![Screenshot 2022-10-14 at 15 07 14](https://user-images.githubusercontent.com/33626130/195855197-46281daa-e4f5-408c-94b7-41ad59ab7596.png)
Desktop:
![Screenshot 2022-10-14 at 15 07 40](https://user-images.githubusercontent.com/33626130/195855275-41273359-801e-44d7-9982-6e15cc528709.png)

2022-10-14 13:58 UTC, Platonn commented on feature-libs/product-configurator/common/components/configurator-cart-entry-bundle-info/configurator-cart-entry-bundle-info.component.spec.ts
> -      it('should display in mobile mode', () => {
I left only unit tests for mobile (aka. "compact") view, and changed test description to just "should display"

2022-10-17 06:31 UTC, ChristophHi submitted a review, later dismissed

2022-10-17 06:44 UTC, Larisa-Staroverova approved these changes, later dismissed

2022-10-17 07:26 UTC, ChristophHi approved these changes

2022-10-18 06:44 UTC, merged