Feature/cxspa 1498
SAP/spartacus pull request #16373
Opened 2022-10-26 12:55 UTC by JedidiahAwuku

2022-10-26 16:00 UTC, SVendittelli requested changes
Please address these comments and the failing checks

2022-10-26 16:00 UTC, SVendittelli commented on .env-cmdrc
> +    "CX_BASE_URL": "https://api.cg79x9wuu9-eccommerc1-p1-public.model-t.myhybris.cloud/"
This should not be permanent

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/assets/translations/en/pickup-in-store.i18n.ts
> +
I believe the rest of these are alphabetical in the file, could this be moved to maintain that?

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/assets/translations/en/pickup-in-store.i18n.ts
> +  setPreferredStore,
Same as above

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/components/container/pickup-option-dialog/pickup-option-dialog.component.spec.ts
> +  it('ngOnInit should set the cartId and userId for a logged in user', () => {
This is a nitpick, but there should be a blank line between `it` blocks

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/components/container/pickup-option-dialog/pickup-option-dialog.component.ts
> +      // TODO change this to be their intended store, not preferred store
Remove completed todo comment

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/components/container/set-preferred-store/set-preferred-store.component.html
> +-->
What is the purpose of this comment?

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/components/container/set-preferred-store/set-preferred-store.component.spec.ts
> +}
Spec file with no tests?

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/components/container/store-list/store-list.component.ts
> -    this.preferredStoreService.setPreferredStore({ name, displayName });
`preferredStoreService` is no longer used, it should be removed

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/components/container/store-list/store-list.component.spec.ts
> -    preferredStoreService = TestBed.inject(PreferredStoreService);
`preferredStoreService` is no longer used, it should be removed

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/core/facade/intended-pickup-location.service.spec.ts
> +      pickupOption: 'pickup' as PickupOption,
This cast is unnecessary, remove it

2022-10-26 16:00 UTC, SVendittelli commented on feature-libs/pickup-in-store/styles/_set-preferred-store.scss
> +  font-weight: 600;
Have a look at the other CSS we've defined. I believe there is a helper method for font size and weight. Talk to me if you can't find it

2022-10-31 09:18 UTC, JedidiahAwuku commented on .env-cmdrc
> +    "CX_BASE_URL": "https://api.cg79x9wuu9-eccommerc1-p1-public.model-t.myhybris.cloud/"
Reverted to initial instance

2022-10-31 09:18 UTC, JedidiahAwuku commented on feature-libs/pickup-in-store/assets/translations/en/pickup-in-store.i18n.ts
> +
Done

2022-10-31 09:20 UTC, JedidiahAwuku commented on feature-libs/pickup-in-store/components/container/set-preferred-store/set-preferred-store.component.html
> +-->
This served as a guideline for implementation. It has now been removed.

2022-10-31 11:47 UTC, JedidiahAwuku commented on feature-libs/pickup-in-store/components/container/store-list/store-list.component.ts
> -    this.preferredStoreService.setPreferredStore({ name, displayName });
Done

2022-10-31 11:47 UTC, JedidiahAwuku commented on feature-libs/pickup-in-store/components/container/store-list/store-list.component.spec.ts
> -    preferredStoreService = TestBed.inject(PreferredStoreService);
Done

2022-10-31 11:47 UTC, JedidiahAwuku commented on feature-libs/pickup-in-store/core/facade/intended-pickup-location.service.spec.ts
> +      pickupOption: 'pickup' as PickupOption,
Done

2022-10-31 11:47 UTC, JedidiahAwuku commented on feature-libs/pickup-in-store/styles/_set-preferred-store.scss
> +  font-weight: 600;
Done

2022-10-31 11:47 UTC, JedidiahAwuku commented on feature-libs/pickup-in-store/components/container/set-preferred-store/set-preferred-store.component.spec.ts
> +}
Added

2022-10-31 14:11 UTC, SVendittelli approved these changes

2022-11-01 09:44 UTC, merged