fix: fix the issue of SmartEdit with Spartacus in SSR not working properly
SAP/spartacus pull request #16477
Opened 2022-11-15 15:57 UTC by WeizhengSap

ticket: CXSPA-776

2022-11-18 09:53 UTC, kacperknapik commented on feature-libs/smartedit/root/services/smart-edit-launcher.service.ts
> +          // we don't want to process smartedit when doing SSR
Does it mean that Smartedit will not be available at all when SSR is used?

2022-12-01 17:03 UTC, WeizhengSap commented on feature-libs/smartedit/root/services/smart-edit-launcher.service.ts
> +          // we don't want to process smartedit when doing SSR
No, it just make smartedit contract added during client apps render,. So, you can still start your app in SSR.

2023-01-09 14:14 UTC, bgambocjaviniar requested changes
new changes doesn't work properly on the server this time

using the setTimeout trick to simulate 'slowness' causes an infinite loop instead of it working. The previous solution was fine, but local was not. 
This solution local is fine, but server is not.

![Screenshot 2023-01-09 at 9 12 01 AM](https://user-images.githubusercontent.com/29099466/211327961-33b8bccd-7483-4aff-b1ac-755c29f64d1a.png)

2023-01-09 17:06 UTC, bgambocjaviniar commented on projects/core/src/routing/store/reducers/router.reducer.ts
> +    console.log('state', state.queryParams.cmsTicketId);
remove the log

2023-01-09 17:10 UTC, bgambocjaviniar commented on feature-libs/smartedit/core/services/smart-edit.service.ts
> +    /**
before I forget, put a TODO(CXPSA-ticketnumber): Remove constructor comment and reference a created issue for this

2023-01-09 19:41 UTC, bgambocjaviniar approved these changes, later dismissed

2023-01-10 17:19 UTC, bgambocjaviniar reviewed
suite runs perfectly

https://cloud.cypress.io/projects/k3nmep/runs?branches=%5B%7B%22label%22%3A%22feature%2FCXSPA-776%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22feature%2FCXSPA-776%22%7D%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D

note:
check for b2b is failing since recent build from manual trigger flaked for a b2b test

2023-01-10 17:35 UTC, bgambocjaviniar approved these changes

2023-01-10 18:20 UTC, merged