feature: removed aria-hidden attribute from active element (CXSPA-1448)
SAP/spartacus pull request #16476
Opened 2022-11-15 15:45 UTC by kimhw0630

removed aria-hidden attribute from an active element in store find list item
closes https://jira.tools.sap/browse/CXSPA-1448

2022-11-17 15:25 UTC, justinlee01 approved these changes
I assume this isn't a breaking change (doesn't seem a customer would use this as a selector)... Would be interested if I were wrong

2022-11-17 15:48 UTC, kimhw0630 commented
> 

 Additions, changes, or deletions of aria attributes (for screen readers) are not considered breaking changes.
(https://sap.github.io/spartacus-docs/breaking-changes/#avoiding-breaking-changes)

2022-11-18 07:24 UTC, Zeyber approved these changes

2022-11-18 07:34 UTC, Zeyber requested changes
Please fix the naming in this PR to follow conventions.

2022-11-18 13:15 UTC, Zeyber approved these changes

2022-11-18 16:41 UTC, merged