Feature/cxspa 1759: Show text with the selected filters
SAP/spartacus pull request #16514
Opened 2022-11-21 12:03 UTC by I539321

Jira ticket: https://jira.tools.sap/browse/CXSPA-1759

2022-11-22 12:24 UTC, MarcinGanczorz requested changes

2022-11-22 12:24 UTC, MarcinGanczorz commented on feature-libs/organization/unit-order/components/unit-level-order-history/filter/unit-level-order-history-filter.component.html
> +        >"{{ unitFilterMobileId.value }}"</span
We shouldn't use control values here because they'll be updated even without request call. We should maybe store those values and update them only if we are about to send filter change event.

2022-11-22 12:37 UTC, I539321 commented on feature-libs/organization/unit-order/components/unit-level-order-history/filter/unit-level-order-history-filter.component.html
> +        >"{{ unitFilterMobileId.value }}"</span
That is a good suggestion, will update it.

2022-11-28 08:57 UTC, MarcinGanczorz approved these changes

2022-11-28 09:07 UTC, I539321 commented on feature-libs/organization/unit-order/components/unit-level-order-history/filter/unit-level-order-history-filter.component.html
> +        >"{{ unitFilterMobileId.value }}"</span
Resolving conversation

2022-11-28 09:07 UTC, merged