Refactor intersection service, enable adding an additional parameters
SAP/spartacus pull request #16550
Opened 2022-11-28 08:37 UTC by Larisa-Staroverova

2022-11-30 14:05 UTC, znikola requested changes

2022-11-30 14:05 UTC, znikola commented on projects/storefrontlib/layout/loading/intersection.service.ts
> +    intersectingCondition?: (entry: IntersectionObserverEntry) => boolean
Since we reuse this fn type in a couple of places, I suggest creating a type out of it

2022-11-30 14:05 UTC, znikola commented on projects/storefrontlib/layout/loading/intersection.service.ts
> +   * @param intersectingCondition - Allows to specify an intersecting condition
Let's make it clear what happens if `intersectingCondition` is not provided

2022-11-30 14:05 UTC, znikola commented on projects/storefrontlib/layout/loading/intersection.service.ts
> +   * @param intersectingCondition - Allows to specify an intersecting condition
The same as above - can we make it a bit clearer to customers what happens if this is provided, and what happens if it is not provided ?

2022-12-01 08:25 UTC, Larisa-Staroverova commented on projects/storefrontlib/layout/loading/intersection.service.ts
> +    intersectingCondition?: (entry: IntersectionObserverEntry) => boolean
Done!

2022-12-01 08:25 UTC, Larisa-Staroverova commented on projects/storefrontlib/layout/loading/intersection.service.ts
> +   * @param intersectingCondition - Allows to specify an intersecting condition
Done!

2022-12-01 08:25 UTC, Larisa-Staroverova commented on projects/storefrontlib/layout/loading/intersection.service.ts
> +   * @param intersectingCondition - Allows to specify an intersecting condition
Done!

2022-12-01 09:42 UTC, znikola approved these changes

2022-12-01 09:59 UTC, merged