[CXEC-17347] addToCart should not overlap footer
SAP/spartacus pull request #16637
Opened 2022-12-13 08:12 UTC by AlexanderKuschner

2022-12-13 08:47 UTC, ChristophHi approved these changes

2022-12-13 08:48 UTC, ChristophHi requested changes

2022-12-13 08:48 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/add-to-cart-button/configurator-add-to-cart-button.component.ts
> +      rootMargin: '9999px 0px -100px 0px',
Could you document why we use 9999px?

2022-12-13 17:50 UTC, AlexanderKuschner commented on feature-libs/product-configurator/rulebased/components/add-to-cart-button/configurator-add-to-cart-button.component.ts
> +      rootMargin: '9999px 0px -100px 0px',
Done

2022-12-14 06:25 UTC, ChristophHi approved these changes

2022-12-14 06:26 UTC, merged