Fixing broken e2e's customer ticketing
SAP/spartacus pull request #16775
Opened 2023-01-15 20:57 UTC by sushant-stha

2023-01-16 13:47 UTC, adolfobee approved these changes

2023-01-16 15:01 UTC, khristian23 requested changes

2023-01-16 15:01 UTC, khristian23 commented on projects/storefrontapp-e2e-cypress/cypress/helpers/customer-ticketing/customer-ticketing-helpers/ticket-listing.ts
> +}
How about using:
helpers/customer-ticketing/customer-ticketing-helpers/ticket-listing.ts
clickTicketInRow(FIRST_ROW)

2023-01-17 16:09 UTC, merged

2023-01-17 16:26 UTC, khristian23 commented on projects/storefrontapp-e2e-cypress/cypress/integration/regression/customer-ticketing/view-ticket-details.e2e-spec.ts
> +        customerTicketing.visitTicketDetailsOfFirstTicketByItsId();
This was not update

2023-01-17 16:26 UTC, khristian23 commented on projects/storefrontapp-e2e-cypress/cypress/helpers/customer-ticketing/customer-ticketing-helpers/ticket-listing.ts
> +export function visitTicketDetailsOfFirstTicketByItsIdThroughURL(){
Could you please explain me the purpose of the function?