fix: show 2nd column of order summary
SAP/spartacus pull request #16799
Opened 2023-01-20 16:05 UTC by kimhw0630

Closes: https://jira.tools.sap/browse/CXSPA-2113

Remove *if structural directive  for checking PO number to hide 2nd column

2023-01-20 16:22 UTC, justinlee01 commented on feature-libs/organization/unit-order/components/unit-level-order-detail/unit-level-order-overview/unit-level-order-overview.component.html
> +    <div class="cx-summary-card">
This needs to be feature flagged, I believe? You need to keep the conditional but also check for the version.

2023-01-20 16:25 UTC, kimhw0630 commented on feature-libs/organization/unit-order/components/unit-level-order-detail/unit-level-order-overview/unit-level-order-overview.component.html
> +    <div class="cx-summary-card">
humm...

2023-01-20 17:12 UTC, justinlee01 approved these changes, later dismissed

2023-01-27 10:07 UTC, Zeyber requested changes

2023-01-27 10:07 UTC, Zeyber commented on feature-libs/organization/unit-order/components/unit-level-order-detail/unit-level-order-overview/unit-level-order-overview.component.html
> +    <!-- TODO:(CXSPA-1695) for next major release remove below structural directive -->
Can we mention the `ngIf` statement specifically here?

2023-01-27 13:22 UTC, Zeyber approved these changes

2023-01-27 18:57 UTC, merged