CXEC-23624: code review changes
SAP/spartacus pull request #16816
Opened 2023-01-26 15:53 UTC by Parthlakhani

2023-01-27 14:44 UTC, bgambocjaviniar requested changes

2023-01-27 14:44 UTC, bgambocjaviniar commented on feature-libs/customer-ticketing/components/details/customer-ticketing-reopen/customer-ticketing-reopen-dialog/customer-ticketing-reopen-dialog.component.ts
> +    this.close('Something went wrong while reopening ticket');
don't forget, it needs the `this.isDataLoading$.next(false);` too. If an error were to occur, they would forever be in a loading state, therefore it needs to be reset back.

2023-01-27 14:44 UTC, bgambocjaviniar commented on feature-libs/customer-ticketing/components/details/customer-ticketing-details/customer-ticketing-details.component.html
> +            prepareCardContent(ticket.id, 'customerTicketing.ticketId') | async
👍 , not related to this file, but there still exist `!` in the customer ticketing lib under `feature-libs/customer-ticketing/components/list/customer-ticketing-list/customer-ticketing-list.component.html`

2023-01-27 14:44 UTC, bgambocjaviniar commented on feature-libs/customer-ticketing/components/details/index.ts
> + * SPDX-FileCopyrightText: 2022 SAP Spartacus team <spartacus-team@sap.com>
don't forget to have these fix from the library to not have both, but just the 2023 one. Just copy paste an existing one from a ts file to have the same 'format'

2023-01-27 14:44 UTC, bgambocjaviniar commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +    containsAttachment?: boolean | false
this is a pretty weird typing. I'm assuming you want to have a default value set if no 2nd param is in right?

Then the following is how you should do it 
```suggestion
    containsAttachment?: boolean = false
```

2023-01-27 15:23 UTC, Parthlakhani commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +    containsAttachment?: boolean | false
It does not accept `=` as a intializer

2023-01-27 15:38 UTC, Parthlakhani commented on feature-libs/customer-ticketing/components/details/index.ts
> + * SPDX-FileCopyrightText: 2022 SAP Spartacus team <spartacus-team@sap.com>
Yup, will be doing it in the separate PR after this one is merged.

2023-01-27 21:02 UTC, ishrarhussain approved these changes
Looks fine to me.

2023-01-27 21:08 UTC, khristian23 requested changes

2023-01-27 21:08 UTC, khristian23 commented on feature-libs/customer-ticketing/components/details/customer-ticketing-messages/customer-ticketing-messages.component.spec.ts
> +      false
What does the second parameter mean?
for understanding purposes can a const be created:
const mustWaitForAttachment = false;  (it could also be includesAttachment)
```suggestion
      mustWaitForAttachment
```

2023-01-27 21:08 UTC, khristian23 commented on feature-libs/customer-ticketing/components/details/customer-ticketing-messages/customer-ticketing-messages.component.ts
> +    const attachmentFlag =
```suggestion
    const mustWaitForAttachment =
```

2023-01-27 21:08 UTC, khristian23 commented on feature-libs/customer-ticketing/components/details/customer-ticketing-reopen/customer-ticketing-reopen-dialog/customer-ticketing-reopen-dialog.component.spec.ts
> +        false
```suggestion
        mustWaitForAttachment
```

2023-01-27 21:08 UTC, khristian23 commented on feature-libs/customer-ticketing/components/details/customer-ticketing-reopen/customer-ticketing-reopen-dialog/customer-ticketing-reopen-dialog.component.ts
> +      const attachmentFlag = this.form.get('file')?.value?.length > 0 ?? false;
```suggestion
      const mustWaitForAttachment = this.form.get('file')?.value?.length > 0 ?? false;
```

2023-01-27 21:08 UTC, khristian23 commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +  protected createTicketEventCommand: Command<
Using flag parameters goes against clean code:
https://github.com/ryanmcdermott/clean-code-javascript#dont-use-flags-as-function-parameters

The best case would be to pass the attachments and let createTicketEvent decide what to do.
Like this you don't need to repeat the line of code that calculates the 'attachmentFlag' to true to false

Another option would be to have two functions:
createTicketEvent and createTicketEventWithAttachments

2023-01-27 21:08 UTC, khristian23 commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +                }
Although we should avoid negative conditions, this reads better:

```suggestion
                } else if (!payload.containsAttachment){
                   if (payload.ticketEvent.toStatus?.id === STATUS.OPEN ||
                    payload.ticketEvent.toStatus?.id === STATUS.INPROCESS) {
                        this.eventService.dispatch({}, TicketReopenedEvent);
                    } else {
                        this.eventService.dispatch({}, NewMessageEvent);
                    }
                }
```

2023-01-27 21:08 UTC, khristian23 commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +    containsAttachment?: boolean | false
```suggestion
    containsAttachment = false
```

2023-01-27 21:11 UTC, khristian23 commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +  protected createTicketEventCommand: Command<
In any case, I am OK with leaving the parameter flag, but tests calling the createTicketEvent function must have proper naming.

2023-01-27 21:59 UTC, Parthlakhani commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +  protected createTicketEventCommand: Command<
yes, we changed the name and keeping the flag as it would be a big refactor.

2023-01-30 20:07 UTC, bgambocjaviniar commented on feature-libs/customer-ticketing/core/facade/customer-ticketing.service.ts
> +    containsAttachment?: boolean | false
only reason why it didn't work is because the `?` optional was there. Only needed to remove `?` and should work. Can't have both a default value and it being optional because it's indirectly optional with the default value

2023-01-30 20:55 UTC, bgambocjaviniar approved these changes
awesome :) 

Thanks Parth. Don't forget to update the license headers

2023-01-30 21:06 UTC, merged