fix: integration-libs/epd-visualization e2e test fixes for 5.2.x
SAP/spartacus pull request #16866
Opened 2023-02-07 10:11 UTC by sam-garland

2023-02-08 12:18 UTC, Matejk00 requested changes

2023-02-08 12:18 UTC, Matejk00 commented on projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/epd-visualization/visual-picking-tab.ts
> +      timeout: 10_000
@sam-garland just wondering if it's necessary to set up a timeout for each button click? If so, maybe we can assign a timeout value to some `const` and re-use that variable in all needed cases.

2023-02-08 18:44 UTC, sam-garland commented on projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/epd-visualization/visual-picking-tab.ts
> +      timeout: 10_000
The timeout is needed on at least some of the button clicks in order to get the tests to work.
I can reduce some of the redundancy in this code.

2023-02-08 20:39 UTC, sam-garland commented on projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/epd-visualization/visual-picking-tab.ts
> +      timeout: 10_000
Actually I found that a fix for https://jira.tools.sap/browse/CXSPA-2384 resolves the underlying problem that the click timeouts were working around.

I have included a fix for https://jira.tools.sap/browse/CXSPA-2384 which eliminates some flakiness affecting one of the integration tests.

As a result of this change I have been able to remove the non-default click timeouts.

2023-02-09 07:26 UTC, Matejk00 submitted a review, later dismissed

2023-02-09 07:27 UTC, Matejk00 commented on projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/epd-visualization/visual-picking-tab.ts
> +      timeout: 10_000
Thank you @sam-garland, now looks good to me. I approved both PR's.

2023-02-09 12:00 UTC, Matejk00 approved these changes

2023-02-09 14:27 UTC, merged