feat: billing address form component
SAP/spartacus pull request #16890
Opened 2023-02-09 11:12 UTC by psmul

2023-02-22 09:00 UTC, Zeyber requested changes

2023-02-22 09:00 UTC, Zeyber commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.html
> +<div>
Does this `div` have any function?

2023-02-22 09:00 UTC, Zeyber commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.ts
> +  editBillingAddress = false;
`sameAsDeliveryAddress `, `userCustomBillingAddress ` and `editBillingAddress` are dynamically changing values while being referenced in the template with `*ngIf` directives. It would be safer to convert these into observables so that we are always detecting these changes as they happen.

2023-02-22 11:50 UTC, psmul commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.html
> +<div>
Nice catch, thanks! Removing it

2023-02-22 12:28 UTC, psmul commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.ts
> +  editBillingAddress = false;
Actually, really good idea, thanks!

2023-02-22 13:07 UTC, Zeyber requested changes

2023-02-22 13:07 UTC, Zeyber commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.ts
> +  get sameAsDeliveryAddress(): boolean {
`getValue()` does not subscribe to value changes of the observable which leaves us with a similar issue in detecting changes in the template. We should be using the async pipe with the observables in the template.

2023-02-22 14:37 UTC, Zeyber requested changes

2023-02-22 14:37 UTC, Zeyber commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.ts
> +        tap((isEditBillingAddress) => {
This can be in the `subscribe()` section instead.

2023-02-22 14:37 UTC, Zeyber commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.ts
> +        tap((isSameAsDeliveryAddress) => {
This can be in the subscribe() section instead.

2023-02-22 14:41 UTC, Zeyber commented on integration-libs/opf/components/opf-checkout-billing-address-form/opf-checkout-billing-address-form.component.ts
> +        tap((isSameAsDeliveryAddress) => {
This can be in the subscribe() section instead.

2023-02-23 07:14 UTC, Zeyber approved these changes

2023-02-23 08:30 UTC, merged