CXCDS-7119: Retrieve CR from local-storage on page refresh to avoid blank CR headers
SAP/spartacus pull request #16892
Opened 2023-02-10 08:19 UTC by ShankariGiri-I

2023-02-24 08:38 UTC, robertstrache submitted a review, later dismissed

2023-02-27 19:18 UTC, plabadie commented on integration-libs/cds/src/profiletag/services/profiletag-event.service.ts
> +      .subscribe((baseSite) => {
It's best practice to unsubscribe any subscription in the onDestroy method.
There are many examples in the code base.  The subscription management is done with a Subscription object.  Something like:

```
      this.subscription.add(
        example.subscribe()
        );
```

```
  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
```

2023-02-27 19:27 UTC, plabadie requested changes
See small comment on the PR

2023-02-28 08:13 UTC, ShankariGiri-I commented on integration-libs/cds/src/profiletag/services/profiletag-event.service.ts
> +      .subscribe((baseSite) => {
Fixed it. Could you have another look? Thanks! :)

2023-02-28 14:14 UTC, plabadie approved these changes

2023-02-28 14:42 UTC, merged