feat: create resume-config-dialog
SAP/spartacus pull request #16943
Opened 2023-02-27 12:42 UTC by Uli-Tiger

* create component
* register modal
* create router data flag displayResumeConfigDialog
* create model attribute isNewConfiguration und set it to true during createConfiguration

2023-03-06 09:46 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/common/assets/translations/en/configurator-common.ts
> +        'Close the resume config dialog an navigate back to the product details page',
I think you mean `and navigate`?

2023-03-07 10:08 UTC, ChristophHi requested changes

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/conflict-solver-dialog/configurator-conflict-solver-dialog-launcher.service.ts
> +          this.subscribeToCloseDialog();
This is reached 2 times when dialog is displayed at first. Later it is called 4 times

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/common/components/configure-product/configure-product.component.html
> +      [queryParams]="{ displayResumeConfigDialog: 'true' }"
Naming (see our slack conversation https://sap-cx.slack.com/archives/C04SPHSG610/p1678172385922529)

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/common/components/service/configurator-router-data.ts
> +    displayResumeConfigDialog?: boolean;
Naming (see our slack conversation https://sap-cx.slack.com/archives/C04SPHSG610/p1678172385922529)

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.ts
> +      newConfiguration: source.newConfiguration ?? false,
That should default to 'true', right? Because we must not show this dialog in case the backend (e.g. 22.05) is not prepared for it, this would quite annoying as the dialog would always come, and breaking

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.spec.ts
> +    xit('should ensure visibility of the element when element.offsetTop is less than container.scrollTop', () => {
Please re-activate, also the subsequent ones

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +  data$: Observable<{ previousOwner: CommonConfigurator.Owner }> =
Please rename (data$ is quite generic)

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/form/configurator-form.component.ts
> +          { previousOwner: configuration.owner }
Why is that 'previousOwner' (the owner stays the same). Why not just 'owner'?

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * closes the  modal
```suggestion
   * Closes the  modal
```

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * resume with current config
```suggestion
   * Resume with current configuration
```

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * discards current configuration and requests a new default configuration
```suggestion
   * Discards current configuration and requests a new default configuration
```

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * navigates back product detail page without making a decision
```suggestion
   * Navigates back to product detail page without making a decision
```

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +export class ConfiguratorResumeConfigDialogComponent {
The component must be exported to our public API via am index.ts

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.module.ts
> +export class ConfiguratorResumeConfigDialogModule {}
The module must be exported to our public API via am index.ts

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/core/facade/configurator-commons.service.ts
> +   * @param forceReset optional - if true, wil force creation of a new default configuration, instead of returning a product bound configuration
Remove this line

2023-03-07 10:08 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/core/facade/configurator-commons.service.ts
> +   * forces the creation of a new default configuration for the given owner
```suggestion
   * Forces the creation of a new default configuration for the given owner
```

2023-03-07 10:18 UTC, Larisa-Staroverova requested changes

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/_index.scss
> +  cx-configurator-conflict-solver-dialog, cx-configurator-resume-config-dialog !default;
I would suggest `cx-configurator-resume-dialog`
Otherwise the word configurator / configuration comes twice.

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/config/augmented-config.model.ts
> +    CONFIGURATOR_RESUME_CONFIG = 'CONFIGURATOR_RESUME_CONFIG',
I would suggest `CONFIGURATOR_RESUME`
Otherwise the word configurator / configuration comes twice.

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.html
> +<div class="cx-configurator-resume-config-dialog cx-modal-container">
Do we need to use `cx-configurator-resume-config-dialog` class?
Our both dialogs could not coexist?
We should to hold our HTML tree as simple as possible.

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/common/assets/translations/en/configurator-common.ts
> +    resumeConfigDialog: {
I would suggest `resumeDialog`

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/common/assets/translations/en/configurator-common.ts
> +      closeResumeConfigDialog:
I would suggest `closeResumeDialog`

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.html
> +          <div class="cx-configurator-dialog-description">
Is it necessary to add a class here?

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.html
> +            (click)="resumeConfig(product)"
Why not simple call the method `resume`?

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.html
> +            class="btn btn-secondary btn-block cx-configurator-dialog-discard"
Is it necessary to add `cx-configurator-dialog-discard` class here?

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +export class ConfiguratorResumeConfigDialogComponent {
I would suggest to rename this component to `ConfiguratorResumeDialogComponent`

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * closes the  modal
Could you start the comment with an upper letter?

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * resume with current config
Could you start the comment with an upper letter?

> Resume with a current configuration

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * @parameter product owning this configuration
Please, change to `@param`

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +    // in case conflict solver was open as well, it was closed by the call above.
Please, start a  comment with an upper letter

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * @parameter previousOwner owner of the current configuration thats will be reused for next configuration
Please, change to `@param`

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * discards current configuration and requests a new default configuration
Please, start a comment with an upper letter

> Discards a current configuration

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * @parameter previousOwner owner of the current configuration thats will be reused for next configuration
You mean:

> that will be reused...

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * @parameter product owning this configuration
Please, change to `@param`

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.ts
> +   * navigates back product detail page without making a decision
Please, start a comment with an upper letter and use a definite article:

> Navigates back to the product detail page without making a decision

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/core/connectors/rulebased-configurator.adapter.ts
> +   * @param forceReset optional - if true, wil force creation of a new default configuration, instead of returning a product bound configuration
You mean:

> if true, it will force a creation of a new default configuration, instead of returning a product bound configuration

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/core/facade/configurator-commons.service.ts
> +   * @param forceReset optional - if true, wil force creation of a new default configuration, instead of returning a product bound configuration
You mean:

> if true, it will force a creation of a new default configuration, instead of returning a product bound configuration

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/core/facade/configurator-commons.service.ts
> +   * forces the creation of a new default configuration for the given owner
Please, start a comment with an upper letter

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/core/state/actions/configurator.action.spec.ts
> +  it('should provide create action that carries the forceReset flag as a payload', () => {
Please, rephrase a test name

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-overview-filter-dialog.scss
> +    z-index: 1000;
I think it should be documented and explained why it was added.

2023-03-07 10:18 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-conflict-solver-dialog.scss
> +    z-index: 2000;
I think it should be documented and explained why it was added.

2023-03-08 19:07 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.spec.ts
> +    xit('should ensure visibility of the element when element.offsetTop is less than container.scrollTop', () => {
@Larisa-Staroverova: Can you please provide a fix for this fragile test as we discussed last week?

2023-03-09 11:32 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/conflict-solver-dialog/configurator-conflict-solver-dialog-launcher.service.ts
> +          this.subscribeToCloseDialog();
should be fixed now - was a bit tricky

2023-03-09 16:24 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.html
> +          <div class="cx-configurator-dialog-description">
it's used by the test to identify the button and could be used to style this by the customer

2023-03-09 16:24 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.html
> +            class="btn btn-secondary btn-block cx-configurator-dialog-discard"
it's used by the test to identify the button and could be used to style this by the customer

2023-03-09 16:40 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/styles/_configurator-overview-filter-dialog.scss
> +    z-index: 1000;
where should we document this? - via the z-index we can control which dialog will be visible on top when multiple dialogs are rendered. For example, when entering a configuration, resume-config as well as conflict solver can be triggered.

2023-03-09 16:40 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/styles/_configurator-conflict-solver-dialog.scss
> +    z-index: 2000;
where should we document this? - via the z-index we can control which dialog will be visible on top when multiple dialogs are rendered. For example, when entering a configuration, resume-config as well as conflict solver can be triggered.

2023-03-09 17:30 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/resume-config-dialog/configurator-resume-config-dialog.component.html
> +            class="btn btn-secondary btn-block cx-configurator-dialog-discard"
additionally now used for a11y

2023-03-10 09:24 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/styles/_configurator-conflict-solver-dialog.scss
> +    z-index: 2000;
done

2023-03-10 10:55 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/core/connectors/rulebased-configurator.adapter.ts
> +    forceReset?: boolean
@Uli-Tiger just FYI: It seems the BC tool is smart enough to know that this is not breaking. Was not sure about that, but I didn't get a warning also for the previous change (adding configIdTemplate)

2023-03-10 10:59 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/core/state/actions/configurator.action.ts
> +      forceReset?: boolean;
That we should mention in the BC doc, will do it

2023-03-10 11:01 UTC, ChristophHi submitted a review, later dismissed

2023-03-10 12:28 UTC, Larisa-Staroverova requested changes

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/restart-dialog/configurator-restart-dialog.component.html
> +        <div class="cx-dialog-header modal-header">
Please, remove `cx-dialog-header` class. `modal-header` class is enough to style this dialog accordingly.
The goal is to hold HTML tree as simple as possible.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/restart-dialog/configurator-restart-dialog.component.html
> +          <div class="cx-dialog-title modal-title">
Please, remove `cx-dialog-title` class. `modal-title` class is enough to style this dialog accordingly.
The goal is to hold HTML tree as simple as possible.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/restart-dialog/configurator-restart-dialog.component.html
> +            class="btn btn-primary btn-block cx-configurator-dialog-resume"
Please, remove `cx-configurator-dialog-resume` class. `btn-primary` class is enough to style this button accordingly.
The goal is to hold HTML tree as simple as possible.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/restart-dialog/configurator-restart-dialog.component.html
> +            class="btn btn-secondary btn-block cx-configurator-dialog-restart"
Please, remove `cx-configurator-dialog-restart` class. `btn-secondary` class is enough to style this button accordingly.
The goal is to hold HTML tree as simple as possible.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-restart-dialog.scss
> +    .cx-dialog-header {
Please, use `modal-header` class instead.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-restart-dialog.scss
> +      .cx-dialog-title {
Please, use `modal-title` class instead.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/restart-dialog/configurator-restart-dialog.component.html
> +        <div class="cx-dialog-body modal-body">
Please, remove `cx-dialog-body` class. `modal-body` class is enough to style accordingly.
The goal is to hold HTML tree as simple as possible.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-restart-dialog.scss
> +    .cx-dialog-body {
Please, use `modal-body` class instead.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/restart-dialog/configurator-restart-dialog.component.html
> +            class="cx-configurator-dialog-description"
Please, shorten the class name to `modal-description`.

2023-03-10 12:28 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/_configurator-restart-dialog.scss
> +    .cx-configurator-dialog-discard {
Please, use `btn-primary`  and `btn-secondary`  classes instead.

2023-03-10 12:37 UTC, Larisa-Staroverova approved these changes, later dismissed

2023-03-10 13:15 UTC, Larisa-Staroverova approved these changes

2023-03-10 13:24 UTC, merged