chore: Remove deprecated code and feature flags before 6.0
SAP/spartacus pull request #16978
Opened 2023-03-03 13:35 UTC by psmul

Closes: [CXSPA-2458](https://jira.tools.sap/browse/CXSPA-2458)

2023-03-09 19:00 UTC, plabadie commented on docs/migration/6_0/typescript-manual-doc.md
> +- Added `GlobalMessageService` to constructor.
No need to document these changes.  Regular typescript changes should be picked up by the BC detection script.

2023-03-09 19:01 UTC, plabadie commented on docs/migration/6_0/typescript-manual-doc.md
> +- Added `TranslationService` to constructor.
No need to document such typescript changes. Regular typescript changes should be picked up by the BC detection script.

2023-03-09 19:02 UTC, plabadie commented on feature-libs/asm/components/asm-main-ui/asm-main-ui.component.html
> +    </div>
Dom breaking changes should be documented.

2023-03-09 20:05 UTC, plabadie commented on feature-libs/asm/components/customer-emulation/customer-emulation.component.html
> +  <cx-asm-bind-cart></cx-asm-bind-cart>
Needs migration docs

2023-03-09 20:07 UTC, plabadie commented on feature-libs/cart/base/components/cart-coupon/applied-coupons/applied-coupons.component.html
> +    <ng-container>
Comment valid for all the html files in the PR: all DOM changes require a corresponding migration doc.

2023-03-09 20:09 UTC, plabadie commented on projects/storefrontstyles/scss/components/product/list/_active-facets.scss
> -  }
CSS changes require corresponding migration doc.

2023-03-09 20:12 UTC, plabadie commented on projects/storefrontlib/cms-components/myaccount/my-interests/my-interests.component.spec.ts
> +    // productService.get.withArgs('553637', 'details').and.returnValue(p553637$);
Remove the line if dead code.
Add it back otherwise.

2023-03-09 20:12 UTC, plabadie commented on projects/storefrontlib/cms-components/myaccount/my-interests/my-interests.component.spec.ts
> +    console.log(tableHeaders);
Remove the console.log as I guess it was not left here on purpose.

2023-03-09 20:18 UTC, plabadie commented on projects/storefrontlib/cms-components/content/paragraph/paragraph.component.ts
>        }
If this is a change in behaviour that could have side effects outside of the component, it should be manually documented.

2023-03-09 20:22 UTC, plabadie commented on feature-libs/smartedit/core/services/smart-edit.service.ts
> -
There should be a migration comment for this removal in `docs/migration/6_0/migration-comments-members.json`

2023-03-09 20:24 UTC, plabadie commented on feature-libs/product-configurator/common/components/configurator-cart-entry-bundle-info/configurator-cart-entry-bundle-info.component.ts
> -
There should be a migration comment for this removal in docs/migration/6_0/migration-comments-members.json

2023-03-09 20:30 UTC, plabadie commented on feature-libs/cart/base/components/cart-shared/cart-item/cart-item.component.spec.ts
> -
It doesn't look like this test case should be removed.
It does need some changes to remove the feature flag.

2023-03-09 21:52 UTC, plabadie requested changes
See comments on the files.

2023-03-13 11:34 UTC, psmul commented on projects/storefrontlib/cms-components/content/paragraph/paragraph.component.ts
>        }
Already documented here:
https://github.com/SAP/spartacus/blob/epic/deprecation-removal-6.0/docs/migration/6_0/typescript-manual-doc.md#:~:text=The%20handleClick()%20method%20now%20uses%20the%20condition%20documentHost%20%3D%3D%3D%20element.host%20to%20recognise%20external%20links.

2023-03-13 12:04 UTC, psmul commented on feature-libs/cart/base/components/cart-shared/cart-item/cart-item.component.spec.ts
> -
Yes, definitely over-refactored here. Reverting.

2023-03-15 19:00 UTC, plabadie submitted a review, later dismissed

2023-03-16 13:23 UTC, Zeyber approved these changes

2023-03-16 13:24 UTC, merged