remove deprecated AsmConfig and use new config
SAP/spartacus pull request #17008
Opened 2023-03-08 08:49 UTC by niehuayang

JIRA: https://jira.tools.sap/browse/CXSPA-1449

2023-03-09 13:54 UTC, justinlee01 submitted a review, later dismissed

2023-03-09 21:33 UTC, ercultimate requested changes
Code is all good.  We just need to document the API changes in the migration documents.

2023-03-13 07:03 UTC, niehuayang commented
> Code is all good. We just need to document the API changes in the migration documents.

The API changes have been added in the migration documents, could you please help me review it?

2023-03-13 22:05 UTC, ercultimate commented on docs/migration/6_0/migration-comments-api-elements.json
> +    "migrationComment": "Use class @spartacus/asm/root/AsmConfig instead."
```suggestion
    "migrationComment": "Use class 'AsmConfig' from '@spartacus/asm/root' instead."
```

2023-03-13 22:08 UTC, ercultimate requested changes
I suggested a clearer migration comment for the documentation.  With that, I think this should be ready for merge.

2023-03-14 04:20 UTC, niehuayang commented on docs/migration/6_0/migration-comments-api-elements.json
> +    "migrationComment": "Use class @spartacus/asm/root/AsmConfig instead."
Yea, have changed

2023-03-14 19:37 UTC, ercultimate approved these changes

2023-03-15 05:16 UTC, merged