Replace GoogleFont by npm library Fontsource
SAP/spartacus pull request #17013
Opened 2023-03-09 01:30 UTC by FollowTheFlo

This change is needed for compliance reason, to avoid loading Fonts form third-party server (Google in our case).
Now the fonts are self-hosted, installed with npm https://www.npmjs.com/package/@fontsource/open-sans (MIT license + licence for Open-Sans -> SIL Open Font License)
data added:
- the css font-face objects, pointing to woff2 file url, added in style.css 
- 4 woff2 files (lazy loaded, most of the time, only 3 needed)
See testing done on https://jira.tools.sap/browse/CXSPA-525
Bundle is slightly larger than before
Google Font: 39kb
FontSource: 4x16=64k
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/30024415/224808883-1d8c58ed-bce6-408d-a8f3-ddb7868264ee.png">

2023-03-13 19:05 UTC, FollowTheFlo commented on projects/storefrontstyles/scss/theme/sparta/_fonts.scss
> +@import '@fontsource/open-sans/300.css';
added 4 files of family 'open-sans' in weight: 300,400,600,700 to mirror the font that were previously downloaded on Google Fonts: https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700

2023-03-13 21:34 UTC, plabadie requested changes
PR looks good, but the CI fails on unit tests.  It is likely that some unit test snapshots have to be updated because some of them contain the list of dependencies (which just got updated with a new lib)

2023-03-14 17:26 UTC, FollowTheFlo commented on projects/schematics/src/ng-add/__snapshots__/index_spec.ts.snap
> +    "@fontsource/open-sans": "^4.5.14",
generated with command:
npm --prefix projects/schematics run test --runInBand -- --u

2023-03-14 19:20 UTC, plabadie approved these changes

2023-03-14 19:48 UTC, merged