Styling issues to be fixed in configurator lib
SAP/spartacus pull request #17103
Opened 2023-03-22 13:39 UTC by Larisa-Staroverova

- [ ] 1. Exit Configuration / Cancel Configuration button should be a tertiary button 
- [ ] 2. Add a shadow at the top border of the product title 
- [ ] 3. Resolve Conflicts / Resolve Issues links on OV should be blue 
- [ ] 4. Resolve Issues link in the cart should be the same size as another text  Check whether Resolve Issues link should be semi-bold
- [ ] 5. Filter button on the overview page is hardly to see on mobile widgets. It should be aa secondary button in blue 
- [ ] 6. Should all clickable elements (links / buttons ant etc.) be in primary color?

2023-03-22 13:56 UTC, Uli-Tiger submitted a review, later dismissed

2023-03-23 05:59 UTC, ChristophHi requested changes

2023-03-23 05:59 UTC, ChristophHi commented on docs/migration/6_0/styling.md
> +- Styling file is obsolet and will be removed because `link cx-action-link` classes are in used
```suggestion
- Styling file was obsolete and has been removed because `link cx-action-link` classes are used
```

2023-03-23 05:59 UTC, ChristophHi commented on docs/migration/6_0/styling.md
> +- Styling file is obsolet and will be removed
```suggestion
- Styling file was obsolete and has been removed 
```

2023-03-23 06:03 UTC, Larisa-Staroverova commented on docs/migration/6_0/styling.md
> +- Styling file is obsolet and will be removed because `link cx-action-link` classes are in used
Done!

2023-03-23 06:03 UTC, Larisa-Staroverova commented on docs/migration/6_0/styling.md
> +- Styling file is obsolet and will be removed
Done!

2023-03-23 06:08 UTC, ChristophHi approved these changes, later dismissed

2023-03-23 06:10 UTC, ChristophHi approved these changes, later dismissed

2023-03-23 13:56 UTC, morganm58 submitted a review, later dismissed

2023-03-24 08:48 UTC, ChristophHi approved these changes

2023-03-24 08:51 UTC, merged