styling: update theme buttons and update styling of the exit button styling
SAP/spartacus pull request #17118
Opened 2023-03-23 16:28 UTC by morganm58

fixes CXSPA-2853
https://jira.tools.sap/browse/CXSPA-2853

2023-03-24 06:08 UTC, Larisa-Staroverova requested changes
Please, documentae styling changes in docs/migration/6_0/styling.md

2023-03-24 06:08 UTC, Larisa-Staroverova commented on projects/storefrontstyles/scss/cxbase/blocks/buttons.scss
> +      background-color: var(--cx-color-border-focus);
I think thess styling changes should be documented because of the major release.

2023-03-27 05:35 UTC, Larisa-Staroverova approved these changes

2023-03-27 05:35 UTC, Larisa-Staroverova commented on docs/migration/6_0/styling.md
> +- Chnaged line 69 `border-color: var(--cx-color-primary);` to `{border-color: var(--cx-color-border-focus);}`
Typo: I have adjusted it accordingly

2023-03-27 10:55 UTC, Larisa-Staroverova approved these changes

2023-03-27 13:18 UTC, RadhepS approved these changes

2023-03-27 13:25 UTC, merged