fix bug - Lazy load BOPIS outlet components
SAP/spartacus pull request #17143
Opened 2023-03-28 10:15 UTC by surya-prakash-singh1

fix bug - Lazy load BOPIS outlet components

2023-03-28 13:02 UTC, WeizhengSap commented
Is `StoreFinderModule` required in `PdpPickupOptionsContainerModule`?

2023-03-28 13:04 UTC, WeizhengSap requested changes
Is `StoreFinderModule` required in `PdpPickupOptionsContainerModule`?
e2e tests failed

2023-04-03 12:56 UTC, WeizhengSap commented on feature-libs/storefinder/root/facade/store-finder.facade.ts
> +        'getStoreLongitude',
missing `getFindStoreEntityById`

2023-04-03 12:57 UTC, WeizhengSap commented on feature-libs/storefinder/root/model/store-finder.model.ts
> +  pointOfServices?: Array<PointOfService>;
`StoreEntities` in `storefinder/core` should be removed.

2023-04-05 10:18 UTC, surya-prakash-singh1 commented on feature-libs/storefinder/root/model/store-finder.model.ts
> +  pointOfServices?: Array<PointOfService>;
Done

2023-04-05 17:38 UTC, WeizhengSap approved these changes

2023-04-06 11:29 UTC, merged