chore : update overview sections to use real data(CXSPA-3136)
SAP/spartacus pull request #17343
Opened 2023-04-26 13:57 UTC by kimhw0630

Closes: https://jira.tools.sap/browse/CXSPA-3136

- Overview header section 
- Active cart section
- Saved cart section
- Interests section
- common components clean up

2023-05-02 09:52 UTC, rmch91 requested changes

2023-05-02 09:52 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/customer-360.component.html
> +                [container]="getAvatarImage(customerOverview)"
Usage of methods inside of template is not good from performance point of view. Method will execute all the time when, change detection will run. Better to use pure pipe, which will be triggered only when the source will be changed. Maybe you can create pipe just for this component (if this functionality is used only here) and move logic from method to the pipe?

2023-05-02 09:52 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/customer-360.component.html
> +              {{ getAvatarText() }}
same as above

2023-05-02 09:52 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/customer-360.component.html
> +                  | cxTranslate: { name: customerOverview.name }
maybe customerOverview?.name ?

2023-05-02 09:52 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/customer-360.component.html
> +              {{ customerOverview.email }}
customerOverview?.email

2023-05-02 09:52 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/customer-360.component.html
> +            *ngIf="customerOverview.cartCode"
customerOverview?.cartCode

2023-05-02 09:52 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/customer-360.component.html
> +                | cxTranslate: { cartSize: customerOverview.cartSize }
There are places where you are using `customerOverview?.something` and somewhere you are not using question mark. So if we not sure that `customerOverview` always will exist, maybe we should add the question mark everywhere

2023-05-02 09:52 UTC, rmch91 commented on feature-libs/asm/customer-360/root/model/customer-360.model.ts
> +  address: Address;
should it be optional also?

2023-05-02 21:15 UTC, kimhw0630 commented on feature-libs/asm/customer-360/components/customer-360/customer-360.component.html
> +                [container]="getAvatarImage(customerOverview)"
thanks created a pipe.

2023-05-04 10:10 UTC, rmch91 approved these changes

2023-05-04 10:10 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/avatar-image.pipe.ts
> +@Pipe({ name: 'avatarImage' })
Nitpick, but almost all of pipes names in the storefront starts from "cx".  Maybe for consistency we should add "cx" prefix also.

2023-05-04 10:10 UTC, rmch91 commented on feature-libs/asm/customer-360/components/customer-360/avatar-label.pipe.ts
> +@Pipe({ name: 'avatarLabel' })
Nitpick, but almost all of pipes names in the storefront starts from "cx".  Maybe for consistency we should add "cx" prefix also.

2023-05-04 12:46 UTC, merged