Feature/cxspa 3400 template strict
SAP/spartacus pull request #17417
Opened 2023-05-16 06:26 UTC by ChristophHi

2023-05-23 13:30 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/group-menu/configurator-group-menu.component.ts
> +  isConflictGroupTypeWUndefined(
Why is this method called isConflictGroupType**W**Undefined and not isConflictGroupTypeUndefined?

2023-05-23 15:50 UTC, steinsebastian requested changes
See comment

2023-05-24 05:50 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/group-menu/configurator-group-menu.component.ts
> +  isConflictGroupTypeWUndefined(
The method should check if a group is a conflict group, allowing undefined input.
What about isConflictGroupTypeAllowingUndefined?

2023-05-24 07:11 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/group-menu/configurator-group-menu.component.ts
> +  isConflictGroupTypeWUndefined(
Sounds good.

2023-05-24 07:38 UTC, steinsebastian approved these changes

2023-05-24 09:02 UTC, merged