Feature/cxspa 3979 e2e test
SAP/spartacus pull request #17625
Opened 2023-07-11 14:32 UTC by ChristophHi

2023-07-12 10:40 UTC, Larisa-Staroverova requested changes

2023-07-12 10:40 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/quote/quote.e2e-flaky.cy.ts
> +      cy.get('cx-page-layout[section="header"]').within(() => {
Could you move this part to quote.ts helper class in case somebody wants to access the quote list this way?

2023-07-12 10:40 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/quote/quote.e2e-flaky.cy.ts
> +      cy.get('cx-quote-action-links').within(() => {
Could you move this part to quote.ts helper class in case somebody wants to access the quote list this way?

2023-07-12 10:40 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/cypress/helpers/quote.ts
> +export function clickOnAddToCartBtnOnPD(): void {
There is the same method in projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator.ts

2023-07-12 10:40 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/cypress/helpers/quote.ts
> +export function clickOnAddToCartBtnOnPD(): void {
Why can't you reuse it?

2023-07-12 10:40 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/cypress/helpers/quote.ts
> +export function clickOnViewCartBtnOnPD(): void {
There is the same method in projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator.ts
Why can't you reuse it?

2023-07-12 10:40 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/cypress/helpers/quote.ts
> +export function goToPDPage(shopName: string, productId: string): void {
There is the same method in projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator-vc.ts
Why can't you reuse it?

2023-07-12 10:40 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/cypress/helpers/quote.ts
> +export function checkLoadingMsgNotDisplayed(): void {
There is the same method in projects/storefrontapp-e2e-cypress/cypress/helpers/product-configurator-vc.ts
Why can't you reuse it?

2023-07-12 12:00 UTC, ChristophHi commented on projects/storefrontapp-e2e-cypress/cypress/helpers/quote.ts
> +export function clickOnAddToCartBtnOnPD(): void {
@Larisa-Staroverova I didn't want to refer to configurators here. But you are right, I should find a way to do some kind of re-use (maybe put those tools into a new, common helper file)

2023-07-13 04:33 UTC, Larisa-Staroverova approved these changes

2023-07-13 04:58 UTC, merged