run product-configurator e2e tests on Wonderful Testing Framework
SAP/spartacus pull request #17913
Opened 2023-10-05 11:26 UTC by alepil

with one script in the root folder the product configurator e2e tests can be called from the Wonderful Testing Framework with the command: ./run-spartacus-product-configurator-e2es.sh cpq
./run-spartacus-product-configurator-e2es.sh b2c
./run-spartacus-product-configurator-e2es.sh b2c_flaky or the tests can be run locally with the second option "local" against specific ccv2 server. I.e.: ./run-spartacus-product-configurator-e2es.sh b2c_flaky local

2023-10-09 07:03 UTC, Larisa-Staroverova requested changes
@alepil, let us check whether the script could be simple renamed in **package.json**

2023-10-09 07:03 UTC, Larisa-Staroverova commented on package.json
> +    "e2e:run:ci:ccv2-product-configurator": "npm --prefix ./projects/storefrontapp-e2e-cypress run cy:run:ci:ccv2-product-configurator",
I am not sure the script could be simple renamed.

2023-10-09 07:03 UTC, Larisa-Staroverova commented on projects/storefrontapp-e2e-cypress/package.json
> +    "cy:run:ci:ccv2-product-configurator": "cypress run --config-file cypress.config.ci.ts --config baseUrl=$ENDPOINT_URL_PUBLIC_SPARTACUS --reporter junit --reporter-options mochaFile=results/sparta
The same here

2023-10-09 14:17 UTC, Larisa-Staroverova approved these changes

2023-10-11 10:26 UTC, Zeyber approved these changes

2023-10-12 09:00 UTC, merged