Feature/cxspa 4968 display from quote cart
SAP/spartacus pull request #18002
Opened 2023-10-23 13:18 UTC by ChristophHi

2023-10-26 15:18 UTC, Uli-Tiger requested changes
see my comments

2023-10-26 15:18 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
> +
```suggestion
```
just remove empty line between comment and code

2023-10-26 15:18 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
> +  /**
```suggestion
 
   /**
```
empty line mising

2023-10-26 15:18 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
>      }
it seems like that this method is not used anymore -  do we keep it just for backward compatibility?

2023-10-26 15:18 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
> +  protected isActiveCart(cartCode: string): boolean {
i find this method name confusing, aren't we checking whether we are in the context of **saved cart**, so maybe isSavedCartActive()?

2023-10-26 15:18 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
> +    readOnlyCartIsActive: boolean
so whats a readOnlyCart in this context?
i see its filled with result isActiveCart()

2023-10-26 15:18 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/occ/variant/variant-configurator-occ.adapter.ts
> +    }
all calls to buildUrl are quite similar. They only differ in the enpoint. So i suggest to only determine the enpoint within the if-else statement and then call  buildUrl afterwards.

2023-10-26 15:18 UTC, Uli-Tiger commented on feature-libs/quote/components/items/quote-items.component.html
> +      </ng-template>
i would move this just before the previous template, as it relates more to first case, then the second case
so we have

1. quote case
2. saved cart case (new)
3. active cart case

2023-10-26 15:22 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
> +    readOnlyCartIsActive: boolean
I mean from the quote perspective it ts the readOnlyQuoteCart case - but from a config perspective we are in the savedCart scenario, which will also solve our 'readOnlyQuoteCart ' case. Still i would name this more with saved cart in mind-

2023-10-26 15:23 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/occ/variant/variant-configurator-occ.adapter.ts
> +    }
```suggestion
    let endpoint;
    if (ownerType === CommonConfigurator.OwnerType.QUOTE_ENTRY) {
      endpoint = 'readVariantConfigurationOverviewForQuoteEntry';
    } else if (ownerType === CommonConfigurator.OwnerType.SAVED_CART_ENTRY) {
      endpoint = 'readVariantConfigurationOverviewForSavedCartEntry';
    } else {
      endpoint = 'readVariantConfigurationOverviewForOrderEntry';
    }
    let url = this.occEndpointsService.buildUrl(endpoint, {
      urlParams: {
        userId: parameters.userId,
        orderId: parameters.orderId,
        orderEntryNumber: parameters.orderEntryNumber,
      },
    });
```

2023-10-26 15:37 UTC, Uli-Tiger commented
when i follow the steps from the task, so basically:

-     Configure the screwdriver, set to professional
-     Request quote for this cart
-     Change config in quote and set to standard
-     Click 'new cart'
-     Call up previous quote
-     Entry summary shows 'Y' correctly,
-    but if i try ti diplay the entries config i get a cart not found error!

using the mock as engine.
- 

i get a cart not found exception
![image](https://github.com/SAP/spartacus/assets/53090888/82f1bf84-e580-43f5-a273-f0997336e11a)

2023-10-27 05:46 UTC, ChristophHi commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
>      }
Yes, that was my idea. But I am currently preparing a new idea how to provide the document context to the outlets that will make the activeCartFacade obsolete, meaning most of the changes to this component most likely are not needed => we will use this method again in a simplified form

2023-10-27 05:47 UTC, ChristophHi commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
> +  protected isActiveCart(cartCode: string): boolean {
No. This is really about checking if we are in active cart mode

2023-10-27 05:50 UTC, ChristophHi commented on feature-libs/product-configurator/common/components/configure-cart-entry/configure-cart-entry.component.ts
> +    readOnlyCartIsActive: boolean
'readOnlyCartIsActive' means: the readOnly cart we are dealing with here is the active cart.
But please note as I said above: Probably we will get rid of activeCartFacade anyhow and don't need that coding.

2023-10-27 05:51 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/variant-configurator-occ.adapter.ts
> +    }
No. The url parameters are different

2023-10-27 06:24 UTC, ChristophHi commented
@Uli-Tiger I cannot reproduce the issue that you mentioned yesterday, tried with CPS and then with mock on https://team-server.tiger-ci.only.sap:17002. Could you try again and maybe give me more hints on how to reproduce? Does it only happen on a local commerce instance?

2023-10-27 08:50 UTC, Uli-Tiger approved these changes
I rested to day and was not able to reproduce the cart not found exception. not sure how and why this happened yesterday,

2023-10-27 08:52 UTC, merged