Feature/cxspa 5484
SAP/spartacus pull request #18176
Opened 2023-11-28 14:52 UTC by steinsebastian

2023-12-04 07:20 UTC, Larisa-Staroverova requested changes

2023-12-04 07:20 UTC, Larisa-Staroverova commented on feature-libs/quote/core/facade/quote.service.spec.ts
> +  let savedCartService: SavedCartFacade;
Please, rename to `savedcartFacade`

2023-12-04 07:20 UTC, Larisa-Staroverova commented on feature-libs/quote/core/facade/quote.service.ts
> +  protected savedCartService = inject(SavedCartFacade);
Please, rename to `savedCartFacade`

2023-12-05 09:38 UTC, steinsebastian commented on feature-libs/quote/core/facade/quote.service.spec.ts
> +  let savedCartService: SavedCartFacade;
Done

2023-12-05 09:38 UTC, steinsebastian commented on feature-libs/quote/core/facade/quote.service.ts
> +  protected savedCartService = inject(SavedCartFacade);
Done

2023-12-05 09:42 UTC, Larisa-Staroverova approved these changes

2023-12-05 10:21 UTC, merged