CXSPA-3242: Display description at attribute and value level
SAP/spartacus pull request #18245
Opened 2023-12-14 07:37 UTC by Larisa-Staroverova

Closes [CXSPA-3242](https://jira.tools.sap/browse/CXSPA-3242)

2023-12-21 11:00 UTC, steinsebastian requested changes

2023-12-21 11:00 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.html
> +        </button>
It is reachable via tab -> ok.
Needs some aria-label to tell SR users that this will open a popover with longtext.

After popover is opened the long-texts are read by screen-reader. -> ok
But after that the focus is lost and it starts again at top of the page. The SR user can't continue after opening the popover.

2023-12-21 11:00 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.html
>          <cx-configurator-price
Same issues as for multi selection image. See above.

2023-12-21 11:00 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/styles/mixins/_configurator-attribute-selection-image.scss
> +
Issue with sticky add-to-cart-button-container: the popover is not scrolling behind the sticky container.
<img width="923" alt="Screenshot 2023-12-21 at 10 43 22" src="https://github.com/SAP/spartacus/assets/54309425/eb329f80-00a3-4e5f-9ff0-25a4397a7a2d">

2023-12-21 11:00 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.html
>  <div
I'm aware that the show-more component has not been introduced with this change.
But nevertheless we should think about the following issue:

The "more" button is not in the tab-chain. For sighted users this might be an advantage as they are not disturbed by this but currently screen-reader users have no chance to reach the complete long text.
We need to find a way, how this could be solved (easiest solution: add it to tab-chain).

But maybe we leave this to customers to add a tabindex if wanted...

2023-12-28 11:43 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.html
> +        </button>
@steinsebastian , good point! 
I added an `aria-label` property with a text: 
> Click on the i-icon to see a description for this value.

Is it okay for you or you prefer another text?

2023-12-28 11:47 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.html
> +        </button>
I understand what you mean and I see a described issue.
Could we have a look together to find a better solution?

2023-12-28 11:48 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.html
>          <cx-configurator-price
Partially solved. See above

2023-12-28 12:00 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/styles/mixins/_configurator-attribute-selection-image.scss
> +
@steinsebastian, imazing that you saw this issue.
I fixed it: 
![image](https://github.com/SAP/spartacus/assets/61147963/1548c9b0-a0f2-42f9-b588-1571d0a7ff63)

2023-12-28 12:20 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.html
>  <div
@steinsebastian, I see what you mean: 
![image](https://github.com/SAP/spartacus/assets/61147963/41e2a542-1b29-4517-ae01-5c04d635e9a2)

2023-12-28 12:37 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.html
>  <div
I fixed it  but it will a breaking change.

2024-01-09 10:47 UTC, steinsebastian requested changes

2024-01-09 10:47 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.html
> +        </button>
I would change the aria-label to "Click to see a description for this value" (as the SR-user does not see any "i-icon").

We should discuss this issue with the lost focus.

2024-01-09 10:59 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.html
> +        </button>
> I would change the aria-label to "Click to see a description for this value" (as the SR-user does not see any "i-icon").
Done!

2024-01-10 14:37 UTC, steinsebastian approved these changes, later dismissed

2024-03-12 15:29 UTC, ChristophHi requested changes

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.html
> +<cx-configurator-show-more
Isn't this breaking?

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox-list/configurator-attribute-checkbox-list.component.html
> +          <cx-configurator-show-more
This is breaking, shouldn't we check for the overall configuration setting?

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox-list/configurator-attribute-checkbox-list.component.spec.ts
> +    it('should not render description', () => {
```suggestion
    it('should not render description in case ....', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox-list/configurator-attribute-checkbox-list.component.spec.ts
> +    it('should render description', () => {
```suggestion
    it('should render description in case...', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox/configurator-attribute-checkbox.component.html
> +          <cx-configurator-show-more
Breaking, see above

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox/configurator-attribute-checkbox.component.spec.ts
> +    it('should not render description', () => {
```suggestion
    it('should not render description in case...', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox/configurator-attribute-checkbox.component.spec.ts
> +    it('should render description', () => {
```suggestion
    it('should render description in case...', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/drop-down/configurator-attribute-drop-down.component.ts
> +    return this.getSelectedValue()?.description ?? '';
One branch not covered by tests

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.spec.ts
> +  it('should render 2 info icons at value level when value has a description', () => {
```suggestion
  it('should render 2 info icons at value level if value has a description', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/radio-button/configurator-attribute-radio-button.component.spec.ts
> +    it('should not render description', () => {
```suggestion
    it('should not render description in case...', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/radio-button/configurator-attribute-radio-button.component.spec.ts
> +    it('should render description', () => {
```suggestion
    it('should render description in case....', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/read-only/configurator-attribute-read-only.component.spec.ts
> +    it('should not render description', () => {
```suggestion
    it('should not render description in case...', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/read-only/configurator-attribute-read-only.component.spec.ts
> +    it('should render description', () => {
```suggestion
    it('should render description in case', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.spec.ts
> +  it('should render info icon at value level when value has a description', () => {
```suggestion
  it('should render info icon at value level if value has a description', () => {
```

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/styles/_configurator-attribute-drop-down.scss
> +  flex-direction: column;
No breaking changes in this file?

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/styles/_configurator-show-more.scss
> +      padding-inline-start: 0;
Not breaking?

2024-03-12 15:29 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/styles/mixins/_configurator-attribute-type.scss
> +        display: flex;
Not breaking?

2024-03-13 09:33 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.html
> +<cx-configurator-show-more
Only for CPQ where we don't know of any customer. For CPS it's guided by a feature flag

2024-03-13 09:51 UTC, ChristophHi approved these changes

2024-03-13 09:51 UTC, merged