Added asterisks to required form fields
SAP/spartacus pull request #18264
Opened 2023-12-15 12:14 UTC by Pio-Bar

https://jira.tools.sap/browse/CXSPA-1026

Added asterisks to all required form inputs to improve their a11y. Please, let me know if I might have missed any.

2023-12-15 13:27 UTC, Zeyber approved these changes, later dismissed

2024-01-10 19:12 UTC, developpeurweb requested changes
@Pio-Bar Great work! Could you please also add the asterisk in the Reviews Section of the PDP, as per screenshot.
![Screenshot 2024-01-10 at 12 58 23 PM](https://github.com/SAP/spartacus/assets/15113219/5b37e2b8-5c7a-4761-946f-44aed34722c1)

I'm meeting the designers tomorrow since most likely there will have to be a reference somewhere to indicate the asterisk means "required".
I’ll get back to you on this.

2024-01-19 15:17 UTC, Pio-Bar commented
> @Pio-Bar Great work! Could you please also add the asterisk in the Reviews Section of the PDP, as per screenshot. ![Screenshot 2024-01-10 at 12 58 23 PM](https://private-user-images.githubusercontent.com/15113219/295680225-5b37e2b8-5c7a-4761-946f-44aed34722c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzYwNjMsIm5iZiI6MTcwNTY3NTc2MywicGF0aCI6Ii8xNTExMzIxOS8yOTU2ODAyMjUtNWIzN2UyYjgtNWM3YS00NzYxLTk0NmYtNDRhZWQzNDcyMmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE0NDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MzE3YmExY2IwYjUxYzVhZGYyNWM1ZGI4M2VjMTNhZDRkMTk5NWYwNDdjZjc4MTE0N2NiMGM5ZWM2Mzg3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDz7c8mJzuThlk3m_nS8XygvWLcF8M6Mskj23kW7B9M)
> 
> I'm meeting the designers tomorrow since most likely there will have to be a reference somewhere to indicate the asterisk means "required". I’ll get back to you on this.

I have added the asterisk to all required inputs in the review form. Let me know if a legend for the asterisk will be needed.

2024-01-22 21:08 UTC, developpeurweb commented
> > @Pio-Bar Great work! Could you please also add the asterisk in the Reviews Section of the PDP, as per screenshot.
> > I'm meeting the designers tomorrow since most likely there will have to be a reference somewhere to indicate the asterisk means "required". I’ll get back to you on this.
> 
> I have added the asterisk to all required inputs in the review form. Let me know if a legend for the asterisk will be needed.

Thx Piotr! A legend will be needed, but since this affects several pages, I have asked designers for their feedback. We are putting this one on hold for now.

2024-01-26 13:18 UTC, Pio-Bar commented
> Thx Piotr! A legend will be needed, but since this affects several pages, I have asked designers for their feedback. We are putting this one on hold for now.

The legend has been included. I also dealt with some code repetition.

2024-01-29 09:50 UTC, Zeyber requested changes
I realized many of these changes are similar. So comments related to `cxFeatureLevel` on the DOM can apply to most of these templates.

2024-01-29 09:50 UTC, Zeyber commented on .github/workflows/ci-merge-checks.yml
> -    types: [ready_for_review]
We can restore this to its original state. It was used to force tests from the `epic/a11y` branch.

2024-01-29 09:50 UTC, Zeyber commented on feature-libs/cart/base/components/cart-coupon/cart-coupon.component.html
> +    <p class="form-legend">
Best to add `cxFeatureLevel` to this and the `abbr` elements since they change rendering of the DOM.

2024-01-29 09:50 UTC, Zeyber commented on feature-libs/checkout/base/components/checkout-payment-method/checkout-payment-form/checkout-payment-form.component.html
> +  <p class="form-legend">
Same thing about `cxFeatureLevel`.

2024-01-29 09:50 UTC, Zeyber commented on feature-libs/user/account/components/login-form/login-form.component.html
> +  <p class="form-legend">
Same thing about using `cxFeatureLevel` here.

2024-01-29 09:50 UTC, Zeyber commented on feature-libs/user/account/components/login-form/login-form.component.html
> +  <abbr
Lets add the `cxFeatureLevel` here too.

2024-01-29 09:51 UTC, Zeyber commented
And a reminder to fix the PR title ;)

2024-01-29 18:11 UTC, Pio-Bar commented
> I realized many of these changes are similar. So comments related to `cxFeatureLevel` on the DOM can apply to most of these templates.

I've included feature flags for all those minor changes

2024-01-30 10:02 UTC, Zeyber approved these changes, later dismissed

2024-01-30 20:46 UTC, developpeurweb approved these changes, later dismissed

2024-03-15 11:36 UTC, Zeyber approved these changes

2024-03-15 13:01 UTC, merged