CXSPA-965: Refocus on input after quick order with keyboard
SAP/spartacus pull request #18313
Opened 2023-12-21 16:28 UTC by Pio-Bar

https://jira.tools.sap/browse/CXSPA-965

After the item has been ordered the focus should go back to the input field.

2023-12-22 12:13 UTC, Zeyber requested changes

2023-12-22 12:13 UTC, Zeyber commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +    this.quickOrderInput.nativeElement.focus();
Lets include a check in the quick order form e2e tests to assert the input gets focused after adding a product to prevent regression.

2024-01-08 11:26 UTC, Zeyber submitted a review, later dismissed

2024-01-11 20:33 UTC, developpeurweb approved these changes, later dismissed
Works well on my end.

2024-03-18 07:23 UTC, Zeyber approved these changes

2024-03-18 14:37 UTC, merged