add feature toggle for chat messngesaging cha
SAP/spartacus pull request #18379
Opened 2024-01-16 19:08 UTC by Uli-Tiger

@Larisa-Staroverova @ChristophHi : Passt das so mit dem Feature Toggle?

2024-01-17 08:52 UTC, ChristophHi requested changes
No that's not the way it is supposed to be.
See the slack conversation https://sap-cx.slack.com/archives/CAC8PULNN/p1705055286677549 please. We cannot bind the features to certain releases anymore, we want to behave like ccv2

2024-01-17 14:21 UTC, Uli-Tiger commented
@ChristophHi : updated the PR accordingly (with exception the scss file). - However, as you can see, the FEATURE_FLAG_QUOTES is always provided with 'true' i wonder how this shall be switched on/off.

2024-01-19 10:55 UTC, ChristophHi requested changes
More comments in slack, I think Kris needs to agree. If my proposal is too simple the core team needs to provide the infrastructure first

2024-01-19 10:55 UTC, ChristophHi commented on projects/storefrontlib/feature-flags.ts
> +export const FEATURE_FLAG_QUOTES = new InjectionToken<boolean>(
It should rather be named FEATURE_FLAG_COMMENTS_PRODUCT_SUPPORT.
And in order to have these flags also available in core I suggest to put it into a new folder projects/core/src/features

2024-01-26 13:06 UTC, merged