feat: add opfAddToCart cms cpnt
SAP/spartacus pull request #18387
Opened 2024-01-18 19:52 UTC by FollowTheFlo

Add CMS cpnt that implements standard AddToCart Cpnt with opf-quick-buy selector in its template.

2024-01-19 21:26 UTC, FollowTheFlo commented on package.json
> +    "start:opf:vm": "env-cmd --no-override -e opf,$SPA_ENV nx serve storefrontapp --configuration=development",
need to run opf without ssl on azure vm to test ApplePay,. VM already has ssl with nginx.

2024-01-22 21:30 UTC, FollowTheFlo commented on integration-libs/opf/base/components/opf-add-to-cart/opf-add-to-cart.component.html
this file is s copy of` add-to-cart.component.ts` with  `<cx-opf-quick-buy></cx-opf-quick-buy>`

2024-01-23 09:03 UTC, Matejk00 requested changes

2024-01-23 09:03 UTC, Matejk00 commented on integration-libs/opf/base/components/opf-add-to-cart/opf-add-to-cart.component.html
The question at hand is whether we should duplicate the content of this "add to cart" template. This would result in two identical copies of the same file, posing potential challenges in maintaining the logic of both files in the future.

An alternative approach could be to introduce an additional outlet position specifically for Quick Buy in the "add to cart" component. This modification is not expected to be a breaking change. For instance:

```
<ng-container *ngIf="hasStock">
  <ng-template [cxOutlet]="CartOutlets.QUICK_BUY"></ng-template>
</ng-container>
```

With this change, the QB module only needs to inject a component into the specified position:

```
providers: [
  provideOutlet({
    id: CartOutlets.QUICK_BUY,
    position: OutletPosition.REPLACE,
    component: OpfQuickBuyComponent,
  }),
],
```
In my view, this approach should be effective. However, I am open to considering any circumstances or considerations that I may not be aware of.

2024-09-30 20:12 UTC, closed without merging