CXSPA-5910: Create new components to cover read-only attribute types with images
SAP/spartacus pull request #18415
Opened 2024-01-24 14:19 UTC by Larisa-Staroverova

2024-02-02 12:40 UTC, steinsebastian requested changes

2024-02-02 12:40 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.html
> +          value.valuePrice && value.valuePrice?.value !== 0
The same aria-label is used for both changeable and read-only values.
This leads to the fact that something like this is announced by the screen reader: 
"Value <value name> of attribute <attriubte name>"

But for read-only it should be:
"Read-only value <value name> of attribute <attribute name>"

For non-image read-only values we use a different aria-label stating that the value is read-only. See configurator-attribute-read-only.component -> Function getAriaLabel().

2024-02-02 12:40 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.html
> +          value.valuePrice && value.valuePrice?.value !== 0
Same comment as for single-selection: A separate read-only aria-label should be used.

2024-02-02 12:52 UTC, ChristophHi requested changes

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.spec.ts
> +    it('should select multi selection image value', () => {
```suggestion
    it('should call service for update', () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.spec.ts
> +    it('should not call select event in case uiType READ_ONLY_MULTI_SELECTION_IMAGE', () => {
```suggestion
    it('should not call service in case uiType READ_ONLY_MULTI_SELECTION_IMAGE', () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.spec.ts
> +    it('should select another single selection image value', () => {
```suggestion
    it('should call service for update', () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.spec.ts
> +    it('should not call click event', () => {
```suggestion
    it('should not call service for update and in case attribute is read-only', () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +    it("should convert read_only_single_selection_image attribute type correctly when isRetractBlocked is set to 'true'", () => {
```suggestion
    it("should convert read_only_single_selection_image attribute type correctly if isRetractBlocked is set to 'true'", () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +    it("should return UIType single_selection_image attribute type correctly when isConflicting is set to 'true'", () => {
```suggestion
    it("should return UIType single_selection_image attribute type correctly if isConflicting is set to 'true'", () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      sourceAttribute.retractBlocked = true;
Here we should also set conflicts, otherwise the test does not make much sense

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +    it("should convert read_only_multi_selection_image attribute type correctly when isRetractBlocked is set to 'true'", () => {
```suggestion
    it("should convert read_only_multi_selection_image attribute type correctly if isRetractBlocked is set to 'true'", () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +      sourceAttribute.retractBlocked = true;
Please add conflicts

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +    it("should return UIType multi_selection_image attribute type correctly when isConflicting is set to 'true'", () => {
```suggestion
    it("should return UIType multi_selection_image attribute type correctly if isConflicting is set to 'true'", () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +    it("should return 'true' because type is READ_ONLY_SINGLE_SELECTION_IMAGE", () => {
```suggestion
    it("should return 'true' in case type is READ_ONLY_SINGLE_SELECTION_IMAGE", () => {
```

2024-02-02 12:52 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
> +    it("should return 'true' because type is READ_ONLY_MULTI_SELECTION_IMAGE", () => {
```suggestion
    it("should return 'true' in case type is READ_ONLY_MULTI_SELECTION_IMAGE", () => {
```

2024-02-05 07:27 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.html
> +          value.valuePrice && value.valuePrice?.value !== 0
@steinsebastian, could you have a look at my current solution and verify whether it is that what you expect?
Thanks a lot in advance!
I have to implement missing karma tests for both methods.

2024-02-05 13:54 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/types/single-selection-image/configurator-attribute-single-selection-image.component.html
> +          value.valuePrice && value.valuePrice?.value !== 0
It works!

2024-02-05 13:56 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/attribute/types/multi-selection-image/configurator-attribute-multi-selection-image.component.html
> +          value.valuePrice && value.valuePrice?.value !== 0
After latest change it is working now.

2024-02-05 13:56 UTC, steinsebastian submitted a review, later dismissed

2024-03-12 14:06 UTC, ChristophHi approved these changes

2024-03-13 06:14 UTC, merged