fix: Fix unit addresses and users in b2b my company not traversing or notifying on creation
SAP/spartacus pull request #18493
Opened 2024-02-13 15:04 UTC by Zeyber

Closes: https://jira.tools.sap/browse/CXSPA-5630

2024-03-04 12:34 UTC, Zeyber commented on feature-libs/organization/administration/core/store/effects/org-unit.effect.ts
> +                new GlobalMessageActions.AddMessage({
It would be better to find a way to listen for the effect to complete and then have the message and routing actions performed by that listener.

2024-03-06 21:19 UTC, Zeyber commented
Have simplified the approach based on the fix provided on [this PR](https://github.com/SAP/spartacus/pull/18360) and following discussion with @Pucek9 about his findings. It leverages the default my company mechanism for generating success messages and proceeding navigation to newly created entities which was broken for these cases in a refactor.

2024-03-07 16:04 UTC, Pucek9 requested changes
![image](https://github.com/SAP/spartacus/assets/8040837/3d74afba-9078-4219-81e4-95bf1af55a83)
Unfortunately, this change causes another problem

2024-03-11 10:40 UTC, Zeyber commented
Note for testers: To enable fixes, add the following provider to the b2b config module `projects/storefrontapp/src/app/spartacus/spartacus-b2b-configuration.module.ts`.

```
    provideConfig(<FeaturesConfig>{
      features: {
        fixMyCompanyUnitAddressCreation: true,
        fixMyCompanyUnitUserCreation: true,
      },
    }),
```

2024-03-11 12:54 UTC, Pucek9 approved these changes
Works as expected! Thank you

2024-03-13 12:29 UTC, rmch91 approved these changes

2024-03-13 13:09 UTC, merged