fix: (CXSPA-2187) - Schedule replenishment order a11y fixes
SAP/spartacus pull request #18525
Opened 2024-02-20 15:28 UTC by Pio-Bar

https://jira.tools.sap/browse/CXSPA-2187

- Fixed missing label for datepicker input 
- Fixed header order

2024-02-21 13:04 UTC, rmch91 requested changes

2024-02-21 13:04 UTC, rmch91 commented on feature-libs/checkout/scheduled-replenishment/components/checkout-schedule-replenishment-order/checkout-schedule-replenishment-order.component.html
> +    <h3 *cxFeatureLevel="'6.8'" class="cx-order-replenishment-header">
I think I don't understand the idea of two identical elements with different feature flags. Is it intended? Without feature flags directive `<h3 class="cx-order-replenishment-header">` is identical with the next `h3` element

2024-02-22 08:31 UTC, Pio-Bar commented on feature-libs/checkout/scheduled-replenishment/components/checkout-schedule-replenishment-order/checkout-schedule-replenishment-order.component.html
> +    <h3 *cxFeatureLevel="'6.8'" class="cx-order-replenishment-header">
The H5 tag should have changed into H3. I have left it the same by accident. It's fixed now ;)

2024-02-22 12:29 UTC, rmch91 submitted a review, later dismissed

2024-02-22 18:35 UTC, developpeurweb approved these changes, later dismissed

2024-03-27 08:29 UTC, Zeyber approved these changes, later dismissed

2024-03-27 13:27 UTC, Zeyber approved these changes

2024-03-27 13:27 UTC, merged