CXEC-16839: Accessibility improvements for tab-bar and addtocart
SAP/spartacus pull request #18530
Opened 2024-02-21 10:54 UTC by steinsebastian

2024-02-26 12:56 UTC, Larisa-Staroverova requested changes

2024-02-26 12:56 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.ts
> +  focusFirstActiveElement(hostQuerySelector: string) {
Could you, please, rename `hostQuerySelector` parameter to `selector`?

2024-02-26 12:56 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.ts
> +    const tabBar = this.getElement(hostQuerySelector);
Could you, please, rename `tabBar` to `element`?

2024-02-26 12:56 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.ts
> +   * @param hostQuerySelector - query selector of the host element
Could you, please, rename `hostQuerySelector` parameter to `selector`?

2024-02-26 12:56 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/tab-bar/configurator-tab-bar.component.ts
> +   * @param routerData - Router data
Please, add an empty line

2024-02-26 12:56 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/tab-bar/configurator-tab-bar.component.ts
> +   * @param routerData - Router data
Please, add an empty line

2024-02-27 11:14 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.ts
> +  focusFirstActiveElement(hostQuerySelector: string) {
Done

2024-02-27 11:14 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.ts
> +    const tabBar = this.getElement(hostQuerySelector);
done

2024-02-27 11:14 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/service/configurator-storefront-utils.service.ts
> +   * @param hostQuerySelector - query selector of the host element
done

2024-02-27 11:14 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/tab-bar/configurator-tab-bar.component.ts
> +   * @param routerData - Router data
done

2024-02-27 11:14 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/tab-bar/configurator-tab-bar.component.ts
> +   * @param routerData - Router data
done

2024-02-27 13:30 UTC, Larisa-Staroverova approved these changes

2024-02-27 15:08 UTC, merged