fix: (CXSPA-2243) - Improved a11y for popovers in 'organization'
SAP/spartacus pull request #18539
Opened 2024-02-22 12:52 UTC by Pio-Bar

https://jira.tools.sap/browse/CXSPA-2243

Improved screen reader readout for information buttons in 'My Company' subpages.

2024-02-26 14:38 UTC, rmch91 approved these changes, later dismissed

2024-03-13 15:41 UTC, developpeurweb requested changes
This works better now for both JAWS and VO.
There are three ways of closing the popover while using the keyboard, regardless of Screen Reader use, either pressing Spacebar or Enter will toggle the display and the narration, and then continue tabbing to the next element without breaking the order.
However, a third way is pressing the ESC key, and this resets the focus to the top of the page thus breaking the order.
Is there a way to align the ESC key to close the popover without the focus moving to the top of the page and continue with the natural order expectation?

2024-03-19 13:24 UTC, Pio-Bar commented
I've modified it to restore focus to the opener element regardless of how it was closed.

2024-03-20 16:50 UTC, Zeyber requested changes

2024-03-20 16:50 UTC, Zeyber commented on projects/storefrontlib/shared/components/popover/popover.service.ts
> +  setFocusOnElement(element: ElementRef) {
Breaking changes need handling :)

2024-03-21 16:12 UTC, Pio-Bar commented on projects/storefrontlib/shared/components/popover/popover.service.ts
> +  setFocusOnElement(element: ElementRef) {
Feature flags added ;)

2024-03-22 06:25 UTC, Zeyber approved these changes, later dismissed

2024-03-25 18:55 UTC, developpeurweb approved these changes, later dismissed

2024-03-27 15:57 UTC, Zeyber approved these changes

2024-03-27 15:58 UTC, merged