test: fix failing cypress tests
SAP/spartacus pull request #18558
Opened 2024-02-27 16:53 UTC by Stofftiger

fixed cypress tests for:
- product-configurator-vc-cart.e2e-flaky 
- product-configurator-vc-ov-filter-menu-e2e-spec-flaky
- product-configurator-textfield.e2e

2024-02-27 17:04 UTC, Uli-Tiger requested changes
please wait for pricing on each value change and on each group navigation

2024-02-27 17:04 UTC, Uli-Tiger commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/product_configurator/product-configurator-vc-ov-filter-menu-e2e-spec-flaky.cy.ts
>    configurationVc.selectAttributeAndWait('CAMERA_VIEWFINDER', RB, 'R');
we should also wait for pricing here

2024-02-27 17:04 UTC, Uli-Tiger commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/product_configurator/product-configurator-vc-ov-filter-menu-e2e-spec-flaky.cy.ts
>    configurationVc.selectAttributeAndWait('CAMERA_MAX_ISO', RB, '25600');
same here, wait for pricing

2024-02-27 17:04 UTC, Uli-Tiger commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/product_configurator/product-configurator-vc-ov-filter-menu-e2e-spec-flaky.cy.ts
>    configurationVc.clickOnNextBtnAndWait('Options');
same here

2024-02-28 14:14 UTC, Stofftiger commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/product_configurator/product-configurator-vc-ov-filter-menu-e2e-spec-flaky.cy.ts
>    configurationVc.selectAttributeAndWait('CAMERA_VIEWFINDER', RB, 'R');
done

2024-02-28 14:14 UTC, Stofftiger commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/product_configurator/product-configurator-vc-ov-filter-menu-e2e-spec-flaky.cy.ts
>    configurationVc.selectAttributeAndWait('CAMERA_MAX_ISO', RB, '25600');
done

2024-02-28 14:14 UTC, Stofftiger commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/product_configurator/product-configurator-vc-ov-filter-menu-e2e-spec-flaky.cy.ts
>    configurationVc.clickOnNextBtnAndWait('Options');
done

2024-02-28 15:56 UTC, Uli-Tiger approved these changes

2024-02-28 16:11 UTC, merged