MultiCart with switch solution
SAP/spartacus pull request #18574
Opened 2024-03-01 16:40 UTC by FollowTheFlo

2024-03-05 14:31 UTC, FollowTheFlo commented on integration-libs/opf/base/components/opf-quick-buy/apple-pay/apple-pay.component.ts
> +    this.cartHandlerService.allowMiniCartUpdate();
we want to ensure the cart does not stay blocked. Even though the logic should be handled, we want to avoid any obscured scenario.

2024-03-06 08:51 UTC, Matejk00 requested changes

2024-03-06 08:51 UTC, Matejk00 commented on integration-libs/opf/base/core/services/opf-cart-handler.service.ts
> +  allowMiniCartUpdate() {
Would you consider creating a mirror function that is more reusable within the cart-handler service?

```
blockMiniCartComponentUpdate(decision: boolean) {
    this.opfMiniCartComponentService.blockUpdate(decision);
}
```

2024-03-06 08:51 UTC, Matejk00 commented on integration-libs/opf/base/core/services/opf-cart-handler.service.ts
> +      tap(() => this.opfMiniCartComponentService.blockUpdate(true)),
then we can use a function directly from the service.

```
      tap(() => this.blockMiniCartComponentUpdate(true)),
```

2024-03-06 08:51 UTC, Matejk00 commented on integration-libs/opf/base/core/services/opf-cart-handler.service.ts
> +      tap(() => this.opfMiniCartComponentService.blockUpdate(false))
same here but with the different argument

```
      tap(() => this.blockMiniCartComponentUpdate(false)),
```

2024-03-06 08:51 UTC, Matejk00 commented on integration-libs/opf/base/root/services/opf-mini-cart-component.service.ts
> +  blockUpdate(val: boolean) {
Can we add a comment on top that describes a context of this method?

2024-03-06 08:51 UTC, Matejk00 commented on integration-libs/opf/base/core/services/opf-cart-handler.service.ts
> +  protected initiateCartHandlerState: CartHandlerState = {
nitpick:
I think `defaultCartHandlerState` fits better for me or `initialCartHandlerState`.
I believe `initiate` is more appropriate for a function that actually initializes a state, but this is just an assignment.

2024-03-06 08:51 UTC, Matejk00 commented on integration-libs/opf/base/components/opf-quick-buy/apple-pay/apple-pay.service.ts
> +  protected loadPdpOriginalCart(orderSuccess = false): void {
I'm steering clear of using the name "Pdp." In GooglePay and ApplePay services, it was referred to as `SingleProduct`, and the context also resembles `OpfQuickBuyLocation.PRODUCT`.

Perhaps we could consider renaming it to `loadCartAfterSingleProductTransaction`?

2024-03-06 18:22 UTC, FollowTheFlo commented on integration-libs/opf/base/core/services/opf-cart-handler.service.ts
> +      .getEntry(this.cartHandlerState.previousCartId, productCode)
We were previously using 'activeCart' to getEntry, but was getting 'undefined' intermittently.
so, moved to 'multipleCart' to fix it.
I guess root cause was due to race condition where previousCart was not yet loaded as activeCart.

2024-03-07 12:05 UTC, Matejk00 approved these changes

2024-03-07 13:39 UTC, merged