Product configurator feature toggle
SAP/spartacus pull request #18641
Opened 2024-03-18 06:44 UTC by Larisa-Staroverova

We have to rename product configurator feature toggle to `productConfiguratorAttributeTypesV2`

2024-03-18 07:20 UTC, ChristophHi requested changes

2024-03-18 07:20 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/config/default-configurator-ui-settings.config.ts
> +        addDescriptions: true,
Default must be false!

2024-03-18 07:20 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox-list/configurator-attribute-checkbox-list.component.spec.ts
> +describe('ConfiguratorAttributeCheckBoxListComponent', () => {
Please revert, let's focus only on fixes with this PR

2024-03-18 07:20 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox/configurator-attribute-checkbox.component.spec.ts
> +describe('ConfiguratorAttributeCheckBoxComponent', () => {
Please revert, let's focus only on fixes with this PR

2024-03-18 07:20 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/input-field/configurator-attribute-input-field.component.spec.ts
> +describe('ConfiguratorAttributeInputFieldComponent', () => {
Please revert, let's focus only on fixes with this PR

2024-03-18 07:20 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/numeric-input-field/configurator-attribute-numeric-input-field.component.service.spec.ts
> +describe('ConfiguratorAttributeNumericInputFieldService', () => {
Please revert, let's focus only on fixes with this PR

2024-03-18 07:20 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/read-only/configurator-attribute-read-only.component.spec.ts
> +describe('ConfiguratorAttributeReadOnlyComponent', () => {
Please revert, let's focus only on fixes with this PR

2024-03-18 07:22 UTC, ChristophHi requested changes

2024-03-18 07:22 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/rulebased-configurator-components.module.ts
> +        productConfiguratorAttributeTypesV2: true,
Default must be false

2024-03-18 08:45 UTC, ChristophHi requested changes

2024-03-18 08:45 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/base/configurator-attribute-base.component.ts
> +   * If the length of the label is longer than 16 singes, it will be shorten and ellipsis will be added at the end.
```suggestion
   * If the length of the label is longer than 16 characters, it will be shortened and ellipsis will be added at the end.
```

2024-03-18 08:45 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/base/configurator-attribute-base.component.ts
> +      ? labelForImage.substring(0, 16).concat('...')
RTL?

2024-03-18 08:49 UTC, ChristophHi requested changes

2024-03-18 08:49 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/types/checkbox/configurator-attribute-checkbox.component.spec.ts
> +describe('ConfigAttributeInputFieldComponent', () => {
Typo
```suggestion
describe('ConfigAttributeCheckBoxComponent', () => {
```

2024-03-19 08:50 UTC, ChristophHi requested changes

2024-03-19 08:50 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/components/attribute/header/configurator-attribute-header.component.spec.ts
> -        addDescriptions: true,
Could you please fix the strict mode issues in line 1126 and 1132? Last week I did notice them in my review

2024-03-19 08:50 UTC, ChristophHi commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
>        expect(result.groups[0].attributes[0].description).toBeDefined();
Please fix strict mode issues (until line 415)

2024-03-19 11:29 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/occ/variant/converters/occ-configurator-variant-normalizer.spec.ts
>        expect(result.groups[0].attributes[0].description).toBeDefined();
Sorry, I have overseen them

2024-03-19 13:33 UTC, ChristophHi approved these changes

2024-03-19 13:33 UTC, merged