Do not display Show Details button for read-only base product
SAP/spartacus pull request #18700
Opened 2024-04-04 11:05 UTC by Larisa-Staroverova

Closes [CXSPA-6484](https://jira.tools.sap/browse/CXSPA-6484)

2024-04-22 12:10 UTC, Uli-Tiger requested changes, later dismissed
In addition to the previous 2 comments, do we also need to handle the case when the customer is still on older release, maybe not even using the make-to-stock feature. Will this break anything?

2024-04-22 12:10 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-product/configure-product.component.ts
> +    );
```suggestion
    return (
      product.baseProduct === product.code || !product.baseProduct 
    );
```
I assume `product.code` may never be `undefined`, as we query the product data using the code.

2024-04-22 12:10 UTC, Uli-Tiger commented on feature-libs/product-configurator/common/components/configure-product/configure-product.component.ts
> +   * In the product detail page a product is a base one when only code is defined.
the different behavior is really strange.....

i would phrase the comment like this:
```suggestion
   * The `baseProduct` property contains the product code of the base product.
   * So if the baseProduct is undefined or if the provided code equals the code of the product itself,
   * we assume this product to be a base product.
```

2024-04-22 12:30 UTC, Larisa-Staroverova commented
Hi @Uli-Tiger,
thank you for your feedback.

> do we also need to handle the case when the customer is still on older release, maybe not even using the make-to-stock feature. Will this break anything?

If make-to-stock scenario is **not** active, then `configure` button will be displayed instead of `show details`

if make-to-stock scenario is **active**, then configurator type with READ_ONLY postfix will be returned (see `isConfiguratorTypeReadOnly` method)

To react to the older versions a feature toggle like 'productConfiguratorMakeToStockV2' should be defined that's why I asked not to merge this PR because of it.

2024-04-22 12:46 UTC, Uli-Tiger commented
> To react to the older versions a feature toggle like 'productConfiguratorMakeToStockV2' should be defined that's why I asked not to merge this PR because of it.

agree - do we have a task for it?

2024-04-22 12:51 UTC, Larisa-Staroverova commented
> agree - do we have a task for it?
Not yet. In first line we wanted to find a solution.
The first version of `make-to-stock` has not been merged yet.

2024-08-06 15:31 UTC, AlexanderKuschner approved these changes

2024-08-06 16:16 UTC, hackergil approved these changes

2024-08-06 16:18 UTC, merged