fix: (CXSPA-1029) - Image text alternative is provided to banners
SAP/spartacus pull request #18719
Opened 2024-04-11 08:11 UTC by sdrozdsap

2024-04-16 06:41 UTC, Zeyber requested changes

2024-04-16 06:41 UTC, Zeyber commented on projects/storefrontlib/cms-components/content/banner/banner.component.ts
> +  getLinkAriaLabel(data: CmsBannerComponent): string | undefined {
We should have a unit test for this method to keep up code coverage.

2024-04-16 10:37 UTC, sdrozdsap commented on projects/storefrontlib/cms-components/content/banner/banner.component.ts
> +  getLinkAriaLabel(data: CmsBannerComponent): string | undefined {
Done

2024-04-17 11:39 UTC, Zeyber approved these changes

2024-04-17 19:30 UTC, developpeurweb approved these changes

2024-04-18 07:56 UTC, merged