fix: (CXSPA-4344) - Quantity update on enter press
SAP/spartacus pull request #18713
Opened 2024-04-08 13:17 UTC by Pio-Bar

[CXSPA-4344](https://jira.tools.sap/browse/CXSPA-4344) I think we can get away with not using feature flags here. I have reused some of the code that have been marked for removal, hence the comment edit. 

- The Item counter updates the value on 'enter' keypress.
- Should restore focus after data gets updated in cart/add to cart modal.

2024-04-09 07:07 UTC, Zeyber approved these changes, later dismissed

2024-04-11 19:04 UTC, developpeurweb requested changes
While on PDP, when changing the quantity and pressing the “Enter” key, the Add To Cart modal gets triggered. This is an unexpected change of context.
Can this be avoided? The expectation is only for the quantity to get updated in the Qty field.

2024-04-16 11:48 UTC, Pio-Bar commented
> While on PDP, when changing the quantity and pressing the “Enter” key, the Add To Cart modal gets triggered. This is an unexpected change of context. Can this be avoided? The expectation is only for the quantity to get updated in the Qty field.

I've disabled the PDP 'add to cart' modal after pressing enter on the quantity input field. Let me know if it behaves as intended. ;)

2024-04-19 08:41 UTC, Zeyber approved these changes

2024-04-22 19:21 UTC, developpeurweb approved these changes

2024-04-23 10:26 UTC, merged