CXSPA-6816 : Estimated delivery date UI
SAP/spartacus pull request #18794
Opened 2024-05-02 18:13 UTC by tiwariakshay55

### **Estimated Delivery Date UI :**
**Requirement** - The existing UI of S4OM(Integration-libs) to show schedule line (estimated delivery) needs to be moved to feature libs as the backend is being moved to core to make this feature more generic and allowing other integration scenarios to use this feature.

**Changes:**

- Added a new library named estimated-delivery-date in feature-libs. Followed the [wiki](https://github.com/SAP/spartacus/blob/develop/docs/libs/creating-lib.md).
- Reused code from S4OM with addition of logic to show arrival slot from consignments-> Introduced new attributes of order entries and consignments as "arrivalSlots"(Array of arrival slot) and arrivalSlot respectively.
- Added arrivalSlots as field in the cart OCC -> default-occ-cart-config.ts.

**Note:** No change in S4OM UI as of now as the backend development is still going on. In future we will remove this code completely and use the existing estimated-delivery-date library for it.

**Screens:**
Follow this [wiki](https://wiki.one.int.sap/wiki/display/CXINT/Spartacus+ACD+Estimated+Delivery+Date) page.

2024-05-07 05:49 UTC, anjana-bl commented
Please add this [DoD checklist](https://github.com/SAP/spartacus/issues/new?assignees=&labels=epic-release-activities&template=epic_release.md&title=Epic+Release%3A+%5Bepic+name%5D) to the description and fill it accordingly

2024-05-07 05:54 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/README.md
can we add more information related to installing this library?

2024-05-08 08:16 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/README.md
Done

2024-05-08 08:44 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.component.ts
Let's use Angular's inject() function instead of constructor for Dependency Injection. 

Please check the Architectural Decision Document "[Use inject() function instead of constructor for Dependency Injection](https://wiki.one.int.sap/wiki/display/spar/Use+inject%28%29+function+instead+of+constructor+for+Dependency+Injection)"
PS. You can find the above mentioned guideline also in our Spartacus [Coding Guidelines](https://wiki.one.int.sap/wiki/display/spar/Coding+Guidelines#CodingGuidelines-Useinject()functioninsteadofconstructorforDependencyInjection) wiki.

2024-05-08 08:44 UTC, anjana-bl commented on feature-libs/cart/base/occ/adapters/default-occ-cart-config.ts
MAJOR: Instead of directly adding arrival slots to the already existing end point in cart library, can we create new end point for arrival slots in EDD library ? and correspondingly invoke the APIs with both scopes. 
Since arrivalSlots property is added only as part of EDD to the model, i think its better to fetch the arrivalSlots data only incase of EDD. 
what do you say ? We can discuss about your thoughts on this approach..

2024-05-08 08:44 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/estimated-delivery-date.module.ts
Note: we can use this module to lazy load the component module

2024-05-08 10:56 UTC, tiwariakshay55 commented on feature-libs/cart/base/occ/adapters/default-occ-cart-config.ts
As per the backend code, this attribute is available at core and the similarly we will be adding the attribute of ArrivalSlots and ArrivalSlot to their respective places in upcoming release.

2024-05-09 04:12 UTC, anjana-bl commented on feature-libs/cart/base/occ/adapters/default-occ-cart-config.ts
all core features are part of `feature-libs`.  this comment is more about how we utilise the fields within the core libraries

2024-05-09 08:43 UTC, anjana-bl commented on projects/schematics/package.json
you can ignore these changes as part of your PR
    "test": "npm run clean && ../../node_modules/.bin/jest --config ./jest.schematics.config.js",
    "copy-feature-toggles": "node copy-feature-toggles"
    "copy-feature-toggles": "node copy-feature-toggles",
    "test": "npm run clean && ../../node_modules/.bin/jest --config ./jest.schematics.config.js"

2024-05-09 08:43 UTC, anjana-bl commented on projects/storefrontapp-e2e-cypress/cypress/e2e/vendor/estimated-delivery-date/estimated-delivery-date..e2e.cy.ts
can the test case be moved to  projects/storefrontapp-e2e-cypress/cypress/e2e/regression as EDD is part of feature-libs?

2024-05-09 08:43 UTC, anjana-bl commented on projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/s4om/s4om.ts
can the helper functions be moved to projects/storefrontapp-e2e-cypress/cypress/e2e/regression as EDD is part of feature-libs?

2024-05-09 08:43 UTC, anjana-bl commented on scripts/install/functions.sh
I think corresponding changes in config.default.sh file is missing. can you add it

2024-05-09 09:22 UTC, tiwariakshay55 commented on projects/storefrontapp-e2e-cypress/cypress/helpers/vendor/s4om/s4om.ts
Reusing S4om's existing helper

2024-05-09 09:23 UTC, tiwariakshay55 commented on projects/storefrontapp-e2e-cypress/cypress/e2e/vendor/estimated-delivery-date/estimated-delivery-date..e2e.cy.ts
done

2024-05-09 09:36 UTC, anjana-bl commented on .env-cmdrc
can you change the system here to s5, as s8 doesnot have config (or) maintain config in s8? 
The expectation is, any one should be able to test the feature when connected to the maintained system

2024-05-09 10:09 UTC, tiwariakshay55 commented on scripts/install/functions.sh
Done

2024-05-09 17:10 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/root/feature-name.ts
MAJOR: can you move it out under the `estimated-delivery-date` folder?

2024-05-09 17:10 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.module.ts
MAJOR: 1. can you rename this to estimated-delivery-date-component.module.ts
MAJOR: 2. Also I can see that this module is eager loaded. Any specific reason? Do you think this can be lazy loaded in cart module?
MAJOR: 3. if we lazy load this, then can we move this outside root folder?

2024-05-09 17:10 UTC, anjana-bl commented on projects/storefrontapp-e2e-cypress/cypress/helpers/estimated-delivery-date.ts
MEDIUM: Do you think already existing functions can be reused here?

2024-05-09 17:10 UTC, anjana-bl commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/estimated-delivery-date/estimated-delivery-date..e2e.cy.ts
> +    it('should see estimated delivery date in cart and order pages', () => {
MEDIUM: can we go to cart details and check if EDD appears ? 
Reason being - E2E test case gives an overview of the function for anyone new to topic. So its better to add all possible scenarios

2024-05-09 17:10 UTC, anjana-bl commented on projects/schematics/src/shared/lib-configs/estimated-delivery-date-schematics-config.ts
> +    CHECKOUT_BASE_FEATURE_NAME,
MAJOR: Why have we added checkout base and order as dependency here? isn't cart alone a dependency?

2024-05-09 17:10 UTC, anjana-bl commented on package-lock.json
> +}
NITPICK: can we remove this?

2024-05-09 17:10 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/styles/_estimated-delivery-date.scss
> +    padding-inline-end: 0.313rem;
NITPICK: very specific number .. any reason why? can it be made 0.3 or 0.4?

2024-05-09 17:10 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/schematics/add-estimated-delivery-date/__snapshots__/index_spec.ts.snap
> +
MAJOR: can we check why they empty? it should have been generated properly

2024-05-09 17:10 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.component.html
> +        attr.aria-describedby="{{ getArrivalSlotInfoId(i) }}"
MAJOR: Will this work? i think we need to use poperty binding []..

2024-05-09 17:10 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.component.html
> +        <div id="{{ getArrivalSlotInfoId(i) }}" class="cx-visually-hidden">
MAJOR: Will this work? i think we need to use poperty binding []..

2024-05-09 17:10 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.component.html
> +            'estimatedDeliveryDate.a11y.estimatedDeliveryDateEntryInfo'
NITPICK: just a thought - why to name it *.a11y.* if we don't use it in aria-label

2024-05-09 17:27 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/root/feature-name.ts
Done

2024-05-09 17:45 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/styles/_estimated-delivery-date.scss
> +    padding-inline-end: 0.313rem;
Reused Existing S4OM changed to 0.3

2024-05-09 17:53 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.module.ts
Done Renamed.

2024-05-09 17:55 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.module.ts
Reusing the S4OM logic to eagerly load the module as in few scenarios(like order details) we should to show EDD readily rather than waiting for the page load completely which can cause bad user experience ?
Reference : Requested delivery date and S4OM schedule lines.

2024-05-09 17:56 UTC, tiwariakshay55 commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/estimated-delivery-date/estimated-delivery-date..e2e.cy.ts
> +    it('should see estimated delivery date in cart and order pages', () => {
Done added

2024-05-09 18:00 UTC, tiwariakshay55 commented on projects/storefrontapp-e2e-cypress/cypress/helpers/estimated-delivery-date.ts
I have customised a bit for all of these functions as per the requirement

2024-05-09 18:15 UTC, tiwariakshay55 commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/estimated-delivery-date/estimated-delivery-date..e2e.cy.ts
> +    it('should see estimated delivery date in cart and order pages', () => {
Done 
Added custom method to go back to cart and check if edd is shown.

2024-05-09 18:19 UTC, tiwariakshay55 commented on package-lock.json
> +}
Done

2024-05-09 18:26 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.component.html
> +        <div id="{{ getArrivalSlotInfoId(i) }}" class="cx-visually-hidden">
It works, but better to use property binding.
Updated

2024-05-09 18:36 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.component.html
> +        attr.aria-describedby="{{ getArrivalSlotInfoId(i) }}"
It works, but better to use property binding.
Updated

2024-05-09 18:38 UTC, tiwariakshay55 commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.component.html
> +            'estimatedDeliveryDate.a11y.estimatedDeliveryDateEntryInfo'
Updated

2024-05-10 09:32 UTC, anjana-bl commented on feature-libs/estimated-delivery-date/root/components/estimated-delivery-date/estimated-delivery-date.module.ts
It is better to lazy load the modules as needed instead of eager loading at the start of application. 
Please refer to https://github.com/SAP/spartacus/pull/18823 for a PoC

2024-05-10 10:00 UTC, anjana-bl commented on feature-libs/cart/base/occ/adapters/default-occ-cart-config.ts
Hi Akshay - I have done a PoC in this PR https://github.com/SAP/spartacus/pull/18823.
Lets not resolve this, until we fix it / get a confirmation from Roman.

2024-05-13 08:25 UTC, anjana-bl commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/estimated-delivery-date/estimated-delivery-date.e2e-flaky.cy.ts
MAJOR: as  we don't have any way to displaying the core property arrivalSlots in UI (besides spinning up and OMSA backend and installing OMSA backend integration) -> then we should add new e2e in only in the /vendor sub-folder called /omsa -> and only there add e2e tests.
Why: in /vendor e2e folder we should have all e2e tests that require some vendor integration to be installed - so we cannot run them in our main pipeline (on PRs and async jobs)
This was suggested by Kris

2024-05-13 08:37 UTC, tiwariakshay55 commented on projects/storefrontapp-e2e-cypress/cypress/e2e/regression/estimated-delivery-date/estimated-delivery-date.e2e-flaky.cy.ts
Done

2024-05-13 10:31 UTC, rmch91 approved these changes, later dismissed

2024-05-13 11:50 UTC, rmch91 requested changes

2024-05-13 11:50 UTC, rmch91 commented on .github/CODEOWNERS
> +/feature-libs/estimated-delivery-date/         @SAP/spartacus-codeowners
I think it should be /feature-libs/estimated-delivery-date/ @SAP/spartacus-codeowners @SAP/spartacus-CDC

2024-05-13 12:03 UTC, rmch91 approved these changes

2024-05-13 17:10 UTC, merged