feat: (CXSPA-2045) - image gallery zoom accessible by keyboard
SAP/spartacus pull request #18820
Opened 2024-05-09 12:54 UTC by Pio-Bar

Ticket: [CXSPA-1045](https://jira.tools.sap/browse/CXSPA-1045)

Draft of an accessible PDP gallery zoom. 
Adds a button that can be triggered by a key press.

2024-06-13 09:37 UTC, Zeyber requested changes

2024-06-13 09:37 UTC, Zeyber commented on feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-view/product-image-zoom-view.component.ts
> +  @Optional() featureConfigService = inject(FeatureConfigService);
Lets use our new knowledge according to the wiki and change this to `private` here ;)
https://wiki.one.int.sap/wiki/pages/viewpage.action?spaceKey=spar&title=Coding+Guidelines#CodingGuidelines-UseaFeatureToggleinourlibraries

2024-06-13 09:37 UTC, Zeyber commented on feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-view/product-image-zoom-view.component.ts
> +  get isMobile(): Observable<boolean> {
Is this method going to be called on initial page load? Would we be able to avoid using the `breakpointService` if so (maybe css instead)? It can potentially cause SSR and hydration issues and it is critical to avoid these on PDP, PLP and anywhere where SSO is important. The reason for this is that "If you change DOM structure in the client (based on the browser width recognition) and it's different from the DOM structure produced in SSR -> then very likely you'll have layout shifts on initial page load, affecting core web vitals".

2024-06-13 15:51 UTC, Pio-Bar commented on feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-view/product-image-zoom-view.component.ts
> +  @Optional() featureConfigService = inject(FeatureConfigService);
done ;)

2024-06-13 15:59 UTC, Pio-Bar commented on feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-view/product-image-zoom-view.component.ts
> +  get isMobile(): Observable<boolean> {
I've replaced it with CSS since the result is the same. I will keep the `breakpointService` tip in mind for the future, thanks. 👍

2024-06-14 08:39 UTC, Zeyber approved these changes

2024-06-14 08:39 UTC, Zeyber commented on feature-libs/product/image-zoom/components/product-image-zoom/product-image-zoom-view/product-image-zoom-view.component.ts
> +  get isMobile(): Observable<boolean> {
Thank you very much for doing this!

2024-06-26 00:41 UTC, developpeurweb approved these changes

2024-06-26 09:07 UTC, merged