fix: (CXSPA-963) - Removed tabindex from storefront component
SAP/spartacus pull request #18936
Opened 2024-06-04 15:31 UTC by Pio-Bar

Ticket: [CXSPA-963](https://jira.tools.sap/browse/CXSPA-963)

Removing this attribute from the storefront component helps to reduce the infamous screen reader bloat. It is better for a screen reader if the focus returns to the body instead.

After my investigation I think there is no consequence to removing it, as i see no effect on the focus directive mentioned in the comment. Some thorough testing may be needed to confirm.

2024-06-05 12:36 UTC, Zeyber submitted a review, later dismissed

2024-06-12 10:01 UTC, Zeyber requested changes
Please follow [these QA steps](https://github.com/SAP/spartacus/pull/18717#issuecomment-2049250540) changing the BRANCH variable to this one to make sure the behaviour is still correct.

2024-06-13 15:30 UTC, Pio-Bar commented
> Please follow [these QA steps](https://github.com/SAP/spartacus/pull/18717#issuecomment-2049250540) changing the BRANCH variable to this one to make sure the behaviour is still correct.

I've tried it and the tabbing order starts from the top of the page for 'selectedHostElement' set body.

2024-06-14 08:42 UTC, Zeyber approved these changes

2024-06-19 17:47 UTC, developpeurweb approved these changes

2024-06-21 08:47 UTC, merged