fix: Different aria-labels for un-/selected values for radio-buttons
SAP/spartacus pull request #19015
Opened 2024-06-28 13:41 UTC by steinsebastian

2024-07-02 09:27 UTC, Larisa-Staroverova approved these changes, later dismissed

2024-07-02 15:00 UTC, Uli-Tiger requested changes

2024-07-02 15:00 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/attribute/types/base/configurator-attribute-single-selection-base.component.ts
> +          })
@steinsebastian can you do me a favor to refactor the method,

- so there is only one call to the translation service. 
- that multi level if can be replacde by a simple if - else if - else if - else

2024-07-02 15:27 UTC, Uli-Tiger commented on feature-libs/product-configurator/rulebased/components/attribute/types/base/configurator-attribute-single-selection-base.component.ts
> +          })
see also: https://github.com/SAP/spartacus/pull/18997/files#r1662749706

2024-07-03 14:12 UTC, Uli-Tiger approved these changes

2024-07-10 11:43 UTC, merged