fix: (CXSPA-979) - Dialogs announcement JAWS fix
SAP/spartacus pull request #19071
Opened 2024-07-24 10:14 UTC by Pio-Bar

Ticket: [CXSPA-979](https://jira.tools.sap/browse/CXSPA-979)

Fixes a JAWS specific bug where the title page was announced while dialog was opened. By providing a label to the dialog container we hear it instead.

2024-07-24 13:34 UTC, Zeyber approved these changes, later dismissed

2024-07-30 20:50 UTC, developpeurweb commented on feature-libs/cart/saved-cart/components/saved-cart-form-dialog/saved-cart-form-dialog.component.html
> +    aria-labbeledby="dialogTitle"
small typo, it should read `aria-labelledby`

2024-07-30 20:51 UTC, developpeurweb commented on feature-libs/quote/components/confirm-dialog/quote-confirm-dialog.component.html
> +  aria-labelldby="dialogTitle"
small typo, it should read `aria-labelledby`

2024-07-30 21:07 UTC, developpeurweb requested changes
Small adjustments please:
1. Small typos were preventing the dialog from being identified.
2. For some reason, the "Add To Cart" dialog doesn't get identified as a dialog, it seems the focus lands one Tab away from the close button still trapped and narrating the page underneath. Once moving focus to the close button, the dialog gets identified. The ideal would be for the focus to move to the close button when opening, as with the other dialogs.

2024-08-02 11:40 UTC, Pio-Bar commented
The 'added to cart' dialog should no longer lose focus after the cart is updated and stay on the close button. Typos fixed, good catch ;)

2024-08-07 10:35 UTC, rmch91 approved these changes

2024-08-08 18:25 UTC, developpeurweb approved these changes

2024-08-09 10:57 UTC, merged