feat(a11y): Arrow keys navigation for carousel
SAP/spartacus pull request #19168
Opened 2024-08-27 20:20 UTC by sdrozdsap

JIRA Ticket: https://jira.tools.sap/browse/CXSPA-7970

2024-09-04 08:34 UTC, Zeyber requested changes

2024-09-04 08:34 UTC, Zeyber commented on projects/storefrontlib/shared/components/carousel/carousel.component.ts
> +  private focusNextPrevItem(
Lets make this at least `protected` instead of `private`.

2024-09-04 08:34 UTC, Zeyber commented on projects/storefrontlib/shared/components/carousel/focusable-carousel-item/focusable-carousel-item.directive.ts
> +@Directive({
Lets add some jsdoc comment here so that we can understand what this directive can do from the editor.

2024-09-04 08:34 UTC, Zeyber commented on projects/storefrontlib/shared/components/carousel/carousel.component.ts
> +  private focusNextPrevItem(
Also lets describe what should be the expected outcomes of this method.

2024-09-05 09:36 UTC, sdrozdsap commented on projects/storefrontlib/shared/components/carousel/carousel.component.ts
> +  private focusNextPrevItem(
Done

2024-09-05 09:36 UTC, sdrozdsap commented on projects/storefrontlib/shared/components/carousel/focusable-carousel-item/focusable-carousel-item.directive.ts
> +@Directive({
Done

2024-09-05 11:15 UTC, Zeyber approved these changes, later dismissed

2024-09-10 12:17 UTC, developpeurweb submitted a review, later dismissed

2024-09-12 08:13 UTC, Zeyber submitted a review, later dismissed

2024-09-13 07:56 UTC, Zeyber approved these changes

2024-09-13 07:57 UTC, merged