fix: (CXSPA-7948) add aria-labelledby to quantity input
SAP/spartacus pull request #19312
Opened 2024-10-01 09:52 UTC by StanislavSukhanov

* closes: https://jira.tools.sap/browse/CXSPA-7948

2024-10-01 14:17 UTC, Pio-Bar submitted a review, later dismissed

2024-10-02 07:19 UTC, Zeyber approved these changes, later dismissed

2024-10-09 23:51 UTC, developpeurweb requested changes
@StanislavSukhanov this didn't work for me on JAWS. Can you please try with **aria-describedby** and associate it to the input field. 
As per screenshot, I emulated it with the Chrome inspector and it seems to work well without interfering with the aria-label.

![aria-describedby](https://github.com/user-attachments/assets/51a9c2d6-2e04-4409-92bd-4de81633cd6f)

2024-10-11 10:51 UTC, Pio-Bar approved these changes

2024-10-16 07:00 UTC, Zeyber approved these changes

2024-10-16 19:14 UTC, developpeurweb approved these changes

2024-10-17 08:53 UTC, merged