fix: (CXSPA-8033) add aria hidden attribute to 'required' asterisks
SAP/spartacus pull request #19327
Opened 2024-10-03 09:29 UTC by StanislavSukhanov

* closes https://jira.tools.sap/browse/CXSPA-8033

2024-10-04 10:36 UTC, Pio-Bar requested changes
Let's just add the attribute to the `abbr`, otherwise you can enter the empty group in read mode. We need to make sure the information about the field being required is still included somewhere. 🤔

2024-10-04 10:36 UTC, Pio-Bar commented on feature-libs/user/account/components/login-form/login-form.component.html
> -</ng-template>
Good on you from cleaning it up, somebody must have left it here while removing the asterisks from the login page. 🤷

2024-10-07 10:00 UTC, StanislavSukhanov commented
@Pio-Bar fixed. The 'required' is still being narrated. It's being picked up by an inputs required attribute.

2024-10-07 11:18 UTC, Pio-Bar submitted a review, later dismissed

2024-10-07 12:43 UTC, Zeyber submitted a review, later dismissed

2024-10-11 20:05 UTC, developpeurweb commented
@StanislavSukhanov your solution works well on JAWS. Now, let's complete the auditor's full request, so please bring back the Login and Reset Password asterisk removed on CXSPA-7418 and **apply your solution there as well**. I have left a comment on that ticket explaining why we can't remove audited content.

2024-10-15 08:44 UTC, StanislavSukhanov commented
@developpeurweb It's done. Please have a look on that once again 🙏

2024-10-16 18:59 UTC, developpeurweb approved these changes

2024-10-17 16:13 UTC, merged