fix: (CXSPA-7992) Store, MyPreferredStoreComponent 'view hours button' icon contrast
SAP/spartacus pull request #19379
Opened 2024-10-10 09:29 UTC by StanislavSukhanov

* fixed an opacity of button's icon to meet a colour contrast requirement.

  * closes https://jira.tools.sap/browse/CXSPA-7992

2024-10-10 14:37 UTC, Pio-Bar requested changes

2024-10-10 14:37 UTC, Pio-Bar commented on projects/core/src/features-config/feature-toggles/config/feature-toggles.ts
> +  useSiteThemeService: true,
Should we leave this toggle on?

2024-10-10 21:04 UTC, StanislavSukhanov commented on projects/core/src/features-config/feature-toggles/config/feature-toggles.ts
> +  useSiteThemeService: true,
Hi @Pio-Bar. Thanks for pointing it out. Fixed.

2024-10-11 10:52 UTC, Pio-Bar approved these changes, later dismissed

2024-10-15 07:03 UTC, Zeyber approved these changes, later dismissed

2024-10-16 19:37 UTC, developpeurweb submitted a review, later dismissed

2024-10-17 09:56 UTC, Zeyber approved these changes

2024-10-17 09:57 UTC, merged