fix: (CXSPA-8048) - Remove narration of Updating Cart in AddedToCartDialog component
SAP/spartacus pull request #19380
Opened 2024-10-10 09:31 UTC by petarmarkov9449

Ticket: [CXSPA-8048](https://jira.tools.sap/browse/CXSPA-8048)

Remove narration of "Updating Cart ..." in AddedToCartDialog component

2024-10-10 15:21 UTC, Pio-Bar approved these changes, later dismissed

2024-10-11 06:28 UTC, Zeyber approved these changes, later dismissed

2024-10-16 18:44 UTC, developpeurweb commented
@petarmarkov9449 for some reason, it seems we have a regression here. As per screenshot, the current branch narrates the _Page Title_ as the dialog's title, as opposed to `develop` branch where the "Updating Cart" narration is set as the dialog's title. 

**Both are inaccurate.** The narration of the dialog's title must match whatever is visible as the dialog's title. E.g.,
- Visible: "Item(s) added to your cart" = Narration: "Item(s) added to your cart **_dialog_**"
- Visible: "This item was already in your cart. The quantity was updated" = Narration: "This item was already in your cart. The quantity was updated **_dialog_**"

Basically, if hidden narrations such as "Loading..." or "Updating Cart..." are getting in the way of matching the visible title with audible one, then please remove those hidden narrations.

![current branch](https://github.com/user-attachments/assets/7495febe-9925-4dad-bd72-d65d58eaa118)
m.
![develop](https://github.com/user-attachments/assets/406ec370-347e-4d5b-bf31-50bb6fe6cef3)

2024-10-16 18:47 UTC, developpeurweb requested changes
Visual and Audible Dialog's Title should match. Please see previous comments and screenshots.

2024-10-30 15:27 UTC, developpeurweb submitted a review, later dismissed

2024-10-30 15:28 UTC, developpeurweb commented
@petarmarkov9449 Works well now. Please have a developer approve your latest code changes. Thanks!

<img width="1538" alt="8048 fixed" src="https://github.com/user-attachments/assets/0743d54a-c0bc-495b-a3d6-9e3801d49588">

2024-10-31 09:14 UTC, Pio-Bar requested changes

2024-10-31 09:14 UTC, Pio-Bar commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.html
> +        <div class="col-sm-12" *cxFeature="'a11yUpdatingCartNoNarration'">
We don't consider the use of aria attributes breaking. 🙂

2024-10-31 09:14 UTC, Pio-Bar commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
> +        { provide: FeatureConfigService, useClass: MockFeatureConfigService },
Is there a reason to provide this service? It doesn't look like it is used in the component.
Since the MockFeatureDirective is already declared that should cover your new feature flag in the template.

2024-10-31 09:14 UTC, Pio-Bar commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
> -    expect(el.query(By.css('cx-spinner')).nativeElement).toBeDefined();
Are we no longer testing for the spinner presence? It looks like its still displayed?

2024-10-31 09:14 UTC, Pio-Bar commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
> +  it('should shouw item added to your cart dialog title message in case a11yUpdatingCartNoNarration is enabled', () => {
We only test the feature with the feature flag enabled, since the change will eventually become permanent. Let's test it as if it already were.

2024-10-31 11:00 UTC, petarmarkov9449 commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
> +  it('should shouw item added to your cart dialog title message in case a11yUpdatingCartNoNarration is enabled', () => {
I've just updated it.

2024-10-31 14:15 UTC, petarmarkov9449 commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
> -    expect(el.query(By.css('cx-spinner')).nativeElement).toBeDefined();
I've just updated it.

2024-10-31 14:15 UTC, petarmarkov9449 commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.spec.ts
> +        { provide: FeatureConfigService, useClass: MockFeatureConfigService },
I've just updated it.

2024-10-31 14:15 UTC, petarmarkov9449 commented on feature-libs/cart/base/components/added-to-cart-dialog/added-to-cart-dialog.component.html
> +        <div class="col-sm-12" *cxFeature="'a11yUpdatingCartNoNarration'">
I've just updated it.

2024-11-04 08:53 UTC, Pio-Bar approved these changes

2024-11-05 07:39 UTC, Zeyber approved these changes

2024-11-05 19:45 UTC, developpeurweb approved these changes

2024-11-06 17:31 UTC, merged