feat(a11y): add aria-label attribute to payment card graphics for Payment Details cards
SAP/spartacus pull request #19404
Opened 2024-10-16 08:39 UTC by uroslates

2024-10-16 08:46 UTC, uroslates commented
Closes  https://jira.tools.sap/browse/CXSPA-8197

2024-10-16 15:17 UTC, Pio-Bar submitted a review, later dismissed

2024-10-17 08:58 UTC, Zeyber submitted a review, later dismissed

2024-10-29 15:11 UTC, developpeurweb commented
@uroslates let's please make some adjustments:

1. It seems Maestro and Switch cards were attributed a generic aria-label as "Credit Card" this won't pass the audit since it doesn't communicate the credit card brand to screen reader users, making the interaction harder. Please match alt text with the specific card brands even if the logo is generic.
2. Please update "Master Card" as "Mastercard Card"
3. Please differentiate the regular Mastercard from "Mastercard Eurocard Card", they currently have the same alt text.
4. Please don't forget to add tooltip for each card as requested in the ticket.

![generic credit card and missing tooltip](https://github.com/user-attachments/assets/443d65ca-9443-41b6-88d3-9affa00b03db)

![add tooltips](https://github.com/user-attachments/assets/36118af2-2a2b-4b13-ac0a-a5e8c544f795)

2024-10-29 15:11 UTC, developpeurweb requested changes
See previous comment for details.

2024-10-31 15:47 UTC, developpeurweb approved these changes

2024-11-05 10:13 UTC, merged