fix: clear persisted focus on entering configuration
SAP/spartacus pull request #19413
Opened 2024-10-18 12:01 UTC by steinsebastian

CXSPA-8638

2024-10-18 15:54 UTC, Uli-Tiger approved these changes, later dismissed
lgtme

2024-10-21 11:46 UTC, Larisa-Staroverova requested changes
@steinsebastian, could you, please, rename the instance?
Otherwise, it looks really good.

2024-10-21 11:46 UTC, Larisa-Staroverova commented on feature-libs/product-configurator/rulebased/components/form/configurator-form.component.ts
> +  protected focusService = inject(KeyboardFocusService);
Please, change the name of the instance to `keyboardFocusService`

2024-10-22 09:25 UTC, steinsebastian commented on feature-libs/product-configurator/rulebased/components/form/configurator-form.component.ts
> +  protected focusService = inject(KeyboardFocusService);
Done.

2024-10-23 13:17 UTC, Larisa-Staroverova approved these changes

2024-10-23 13:28 UTC, merged