Fix accessibility issue
SAP/spartacus pull request #19518
Opened 2024-11-08 06:58 UTC by Jali-Khusi

2024-11-25 07:00 UTC, vigneshkrish8691 submitted a review, later dismissed

2024-12-19 16:40 UTC, Pio-Bar requested changes
These changes would be considered breaking. We should put them behind a feature toggle like other a11y ones. They can be recognized by the `a11y` prefix we include for each one.

2024-12-19 16:40 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +<nav [attr.aria-label]="navAriaLabel" [attr.role]="'navigation'">
The semantic `nav` element makes the use of `role` attribute redundant. It provides the same result.

2024-12-19 16:40 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +      <button (click)="back()" [attr.aria-label]="'common.back' | cxTranslate">
The back button already has proper text inside it. There is no benefit to give it the same text as a label.

2024-12-19 16:40 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> -        (keydown.esc)="back()"
Removing this call without an alternative would result in keyboard controls being negatively affected.

2024-12-19 16:40 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +        <span role="presentation" *ngIf="node.title" [attr.tabindex]="0">
This text is used as a heading for the following elements and should be recognized as one. Giving it a role of `presentation` would hide it from a11y software, which is not allowed for elements that convey information visible on the screen.

Elements that cannot be interacted with directly should not have tabindex of 0

2024-12-19 16:40 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +          flyout && (node?.children?.length ?? 0) > 1 ? 'presentation' : 'list'
The `presentation` role would hide the list from a11y software.

2024-12-19 16:40 UTC, Pio-Bar commented on projects/storefrontstyles/scss/components/content/navigation/_my-account-v2-navigation.scss
> +  }
- We may need to keep these within the component's scope. 
- There should be a better way to overwrite these styles then using the nuclear option of `!important`.
- We probably should stick to the breakpoints established by Spartacus already.

2025-01-08 11:25 UTC, Pio-Bar requested changes
Some of my older concerns are still valid, Please let me know if you have any doubts, thanks.

2025-01-08 11:25 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
>            {{ node.title }}
- The `aria-label` is unnecessary since the element itself contains the exact same text.
- I think this element was meant as a heading displaying the nodes title. Are we getting rid of that extra information?
- Tabbing order changes may affect the keyboard controls of the navigation. Are we giving focus to just a pice of text? Does not look like it's intractable.

2025-01-08 11:25 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +          flyout && (node?.children?.length ?? 0) > 1 ? 'list' : null
Do we want the role to be blank for non flyout navigation? I think it can still contain list items?

2025-01-08 11:40 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> -                  listLength,
Having a proper list count is one of the requirements we need to meet. Let's make sure it's preserved where needed.
https://jira.tools.sap/browse/CXSPA-8035

2025-01-08 11:41 UTC, Pio-Bar commented on projects/assets/src/translations/en/common.json
> +    "mainNavigation": "Main Navigation"
Seems like the uses of some of these have been removed. We don't need them probably

2025-01-09 04:53 UTC, Jali-Khusi commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> -                  listLength,
Thank you for the feedback. Regarding the JIRA ticket https://jira.tools.sap/browse/CXSPA-7979 , I addressed the issue where additional information like "list with 1 item, list with 3 items" was being read out when accessing the ‘Saved Carts’ list item within the ‘Order Information’ group. I’ve updated the aria-label to ensure only relevant information is announced, removing redundant details. The list count is preserved as needed, but without unnecessary repetition for screen readers.

2025-01-09 09:17 UTC, Jali-Khusi commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
>            {{ node.title }}
The issue was that group labels like "Order Information" and "Account Information" were not being read when accessing the list items within their respective groups. To resolve this, I updated the tabindex to 0 to ensure these group labels are focusable and properly announced.

I also removed role="heading" and aria-level="4" to avoid unnecessary additional information being read out by screen readers

https://jira.tools.sap/browse/CXSPA-7980

2025-01-14 12:35 UTC, Pio-Bar requested changes
I do have concerns about some of the changes being made to the `navigation-ui` component. This component is reused within Spartacus for quite important features like the main navigation. We should be especially careful modifying it since the changes impact other implementations. Some a11y improvements have been made already and if we are going to introduce new ones they can't be to the detriment of the existing ones.

I've brought to attention that some of these changes are considered breaking. We need to properly handle those by using feature flags, this mitigates any possible problems our clients might face. More information can be found on the wiki and here is a nice writeup about the new FF system for CSS changes.

Feel free to reach out to me directly or any a11y team members for help!

2025-01-14 12:35 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> -                  listLength,
The removed translation seems not to be related to the one mentioned in the ticket. ("list with 1 item, list with 3 items"). Each option should include its count within the list ( _n_ of _n options_). However, if this case is different an exception would need to be made for it. We cannot remove this from other implementations as this is a functionality we need to upkeep.

2025-01-14 12:35 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> -            aria-level="4"
If the role is set `heading` we need to specify the level too.

2025-01-14 12:35 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> -        >
These attributes are required by the main navigation in the header and provide a good a11y experience for that use case. We need to satisfy both cases, we cannot remove one in favour of the other.

2025-01-14 12:35 UTC, Pio-Bar commented on projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss
> -        margin-bottom: 10px;
I am afraid these changes will influence the look of other implementations as well.

2025-01-14 12:35 UTC, Pio-Bar commented on projects/storefrontstyles/scss/layout/page-templates/_myaccount-v2-page.scss
> +    max-width: 26% !important;
We should not use the `!important` to override styles.

2025-01-16 09:41 UTC, Jali-Khusi commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> -        >
Hi @Pio-Bar 
Thank you for your message. As per my understanding, I have implemented the changes accordingly. Could you kindly suggest if there is an alternative approach I could take that would allow me to make adjustments without affecting the current functionality?

2025-01-23 19:30 UTC, Jali-Khusi commented on projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss
> -        margin-bottom: 10px;
I removed the margin-top: 10px; and margin-bottom: 10px; because they were causing some unwanted gaps between the list items. If you'd prefer, I can revert this change
![gap-list](https://github.com/user-attachments/assets/e812c37c-b92a-41d0-87b7-84dda40b882b)

2025-01-24 09:45 UTC, Pio-Bar requested changes

2025-01-24 09:45 UTC, Pio-Bar commented on projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss
> -        margin-bottom: 10px;
Here is screenshot from the current `bugs-acc-issue` branch. If we remove the margins the main navigation will shift. 

I understand this fixes the issue for this particular case. At the same time we can not break other implementations. These changes should be kept within the affected component.

<img width="1426" alt="Screenshot 2025-01-24 at 10 17 39" src="https://github.com/user-attachments/assets/a7c3bbd0-de04-4306-9ac8-67d11bbd3bba" />

2025-01-24 09:45 UTC, Pio-Bar commented on projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss
> +  display: contents;
This is a significant change, not sure why flex would be overwritten here. This will surely affect the layout.

<img width="1477" alt="image" src="https://github.com/user-attachments/assets/9a4e9520-be08-47aa-a6f3-7497abc1a697" />

2025-02-04 12:13 UTC, Pio-Bar requested changes

2025-02-04 12:13 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/myaccount/my-account-v2/my-account-v2-navigation/my-account-v2-navigation.component.ts
> +}
Changing the CMS data would modify the outcome of the logic based on this. If the name was added the count would be present too. It's probably not what we want. 

We should not use a hard coded string for comparison.

2025-02-04 12:13 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +          navAriaLabel !== ('navigation.myAccountSideNavigation' | cxTranslate)
We probably should not base logic on a translation. Maybe we can include `provideOptionCount` input set to `true` by default. This way we would have an easy way to disable the option count where needed.

2025-02-04 12:13 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +          "
Should the title be stripped of its semantic value? As mentioned previously, role `presentation` hides the element from accessibility software. [In this case it's ignored because the](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role#:~:text=Browsers%20ignore%20role%3D%22presentation%22%20and%20role%3D%22none%22%20on%20focusable%20elements%2C%20including%20link%20and%20inputs%2C%20or%20anything%20with%20a%20tabindex%20attribute%20set.) tab index is 0. If these are a11y improvements, the intention here is not clear to me. Are we reducing the title to just a pice of text in this case?

2025-02-14 05:35 UTC, suprishi commented
Hi @Pio-Bar, I've renamed the input variable to a generic name `a11yOptionCount` and also added the documentation for it and set its default value to `false` in `NavigationUIComponent`. And the issues addressed in this PR are implemented conditionally so that they do not impact wherever they are reused.
Please have a look again and let me know if any additional changes are required.

2025-02-14 16:45 UTC, Pio-Bar requested changes

2025-02-14 16:45 UTC, Pio-Bar commented on projects/assets/src/translations/en/common.json
> +
```suggestion

```

2025-02-14 16:45 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.html
> +          [attr.tabindex]="a11yOptionCount ? 0 : -1"
Is the title getting focus relevant to the option count? What if a developer only needs to disable the count itself? We should avoid a side effect here. Making the title intractable should be a separate toggle.

2025-02-14 16:45 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.ts
> +  @Input() a11yOptionCount: boolean = false;
Looks like the code actually disabling the option count has been removed within [this commit](https://github.com/SAP/spartacus/pull/19518/commits/924374ae933f9d46348329c5ef0db6ff9e83984b). Is that part no longer relevant? If so, setting up `a11yOptionCount` input might not be needed anymore.

2025-02-14 16:45 UTC, Pio-Bar commented on projects/storefrontstyles/scss/components/content/navigation/_navigation-ui.scss
> +  width: 100%;
Some changes might be considered breaking. I have mentioned this in the PR comments previously. See [here](https://github.com/SAP/spartacus/pull/19518#pullrequestreview-2549576614) for more information.

2025-02-17 14:53 UTC, Pio-Bar requested changes

2025-02-17 14:53 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/myaccount/my-account-v2/my-account-v2-navigation/my-account-v2-navigation.component.ts
> +}
```suggestion
export class MyAccountV2NavigationComponent extends NavigationComponent {}
```

Looks like this variable does not have a purpose, we should be able to remove it.

2025-02-17 14:53 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/myaccount/my-account-v2/my-account-v2-navigation/my-account-v2-navigation.component.html
> +  [a11yIntraceableNavSectionTitle]="isMyAccount"
```suggestion
  [a11yIntraceableNavSectionTitle]="true"
```

2025-02-17 14:53 UTC, Pio-Bar commented on projects/storefrontlib/cms-components/navigation/navigation/navigation-ui.component.ts
> +  @Input() a11yIntraceableNavSectionTitle: boolean = false;
```suggestion
  /**
   * Include non intractable node titles within the tabbing order. 
   */
  @Input() focusableNodeTitles: boolean = false;
```

Let's remove the typo from the input name. We should make our intentions more clear.

2025-02-17 16:03 UTC, Pio-Bar approved these changes

2025-02-17 17:04 UTC, merged