fix: style Get Directions link as link
SAP/spartacus pull request #19520
Opened 2024-11-11 09:42 UTC by uroslates

Closes https://jira.tools.sap/browse/CXSPA-8814

2024-11-12 16:32 UTC, Pio-Bar requested changes

2024-11-12 16:32 UTC, Pio-Bar commented on feature-libs/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
> -      class="btn btn-sm btn-secondary btn-block cx-button"
A small change, but I think it's still considered breaking. Let's use a feature flag here.

2024-11-13 11:16 UTC, uroslates commented on feature-libs/storefinder/components/store-finder-list-item/store-finder-list-item.component.html
> -      class="btn btn-sm btn-secondary btn-block cx-button"
Should be addressed. Added new feature flag for these kind of changes.

2024-11-13 15:18 UTC, Pio-Bar requested changes

2024-11-13 15:18 UTC, Pio-Bar commented on projects/core/src/features-config/feature-toggles/config/feature-toggles.ts
> +  a11yStyleExternalLinksAsLinks: true,
New feature flags need to be turned off by default for the first 6 months.

2024-11-13 16:03 UTC, uroslates commented on projects/core/src/features-config/feature-toggles/config/feature-toggles.ts
> +  a11yStyleExternalLinksAsLinks: true,
OK thanks for the info. Should be updated now!

2024-11-14 11:00 UTC, Pio-Bar approved these changes

2024-11-14 14:40 UTC, Zeyber approved these changes

2024-11-14 21:06 UTC, developpeurweb approved these changes

2024-11-15 12:39 UTC, merged