fix: make form required fields * red
SAP/spartacus pull request #19679
Opened 2024-12-02 10:58 UTC by uroslates

Closes: https://jira.tools.sap/browse/CXSPA-8992

2024-12-02 13:08 UTC, Zeyber approved these changes, later dismissed

2024-12-02 13:45 UTC, Pio-Bar requested changes

2024-12-02 13:45 UTC, Pio-Bar commented on projects/storefrontstyles/scss/cxbase/blocks/forms.scss
> +  abbr[title='required'] {
Should we tie the translation with the selector? Wouldn't changing the language stop the asterisks from being red?

2024-12-02 23:27 UTC, developpeurweb commented
@uroslates please address Piotr's comment and reassign to me.

2024-12-03 09:35 UTC, uroslates commented on projects/storefrontstyles/scss/cxbase/blocks/forms.scss
> +  abbr[title='required'] {
Good catch! Didn't noticed! Should be addressed now.

2024-12-03 11:41 UTC, Pio-Bar approved these changes

2024-12-03 11:53 UTC, Zeyber approved these changes

2024-12-03 21:06 UTC, developpeurweb approved these changes

2024-12-04 11:28 UTC, merged