fix: (CXSPA-9059) - Quick order searchbox refocus
SAP/spartacus pull request #19695
Opened 2024-12-03 13:22 UTC by Pio-Bar

Closes: [CXSPA-9059](https://jira.tools.sap/browse/CXSPA-9059)

2024-12-04 11:47 UTC, Zeyber requested changes

2024-12-04 11:47 UTC, Zeyber commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +        setTimeout(() => {
Should we use `requestAnimationFrame` instead here?

2024-12-04 17:01 UTC, Pio-Bar commented on feature-libs/cart/quick-order/components/quick-order/form/quick-order-form.component.ts
> +        setTimeout(() => {
Switched to `requestAnimationFrame` 😉

2024-12-05 09:32 UTC, Zeyber approved these changes, later dismissed

2024-12-05 18:17 UTC, developpeurweb approved these changes, later dismissed

2024-12-19 09:55 UTC, sdrozdsap approved these changes

2024-12-19 12:12 UTC, merged