Fix/for guest cart
SAP/spartacus pull request #19712
Opened 2024-12-04 15:16 UTC by rmch91

2025-02-06 10:14 UTC, Matejk00 requested changes

2025-02-06 10:14 UTC, Matejk00 commented on integration-libs/opf/checkout/components/opf-checkout-login/opf-checkout-login.module.ts
> +          component: OpfCheckoutLoginComponent,
Actually, this component is more about setting up an email during the checkout process, not to create any authentication itself.
What do you think to re-phrase the name to `OpfCheckoutEmailUpdateComponent`?

2025-02-06 10:14 UTC, Matejk00 commented on integration-libs/opf/checkout/components/opf-checkout-login/opf-checkout-login.module.ts
> +        OpfCheckoutLoginComponent: {
The same for a sample-data.

2025-02-06 10:14 UTC, Matejk00 commented on integration-libs/opf/checkout/root/config/default-opf-checkout-routing-config.ts
> +        paths: ['opf-checkout-login'],
Following the name change suggestion, we should also change a route, maybe to "/opf-checkout-email"?

2025-02-06 10:14 UTC, Matejk00 commented on integration-libs/opf/checkout/root/services/opf-cart-user-email-checker.service.ts
> +      .pipe(map((value) => value.sapCustomerEmail !== 'demo@example.com'));
As you wrote, this should be replaced by the backend response, so this placeholder hardcoded part ('demo@example.com') will be removed?

2025-02-06 10:14 UTC, Matejk00 commented on projects/core/src/features-config/feature-toggles/config/feature-toggles.ts
> +  opfEnablePreventingFromCheckoutWithoutEmail: false,
Should we hide it behind a feature flag? I thought that is rather a bugfix. Also this flag is related to the OPF integration, so in my opinion default feature toggles data set in SPA core should know nothing about OPF.

2025-02-06 10:14 UTC, Matejk00 commented on integration-libs/opf/checkout/root/сheckout-guard/opf-checkout-auth.guard.ts
> +   * - If the guest user **does not have an email**, they are redirected to the OPF checkout login page.
"they are redirected to the OPF checkout email update page".

2025-02-06 13:06 UTC, rmch91 commented on integration-libs/opf/checkout/root/services/opf-cart-user-email-checker.service.ts
> +      .pipe(map((value) => value.sapCustomerEmail !== 'demo@example.com'));
Yes, it will be changed when the backend will be ready

2025-02-06 13:45 UTC, rmch91 commented on projects/core/src/features-config/feature-toggles/config/feature-toggles.ts
> +  opfEnablePreventingFromCheckoutWithoutEmail: false,
From a purely technical perspective, this is a breaking change. Theoretically, a user could have encountered this issue, created some custom routing interceptor, forced the user to enter an email on their side, added additional logic, or introduced some side effects and because of our change, all his stuff will not run. What's the probability that it is true? – 0.1%. Should we be that precise? – An open question, especially in the case of OPF.

If to talk about place where it is defined, I think that we are defining all toggle in one place, you can check that there are also different feature toggles related to feature/integration libs like product configurator, trending searches etc.

2025-02-06 13:46 UTC, rmch91 commented on integration-libs/opf/checkout/components/opf-checkout-login/opf-checkout-login.module.ts
> +          component: OpfCheckoutLoginComponent,
Thanks, changed

2025-02-06 13:46 UTC, rmch91 commented on integration-libs/opf/checkout/components/opf-checkout-login/opf-checkout-login.module.ts
> +        OpfCheckoutLoginComponent: {
Changed

2025-02-06 13:46 UTC, rmch91 commented on integration-libs/opf/checkout/root/config/default-opf-checkout-routing-config.ts
> +        paths: ['opf-checkout-login'],
Thanks, changed

2025-02-06 13:46 UTC, rmch91 commented on integration-libs/opf/checkout/root/сheckout-guard/opf-checkout-auth.guard.ts
> +   * - If the guest user **does not have an email**, they are redirected to the OPF checkout login page.
Thanks, changed

2025-02-07 09:12 UTC, Matejk00 submitted a review, later dismissed

2025-04-04 11:51 UTC, Matejk00 approved these changes
LGTM

2025-04-04 11:55 UTC, merged