CXSPA-8566 bug fix
SAP/spartacus pull request #19779
Opened 2024-12-13 15:27 UTC by suprishi

https://jira.tools.sap/browse/CXSPA-8566

returning `undefined` if `intendedLocation.displayName` is not defined, so that pickup option is reset when navigating between 2 products.

2024-12-23 07:02 UTC, Matejk00 requested changes

2024-12-23 07:02 UTC, Matejk00 commented on feature-libs/pickup-in-store/components/container/pdp-pickup-options-container/pdp-pickup-options-container.component.ts
> +      switchMap(({ intendedLocation, productCode }) => {
What do you think about this change proposal?

```
switchMap(({ intendedLocation, productCode }) => {
  if (intendedLocation?.displayName) {
    this.displayNameIsSet = true;
    return of(getProperty(intendedLocation, 'displayName'));
  }

  this.setIntendedPickupLocation(productCode);
  return of(undefined);
})
```

The use of optional chaining (?.) simplifies the null checks and removing the double negation (!!) makes the condition cleaner. Also, dropping the unnecessary else block aligns well with an early return pattern. I think it is improving readability.

2024-12-23 07:02 UTC, Matejk00 commented on feature-libs/pickup-in-store/components/container/pdp-pickup-options-container/pdp-pickup-options-container.component.ts
> +      .subscribe((storeDetails) => {
Shouldn't we unsubscribe this subscription somewhere? I am not sure if it not cause a potential memory leaks.

2025-01-06 06:03 UTC, suprishi commented on feature-libs/pickup-in-store/components/container/pdp-pickup-options-container/pdp-pickup-options-container.component.ts
> +      switchMap(({ intendedLocation, productCode }) => {
Agreed, I've updated the code as per your proposal.

2025-01-06 06:04 UTC, suprishi commented on feature-libs/pickup-in-store/components/container/pdp-pickup-options-container/pdp-pickup-options-container.component.ts
> +      .subscribe((storeDetails) => {
I've added this to the list of subscriptions which get unsubscribed within `ngOnDestroy()`.

2025-01-07 07:43 UTC, Matejk00 approved these changes

2025-01-07 08:08 UTC, merged