fix: test and fix dialogs affected by the removal of extended bootstrap clasees
SAP/spartacus pull request #19803
Opened 2024-12-23 14:35 UTC by Pio-Bar

Closes: https://jira.tools.sap/browse/CXSPA-9185

Removes commented out `@extend` rules and get rids of the remaining ones. I've manually tested each affected dialog and made sure it displays as expected.

2025-01-02 15:08 UTC, kpawelczak requested changes

2025-01-02 15:08 UTC, kpawelczak commented on feature-libs/user/profile/styles/_close-account-modal.scss
> -      .cx-close-account-modal-body {
I cant find it in the diff. Did you remove the class from the HTML?

2025-01-02 15:08 UTC, kpawelczak commented on feature-libs/user/profile/styles/_suggested-addresses-dialog.scss
> -      .cx-suggested-addresses-body {
Should we remove `cx-suggested-addresses-body` from the html?

2025-01-07 12:20 UTC, Pio-Bar commented on feature-libs/user/profile/styles/_close-account-modal.scss
> -      .cx-close-account-modal-body {
Removed after changes

2025-01-07 12:21 UTC, Pio-Bar commented on feature-libs/user/profile/styles/_suggested-addresses-dialog.scss
> -      .cx-suggested-addresses-body {
Removed the class from the HTML too.

2025-01-07 12:39 UTC, kpawelczak approved these changes

2025-01-07 12:43 UTC, merged