feat: reusable keyboard focus directieas
SAP/spartacus pull request #6867
Opened 2020-03-10 14:14 UTC by tobi-or-not-tobi

closes #6866

2020-03-11 14:25 UTC, LTiger14 requested changes

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/base/base-focus.directive.ts
> + * - Trap Focus
Missing Block Focus

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/persist/persist-focus.directive.ts
> + * The focus key is peristed on the focus element, so that
A part of the sentence is missing

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/escape/escape-focus.service.ts
> +        // if (config.initialTabindex && config.initialTabindex !== -1) {
You can remove this

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/autofocus/auto-focus.service.ts
> +   * The
You don't need the `The` here

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/autofocus/auto-focus.service.spec.ts
> +  describe('findFirstFocusable', () => {
Could you add a case for the config as a string but not host? Just out of curiosity.

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/tab/tab-focus.service.ts
> +    increment: number,
Should this type be `MOVE_FOCUS`?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/tab/tab-focus.service.ts
> +  // considering dropping the config or tab
Was this comment meant for you?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/tab/tab-focus.service.ts
> +    let index = this.getChilds(host, config)?.findIndex(tab =>
I am not sure I understand why we have so many `getChilds`

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/tab/tab-focus.service.ts
> +  protected getChilds(
This should be `getChildren`

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/trap/trap-focus.service.ts
> +  hasFocusableChilds(host: HTMLElement): boolean {
Should be `hasFocusableChildren`

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +  // @Output() unlock = new EventEmitter<boolean>();
You can remove this

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +      // this.unlock.emit(!this.hasbeenUnlocked);
This too

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +    if (this.isLocked && !this.hasFocusableChilds) {
Why does it not need to have focusable children to unlock?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +    if (!!this.group) {
Could you double check all your comments in this function

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +  protected addTabindexToChilds(index = 0): void {
Should be `addTabIntedToChildren`

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +  private get hasFocusableChilds(): boolean {
Should be `hasFocusableChildren`

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.service.spec.ts
> +    <div id="a"></div>
Do you really need all of this?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/trap/trap-focus.service.ts
> +      // TODO: evalute if this is required
Is this for future reference?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/keyboard-focus.module.ts
> +  // providers: [{ provide: KEYBOARD_FOCUS_TOKEN, useValue: { focus } }],
Can this be removed?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.ts
> +    `textarea`,
Why isn't text area a string?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.ts
> +    // TODO: consider dopping the not-hidden
Todo for later?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.ts
> +export abstract class SelectFocusUtility {
Why is it abstract?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/keyboard-focus.model.ts
> +  lock?: boolean; // we used to have string as well...
Should we have a string as well or adjust the comment?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/trap/trap-focus.service.spec.ts
> +      describe('trap focus on last element', () => {
Shouldn't you add a test here for trap = 'end'?

2020-03-11 14:25 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/trap/trap-focus.service.spec.ts
> +      describe('trap focus on first element', () => {
Shouldn't you add a test here for trap = 'start'

2020-03-11 15:38 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/autofocus/auto-focus.service.spec.ts
> +  describe('findFirstFocusable', () => {
it's a CSS selector, so you can autofocus a specific DOM element, i.e. `button:nth-child(4)` or `div.section > button[submit]`.

2020-03-11 15:42 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/tab/tab-focus.service.ts
> +  // considering dropping the config or tab
can't recall. have dropped it.

2020-03-11 15:52 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +    if (this.isLocked && !this.hasFocusableChilds) {
if the group is locked, but there are no focusable child element, there's not much we can do.

2020-03-11 16:34 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.service.spec.ts
> +    <div id="a"></div>
nooooo

2020-03-11 16:34 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/keyboard-focus.module.ts
> +  // providers: [{ provide: KEYBOARD_FOCUS_TOKEN, useValue: { focus } }],
that's outdated code

2020-03-11 16:34 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.ts
> +    // TODO: consider dopping the not-hidden
I had to talk it through with Caine, which I did.

2020-03-11 16:38 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/keyboard-focus.model.ts
> +  lock?: boolean; // we used to have string as well...
I've dropped the comment, we do not have a css selector for locking. I don't think we need it now, it might come back.

2020-03-11 18:11 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/trap/trap-focus.service.ts
> +      // TODO: evalute if this is required
nope, it's gone now

2020-03-12 16:36 UTC, LTiger14 requested changes

2020-03-12 16:36 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +        .forEach(el =>
Build is failing because el is not used

2020-03-12 17:10 UTC, LTiger14 approved these changes

2020-03-12 17:25 UTC, merged

2020-03-18 07:32 UTC, tobi-or-not-tobi commented
QA
- we will QA these features with specific features.