autofocus will no longer force the focus when the user clicks anywhere on the screen
SAP/spartacus pull request #6965
Opened 2020-03-18 10:32 UTC by tobi-or-not-tobi

fixes #6964

2020-03-19 14:00 UTC, marlass requested changes
With the public API change build fails.

2020-03-19 14:00 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/skip-link/service/skip-link.service.ts
> +    const hasTabindex = target.hasAttribute('tabindex');
Why we check `target` element instead of `firstFocusable`?

2020-03-19 14:00 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts
> +  @HostBinding('class.mouse-focus') visibleFocus = false;
Imo: `mouseFocus` fitted better. Often the mouseFocus is not visible, yet here it is reversed,

2020-03-19 14:00 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts
> +  ngOnInit() {
Can we remove it?

2020-03-19 14:00 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.spec.ts
> +      <button id="d2" disabled>focusable</button>
Did you meant to use `hidden` attribute?

2020-03-19 14:00 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.spec.ts
> +    <div id="e">
Did you want to use this div for some tests?

2020-03-19 14:00 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/index.ts
> +// export * from './services/index';
This one can actually be removed here
```suggestion
```

2020-03-19 14:20 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/skip-link/service/skip-link.service.ts
> +    const hasTabindex = target.hasAttribute('tabindex');
good spot! That's indeed wrong, as we moved to firstFocusable (which might be the target though).

2020-03-19 16:36 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.spec.ts
> +    <div id="e">
I did, but changed my mind. I'll remove it now.

2020-03-19 16:36 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/services/select-focus.util.spec.ts
> +      <button id="d2" disabled>focusable</button>
yup ;) thx

2020-03-20 07:26 UTC, marlass submitted a review, later dismissed

2020-03-20 07:26 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/visible/visible-focus.directive.ts
> +  implements OnInit {
nit: We could drop `OnInit` here

2020-03-20 07:26 UTC, marlass commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/index.ts
>  export * from './keyboard-focus.model';
Do we want to export in public API all interfaces or only `FocusConfig`?

2020-03-20 07:35 UTC, marlass submitted a review, later dismissed

2020-03-20 08:31 UTC, marlass approved these changes

2020-03-20 09:00 UTC, merged