Shipping address checkout page missing Set as default checkbox (GH-7153)
SAP/spartacus pull request #7223
Opened 2020-04-08 21:00 UTC by qjimmy

Closes GH-7153

- change was made on line 54
- prettier automatically removes ending commas for object properties for some reason

<hr />

should have no checkbox with guest checkout:
<img width="942" alt="Screen Shot 2020-04-08 at 4 45 26 PM" src="https://user-images.githubusercontent.com/30666844/78832998-2e8b9900-79ba-11ea-9710-d978f57c700b.png">

<hr />

should have checkbox if not guest checkout:
<img width="670" alt="Screen Shot 2020-04-08 at 4 54 14 PM" src="https://user-images.githubusercontent.com/30666844/78833014-32b7b680-79ba-11ea-94a6-a0d4ec68fce9.png">

2020-04-09 19:36 UTC, bgambocjaviniar commented
I think you need to fix your prettier first

you can do so, with the following

upgrade manually, and do the following steps Stan provided

or 

go to develop, git pull, delete node modules, and install the new versions from the updated package.json. (fastest is to just clone a new one and install a fresh one :')) haha

2020-04-30 20:25 UTC, LTiger14 requested changes
I can see the “Set as default” checkbox is only visible if you don’t already have a saved address. I you click add an address there is no checkbox. From the ticket it seems there should be a checkbox even for the “Add new address”.

2020-05-04 19:28 UTC, LTiger14 requested changes
Upon submit the request to add a new address I get this console error.
<img width="646" alt="Screen Shot 2020-05-04 at 3 26 40 PM" src="https://user-images.githubusercontent.com/10605724/81005412-ea09e680-8e1b-11ea-9dde-f7b81d17c0e0.png">
 Not just in your branch but also develop. This is not part of this issue. See if it's a quick thing that could be included in this PR. If not please open an issue.

2020-05-04 19:28 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
> +    private fb: FormBuilder,
These should be protected

2020-05-04 19:28 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
> +    if (this.addressForm.controls['region'].value.isocode) {
Why did you remove the check for `this.addressForm.valid`?

2020-05-04 19:28 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
> +    if (this.addressForm.controls['region'].value.isocode) {
Why did you change `this.addressForm.get('region').value.isocode` to `this.addressForm.controls['region'].value.isocode`? The get seems cleaner

2020-05-04 19:28 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
> +    defaultAddress: [false],
This change is not required and should be left out to keep a cleaner diff.

2020-05-04 19:28 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/checkout/components/shipping-address/address-form/address-form.component.ts
> +    country: this.fb.group({
This is also not required.

2020-05-04 20:17 UTC, LTiger14 approved these changes

2020-05-04 20:40 UTC, merged