feat: Fix Storefinder Radius and make configurable
SAP/spartacus pull request #7252
Opened 2020-04-14 13:48 UTC by Zeyber

Closes: #6275

2020-04-16 09:49 UTC, Pucek9 reviewed
Hard to do local QA (You are using this API without a key. See http://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors)

2020-04-16 09:49 UTC, Pucek9 requested changes
Please use `yarn prettier:fix` because of problems here:
projects/core/src/store-finder/config/default-store-finder-config.ts
projects/core/src/store-finder/connectors/store-finder.adapter.ts
projects/core/src/store-finder/connectors/store-finder.connector.ts
projects/core/src/store-finder/store/effects/find-stores.effect.ts

2020-04-16 09:49 UTC, Pucek9 requested changes
-

2020-04-16 11:38 UTC, Zeyber commented
> Hard to do local QA (You are using this API without a key. See http://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors)

The storefinder still works in dev mode without a key.

2020-04-16 12:29 UTC, Zeyber commented
QA Steps for Config:
- Modify the `raidius` in `default-store-finder-config.ts`
- Navigate to storefinder
- Click `Use My Location`
- Check that the radius parameter in the request uses the modified value in the default config

![image](https://user-images.githubusercontent.com/11735817/79456385-b7c05280-7fee-11ea-8b98-2e49c3d18ec8.png)


Note: New radius may result in no stores found depending on your testing location because the old radius was large enough of 10000000 was large enough to cover the world.

2020-04-16 13:39 UTC, Pucek9 submitted a review, later dismissed

2020-04-17 13:32 UTC, marlass requested changes
Could you also add StoreFinderConfig to StorefrontConfig and change all properties of googleMaps to optional? Then it would be following the same convention as any other configuration.

2020-04-17 13:32 UTC, marlass commented on projects/storefrontlib/src/cms-components/storefinder/components/store-finder-search-result/store-finder-search-result.component.ts
>      private storeFinderService: StoreFinderService,
Could we also in this PR make those dependencies protected?

2020-04-20 12:28 UTC, marlass requested changes

2020-04-20 12:28 UTC, marlass commented on docs/migration/2_0.md
> +Paramater `radius` of `googleMaps?` parameter in `StoreFinderConfig` is now required.
I would change that. To only say that the radius is now configurable through the config. It is no longer required after the latest config changes ;)

2020-04-20 13:31 UTC, marlass submitted a review, later dismissed

2020-04-22 07:33 UTC, marlass approved these changes

2020-04-22 13:32 UTC, merged