fix: fix store-finder-list-item link to use routerLink instead of href #7304
SAP/spartacus pull request #7308
Opened 2020-04-20 15:40 UTC by Pucek9

Closes #7304

2020-04-21 14:05 UTC, Matejk00 submitted a review, later dismissed

2020-04-23 12:31 UTC, marlass requested changes

2020-04-23 12:31 UTC, marlass commented on projects/schematics/src/migrations/2_0/constructor-deprecations/constructor-deprecation-data.ts
> +import { CART_ITEM_COMPONENT_MIGRATIONS } from './data/cart-item.component.migration';
Merge conflict leftover?

2020-04-23 12:36 UTC, marlass approved these changes

2020-04-23 13:08 UTC, merged