refactor: Remove deprecated constructor of TabParagraphContainerComponent
SAP/spartacus pull request #7353
Opened 2020-04-23 11:35 UTC by Zeyber

Closes: #7320

2020-04-23 13:42 UTC, Pucek9 commented on projects/storefrontlib/src/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts
> +      this.winRef.nativeWindow.history.state;
```suggestion
      this.winRef.nativeWindow.history?.state;
```

2020-04-23 13:42 UTC, Pucek9 commented on projects/storefrontlib/src/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts
> +    if (routeState && routeState['activeTab']) {
```suggestion
    if (routeState?.['activeTab']) {
```

2020-04-23 13:46 UTC, Pucek9 commented on projects/storefrontlib/src/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts
> +    if (routeState && routeState['activeTab']) {
or just
```
    const activeTab = this.winRef.nativeWindow.history?.state?.['activeTab'];
    if (activeTab) {
      this.activeTabNum = activeTab;
    }
```

2020-04-24 13:38 UTC, marlass requested changes

2020-04-24 13:38 UTC, marlass commented on projects/storefrontlib/src/cms-components/content/tab-paragraph-container/tab-paragraph-container.component.ts
>      private cmsService: CmsService,
Let's make both of these protected as well

2020-04-24 13:43 UTC, marlass approved these changes

2020-04-24 15:07 UTC, merged