GH-6454: Remove unnecessary onChange functions
SAP/spartacus pull request #7372
Opened 2020-04-27 07:04 UTC by mszczepaniak

Closes #6454 

Could not remove countrySelected, because it is triggering the change on selectedCountry
behaviour subject, which is required by regions.

2020-04-28 07:21 UTC, psmul requested changes
For file:
`projects/storefrontlib/src/cms-components/checkout/components/payment-method/payment-form/payment-form.component.ts`
I think `monthSelected` and `yearSelected` can be removed too, please comment on this one

2020-04-28 12:10 UTC, psmul submitted a review, later dismissed

2020-04-29 09:31 UTC, psmul approved these changes

2020-04-29 09:35 UTC, merged

2020-04-30 12:23 UTC, mszczepaniak commented
**QA Steps:**
- go through the checkout
- add new address
- add new payment
- see if you can place an order without any errors