Feature/GH-6115
SAP/spartacus pull request #7404
Opened 2020-04-29 11:53 UTC by lohithosur

Hi Mihal,
Can you review ".../organization/facade/permission.service.spec.ts"? The test fail for getTypes().

Regards,
Lohit

2020-04-29 11:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/spartacus?pullRequest=7404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SAP/spartacus?pullRequest=7404) before we can accept your contribution.<br/><hr/>**lohitbhosur** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/spartacus?pullRequest=7404) it.</sub>

2020-05-01 12:07 UTC, lohithosur commented
Hi Michal,
I have made the second commit.
I have updated the following <*.spec.ts> files with permission types use case:
1) Action
2) Connector
3) Effect
4) Selector
5) Service

I only have issue with Effect. I'm not sure if the error is in the corresponding permission.effect.ts file? What do you think?

Also kindly review, other <*.spec.ts> files and let me know if they are ok.

Thanks & Regards,
Lohit

2020-05-04 18:46 UTC, Pucek9 requested changes
CR done
- [x] Action
- [x] Connector
- [x] Effect (fixed)
- [x] Selector
- [ ] Service (missed case)

2020-05-04 18:46 UTC, Pucek9 commented on projects/core/src/organization/facade/permission.service.spec.ts
> +    it('getTypes() should trigger load permission types when they are not present in the store', () => {
need to check also positive scenario
![image](https://user-images.githubusercontent.com/8040837/81001553-32d79480-8e48-11ea-8d4f-1e1664b48210.png)

2020-05-05 09:30 UTC, Pucek9 commented on projects/core/src/organization/facade/permission.service.spec.ts
> +const permissionTypes2: OrderApprovalPermissionType[] = [permissionType2];
const permissionType: OrderApprovalPermissionType = {
  code: 'testPermissionTypeCode',
  name: 'testPermissionTypeName',
};
const permissionTypes: OrderApprovalPermissionType[] = [permissionType]

2020-05-05 09:31 UTC, Pucek9 commented on projects/core/src/organization/facade/permission.service.spec.ts
> +      expect(permisstionTypes).toEqual(permissionTypes2);
```suggestion
        new PermissionActions.LoadPermissionTypesSuccess(permissionTypes)
      );
      let types: OrderApprovalPermissionType[];
      service
        .getTypes()
        .subscribe((data) => {
          types = data;
        })
        .unsubscribe();

      expect(types).toEqual(permissionTypes);
```

2020-05-05 09:53 UTC, Pucek9 approved these changes

2020-05-05 09:58 UTC, merged