Feature/gh 6653
SAP/spartacus pull request #7757
Opened 2020-05-25 15:23 UTC by WeizhengSap

close #6653

2020-05-26 21:12 UTC, plabadie requested changes
There is just a small typo to fix.

2020-05-26 21:12 UTC, plabadie commented on projects/core/src/user/store/reducers/user-cost-center.reducer.ts
> +    case UserActions.LOAD_ACTIVT_COST_CENTERS_FAIL: {
Small typo in `LOAD_ACTIVT_COST_CENTERS_FAIL`

2020-05-26 21:12 UTC, plabadie commented on projects/core/src/user/store/reducers/user-cost-center.reducer.spec.ts
> +  describe('LOAD_ACTIVT_COST_CENTERS_FAIL action', () => {
Small typo

2020-05-26 21:12 UTC, plabadie commented on projects/core/src/user/store/actions/user-cost-center.action.ts
> +export const LOAD_ACTIVT_COST_CENTERS_FAIL =
Small typo in `LOAD_ACTIVT_COST_CENTERS_FAIL`

2020-05-27 13:02 UTC, WeizhengSap commented on projects/core/src/user/store/reducers/user-cost-center.reducer.ts
> +    case UserActions.LOAD_ACTIVT_COST_CENTERS_FAIL: {
done

2020-05-27 13:58 UTC, plabadie approved these changes

2020-05-27 15:55 UTC, merged