GH-7785 login register component
SAP/spartacus pull request #7913
Opened 2020-06-08 21:46 UTC by hackergil

Fixes #7785

2020-06-18 14:00 UTC, plabadie commented on projects/assets/src/translations/en/user.ts
>      guestCheckout: 'Guest Checkout',
Moving the `guestCheckout` label under `loginRegister ` is a breaking change.

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.spec.ts
> +    return '2.0';
As a rule of thumb we've been adding coverage only for the most recent version of a feature, here 2.1.

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.html
> +<div class="register" *cxFeatureLevel="'2.0'">
What is the purpose if this feature logic?
I think this might be what we need `*cxFeatureLevel="'!2.1'"`. 
Let's discuss.

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts
> +    if (this.featureConfigService?.isLevel('2.0')) {
What is the purpose if this feature logic?
I think this might be what we need `(this.featureConfigService?.isLevel('!2.1')) {`. 
Let's discuss.

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-register/login-register.component.spec.ts
> +      createComponent();
Seems like updating the value in the mock could be a simpler approach than recreating the testbed.  Your call

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-register/login-register.component.spec.ts
> +      createComponent();
Seems like updating the value in the mock could be a simpler approach than recreating the testbed. Your call.

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-register/login-register.module.ts
> +import { LoginRegisterComponent } from '../login-register/login-register.component';
import path should probably be from `./login-register.component`

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontstyles/scss/layout/page-templates/_login-page.scss
> +      max-width: var(--cx-max-width, 52%);
Changing existing styles is unfortunately a breaking change.

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-register/login-register.component.spec.ts
> +    declarations: [LoginRegisterComponent, MockUrlPipe],
We may want to mock the `cxFeatureLevel` directive also to complete the mocking scenario.

2020-06-18 14:00 UTC, plabadie commented on projects/assets/src/translations/en/user.ts
>      wrongEmailFormat: 'This is not a valid email format.',
As a whole, shouldn't this PR be merged to develop?  It doesn't depend on anything b2b.  Your call

2020-06-18 14:00 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts
> +  );
This deprecated constructor looks the same as the non-deprecated one below.

2020-06-18 14:56 UTC, hackergil commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts
> +   * Use constructor (auth: AuthService, globalMessageService: GlobalMessageService, fb: FormBuilder, authRedirectService: AuthRedirectService, winRef: WindowRef)
Fix this comment

2020-06-18 15:02 UTC, hackergil commented on projects/storefrontstyles/scss/layout/page-templates/_login-page.scss
> +      max-width: var(--cx-max-width, 52%);
I'll undo this and create a new ticket to follow up

2020-06-18 17:34 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts
> +   * Use constructor (auth: AuthService, globalMessageService: GlobalMessageService, fb: FormBuilder, authRedirectService: AuthRedirectService, winRef: WindowRef)
Doc needs fixing

2020-06-18 17:36 UTC, hackergil commented on projects/assets/src/translations/en/user.ts
>      guestCheckout: 'Guest Checkout',
I didn't move it, I duplicated it

2020-06-19 16:16 UTC, plabadie requested changes

2020-06-19 16:16 UTC, plabadie commented on projects/assets/src/translations/en/user.ts
>      guestCheckout: 'Guest Checkout',
No need to start duplicating labels, we should use the existing one as-is.

2020-06-19 16:16 UTC, plabadie commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts
> +
We can just use the existing constructor as-is.  No need to deprecate the old one.

2020-06-19 16:25 UTC, plabadie requested changes
This feature requires a followup ticket for styling.

2020-06-19 17:12 UTC, hackergil commented on projects/storefrontlib/src/cms-components/user/login-form/login-form.component.ts
> +
Done and done

2020-06-19 17:41 UTC, plabadie approved these changes

2020-06-19 18:30 UTC, merged