FUSION-1280 Changes to support cdc integration
SAP/spartacus pull request #7978
Opened 2020-06-16 07:41 UTC by pratikkumar90

Changes to support CDC in Spartacus. 

Create a new library project which contains, 
1. GigyaJSService - Which initializes on app startup and it handles user login and profile update functionality. 
2. GigyaRaasComponent - Component responsible for rendering the CDC Screen Sets 
3. Auth Module - New Auth module to call the new OAuth flow to fetch OAuth token-based on the data retrieved from the onLogin event from CDC
4. Enhancement to the sample storefrontapp to test the CDC functionality.

2020-06-16 09:40 UTC, marlass requested changes

2020-06-16 09:40 UTC, marlass commented on package.json
> +    "release-notes:cds": "ts-node ./scripts/changelog.ts --verbose --lib cds",
I think this should be removed

2020-06-16 09:40 UTC, marlass commented on package.json
> +    "@ngrx/effects": "^9.0.0",
Why we change type of effect allowed versions?

2020-06-16 09:40 UTC, marlass commented on projects/gigya/README.md
> +`import { GigyaModule } from '@spartacus/gigya';`
You can remove that line, as it will be described in details in the docs, how to enable it and configure.

2020-06-16 09:40 UTC, marlass commented on package.json
> +    "@ngrx/effects": "^9.0.0",
That might be the reason behind the yarn.lock issue on Travis

2020-06-24 13:07 UTC, marlass requested changes

2020-06-24 13:07 UTC, marlass commented on projects/gigya/package.json
> +  "repository": "https://github.com/SAP/spartacus",
Can you point here to specific library directory? Similar thing like we do for other libraries?

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/auth/store/actions/gigya-user-token.action.ts
> +    public payload: {
Could you extract it into interface and then use in LoadUserTokenSuccessPayload interface?

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/auth/store/actions/gigya-user-token.action.ts
> +export interface LoadUserTokenSuccessPayload {
It needs to be exported?

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/auth/store/effects/gigya-user-token.effect.ts
> +              new GigyaAuthActions.LoadUserTokenFail(
Could you also pass initActionPayload to this action?

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/auth/store/effects/index.ts
> +export const effects: any[] = [GigyaUserTokenEffects];
Remove this extra variable `effects`. Directly list `GigyaUserTokenEffects` in module

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/cms-components/gigya-js/gigya-js.service.ts
> +      this.baseSiteService.getActive().subscribe((baseSite) => {
Could you combine these two subscriptions with `combineLatest`?

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/cms-components/gigya-js/gigya-js.service.ts
> +            this.registerEventListeners();
You can pass here the basesite to registerEventListeners. Then you can remove `getCurrentBaseSite` method.

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/auth/auth.module.ts
> +export class AuthModule {}
Could we rename it to `GigyaAuthModule`?

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/gigya.module.ts
> +    EffectsModule.forRoot([GigyaUserTokenEffects]),
Effects are registered both here and in StoreModule. Is it intended?

2020-06-24 13:07 UTC, marlass commented on package.json
> +    "start:b2b:ci:2005": "cross-env SPARTACUS_BASE_URL=https://dev-com-7.accdemo.b2c.ydev.hybris.com:9002 SPARTACUS_API_PREFIX=/occ/v2/ SPARTACUS_B2B=true ng serve --prod",
This script can be removed

2020-06-24 13:07 UTC, marlass commented on projects/gigya/src/auth/store/reducers/index.ts
> +export function clearAuthState(
Do we have to repeat all this from the core module? I thought we only needed new reducer?

2020-06-24 13:07 UTC, marlass commented on tsconfig.json
> +      "@spartacus/schematics": ["projects/schematics/src/public_api"],
Why we have this duplicate?

2020-06-25 05:21 UTC, pratikkumar90 commented on projects/gigya/src/gigya.module.ts
> +    EffectsModule.forRoot([GigyaUserTokenEffects]),
No registering here is not required as it is already registered in the auth store. I will remove this.

2020-07-02 14:16 UTC, marlass requested changes

2020-07-02 14:16 UTC, marlass commented on projects/gigya/src/auth/store/effects/gigya-user-token.effect.spec.ts
> +    it('should serialize string error before returning it', () => {
Could you extract all makeErrorSerializable tests into separate `describe` block?

2020-07-02 14:16 UTC, marlass commented on projects/gigya/public_api.ts
> +export * from './src/auth/store/actions/index';
GigyaJSService should also be exported in the public API. Additionally we should move this service into `facade` directory.

2020-07-02 14:16 UTC, marlass commented on package.json
> +    "build:core:lib:gigya": "yarn build:core:lib && ng build gigya",
This script can be removed. Instead added it to general `build:core:lib`

2020-07-02 14:16 UTC, marlass commented on projects/gigya/src/cms-components/gigya-js/gigya-js.service.ts
> +  subscription: Subscription = new Subscription();
Let's make all these properties protected instead of private.

2020-07-06 12:06 UTC, marlass commented on projects/gigya/public_api.ts
> +export * from './src/auth/store/actions/index';
I meant to move the file under this path: `/src/auth/facade/gigya-js.service` as it is no longer related to CMS components.

2020-08-03 16:54 UTC, marlass approved these changes

2020-08-03 16:55 UTC, merged