Feature/gh 7837
SAP/spartacus pull request #7980
Opened 2020-06-16 10:14 UTC by MichaelBoeser

2020-06-17 13:53 UTC, ChristophHi requested changes

2020-06-17 13:53 UTC, ChristophHi commented on projects/storefrontlib/src/cms-components/configurator/commons/config-attribute-types/config-attribute-checkbox-list/config-attribute-checkbox-list.component.html
> +        <ng-container *ngIf="!attribute.isNumeric">
Why 2 containers with the same content?

2020-06-17 13:53 UTC, ChristophHi commented on projects/storefrontlib/src/cms-components/configurator/commons/config-attribute-types/config-attribute-drop-down/config-attribute-drop-down.component.ts
> +  internalAttribute: Configurator.Attribute;
'internalAttribute' is probably not a good name. The attribute is supposed to carry localized values, this should be reflected in the name

2020-06-17 13:53 UTC, ChristophHi commented on projects/storefrontlib/src/cms-components/configurator/commons/config-attribute-types/config-attribute-drop-down/config-attribute-drop-down.component.ts
> +                element.valueDisplay
Why is this needed? For numeric input at least the value was available in en locale, let's discuss.

2020-06-22 11:55 UTC, ChristophHi commented on projects/storefrontlib/src/cms-components/configurator/commons/config-attribute-types/config-attribute-checkbox-list/config-attribute-checkbox-list.component.html
> +        <ng-container *ngIf="!attribute.isNumeric">
Checked it again: This is still wrong, correct? Because those containers do the very same thing. Did you mean to put the pipe here?

2020-06-24 08:38 UTC, closed without merging

2020-06-24 08:40 UTC, MichaelBoeser commented
Number formatting is not necessary on UI layer, as it is done in OCC layer.