UI View changes for Unit -> Manage Roles
SAP/spartacus pull request #8015
Opened 2020-06-19 22:30 UTC by lohithosur

2020-07-01 23:52 UTC, Pucek9 commented on projects/storefrontlib/src/cms-components/organization/units/unit-assign-roles/unit-assign-roles.component.ts
> +              manager: user.roles.includes('b2bmanagergroup'),
```suggestion
              b2badmingroup: user.roles.includes('b2badmingroup'),
              b2bapprovergroup: user.roles.includes('b2bapprovergroup'),
              b2bcustomergroup: user.roles.includes('b2bcustomergroup'),
              b2bmanagergroup: user.roles.includes('b2bmanagergroup'),
```

2020-07-01 23:56 UTC, Pucek9 commented on projects/storefrontlib/src/cms-components/organization/units/unit-assign-roles/unit-assign-roles.component.spec.ts
> +      expect(b2bUsersService.update).toHaveBeenCalled();
https://sap-cx.slack.com/archives/C0118U91T54/p1588940533003100

2020-07-01 23:59 UTC, Pucek9 requested changes
Please follow comments

2020-07-02 10:47 UTC, lohithosur commented on projects/storefrontlib/src/cms-components/organization/units/unit-assign-roles/unit-assign-roles.component.ts
> +              manager: user.roles.includes('b2bmanagergroup'),
Done

2020-07-02 11:13 UTC, lohithosur commented on projects/storefrontlib/src/cms-components/organization/units/unit-assign-roles/unit-assign-roles.component.spec.ts
> +      expect(b2bUsersService.update).toHaveBeenCalled();
Done

2020-07-02 12:49 UTC, Pucek9 approved these changes

2020-07-02 13:58 UTC, merged