Fixes https://github.com/SAP/spartacus/issues/7995
SAP/spartacus pull request #8136
Opened 2020-07-07 09:32 UTC by aphanor-sap

2020-07-07 09:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/spartacus?pullRequest=8136) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/spartacus?pullRequest=8136) before we can accept your contribution.<br/>**9** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: znikola<br/>:white_check_mark: lohithosur<br/>:white_check_mark: Pucek9<br/>:white_check_mark: WeizhengSap<br/>:white_check_mark: bgambocjaviniar<br/>:white_check_mark: psmul<br/>:white_check_mark: Fonsu<br/>:white_check_mark: mszczepaniak<br/>:white_check_mark: Matejk00<br/>:x: aphanor<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/spartacus?pullRequest=8136) it.</sub>

2020-07-07 09:59 UTC, Matejk00 requested changes

2020-07-07 09:59 UTC, Matejk00 commented on projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts
> +fdescribe('UnitTreeNavigationUIComponent', () => {
It should be `describe`.

2020-07-07 09:59 UTC, Matejk00 commented on projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts
> +fdescribe('UnitTreeNavigationUIComponent', () => {
We are using `fdescribe` only locally to prevent reloading full sets of tests every time.

2020-07-07 09:59 UTC, Matejk00 commented on projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts
> +      for (var i = 0; i < mockNode.children[0].children[0].children[0].children.length; i++) {
I think `forEach` will be shorter and more elegant.

2020-07-07 09:59 UTC, Matejk00 commented on projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts
> +        expect(domElements[2].getAttribute('title')).toBe(mockNode.children[0].children[0].children[0].title);
This part `mockNode.children[0].children[0].children[0]` is little bit painfull ;) 
Can we declare somewhere at the top some kind of segments?

for example:
`const segment_third = mockNode.children[0].children[0].children[0];` and then just using this `segment_third` variable everywhere?

2020-07-07 09:59 UTC, Matejk00 commented on projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts
> +        expect(domElements[2].getAttribute('title')).toBe(mockNode.children[0].children[0].children[0].title);
Same for rest of segments.

2020-07-07 09:59 UTC, Matejk00 commented on projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts
> +      const domElements: any = domTree.querySelectorAll('cx-generic-link');
This const seems to be not indented properly. Try `yarn prettier:fix` to fix this file.

2020-07-07 11:05 UTC, aphanor-sap commented
The changes have been made. Would you mind reviewing it again, please :-)?

2020-07-09 09:01 UTC, Matejk00 commented
https://travis-ci.org/github/SAP/spartacus/builds/705742399?utm_source=github_status&utm_medium=notification

```
Validating code formatting (using prettier)
yarn run v1.22.0
$ prettier --config ./.prettierrc --list-different "{projects,feature-libs}/**/*{.ts,.js,.json,.scss,.html}"
projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts
error Command failed with exit code 1.
```

Please fix this prettier issue in `projects/storefrontlib/src/cms-components/organization/units/unit-tree-navigation-ui/unit-tree-navigation-ui.component.spec.ts`

You can use `yarn prettier:fix` command.

2020-07-14 08:09 UTC, Matejk00 approved these changes

2020-07-14 12:26 UTC, merged