Feature/gh 8137 move components to lib
SAP/spartacus pull request #8148
Opened 2020-07-08 07:55 UTC by ChristophHi

2020-07-08 11:10 UTC, znikola requested changes

2020-07-08 11:10 UTC, znikola commented on feature-libs/product/configurators/common/src/components/service/config-component-test-utils.service.ts
> +@Injectable({ providedIn: 'root' })
Hmm, having this as an `Injectable` doesn't feel like a good practice. 
I'd suggest to remove it, which will effectively make this a regular class.
Moreover, we should try _not_ to export it, if possible. The easiest way to check is to try to import it in the `app.module.ts` from `@spartacus/product`.

2020-07-08 11:10 UTC, znikola commented on feature-libs/product/configurators/common/src/components/service/config-component-test-utils.service.ts
> +@Injectable({ providedIn: 'root' })
We could move it to the common configurators `/shared/testing`

2020-07-08 11:10 UTC, znikola commented on feature-libs/product/configurators/common/src/components/common-configurator-components.module.ts
> +  ],
Do you expect to have more common components here?
If so, we can consider having a module per component (in which you can declare and export the component, as well as mark it as an entry component).
Then you could just import those modules here.

Moreover, you could create an `index.ts` file inside of each of the component folders, and export from those index files in https://github.com/SAP/spartacus/pull/8148/files#diff-6bca718ed8bf30e6a313092f450147c5

2020-07-08 11:10 UTC, znikola commented on todo.md
> +5. Get rid of import { makeErrorSerializable } from '@spartacus/product/configurators/common', instead expose it from core lib
Thanks for this 👍

2020-07-08 11:10 UTC, znikola commented on feature-libs/product/configurators/public_api.ts
> +export * from '@spartacus/product/configurators/textfield';*/
Discussed offline

2020-07-08 11:10 UTC, znikola commented on todo.md
> +5. Get rid of import { makeErrorSerializable } from '@spartacus/product/configurators/common', instead expose it from core lib
To save us some time, maybe also mention the path where it's exposed - `feature-libs/product/configurators/common/src/index.ts`

2020-07-09 04:40 UTC, ChristophHi commented on feature-libs/product/configurators/common/src/components/common-configurator-components.module.ts
> +  ],
Yes, we expect more components. 
And yes, created modules for each components and dedicated index files

2020-07-09 08:13 UTC, znikola approved these changes

2020-07-09 08:25 UTC, merged