feat: Expose lighter version of makeErrorSerializable
SAP/spartacus pull request #8197
Opened 2020-07-10 17:46 UTC by dunqan

Current version of 'makeErrorSerializable' is widely used as a utility but contains some complex preprocessing of http errors.

Rename current implementation and expose new, more lightweight one.

Closes #8195

2020-07-13 05:43 UTC, marlass submitted a review, later dismissed

2020-07-13 09:32 UTC, Platonn commented on projects/core/src/util/serialization-utils.ts
> + * unserializable parts from Error and HttoErrorResponse in a common way.
```suggestion
 * unserializable parts from Error and HttpErrorResponse in a common way.
```

2020-07-14 13:05 UTC, marlass commented on projects/core/src/util/normalize-http-error.spec.ts
> +describe('makeErrorSerializable', () => {
👀

2020-07-14 13:07 UTC, marlass requested changes

2020-07-14 13:07 UTC, marlass commented on projects/core/src/util/normalize-http-error.ts
> +      'Error passed to nomalizeHttpError is not HttpErrorResponse instance',
```suggestion
      'Error passed to normalizeHttpError is not HttpErrorResponse instance',
```

2020-07-14 13:11 UTC, dunqan commented on projects/core/src/util/normalize-http-error.ts
> +      'Error passed to nomalizeHttpError is not HttpErrorResponse instance',
thx, fixed 👍

2020-07-14 13:12 UTC, dunqan commented on projects/core/src/util/normalize-http-error.spec.ts
> +describe('makeErrorSerializable', () => {
;-)

2020-07-14 13:30 UTC, marlass approved these changes

2020-07-14 14:48 UTC, merged