Configurable table renderers
SAP/spartacus pull request #8712
Opened 2020-08-24 13:54 UTC by tobi-or-not-tobi

closes #8704

2020-08-25 13:09 UTC, dunqan commented on feature-libs/my-account/organization/src/components/shared/organization-table/organization-table.module.ts
> +export class OrganizationCellModule {}
Should be `OrganizationTableModule`?

2020-08-25 13:09 UTC, dunqan commented on projects/storefrontlib/src/shared/components/table/table-renderer.service.ts
> +export class TableRendererService {
Would be good to add some description to the service and its role.

2020-08-25 13:09 UTC, dunqan commented on projects/storefrontlib/src/shared/components/table/table.component.ts
> +    // test breakpoint specific cell components
do we want to keep those comments?

2020-08-25 14:58 UTC, dunqan approved these changes

2020-09-01 11:11 UTC, Pucek9 requested changes
- missing translation in users/details or edit [organization:user.orgUnit]
- I can't open address details (NullInjectorError: No provider for CurrentUnitAddressService!)
- in details pages, while open sub-page there is missing active class styling (grey background)

2020-09-22 12:31 UTC, tobi-or-not-tobi commented
closing as this has been added by #8924 directly

2020-09-22 12:31 UTC, closed without merging