Allow BASE_URL and API_PREFIX to override env config
SAP/spartacus pull request #8778
Opened 2020-09-01 12:23 UTC by pg-sap

This change is to align with [environment.prod.ts](https://github.com/SAP/spartacus/blob/develop/projects/storefrontapp/src/environments/environment.prod.ts), so that developers can override their local environment configuration using variables `SPARTACUS_BASE_URL` and `SPARTACUS_API_PREFIX`.

This is https://github.com/SAP/spartacus/pull/8777 with the corrected branch name for CI.

2020-09-01 12:46 UTC, tobi-or-not-tobi requested changes
Prettier error, see https://travis-ci.org/github/SAP/spartacus/builds/723063273

2020-09-28 09:49 UTC, tobi-or-not-tobi approved these changes

2020-12-06 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/spartacus?pullRequest=8778) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/spartacus?pullRequest=8778) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tobi-or-not-tobi<br/>:x: pg-sap<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/spartacus?pullRequest=8778) it.</sub>

2023-11-14 20:13 UTC, giancorderoortiz commented
Closing due to many months of inactivity.
If still relevant, please update PR with latest develop branch, and re-open with meaningful comments so that it can be evaluated by development team.

2023-11-14 20:13 UTC, closed without merging