feat: implement the cancel feature for replenishment in replenishment order details (UI/UX) #8752
SAP/spartacus pull request #8842
Opened 2020-09-08 18:02 UTC by bgambocjaviniar

closes GH-8752

2020-09-15 20:15 UTC, LTiger14 requested changes

2020-09-15 20:15 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/myaccount/order/replenishment-order-details/replenishment-order-cancellation/replenishment-order-cancellation.component.ts
> +    this.subscription.add(
Is there a particular reason why you didn't use an async pipe here?

2020-09-15 20:15 UTC, LTiger14 commented on projects/storefrontlib/src/cms-structure/routing/default-routing-config.ts
> +    paths: ['my-account/my-replenishment'],
What is this page for again?

2020-09-15 20:15 UTC, LTiger14 commented on projects/storefrontlib/src/shared/components/replenishment-order-cancellation-dialog/replenishment-order-cancellation-dialog.module.ts
> +  imports: [CommonModule, I18nModule, IconModule],
I didn't see an icon in the html so you can remove the IconModule

2020-09-16 04:09 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-structure/routing/default-routing-config.ts
> +    paths: ['my-account/my-replenishment'],
was so that I can see replenishment history, but forgot to clean that out

2020-09-16 04:10 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-components/myaccount/order/replenishment-order-details/replenishment-order-cancellation/replenishment-order-cancellation.component.ts
> +    this.subscription.add(
there was a reason, which I used the data somewhere in the ts, but I don't remember exactly what.

I'll switch into template

2020-09-16 05:44 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-structure/routing/default-routing-config.ts
> +    paths: ['my-account/my-replenishment'],
but it is being used in cxRoute template for `replenishment-order-cancellation.component.html button when going back

I'll still remove it though

2020-09-16 20:50 UTC, LTiger14 approved these changes

2020-09-16 21:30 UTC, merged