feat: Implement core/occ functionality to get the replenishment order list for the listing page
SAP/spartacus pull request #8861
Opened 2020-09-09 18:30 UTC by saad-mo

closes #8576

Add Core functionality for Repleishmet Order History List.

### created fresh PR with resolved conflicts

2020-09-11 23:11 UTC, bgambocjaviniar requested changes
1 - most important one is too fix the previous review comments before putting it in review again. I went one by one to verify if it was fixed and placed it accordingly in this PR as well.

2 - left additional review comments for this set of review other than the old ones from before

3 - remember when I explained that maybe some places are very old in order history, so copy paste accordingly and improve it as you go, such as comments I left that are new for this PR

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/user/occ-user-replenishment-order.adapter.spec.ts
> +  describe('getUserReplineshmentOrders', () => {
typo
- Replenishment

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/user/occ-user-replenishment-order.adapter.spec.ts
> +      const sort = 'byDate';
these constants above are also used in `getUserReplineshmentOrders`, so you can move these to the global level to be used for all

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/user/occ-user-replenishment-order.adapter.spec.ts
> +      httpMock.expectOne((req: HttpRequest<any>) => {
take a look at the other test I wrote above, and adapt it. Basically, you can place it in a variable and do another assertion to verify the response type and others if exist like params

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/connectors/replenishment-order/user-replenishment-order.connector.spec.ts
> +        UserReplenishmentOrderConnector,
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482698956

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/connectors/replenishment-order/user-replenishment-order.connector.spec.ts
> +    connector.loadHistory('user3').subscribe((res) => (result = res));
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482699251

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.ts
> +  getReplenishmentOrderHistoryListLoaded(): Observable<boolean> {
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482700487

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.ts
> +    pageSize: number,
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482700646

* Why optional because maybe customers want to just dispatch this action without changing the default pageSize

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.ts
> +   * Retrieves an replenishment order list
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482700748

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.ts
> +      this.store.dispatch(
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482700876

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.ts
> +   * Cleaning order list
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482700962

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/actions/user-replenishment-orders.action.ts
> +      pageSize: number;
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482703472

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/actions/user-replenishment-orders.action.spec.ts
> +const mockUserReplenishmentOrder: {
still not fixed from previous PR's comment
and wasn't followed up with

https://github.com/SAP/spartacus/pull/8785#discussion_r485163853

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/effects/user-replenishment-orders.effect.ts
> +    private orderReplenishmentConnector: UserReplenishmentOrderConnector
still not fixed from previous PR's comment 

https://github.com/SAP/spartacus/pull/8785#discussion_r482704429

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/effects/user-replenishment-orders.effect.ts
> +  loadUserReplenishOrders$: Observable<
still not fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482705017

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/effects/user-replenishment-orders.effect.spec.ts
> +    it('should load user Orders', () => {
still wasn't fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482705645

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/effects/user-replenishment-orders.effect.spec.ts
> +  let actions$: Observable<any>;
still wasn't fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482705710

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/effects/user-replenishment-orders.effect.spec.ts
> +import * as fromUserOrdersEffect from './user-replenishment-orders.effect';
still wasn't fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482706001

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/reducers/user-replenishment-orders.reducer.ts
> +    case UserActions.LOAD_USER_REPLENISHMENT_ORDERS_FAIL: {
still isn't addressed from previous PR's comment
wasn't followed up with too

https://github.com/SAP/spartacus/pull/8785#discussion_r483386504
and
https://github.com/SAP/spartacus/pull/8785#discussion_r485175094

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/reducers/user-replenishment-orders.reducer.spec.ts
> +      const mockUserOrders: ReplenishmentOrderList = {
still isn't fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482709007

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/reducers/user-replenishment-orders.reducer.spec.ts
> +    it('should populate the user Orders state entities', () => {
still isn't fixed from previous PR's comment

https://github.com/SAP/spartacus/pull/8785#discussion_r482709270

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/reducers/user-replenishment-orders.reducer.spec.ts
> +      const replenishmentOrders: OrderHistory[] = [
still isn't fixed from previous PR's comment
and wasn't followed up with

https://github.com/SAP/spartacus/pull/8785#discussion_r485173831

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/selectors/user-replenishment-orders.selectors.ts
> +
still isn't fixed from previous PR's comment
and wasn't followed with

https://github.com/SAP/spartacus/pull/8785#discussion_r485176108

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/user/occ-user-replenishment-order.adapter.spec.ts
> +    it('should fetch user Replineshment Orders with default options', async(() => {
why the need to set as async

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/user/occ-user-replenishment-order.adapter.spec.ts
> +  describe('getUserReplineshmentOrders', () => {
also you don't have a function called getUserReplenishmentOrders, but a function called loadHistory instead

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/user/user-occ.module.ts
> +      provide: UserReplenishmentOrderAdapter,
please remove as this is a duplicate of the last object in the array

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/connectors/replenishment-order/user-replenishment-order.connector.spec.ts
> +  loadHistory = createSpy(
this is fine as it was in the other file, but adapt it to how it's done below as the output is the same. 

It is just weird having this when the others in this file does it in a different way

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/connectors/replenishment-order/user-replenishment-order.connector.spec.ts
> +  let adapter: UserReplenishmentOrderAdapter;
please remove and just add the `it` function assertion to above existing `describe` function

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.spec.ts
> +    it('should UserOrderService is injected', inject(
duplicate of line 70, where it checks if it is already injected, please remove

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.spec.ts
> +    it('should be able to get replenishment order list loaded flag', () => {
success flag

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.spec.ts
> +      store.dispatch(new UserActions.LoadUserReplenishmentOrdersSuccess({}));
instead of using empty object,

create a mock list (minimal data is fine)

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.spec.ts
> +          userId: OCC_USER_ID_CURRENT,
there's a constant to used above called mockUserId

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/actions/user-replenishment-orders.action.spec.ts
> +const mockUserReplenishmentOrders: ReplenishmentOrderList = {
since these constant are only used in one specific `describe` function, lets put snap them in there

2020-09-11 23:11 UTC, bgambocjaviniar commented on projects/core/src/user/store/effects/user-replenishment-orders.effect.spec.ts
> +  let orderReplenishmentConnector: UserReplenishmentOrderConnector;
still wasn't fixed from previous PR's comment 

https://github.com/SAP/spartacus/pull/8785#discussion_r482705884

2020-09-14 17:15 UTC, saad-mo commented on projects/core/src/user/store/reducers/user-replenishment-orders.reducer.ts
> +    case UserActions.LOAD_USER_REPLENISHMENT_ORDERS_FAIL: {
no need for follow up on this one.

2020-09-14 17:41 UTC, saad-mo commented on projects/core/src/user/store/reducers/user-replenishment-orders.reducer.spec.ts
> +      const replenishmentOrders: OrderHistory[] = [
figured it out. no need to follow up

2020-09-14 17:52 UTC, saad-mo commented on projects/core/src/occ/adapters/user/user-occ.module.ts
> +      provide: UserReplenishmentOrderAdapter,
surprised it didn't get picked up by linting...

2020-09-17 05:24 UTC, bgambocjaviniar requested changes
one more push before 🟢 !

2020-09-17 05:24 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.ts
> +  getReplenishmentOrderHistoryListSuccess(): Observable<boolean> {
missing the selectors that we said to create in the selectors file, where you have success, load, fail, 'value', so that we have this facade service to get those slices

2020-09-17 05:24 UTC, bgambocjaviniar commented on projects/core/src/user/facade/user-replenishment-order.service.spec.ts
> +          pageSize: 10,
add missing unit test `it` from what I commented on the service

2020-09-17 05:24 UTC, bgambocjaviniar commented on projects/core/src/user/store/effects/user-replenishment-orders.effect.spec.ts
> +  let actions$: Observable<Actions>;
when it was any, and I said to add the type, the type is `Action` and not Actions

2020-09-17 05:24 UTC, bgambocjaviniar commented on projects/core/src/user/store/reducers/index.ts
> +
remove extra line please

2020-09-17 05:24 UTC, bgambocjaviniar commented on projects/core/src/user/store/reducers/user-replenishment-orders.reducer.spec.ts
> +  describe('LOAD_USER_REPLENISHMENT_ORDERS_FAIL action', () => {
good you removed the switch as said in the main reducer file, but you haven't taken it out from the spec file

2020-09-17 05:24 UTC, bgambocjaviniar commented on projects/core/src/user/store/selectors/user-replenishment-orders.selectors.ts
> +
missing loading state

2020-09-17 05:24 UTC, bgambocjaviniar commented on projects/core/src/user/store/selectors/user-replenishment-orders.selectors.spec.ts
> +
assuming some parts were based on repl order details, you may have noticed, you need loading state as well

2020-09-17 18:49 UTC, bgambocjaviniar approved these changes

2020-09-17 18:59 UTC, merged