fix: for issue 8658, rename CustomEncoder class to HttpParamsURIEncod…
SAP/spartacus pull request #8990
Opened 2020-09-22 14:35 UTC by wangzixi-diablo

…er, move it to util folder and export to public API

This fix is for issue: https://github.com/SAP/spartacus/issues/8658

2020-09-23 13:37 UTC, kacperknapik requested changes
Please fix prettier and other CI checks

2020-09-24 10:58 UTC, Platonn approved these changes

2020-09-24 12:13 UTC, kacperknapik approved these changes

2020-09-24 12:18 UTC, kacperknapik approved these changes

2020-09-24 12:18 UTC, kacperknapik commented on projects/core/src/occ/adapters/checkout/occ-checkout-payment.adapter.ts
> +import { HttpParamsURIEncoder } from '../../../util/http-params-uri.encoder';
Testing CR comments

2020-09-24 13:07 UTC, merged