#8490 part 3: add config for parent cms route
SAP/spartacus pull request #9019
Opened 2020-09-23 16:41 UTC by Platonn

2020-09-24 05:45 UTC, tobi-or-not-tobi requested changes

2020-09-24 05:45 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-structure/services/cms-components.service.ts
> +   * Standardizes the format to an object with defined parent and children routes, even if parent is undefined
can we truncate the text a bit?

2020-09-24 05:45 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-structure/services/cms-components.service.ts
> +  private standardizeChildRoutes(
any particular reason to make this private?

2020-09-24 05:45 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-structure/services/cms-components.service.ts
> +        parent: undefined,
I'd prefer to come up with an object without the parent if it is `undefined`. For the 3 cases in this code.

2020-09-24 05:45 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-structure/services/cms-components.service.spec.ts
> +        parent: undefined,
would be nice to not have this prop, see note in service

2020-09-24 05:45 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-structure/services/cms-components.service.ts
> +        parent: undefined,
I find the code hard to read. 
Perhaps we create the vars, and then put it (optionally, if truthy) in an object?

2020-09-28 14:37 UTC, Platonn commented
Closing, as it's partial PR.

2020-09-28 14:37 UTC, closed without merging