feat: Active state update on facade #8976
SAP/spartacus pull request #9048
Opened 2020-09-25 15:27 UTC by Pucek9

Closes #8976

2020-09-29 17:48 UTC, Pucek9 commented on feature-libs/my-account/organization/core/services/budget.service.spec.ts
> +    it('update() should should be able to get status change from loading with value', () => {
```suggestion
    it('update() should should dispatch UpdateBudget action', () => {
```

2020-09-29 20:15 UTC, tobi-or-not-tobi requested changes
Only a few notes on the models. I've tested it with toggle status, works fine. 
I'll ask Stan to have a look at it as well.

2020-09-29 20:15 UTC, tobi-or-not-tobi commented on feature-libs/my-account/organization/core/model/LoadStatus.ts
> +export enum LoadStatus {
this file doesn't follow naming convention; lower case, ending with `.model.ts`

2020-09-29 20:15 UTC, tobi-or-not-tobi commented on feature-libs/my-account/organization/core/model/LoadStatus.ts
> +export function mapToItemInfo<T>(currentState: LoaderState<T>): ItemInfo<T> {
This is not a model, consider moving to another utility file.

2020-09-29 20:15 UTC, tobi-or-not-tobi commented on feature-libs/my-account/organization/core/model/LoadStatus.ts
> +  value: T;
what about renaming to `item`? We've used item in a lot of places, and this one is even called ItemInfo.

2020-09-29 20:15 UTC, tobi-or-not-tobi commented on feature-libs/my-account/organization/core/model/LoadStatus.ts
> +export interface ItemInfo<T> {
what about `ItemStatus`?

2020-09-29 20:15 UTC, tobi-or-not-tobi commented on feature-libs/my-account/organization/core/model/LoadStatus.ts
> +export interface ItemInfo<T> {
we might also want to prefix those models with `Organization`, i.e. `OrganizationItemStatus `, to make them more specific.

2020-09-30 11:16 UTC, marlass requested changes

2020-09-30 11:16 UTC, marlass commented on feature-libs/my-account/organization/core/model/LoadStatus.ts
> +export function mapToItemInfo<T>(currentState: LoaderState<T>): ItemInfo<T> {
In the same util file for this method you can also crate util that takes the stream and does the `pairwise`, login check and then uses this function in map so it is not repeated in every service.

2020-09-30 11:49 UTC, Pucek9 commented
QA steps:
you can test toggling by change toggle-status.component
```
protected update(item: T): void {
  this.itemService
    .update(item[this.key], this.getPatchedItem(item))
    .pipe(take(1))
    .subscribe(console.log);
}
```

2020-09-30 13:32 UTC, tobi-or-not-tobi submitted a review, later dismissed

2020-10-01 10:31 UTC, marlass commented on feature-libs/my-account/organization/components/unit/links/users/services/unit-user-item.service.ts
> +    _customerId: string,
Should it also be prefixed with `_` as this variable is now used?

2020-10-01 10:33 UTC, Pucek9 commented on feature-libs/my-account/organization/components/unit/links/users/services/unit-user-item.service.ts
> +    return this.b2bUserService.getLoadingStatus(_customerId);
```suggestion
    customerId: string,
    _user: B2BUser
  ): Observable<OrganizationItemStatus<B2BUser>> {
    return this.b2bUserService.getLoadingStatus(customerId);
```

2020-10-01 10:35 UTC, marlass approved these changes

2020-10-01 12:43 UTC, merged