fix: Facets null check
SAP/spartacus pull request #9407
Opened 2020-10-19 15:31 UTC by LTiger14

Closes #8231 & #8956

2020-10-20 16:31 UTC, bgambocjaviniar submitted a review, later dismissed

2020-10-21 14:12 UTC, znikola approved these changes

2020-10-21 14:14 UTC, znikola requested changes
Please update the existing test

2020-10-21 14:30 UTC, znikola approved these changes

2020-10-21 17:44 UTC, merged