fix: GH-9103 Use DateTimePickerFormatterService in Replenishment Order
SAP/spartacus pull request #9457
Opened 2020-10-21 15:00 UTC by saad-mo

closes #9103

- Moved `DatePickerFormatterService` and `DateTimePickerFormatterService` to the core to make it easier for other features to use these services 
- Used `DateTimePickerFormatterService` in `OccReplenishmentOrderFormSerializer` because we need accurate time in the string. I found that the order was off by a day when the time was being zeroed out (00:00:00). 
- Furthermore, the date picker returns a string with the current time only if the replenishment date is not changed. If the date is changed, the date picker does not return the current time. `OccReplenishmentOrderFormSerializer` has been updated to handle this `getCurrentLocalTime` function. 
- Finally, we are using `toModel` method from `DateTimePickerFormatterService` to append an accurate timezone to the date string.

2020-10-22 21:07 UTC, bgambocjaviniar requested changes
Small quick question: Why was the PR necessary to re-create?

--------

I dug dipper and the fix for this date problem is just to provide the datetime hh:mm:00 with no offset of timezone, but with +00:00

Moreover, from my findings and additional testing, I believe there is no need to pass an offset of a timezone as that does not work well from the given response of a request as it will add/substract to the current time that was originally sent.

What was sent as a request
![Screen Shot 2020-10-22 at 5 06 19 PM](https://user-images.githubusercontent.com/29099466/96929964-f85ec400-1488-11eb-9f3d-55b88fa71706.png)

What we receive as response
![Screen Shot 2020-10-22 at 5 06 30 PM](https://user-images.githubusercontent.com/29099466/96929994-03195900-1489-11eb-9ce8-05fff13bcadc.png)

As you can see, what was being sent , the offset added additional time to the original current datetime of the date.

I proposed a potential solution with a snippet in https://github.com/SAP/spartacus/pull/9457#discussion_r510454392

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts
> +      modelDate = date.slice(0, index);
When index is bigger than 0, then that means a `:` is found. This case covers the issue, where the user did not choose a date from the datepicker. However, this logic is wrong, where you target the last index of a colon because the date string that was provided contains the hours and mins already which is set to UTC, therefore the hours being 4 hours ahead. 

For example, the default value that came contains `2011-10-05T14:48:00.000Z`, but 14:48 is the wrong datetime as the current eastern time would be 10:48, so instead of stripping the string from ':', we would strip the string from `T`.

All in all, I have provided a snippet and potential solution in the following link https://github.com/SAP/spartacus/pull/9457#discussion_r510454392

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts
> +      modelDate = `${date}T${this.getCurrentLocalTime()}`;
👍

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts
> +  it('should convert the date string with time', () => {
add a test for `getCurrentLocalTime` please

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts
> +    const mockDateWithTime = '1994-01-11:01:02:03.456Z';
As mentioned in the component, where I inserted comments, the date by default without choosing a date from the datepicker comes in utc time already, so this mock date with time is wrong as it won't represent the case you're trying to test

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts
> +   * Converts the date string from a Standard ISO 860 format with or without time to valid OCC model format
I would not change the comment as the ' accepted occ model format' is literally a Standard ISO 8601 format

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts
> +   * Converts the date string from a Standard ISO 860 format with or without time to valid OCC model format
Moreover, there's a typo, where you mentioned 860 and not 8601

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts
> +    const mockDateWithTime = '1994-01-11:01:02:03.456Z';
The format is wrong too, where the mock date has a `T` and not a `:`

I would fix to have some data consistency even if mocked for this special representation.

2020-10-22 21:07 UTC, bgambocjaviniar commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts
> +    return this.dateTimePickerFormatterService.toModel(modelDate);
I had to dig deeper and noticed the response that we get back from the backend returns a date 
- need to checkup with someone to checkout the backend as I believe we don't have to set the offset, and we only needed the datetime HH:mm 

Solution for this is just pass in HH:MM:00Z or HH:MM:00-00:00 (same thing)

2020-10-27 20:31 UTC, hackergil commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.ts
> +      modelDate = `${date}T${this.getCurrentLocalTime()}`;
I got rid of this. Service should just get a date with no time

2020-10-27 20:31 UTC, hackergil commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts
> +  it('should convert the date string with time', () => {
I think there's no need anymore.

2020-10-27 20:32 UTC, hackergil commented on projects/core/src/occ/adapters/checkout/converters/occ-replenishment-order-form-serializer.spec.ts
> +    const mockDateWithTime = '1994-01-11:01:02:03.456Z';
Fixed

2020-10-27 21:10 UTC, bgambocjaviniar requested changes
LGTM except the offset, we need to talk about this before approval
Thanks for picking it up Gil.

2020-10-27 21:10 UTC, bgambocjaviniar commented on projects/storefrontlib/src/cms-components/checkout/services/checkout-replenishment-form-service.ts
> +    replenishmentStartDate: new Date().toISOString().split('T')[0],
👍  Better than changing it in the serializer

2020-10-28 17:47 UTC, bgambocjaviniar approved these changes

2020-10-30 16:43 UTC, merged