Feature/gh 9481
SAP/spartacus pull request #9498
Opened 2020-10-23 13:29 UTC by tobi-or-not-tobi

Draft for all the changes of #9481

2020-10-26 16:12 UTC, LTiger14 requested changes
In my opinion, the direction the carousel is heading into is very good. That said, there are a few areas I would like to improve.

1. The styling in Firefox and Safari needs a bit of tweaking. I found that despite the odd looks, the behaviour was still correct on both browsers. Additionally, the carousel didn't really like my Iphone 11 Pro simulator.

Firefox 82:
<img width="1252" alt="Screen Shot 2020-10-23 at 1 42 44 PM" src="https://user-images.githubusercontent.com/10605724/97197711-568af000-1784-11eb-976f-6301dff173d3.png">

Safari:
<img width="963" alt="Screen Shot 2020-10-23 at 1 42 34 PM" src="https://user-images.githubusercontent.com/10605724/97197776-67d3fc80-1784-11eb-9f56-3f46e951300f.png">
<img width="943" alt="Screen Shot 2020-10-23 at 1 42 38 PM" src="https://user-images.githubusercontent.com/10605724/97197797-6dc9dd80-1784-11eb-8ce0-54f7788f0e9d.png">

IOS safari, Iphone 11 PRO:
<img width="543" alt="Screen Shot 2020-10-26 at 12 01 28 PM" src="https://user-images.githubusercontent.com/10605724/97197847-7d492680-1784-11eb-86a0-398707da70b2.png">

2. I did some logging and I noticed that the `getProduct(code: string, prefetch: boolean)` in `product-carousel.component` got called a TON of times. I understand that there is some prefetching going on, I added a comment regarding the `mouseover` on carousel items that added a few calls.

3. The carousel has always been some pretty complicated code to understand but I feel like now it's gotten a step more difficult. I'm sorry I don't have a good suggestion to simplify it at the moment; perhaps if we get together we could find something.

**For after**: I added some cleanup comments so we don't forget.

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/shared/components/carousel/carousel.component.ts
> +    window.setTimeout(() => {
Please use windowRef

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/shared/components/carousel/carousel.component.ts
> +    // focusOnScroll: true,
Cleanup

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/layout/loading/intersect.directive.ts
> +    // TODO: read the default config from the intersectionService->LayoutConfig
You could introduce optional `threshold` to the config is you want to keep backwards compatibility.

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/lock/lock-focus.directive.ts
> +      // this.service.clear(this.config.group);
Why did you change this?

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/cms-components/product/carousel/product-carousel/product-carousel.component.html
> +<!-- *ngIf="(title$ | async) === 'Our Bestselling Products'" -->
Cleanup

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/shared/components/carousel/carousel.model.ts
> +  // visible: boolean;
I don't think we need the visible property.

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/shared/components/carousel/carousel.component.html
> +    [ngClass]="'size-' + size"
Isn't the `size-...` class logic commented out of the css?

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/tab/tab-focus.service.ts
> +      console.log('next', next);
Cleanup

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/layout/a11y/keyboard-focus/autofocus/auto-focus.directive.ts
> +      // TODO: cleanup
Cleanup

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontlib/src/shared/components/carousel/carousel.component.html
> +            (mouseenter)="prefetch()"
Is this mouseenter required? I find it executes quite a bit of logic every time you hover an item. Obviously it won't send new network call when the data is already fetched but moving your mouse back and forth leads to a lot of function calls.

2020-10-26 16:12 UTC, LTiger14 commented on projects/storefrontstyles/scss/components/product/carousel/_carousel.scss
>  %cx-carousel {
CSS cleanup general comment 😉

2020-10-26 19:29 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/shared/components/carousel/carousel.component.html
> +            (mouseenter)="prefetch()"
It is, but the current separate data we pass into the carousel item template is causing loads of change detection cycles. I believe we must change this into a single object with observables for the item, prefetch and tabindex. I need to test it out though.

2021-02-16 17:02 UTC, saad-mo commented
Hello - @tobi-or-not-tobi @LTiger14, This PR contains a11y fixes for keyboard focus which would be helpful to have in place while we address Screen Reader issues. What is the likely hood of this getting done anytime soon?

2021-04-19 15:27 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/shared/components/carousel/carousel.component.html
> +    [ngClass]="'size-' + size"
yes, it's gone now.

2023-01-09 15:47 UTC, closed without merging