fix - add ellipsis in sub-lists of MyCompany when content too long
SAP/spartacus pull request #9518
Opened 2020-10-26 16:27 UTC by Platonn

The CSS ellipsis was working well for the main tables (i.e. the main users table), but was not working for the sub lists (i.e. list of Users for the Unit). When the sub-list's cell had too long content, text went beyond the borders.

Not it's fixed. The last column is the sqhashed and aligned to the right. And the rest of preceding columns take proportionally he remaining space and are truncated with ellipsis, if their content is too long. 

Moreover:
- added `title` attributes to the cell components - for better desktop experience, to allow for mouse-hover lookup of the full value
- reused templates in cell-components to avoid duplication

closes GH-9490

2020-10-26 19:40 UTC, Pucek9 requested changes
Found 1 place where it doesn't seems ideal. I mean http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Services/approvers/assign

2020-10-28 12:30 UTC, Platonn commented on feature-libs/organization/administration/components/unit/list/toggle-link/toggle-link-cell.component.ts
> -  @HostBinding('class.content-wrapper') cls = true;
When I changed `.content-wrapper` to `display:inline`, it broke the rows of the unit tree. I fixed that, by removing this class from the toggle-link-cell component (used in unit tree).
I believe it's a right decision btw. becuase semantically this is not _content_ cell. And it looks well (same as before) without `.content-wrapper` class anyway.

2020-10-28 14:14 UTC, Pucek9 commented on feature-libs/organization/administration/components/unit/list/toggle-link/toggle-link-cell.component.ts
> -  @HostBinding('class.content-wrapper') cls = true;
I don't see any disadvantages of that change 👍

2020-10-28 14:16 UTC, Pucek9 requested changes
On mobile view in http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Services/users it seems like this:
![image](https://user-images.githubusercontent.com/8040837/97447920-5cbdcf80-1930-11eb-8667-a7f1d201d560.png)
Not sure we can close without fix that

2020-10-28 14:38 UTC, Pucek9 approved these changes
We decided to create new - stretch issue with that small visual defect in mobile #9561

2020-10-29 09:12 UTC, merged