fix: Unit address is not saved after changing country #8907
SAP/spartacus pull request #9598
Opened 2020-10-30 17:09 UTC by Pucek9

After discuss with @Platonn decided to add global message handler for address conversion error. 
As it's only workaround for backend issue, that is the least invasive method:
- catch only one broken case of changing country (from 4 available, other works well)
- needn't changes after fix backend
- avoid of breaking changes

Closes #8907

2020-10-30 17:38 UTC, Pucek9 commented
QA steps: 
1 [Open edit form address with region (eg. country Canada or China).](http://localhost:4200/powertools-spa/de/USD/organization/units/Rustic%20Services/addresses/8796196732951/edit) *Or create similar address if it doesnt exist.
2 Change country to other, without regions (eg. Albania), Click save

Expect results:
- See global message: 'We can not update this address. Please create a new one instead.'

2020-11-02 13:22 UTC, tobi-or-not-tobi approved these changes, later dismissed

2020-11-02 14:03 UTC, tobi-or-not-tobi commented
I believe the approach taken here is wrong. I don't like pollute our error handlers more with specific errors. Moreover, the organisation specific error handling now leaks into the core library. 

We should tackle this differently: 
- drop organization specifics from core lib
- introduce error messaging on top of the success messaging we have today in `OrganizationFormComponent.save`
- show error result in local views
- fix an error with the address; the region got reset when you land at an address regions

2020-11-02 14:04 UTC, tobi-or-not-tobi requested changes
I believe the approach taken here is wrong. I don't like pollute our error handlers more with specific errors. Moreover, the organisation specific error handling now leaks into the core library. 

We should tackle this differently: 
- drop organization specifics from core lib
- introduce error messaging on top of the success messaging we have today in `OrganizationFormComponent.save`
- show error result in local views
- fix an error with the address; the region got reset when you land at an address regions

2020-11-02 16:51 UTC, Pucek9 commented
> I believe the approach taken here is wrong. I don't like pollute our error handlers more with specific errors. Moreover, the organisation specific error handling now leaks into the core library.
> 
> We should tackle this differently:
> 
> * drop organization specifics from core lib
> * introduce error messaging on top of the success messaging we have today in `OrganizationFormComponent.save`
> * show error result in local views
> * fix an error with the address; the region got reset when you land at an address regions

It's not related to organization only. Same problem occurs in b2c and my solution is universal there

2020-11-16 14:04 UTC, Pucek9 commented
After discussion, we decided to not deliver notify by global message

2020-11-16 14:04 UTC, closed without merging