Feature/gh-9631
SAP/spartacus pull request #9788
Opened 2020-11-16 10:57 UTC by markywilson

2020-11-24 08:14 UTC, tobi-or-not-tobi requested changes

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/index.ts
> -export * from './update-email-form/update-email-form.component';
the new service should become part of public API

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +  }
Do you use Prettier? Prettier adds auto-formatting, which is mandatory on our pipeline

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts
> +    this.updateEmailForm.reset();
I wonder if we need to reset both in the init and destroy? I'd prefer to keep only one of them.

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts
> +    this.isLoading$ = this.updateEmailService.getUpdateEmailResultLoading();
I'd move the initialisations to the assignments:
```ts
updateEmailForm: FormGroup = this.updateEmailService.form;
isLoading$: Observable<boolean> = this.updateEmailService.getUpdateEmailResultLoading();
```

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts
> +  updateEmailForm: FormGroup;
what about just `form`?

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.html
> +      <div class="cx-spinner loader-overlay" *ngIf="isLoading$ | async">
Since there's already a cx-spinner selector, we can drop the wrapper.

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.html
> +<div class="container" [ngClass]="{'is-loading': isLoading$ | async}">
I wonder why we need the is-loading class? I believe the spinner does it all currently.

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.html
> +  <div class="row d-flex justify-content-center">
I prefer to drop the bootstrap classes here:
- polluting the html
- forces multiple wrapping elements (div>div>div)
- "blocks" customers from changing the UI easily (i.e. say you don't like to center the form?).

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts
>    isLoading$: Observable<boolean>;
It's actually `isUpdating$`. `isLoading$` indicates something that is done upfront.

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts
> +    this.updateEmailForm.reset();
I also don't know why we reset in the first place. Is this something we can clarify in a documentation (in the service I'd say)?

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.module.ts
>    entryComponents: [UpdateEmailComponent],
We no longer need the entryComponents. 
I don't think there's a good case for export, but I might be wrong

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +  protected newUid: string;
I'd drop the local property and pass on the uid in the code.

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +  getUpdateEmailResultLoading(): Observable<boolean> {
I'd clean up the method names, to get a nicer API, i.e.:

`updateEmailService.reset()`
`updateEmailService.save()`

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +  private async onSuccess(success: boolean): Promise<void> {
I'm actually not sure if we need to make the method `async`. What about just doing: 

```ts
this.authService.coreLogout().then(() => {
  // routing
})
```

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +  private async onSuccess(success: boolean): Promise<void> {
also, this logic will change with #9638, so if we won't need the `async` then as well, and can then more easily change the code without introducing a breaking change.

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontstyles/scss/components/misc/spinner/_spinner-overlay.scss
> +  .loader-overlay {
very nice. I'd make it a first class citizen of the spinner, so that you can do:

```html
<cx-spinner class="overlay"></cx-spinner>
```

2020-11-24 08:14 UTC, tobi-or-not-tobi commented on projects/storefrontstyles/scss/components/misc/spinner/_spinner-overlay.scss
> +  .loader-overlay {
so, you could move it to the spinner css

2020-11-25 16:12 UTC, markywilson commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.html
> +    [disabled]="isUpdating$ | async"
`[disabled]` is added because the overlay isn't enough to disable keyboard navigation.

2020-11-25 23:58 UTC, tobi-or-not-tobi requested changes

2020-11-25 23:58 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +  ngOnDestroy(): void {
I was hoping to omit the ngDestroy and infinite subscriptions in this service by:
- use the `first(Boolean)` operator, which stops subscribing after the first succesful emission is passed
- disable the form in save() method, and re-enable  in the success

2020-11-25 23:58 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +  // Show global message then log the user out
Perhaps use `/** */` style comments so that it contributes to IDE docs

2020-11-25 23:58 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts
> +  form: FormGroup = this.service.form;
I'd prefer a space line between those for better readibility

2020-11-25 23:58 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.service.ts
> +import { FormControl, FormGroup, Validators } from '@angular/forms';
we also use automated imports in our IDE, which sorts imports automatically on save. very convenient and never any differences between devs!

2020-11-27 09:37 UTC, tobi-or-not-tobi requested changes
view nitpicks, looks great!

2020-11-27 09:37 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.module.ts
> +    UpdateEmailService,
No need to provide this explicitly. The service is provided in 'root' and that's enough. We like this pattern so that it is more optional.

2020-11-27 09:37 UTC, tobi-or-not-tobi commented on projects/storefrontlib/src/cms-components/myaccount/update-email/update-email.component.ts
> +  isUpdating$: Observable<boolean> = this.service.isUpdating$;
nitpick: what about leaving out the typing here? It's implicit from the service method signature, and both in controller and view logic my IDE is fully aware of the type. Or any arguments against it?

2020-12-06 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SAP/spartacus?pullRequest=9788) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/SAP/spartacus?pullRequest=9788) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tobi-or-not-tobi<br/>:x: markywilson<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SAP/spartacus?pullRequest=9788) it.</sub>

2020-12-18 14:31 UTC, merged