chore: migration docs, schematics, and fix order of constructor deps for PlaceOrderComponent
SAP/spartacus pull request #9886
Opened 2020-11-18 14:05 UTC by Platonn

Automatic migration can't inject constructor param at the start. It will always be at the end. To fix the automatic migration we change order of parameters in a component constructor.

fix #9881

2020-11-18 16:42 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/3_0/constructor-deprecations/data/place-order.component.migration.ts
> +  // projects\storefrontlib\src\cms-components\checkout\components\place-order\place-order.component.ts
let's change the black slashes to forward slashes

2020-11-18 16:44 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/3_0/component-deprecations/data/place-order.component.migration.ts
> +      comment: `'placeOrderSubscription' property was removed - no replacement`,
The name was changed to a more generic name `subscription` and just instantiates a new Subscription object to support other Observables than the placeOrder one

So I don't think it was removed

2020-11-18 16:50 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/3_0/component-deprecations/data/place-order.component.migration.ts
> +export const PLACE_ORDER_COMPONENT_MIGRATION: ComponentData = {
let's add path to file as comment here as well

2020-11-18 16:53 UTC, bgambocjaviniar commented on projects/schematics/src/migrations/3_0/constructor-deprecations/data/place-order.component.migration.ts
> +      importPath: ANGULAR_ROUTER,
should be `SPARTACUS_CORE`

2020-11-18 16:57 UTC, bgambocjaviniar requested changes, later dismissed
a few minor changes needed

2020-11-19 12:45 UTC, marlass submitted a review, later dismissed

2020-11-19 13:01 UTC, marlass approved these changes

2020-11-19 13:19 UTC, Matejk00 approved these changes

2020-11-19 13:21 UTC, dunqan approved these changes

2020-11-19 13:23 UTC, merged