feat; Missing migrations for anonymous-consents #9841
SAP/spartacus pull request #9909
Opened 2020-11-18 15:22 UTC by Pucek9

Closes #9841

2020-11-18 15:32 UTC, kacperknapik submitted a review, later dismissed

2020-11-18 15:32 UTC, kacperknapik commented
Wait for the decision about merge destination - we think about merging all migration tickets to epic branch first.

2020-11-19 06:59 UTC, marlass commented on docs/migration/3_0.md
> +- `anonymousConsentsStoreConfigFactory` was removed. Function has been replaced by `anonymousConsentsStatePersistenceFactory`. It requires param type `AnonymousConsentsStatePersistenceService` and it
These details are not important. More important is mention of storageSync config. Eg.
```suggestion
- `storageSync` configuration for `anonymous-consents` branch in ngrx store was removed. State is now synchronized with `AnonymousConsentsStatePersistenceService`. Override this service if you want to sync more/less properties to localStorage.
```

2020-11-19 07:00 UTC, marlass requested changes
Also add information about adapter/connector change in the migration doc (3_0.md)

2020-11-19 09:44 UTC, Matejk00 commented
Please check requested changes.

2020-11-19 10:41 UTC, marlass submitted a review, later dismissed

2020-11-19 11:21 UTC, Matejk00 approved these changes

2020-11-19 11:48 UTC, marlass approved these changes

2020-11-19 11:48 UTC, merged